import type { VaultPatternItem } from "../types";

export const BUNDLED_PATTERNS: VaultPatternItem[] = [
  {
    id: "pat:hard-shadow-tactile-card",
    name: "硬阴影触感卡片 (Tactile Hard Shadow Card)",
    category: "card",
    description: "带有坚实质感位移与纯黑硬边框的实体物理按压卡片，常用于新丑风（Neo-Brutalism）与波普风（Pop Manga）。",
    author: "Setup Center Design Lab",
    tags: ["新丑风", "硬阴影", "实体触感", "微交互"],
    codeSnippet: "<div class=\"tactile-card\">\n  <h3 class=\"font-bold text-lg\">可交互实体卡片</h3>\n  <p class=\"text-sm text-gray-700\">点击或悬浮时带有自然的物理压下效果与硬阴影位移。</p>\n</div>",
    cssRules: ".tactile-card {\n  background: #ffffff;\n  border: 2px solid #000000;\n  box-shadow: 4px 4px 0px #000000;\n  border-radius: 4px;\n  padding: 16px;\n  transition: all 0.15s cubic-bezier(0.16, 1, 0.3, 1);\n}\n.tactile-card:hover {\n  transform: translate(-2px, -2px);\n  box-shadow: 6px 6px 0px #000000;\n}\n.tactile-card:active {\n  transform: translate(2px, 2px);\n  box-shadow: 2px 2px 0px #000000;\n}",
    usage: "适用于仪表盘核心指标卡片、功能入口按钮与强调操作。",
    targetStyles: ["neo-brutalism", "phantom-comic", "bauhaus"],
    updatedAt: "2026-10-02",
  },
  {
    id: "pat:editorial-section-header",
    name: "排印分栏标题栏 (Editorial Section Header)",
    category: "header",
    description: "融合了瑞士国际主义与百年报刊双细线装订特征的内容分块标头。",
    author: "Setup Center Design Lab",
    tags: ["瑞士排版", "衬线标题", "双细线", "网格结构"],
    codeSnippet: "<header class=\"editorial-header\">\n  <div class=\"editorial-meta\">\n    <span class=\"editorial-index\">SECTION 01</span>\n    <span class=\"editorial-date\">VOL. 2026</span>\n  </div>\n  <h2 class=\"editorial-title\">排印叙事与系统结构</h2>\n  <div class=\"editorial-rule\"></div>\n</header>",
    cssRules: ".editorial-header {\n  border-bottom: 2px solid currentColor;\n  padding-bottom: 8px;\n  margin-bottom: 20px;\n}\n.editorial-meta {\n  display: flex;\n  justify-content: space-between;\n  font-family: monospace;\n  font-size: 11px;\n  letter-spacing: 0.1em;\n  opacity: 0.7;\n}\n.editorial-title {\n  font-size: 24px;\n  font-weight: 800;\n  margin-top: 4px;\n  letter-spacing: -0.02em;\n}",
    usage: "用于各类杂志排版、深度文章阅读或高质量内容模块的引言标题。",
    targetStyles: ["swiss-editorial", "newspaper-editorial"],
    updatedAt: "2026-10-02",
  },
  {
    id: "pat:spatial-glass-detail-panel",
    name: "高透光空间玻璃面板 (Spatial Glass Panel)",
    category: "panel",
    description: "带有 24px 背景多重模糊、1px 亚克力边缘微高光与半透明景深感的高阶悬浮面板。",
    author: "Setup Center Design Lab",
    tags: ["空间计算", "毛玻璃", "亚克力高光", "景深"],
    codeSnippet: "<div class=\"spatial-panel\">\n  <div class=\"spatial-glow\"></div>\n  <div class=\"spatial-content\">\n    <h4>空间计算浮层</h4>\n    <p>自适应融合底层复杂色彩背景，保留极高文字辨识度。</p>\n  </div>\n</div>",
    cssRules: ".spatial-panel {\n  background: rgba(255, 255, 255, 0.08);\n  backdrop-filter: blur(24px) saturate(180%);\n  -webkit-backdrop-filter: blur(24px) saturate(180%);\n  border: 1px solid rgba(255, 255, 255, 0.18);\n  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);\n  border-radius: 16px;\n  padding: 24px;\n}",
    usage: "用于详情弹窗、半透明侧边浮层与沉浸式卡片展示。",
    targetStyles: ["spatial-glass", "y2k-digital"],
    updatedAt: "2026-10-02",
  },
  {
    id: "pat:command-palette-bar",
    name: "全局指令调色板 (Command Palette Bar)",
    category: "navigation",
    description: "专为桌面端与 Pro 工具打造的快捷指令搜索输入条，支持 ⌘K 触发与即时过滤。",
    author: "Setup Center Design Lab",
    tags: ["快捷搜索", "CommandPalette", "键盘优先", "Pro工具"],
    codeSnippet: "<div class=\"cmd-palette-bar\">\n  <span class=\"cmd-icon\">⌘K</span>\n  <input type=\"text\" placeholder=\"搜索命令或资产... (按 ↑↓ 选择，↵ 执行)\" />\n  <kbd>ESC</kbd>\n</div>",
    cssRules: ".cmd-palette-bar {\n  display: flex;\n  align-items: center;\n  gap: 10px;\n  background: var(--surface-raised);\n  border: 1px solid var(--line-strong);\n  border-radius: 8px;\n  padding: 8px 12px;\n  box-shadow: 0 4px 16px rgba(0,0,0,0.12);\n}\n.cmd-palette-bar input {\n  flex: 1;\n  background: transparent;\n  border: none;\n  outline: none;\n  color: var(--text-strong);\n  font-size: 13px;\n}\n.cmd-palette-bar kbd {\n  font-size: 10px;\n  font-family: monospace;\n  padding: 2px 6px;\n  border-radius: 4px;\n  background: var(--surface-inset);\n  border: 1px solid var(--line-subtle);\n}",
    usage: "适用于所有需要高频键盘操作的桌面应用或高级后台。",
    targetStyles: ["default", "spatial-glass", "swiss-editorial", "nordic-frost"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:segmented-control-tabs",
    name: "流体分段胶囊控制台 (Segmented Control Tabs)",
    category: "navigation",
    description: "具有温润背景胶囊滑块与触觉反馈的分段标签切换控件，避免传统 Tab 的突兀闪烁。",
    author: "Setup Center Design Lab",
    tags: ["分段控制", "胶囊滑块", "平滑过渡", "触觉反馈"],
    codeSnippet: "<div class=\"segmented-control\" role=\"tablist\">\n  <button class=\"segment-pill active\" role=\"tab\">推荐</button>\n  <button class=\"segment-pill\" role=\"tab\">最新</button>\n  <button class=\"segment-pill\" role=\"tab\">已收藏</button>\n</div>",
    cssRules: ".segmented-control {\n  display: inline-flex;\n  padding: 3px;\n  background: var(--surface-sunken);\n  border-radius: 8px;\n  border: 1px solid var(--line-subtle);\n  gap: 2px;\n}\n.segment-pill {\n  padding: 4px 12px;\n  font-size: 12px;\n  font-weight: 500;\n  border-radius: 6px;\n  color: var(--text-secondary);\n  transition: all 0.15s ease;\n  border: none;\n  background: transparent;\n  cursor: pointer;\n}\n.segment-pill.active {\n  background: var(--surface-raised);\n  color: var(--text-strong);\n  box-shadow: 0 1px 3px rgba(0,0,0,0.1);\n  font-weight: 600;\n}",
    usage: "用于页面分类过滤、多视图模式切换（如卡片/列表）与状态筛选。",
    targetStyles: ["soft-product-minimal", "spatial-glass", "nordic-frost"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:status-badge-chip",
    name: "状态指示微标徽章 (Status Indicator Chip)",
    category: "feedback",
    description: "带有活体呼吸脉冲微点与微弱外发光的紧凑型状态指示徽章，用于实时呈现运行健康度。",
    author: "Setup Center Design Lab",
    tags: ["状态微标", "呼吸脉冲", "健康度指示", "可访问性"],
    codeSnippet: "<span class=\"status-chip status-ok\">\n  <span class=\"pulse-dot\"></span>\n  <span class=\"status-text\">在线就绪</span>\n</span>",
    cssRules: ".status-chip {\n  display: inline-flex;\n  align-items: center;\n  gap: 6px;\n  padding: 2px 8px;\n  border-radius: 9999px;\n  font-size: 11px;\n  font-family: monospace;\n  border: 1px solid currentColor;\n}\n.status-chip.status-ok {\n  color: #10b981;\n  background: rgba(16, 185, 129, 0.1);\n}\n.pulse-dot {\n  width: 6px;\n  height: 6px;\n  border-radius: 50%;\n  background: currentColor;\n  box-shadow: 0 0 6px currentColor;\n  animation: pulse 2s infinite;\n}\n@keyframes pulse {\n  0%, 100% { opacity: 1; transform: scale(1); }\n  50% { opacity: 0.4; transform: scale(0.85); }\n}",
    usage: "用于软件安装状态、服务器连通性检测与环境依赖就绪度呈现。",
    targetStyles: ["terminal-crt", "industrial-console", "cyber-neon", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:split-detail-drawer",
    name: "侧滑深度抽屉面板 (Slide-Over Detail Drawer)",
    category: "layout",
    description: "从右侧平滑滑出的深度检视抽屉，适用于在不跳离当前工作流的情况下查看配置或历史日志。",
    author: "Setup Center Design Lab",
    tags: ["侧滑抽屉", "无跳离检视", "工作流保持", "平滑过渡"],
    codeSnippet: "<div class=\"detail-drawer open\">\n  <div class=\"drawer-header\">\n    <h3>详细信息</h3>\n    <button class=\"close-btn\">✕</button>\n  </div>\n  <div class=\"drawer-body\">\n    <p>深度配置与变更记录...</p>\n  </div>\n</div>",
    cssRules: ".detail-drawer {\n  position: fixed;\n  top: 0;\n  right: 0;\n  bottom: 0;\n  width: 420px;\n  background: var(--surface-raised);\n  border-left: 1px solid var(--line-strong);\n  box-shadow: -10px 0 30px rgba(0,0,0,0.3);\n  transform: translateX(100%);\n  transition: transform 0.25s cubic-bezier(0.16, 1, 0.3, 1);\n  z-index: 40;\n}\n.detail-drawer.open {\n  transform: translateX(0);\n}",
    usage: "用于 Transfer Inbox 外部收件箱、安装历史时间线与详细环境检测报告展板。",
    targetStyles: ["default", "spatial-glass", "swiss-editorial"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:diff-viewer-panel",
    name: "差异对比分栏面板 (Diff Viewer Panel)",
    category: "inspector",
    description: "并排或单列展示两段配置、文本或代码差异的对比视窗，具备清晰的增删高亮背景与字符微位移装饰。",
    author: "Setup Center Design Lab",
    tags: ["代码对比", "Diff", "版本差异", "暗黑控制台"],
    codeSnippet: "<div class=\"diff-container\">\n  <div class=\"diff-line diff-del\"><span class=\"prefix\">-</span><span class=\"content\">const remoteUrl = 'https://raw.../main'</span></div>\n  <div class=\"diff-line diff-add\"><span class=\"prefix\">+</span><span class=\"content\">const remoteUrl = `https://raw.../${commitSha}`</span></div>\n</div>",
    cssRules: ".diff-container {\n  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;\n  font-size: 12px;\n  background: #090a0f;\n  border: 1px solid #1e2230;\n  border-radius: 6px;\n  overflow: hidden;\n}\n.diff-line {\n  display: flex;\n  padding: 3px 10px;\n  line-height: 1.5;\n}\n.diff-line .prefix {\n  width: 20px;\n  user-select: none;\n  font-weight: bold;\n}\n.diff-line.diff-del {\n  background: rgba(239, 68, 68, 0.12);\n  color: #fca5a5;\n}\n.diff-line.diff-add {\n  background: rgba(34, 197, 94, 0.12);\n  color: #86efac;\n}",
    usage: "用于配置仲裁、版本更新变更集展示以及代码审查审查弹层。",
    targetStyles: ["nordic-frost", "academic-lab", "dos-utility"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:terminal-log-stream",
    name: "终端日志流视图 (Terminal Log Stream)",
    category: "terminal",
    description: "模拟真实系统底层控制台输出的流式日志展示面板，具备光标呼吸闪烁、行号对齐与彩色级别指示器。",
    author: "Setup Center Design Lab",
    tags: ["终端控制台", "流式输出", "日志流", "暗色极客"],
    codeSnippet: "<div class=\"terminal-panel\">\n  <div class=\"terminal-header\">\n    <span class=\"dot dot-red\"></span><span class=\"dot dot-yellow\"></span><span class=\"dot dot-green\"></span>\n    <span class=\"terminal-title\">setup-agent.log</span>\n  </div>\n  <pre class=\"terminal-body\"><code>[INFO] 10:20:54 Verified 40 assets in Vault.\n[EXEC] cargo check --manifest-path src-tauri/Cargo.toml\n[DONE] Built binary at target/release/ai-student-setup.exe<span class=\"cursor\">_</span></code></pre>\n</div>",
    cssRules: ".terminal-panel {\n  background: #0d1117;\n  border: 1px solid #30363d;\n  border-radius: 8px;\n  overflow: hidden;\n  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);\n}\n.terminal-header {\n  display: flex;\n  align-items: center;\n  gap: 6px;\n  padding: 8px 12px;\n  background: #161b22;\n  border-bottom: 1px solid #30363d;\n}\n.terminal-header .dot {\n  width: 10px;\n  height: 10px;\n  border-radius: 50%;\n}\n.dot-red { background: #ff5f56; }\n.dot-yellow { background: #ffbd2e; }\n.dot-green { background: #27c93f; }\n.terminal-title {\n  font-size: 11px;\n  color: #8b949e;\n  margin-left: 6px;\n  font-family: monospace;\n}\n.terminal-body {\n  padding: 12px;\n  margin: 0;\n  font-family: 'JetBrains Mono', Consolas, monospace;\n  font-size: 12px;\n  line-height: 1.6;\n  color: #c9d1d9;\n}\n.cursor {\n  display: inline-block;\n  animation: blink 1s step-end infinite;\n  color: #58a6ff;\n}\n@keyframes blink {\n  50% { opacity: 0; }\n}",
    usage: "用于软件安装进度输出、脚手架克隆执行反馈与后端探针调试日志。",
    targetStyles: ["cyber-neon", "dos-utility", "swiss-dark"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:filter-pill-cloud",
    name: "过滤标签胶囊云 (Filter Pill Cloud)",
    category: "navigation",
    description: "紧凑水平排列的标签胶囊群，支持单选/多选状态切换、数量计数字标以及微边框过渡高亮。",
    author: "Setup Center Design Lab",
    tags: ["标签筛选", "胶囊按钮", "微交互", "探索器过滤"],
    codeSnippet: "<div class=\"pill-cloud\">\n  <button class=\"pill active\">全部 <span class=\"count\">18</span></button>\n  <button class=\"pill\">工具库 <span class=\"count\">6</span></button>\n  <button class=\"pill\">设计模式 <span class=\"count\">8</span></button>\n</div>",
    cssRules: ".pill-cloud {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 6px;\n  align-items: center;\n}\n.pill {\n  display: inline-flex;\n  align-items: center;\n  gap: 6px;\n  padding: 4px 10px;\n  font-size: 12px;\n  border-radius: 9999px;\n  background: rgba(255, 255, 255, 0.05);\n  border: 1px solid rgba(255, 255, 255, 0.1);\n  color: #a1a1aa;\n  cursor: pointer;\n  transition: all 0.15s ease;\n}\n.pill:hover {\n  background: rgba(255, 255, 255, 0.09);\n  color: #f4f4f5;\n  border-color: rgba(255, 255, 255, 0.2);\n}\n.pill.active {\n  background: #3b82f6;\n  border-color: #3b82f6;\n  color: #ffffff;\n  box-shadow: 0 0 12px rgba(59, 130, 246, 0.35);\n}\n.pill .count {\n  font-size: 10px;\n  opacity: 0.8;\n}",
    usage: "用于各类资源卡片池、风格画廊及搜索分类标签筛选栏。",
    targetStyles: ["nordic-frost", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:activity-feed-timeline",
    name: "活动流水时间线 (Activity Feed Timeline)",
    category: "timeline",
    description: "竖向连接的审计流与流转流水线，节点带有状态圆点与时间戳，用于展示安装、同步与变更历史。",
    author: "Setup Center Design Lab",
    tags: ["时间线", "操作流水", "审计追踪", "微指示器"],
    codeSnippet: "<div class=\"timeline-feed\">\n  <div class=\"timeline-item done\">\n    <div class=\"timeline-marker\"></div>\n    <div class=\"timeline-content\">\n      <div class=\"timeline-title\">同步 Remote Vault 成功</div>\n      <div class=\"timeline-time\">10:20:54 · v2026.10.03.2</div>\n    </div>\n  </div>\n</div>",
    cssRules: ".timeline-feed {\n  position: relative;\n  padding-left: 20px;\n}\n.timeline-feed::before {\n  content: '';\n  position: absolute;\n  left: 6px;\n  top: 6px;\n  bottom: 6px;\n  width: 1px;\n  background: #27272a;\n}\n.timeline-item {\n  position: relative;\n  padding-bottom: 16px;\n}\n.timeline-marker {\n  position: absolute;\n  left: -20px;\n  top: 4px;\n  width: 13px;\n  height: 13px;\n  border-radius: 50%;\n  background: #09090b;\n  border: 2px solid #52525b;\n}\n.timeline-item.done .timeline-marker {\n  border-color: #22c55e;\n  background: #14532d;\n}\n.timeline-title {\n  font-size: 13px;\n  font-weight: 500;\n  color: #e4e4e7;\n}\n.timeline-time {\n  font-size: 11px;\n  color: #71717a;\n  margin-top: 2px;\n}",
    usage: "用于 TransferHistory 历史记录屏、安装步骤回放与版本发布变更志。",
    targetStyles: ["monochrome-research", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:empty-state-canvas",
    name: "优雅空状态占位 (Empty State Canvas)",
    category: "empty-state",
    description: "无数据、搜索无匹配或收件箱清空时的引导占位设计，带有虚线轮廓、微淡图标与明确的引导行动按钮。",
    author: "Setup Center Design Lab",
    tags: ["空状态", "引导", "无数据", "去玩具化"],
    codeSnippet: "<div class=\"empty-canvas\">\n  <div class=\"empty-icon\"><svg ...></svg></div>\n  <h4 class=\"empty-heading\">未检索到匹配的资源</h4>\n  <p class=\"empty-desc\">换一个关键词或按下快捷键重置筛选范围。</p>\n  <button class=\"empty-action\">清除筛选条件</button>\n</div>",
    cssRules: ".empty-canvas {\n  display: flex;\n  flex-direction: column;\n  align-items: center;\n  justify-content: center;\n  padding: 48px 24px;\n  border: 1px dashed rgba(255, 255, 255, 0.15);\n  border-radius: 8px;\n  text-align: center;\n  background: rgba(255, 255, 255, 0.015);\n}\n.empty-icon {\n  width: 44px;\n  height: 44px;\n  color: #71717a;\n  margin-bottom: 12px;\n}\n.empty-heading {\n  font-size: 14px;\n  font-weight: 600;\n  color: #e4e4e7;\n  margin-bottom: 6px;\n}\n.empty-desc {\n  font-size: 12px;\n  color: #a1a1aa;\n  max-width: 320px;\n  line-height: 1.5;\n  margin-bottom: 16px;\n}\n.empty-action {\n  font-size: 12px;\n  padding: 6px 14px;\n  background: #27272a;\n  color: #f4f4f5;\n  border: 1px solid #3f3f46;\n  border-radius: 6px;\n  cursor: pointer;\n}",
    usage: "用于书签收藏为空、搜索结果为零以及流转收件箱（Inbox）初始状态。",
    targetStyles: ["japanese-editorial", "nordic-frost", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:metric-stat-counter",
    name: "指标统计卡片 (Metric Stat Counter)",
    category: "dashboard",
    description: "用于仪表盘与总览页的高信息密度数值展示卡片，包含大号等宽数字、趋势徽章与辅助说明文本。",
    author: "Setup Center Design Lab",
    tags: ["数据统计", "仪表盘", "大字阶", "高密度"],
    codeSnippet: "<div class=\"stat-card\">\n  <div class=\"stat-label\">收录样式总数</div>\n  <div class=\"stat-value\">20 <span class=\"stat-badge\">+8 新增</span></div>\n  <div class=\"stat-sub\">覆盖和风、赛博、极简等主流设计语言</div>\n</div>",
    cssRules: ".stat-card {\n  background: #12141a;\n  border: 1px solid #232733;\n  border-radius: 8px;\n  padding: 16px;\n}\n.stat-label {\n  font-size: 12px;\n  color: #8f96a3;\n  text-transform: uppercase;\n  letter-spacing: 0.05em;\n}\n.stat-value {\n  font-size: 28px;\n  font-weight: 700;\n  font-family: ui-monospace, monospace;\n  color: #ffffff;\n  margin: 6px 0;\n  display: flex;\n  align-items: baseline;\n  gap: 8px;\n}\n.stat-badge {\n  font-size: 11px;\n  padding: 2px 6px;\n  border-radius: 4px;\n  background: rgba(34, 197, 94, 0.15);\n  color: #4ade80;\n  border: 1px solid rgba(34, 197, 94, 0.3);\n}\n.stat-sub {\n  font-size: 11px;\n  color: #636b7b;\n}",
    usage: "用于首页总览屏统计、Vault 资源库规模指标及硬件参数探测总结面板。",
    targetStyles: ["financial-terminal", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:code-snippet-box",
    name: "代码语法框带一键复制 (Code Snippet Box with Copy)",
    category: "code",
    description: "专为终端命令与配置文件设计的代码块容器，带有右上角快速复制按钮、轻量悬浮反馈与横向优雅滚动。",
    author: "Setup Center Design Lab",
    tags: ["代码展示", "一键复制", "等宽排版", "命令容器"],
    codeSnippet: "<div class=\"code-box\">\n  <pre><code>pnpm add -D tailwindcss @tailwindcss/vite</code></pre>\n  <button class=\"copy-btn\">复制</button>\n</div>",
    cssRules: ".code-box {\n  position: relative;\n  background: #090a0f;\n  border: 1px solid #1f2430;\n  border-radius: 6px;\n  padding: 12px 48px 12px 14px;\n  overflow-x: auto;\n}\n.code-box pre {\n  margin: 0;\n  font-family: 'JetBrains Mono', Consolas, monospace;\n  font-size: 12px;\n  color: #e6edf3;\n}\n.copy-btn {\n  position: absolute;\n  right: 8px;\n  top: 8px;\n  font-size: 11px;\n  padding: 3px 8px;\n  border-radius: 4px;\n  background: rgba(255, 255, 255, 0.08);\n  border: 1px solid rgba(255, 255, 255, 0.15);\n  color: #d1d5db;\n  cursor: pointer;\n  transition: all 0.15s;\n}\n.copy-btn:hover {\n  background: rgba(255, 255, 255, 0.16);\n  color: #ffffff;\n}",
    usage: "用于详情弹层包管理器安装命令、脚手架创建指令及样板配置展示。",
    targetStyles: ["nordic-frost", "swiss-dark", "academic-lab", "dos-utility"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:progress-step-tracker",
    name: "多步骤进度追踪条 (Progress Step Tracker)",
    category: "wizard",
    description: "线性向导步骤状态条，以数字圆标、连线与完成对勾直观表达安装流程阶段。",
    author: "Setup Center Design Lab",
    tags: ["向导", "步骤条", "进度跟踪", "多阶段"],
    codeSnippet: "<div class=\"step-tracker\">\n  <div class=\"step completed\"><div class=\"circle\">✓</div><span>环境检测</span></div>\n  <div class=\"line completed\"></div>\n  <div class=\"step current\"><div class=\"circle\">2</div><span>方案定制</span></div>\n  <div class=\"line\"></div>\n  <div class=\"step\"><div class=\"circle\">3</div><span>开始安装</span></div>\n</div>",
    cssRules: ".step-tracker {\n  display: flex;\n  align-items: center;\n  gap: 8px;\n}\n.step {\n  display: flex;\n  align-items: center;\n  gap: 6px;\n  font-size: 12px;\n  color: #71717a;\n}\n.circle {\n  width: 20px;\n  height: 20px;\n  border-radius: 50%;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  font-size: 11px;\n  font-weight: 600;\n  background: #27272a;\n  color: #a1a1aa;\n}\n.step.current {\n  color: #ffffff;\n}\n.step.current .circle {\n  background: #3b82f6;\n  color: #ffffff;\n}\n.step.completed .circle {\n  background: #10b981;\n  color: #ffffff;\n}\n.line {\n  flex: 1;\n  height: 2px;\n  background: #27272a;\n}\n.line.completed {\n  background: #10b981;\n}",
    usage: "用于新手初始化向导、多阶段 Recipe 自动化执行追踪。",
    targetStyles: ["fluent-spatial", "nordic-frost", "japanese-editorial"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:master-detail-split",
    name: "主从联动分割视窗 (Master Detail Split Layout)",
    category: "layout",
    description: "左侧列表快速筛选索引、右侧常驻展开选定条目深度元数据与操作的专业桌面端两栏布局。",
    author: "Setup Center Design Lab",
    tags: ["双栏布局", "主从联动", "桌面端经典", "高效率"],
    codeSnippet: "<div class=\"master-detail-split\">\n  <aside class=\"split-master\">列表项...</aside>\n  <main class=\"split-detail\">详细内容...</main>\n</div>",
    cssRules: ".master-detail-split {\n  display: flex;\n  height: 100%;\n  overflow: hidden;\n}\n.split-master {\n  width: 320px;\n  flex-shrink: 0;\n  border-right: 1px solid rgba(255, 255, 255, 0.08);\n  overflow-y: auto;\n  padding: 12px;\n}\n.split-detail {\n  flex: 1;\n  overflow-y: auto;\n  padding: 24px;\n  background: rgba(255, 255, 255, 0.01);\n}",
    usage: "用于软件管理屏、配置参数设置中心及长文档章节阅读视窗。",
    targetStyles: ["retro-mac", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:notification-toast-shelf",
    name: "浮动微通知托架 (Notification Toast Shelf)",
    category: "feedback",
    description: "位于视窗底部中轴或右下角的悬浮消息队列托架，以物理轻微弹入/淡出展示命令复制、同步完成等非阻断通知。",
    author: "Setup Center Design Lab",
    tags: ["微通知", "Toast", "非阻断反馈", "操作提示"],
    codeSnippet: "<div class=\"toast-shelf\">\n  <div class=\"toast toast-success\">\n    <span class=\"toast-icon\">✓</span>\n    <span class=\"toast-message\">已复制安装命令到剪贴板</span>\n  </div>\n</div>",
    cssRules: ".toast-shelf {\n  position: fixed;\n  bottom: 24px;\n  right: 24px;\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n  z-index: 9999;\n  pointer-events: none;\n}\n.toast {\n  display: inline-flex;\n  align-items: center;\n  gap: 8px;\n  padding: 8px 14px;\n  background: #18181b;\n  border: 1px solid #27272a;\n  color: #f4f4f5;\n  font-size: 12px;\n  border-radius: 6px;\n  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.45);\n  animation: toastIn 0.2s cubic-bezier(0.16, 1, 0.3, 1);\n  pointer-events: auto;\n}\n.toast-success .toast-icon { color: #22c55e; }\n@keyframes toastIn {\n  from { opacity: 0; transform: translateY(8px); }\n  to { opacity: 1; transform: translateY(0); }\n}",
    usage: "用于 SetupActionButton 复制成功反馈、Vault 同步通知及脚手架创建完成状态。",
    targetStyles: ["japanese-editorial", "nordic-frost", "swiss-dark"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:hero-action-banner",
    name: "行动召唤主旗标 (Hero Action Banner)",
    category: "hero",
    description: "位于画廊或工坊顶部的品牌主标语与关键行动横幅，采用精练排印、微细背景网格与明确的首要操作入口。",
    author: "Setup Center Design Lab",
    tags: ["首屏横幅", "行动召唤", "视觉焦点", "画廊引导"],
    codeSnippet: "<div class=\"hero-banner\">\n  <div class=\"badge\">Setup Runtime 2026</div>\n  <h1 class=\"headline\">Setup Everything Needed to Build.</h1>\n  <p class=\"lead\">将全球开源资产、设计系统与工具链即刻迁移至本机。</p>\n</div>",
    cssRules: ".hero-banner {\n  padding: 32px 24px;\n  background: radial-gradient(circle at top left, rgba(59, 130, 246, 0.08), transparent 70%);\n  border-bottom: 1px solid rgba(255, 255, 255, 0.06);\n  margin-bottom: 24px;\n}\n.badge {\n  display: inline-block;\n  font-size: 11px;\n  font-family: monospace;\n  color: #60a5fa;\n  background: rgba(59, 130, 246, 0.12);\n  padding: 2px 8px;\n  border-radius: 4px;\n  margin-bottom: 12px;\n}\n.headline {\n  font-size: 24px;\n  font-weight: 700;\n  color: #f8fafc;\n  letter-spacing: -0.02em;\n  margin: 0 0 8px 0;\n}\n.lead {\n  font-size: 13px;\n  color: #94a3b8;\n  margin: 0;\n  max-width: 600px;\n}",
    usage: "用于首页 Welcome 屏、Style 展厅顶栏及新手引导页面头图。",
    targetStyles: ["japanese-editorial", "cyber-neon", "nordic-frost"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:keybinding-cheat-grid",
    name: "快捷键指南速查网格 (Keybinding Cheat Grid)",
    category: "shortcuts",
    description: "并排紧凑展示全局物理快捷键（Kbd 键位符）与对应操作说明的高信息密度指南视窗。",
    author: "Setup Center Design Lab",
    tags: ["快捷键", "Kbd", "键盘流", "效率工具"],
    codeSnippet: "<div class=\"kbd-grid\">\n  <div class=\"kbd-row\"><span class=\"desc\">全局命令调色板</span><kbd>Ctrl</kbd> + <kbd>K</kbd></div>\n  <div class=\"kbd-row\"><span class=\"desc\">上一项 / 下一项</span><kbd>←</kbd> / <kbd>→</kbd></div>\n  <div class=\"kbd-row\"><span class=\"desc\">退出详情弹层</span><kbd>Esc</kbd></div>\n</div>",
    cssRules: ".kbd-grid {\n  display: flex;\n  flex-direction: column;\n  gap: 8px;\n  background: #101216;\n  border: 1px solid #20242c;\n  border-radius: 8px;\n  padding: 16px;\n}\n.kbd-row {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  font-size: 12px;\n  color: #c0c6d4;\n}\n.kbd-row kbd {\n  font-family: ui-monospace, monospace;\n  font-size: 11px;\n  padding: 2px 6px;\n  background: #1c202a;\n  border: 1px solid #333a4d;\n  border-bottom: 2px solid #262c3b;\n  border-radius: 4px;\n  color: #ffffff;\n}",
    usage: "用于 Command Palette 底部提示栏、设置页面与效率帮助面板。",
    targetStyles: ["dos-utility", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:spatial-acrylic-header",
    name: "空间高透亚克力毛玻璃顶栏 (Spatial Acrylic Header)",
    category: "header",
    description: "带有微妙模糊滤镜（backdrop-filter）、极细内阴影描边与内容透光的现代空间顶栏。",
    author: "Setup Center Design Lab",
    tags: ["毛玻璃", "空间感", "顶栏", "流光透视"],
    codeSnippet: "<header class=\"acrylic-header\">\n  <div class=\"brand\">Setup Center</div>\n  <nav class=\"nav-pills\">...</nav>\n</header>",
    cssRules: ".acrylic-header {\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  height: 48px;\n  padding: 0 16px;\n  background: rgba(18, 20, 26, 0.75);\n  backdrop-filter: blur(16px) saturate(180%);\n  -webkit-backdrop-filter: blur(16px) saturate(180%);\n  border-bottom: 1px solid rgba(255, 255, 255, 0.08);\n  box-shadow: 0 1px 0 0 rgba(255, 255, 255, 0.04) inset;\n  position: sticky;\n  top: 0;\n  z-index: 50;\n}",
    usage: "用于应用主窗口 TitleBar、画廊二级吸顶导航条及模态浮层顶栏。",
    targetStyles: ["fluent-spatial", "nordic-frost", "japanese-editorial"],
    updatedAt: "2026-10-03",
  },
  {
    id: "pat:activity-stream-live",
    name: "实时活动事件流 (Live Activity Stream)",
    category: "timeline",
    description: "带级别过滤、来源徽标、相对时间与「新事件」分隔线的实时事件流，专为持续追加的日志与审计场景设计。",
    author: "Setup Center Design Lab",
    tags: ["实时流", "事件分级", "相对时间", "增量追加"],
    codeSnippet: "import { useMemo, useState } from \"react\";\n\nexport type StreamEvent = {\n  id: string;\n  level: \"info\" | \"warn\" | \"error\";\n  source: string;\n  message: string;\n  at: number;\n};\n\nconst LEVELS = [\"info\", \"warn\", \"error\"] as const;\n\nexport function ActivityStreamLive({\n  events,\n  unseenFrom = 0,\n}: {\n  events: StreamEvent[];\n  unseenFrom?: number;\n}) {\n  const [levels, setLevels] = useState<string[]>([...LEVELS]);\n\n  const visible = useMemo(\n    () => events.filter((e) => levels.includes(e.level)),\n    [events, levels],\n  );\n\n  const toggle = (level: string) =>\n    setLevels((prev) =>\n      prev.includes(level) ? prev.filter((l) => l !== level) : [...prev, level],\n    );\n\n  return (\n    <div className=\"asl-root\">\n      <header className=\"asl-filter\">\n        {LEVELS.map((level) => (\n          <button\n            key={level}\n            type=\"button\"\n            aria-pressed={levels.includes(level)}\n            onClick={() => toggle(level)}\n            className=\"asl-chip\"\n            data-level={level}\n          >\n            {level}\n          </button>\n        ))}\n      </header>\n\n      <ol className=\"asl-list\">\n        {visible.map((event) => (\n          <li key={event.id}>\n            <article className=\"asl-event\" data-level={event.level}>\n              <span className=\"asl-level\" aria-hidden=\"true\" />\n              <span className=\"asl-source\">{event.source}</span>\n              <p className=\"asl-message\">{event.message}</p>\n            </article>\n          </li>\n        ))}\n      </ol>\n    </div>\n  );\n}",
    cssRules: ".asl-root {\n  display: flex;\n  flex-direction: column;\n  max-height: 520px;\n  background: var(--surface-inset, #0c0e13);\n  border: 1px solid var(--line-subtle, #1e2230);\n  border-radius: 10px;\n  overflow: hidden;\n  font-size: 12px;\n  color: var(--text-strong, #e2e8f0);\n}",
    usage: "用于后台任务监控、部署流水线实时输出与协作空间动态墙。",
    targetStyles: ["swiss-dark", "dos-utility", "monochrome-research", "nordic-frost"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:app-dock",
    name: "应用停靠坞 (Application Dock)",
    category: "navigation",
    description: "底部／侧边固定图标停靠坞，带运行态指示点、悬停放大与键盘可达的图标按钮队列。",
    author: "Setup Center Design Lab",
    tags: ["停靠坞", "图标导航", "运行态指示", "桌面隐喻"],
    codeSnippet: "import { useState } from \"react\";\n\nexport function AppDock({\n  items,\n  activeId,\n  onSelect,\n}: {\n  items: Array<{ id: string; label: string; glyph: string; running?: boolean }>;\n  activeId: string;\n  onSelect: (id: string) => void;\n}) {\n  return (\n    <nav className=\"dock-root\" aria-label=\"Application dock\">\n      {items.map((item) => (\n        <button\n          key={item.id}\n          type=\"button\"\n          aria-label={item.label}\n          aria-current={item.id === activeId}\n          onClick={() => onSelect(item.id)}\n          className={item.id === activeId ? \"dock-item is-active\" : \"dock-item\"}\n        >\n          <span aria-hidden=\"true\">{item.glyph}</span>\n          {item.running ? <i className=\"dock-dot\" /> : null}\n        </button>\n      ))}\n    </nav>\n  );\n}",
    cssRules: ".dock-root {\n  display: flex;\n  align-items: flex-end;\n  gap: 8px;\n  padding: 8px 12px;\n  border-radius: 18px;\n  background: var(--surface-glass, rgba(255, 255, 255, 0.14));\n  backdrop-filter: blur(20px);\n  box-shadow: 0 12px 32px rgba(0, 0, 0, 0.28);\n}\n.dock-item {\n  position: relative;\n  width: 44px;\n  height: 44px;\n  display: grid;\n  place-items: center;\n  border: none;\n  border-radius: 12px;\n  background: var(--surface-raised, rgba(255, 255, 255, 0.1));\n  color: var(--text-strong, #f8fafc);\n  cursor: pointer;\n}",
    usage: "用于桌面应用主切换器、工作区切换与固定工具入口。",
    targetStyles: ["retro-mac", "spatial-glass", "y2k-digital", "default"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:command-menu-popover",
    name: "指令下拉菜单 (Command Menu Popover)",
    category: "navigation",
    description: "锚定触发按钮的命令菜单浮层，带分组、勾选态、禁用项、快捷键提示与 Escape／方向键键盘语义。",
    author: "Setup Center Design Lab",
    tags: ["下拉菜单", "命令分组", "键盘导航", "浮层锚定"],
    codeSnippet: "<div className=\"cmp-root\">\n  <button type=\"button\" className=\"cmp-trigger\">Actions ⌄</button>\n  <div className=\"cmp-menu\" role=\"menu\">\n    <div className=\"cmp-group\"><p className=\"cmp-group-title\">General</p></div>\n  </div>\n</div>",
    cssRules: ".cmp-root {\n  position: relative;\n  display: inline-block;\n  font-size: 13px;\n}\n.cmp-trigger {\n  display: inline-flex;\n  align-items: center;\n  gap: 6px;\n  padding: 5px 11px;\n  border-radius: 7px;\n  border: 1px solid var(--line-subtle, #e4e4e7);\n  background: var(--surface-base, #ffffff);\n  color: var(--text-strong, #18181b);\n  cursor: pointer;\n}\n.cmp-menu {\n  position: absolute;\n  top: calc(100% + 6px);\n  left: 0;\n  z-index: 20;\n  min-width: 216px;\n  padding: 5px;\n  border-radius: 10px;\n  background: var(--surface-overlay, #ffffff);\n  box-shadow: 0 12px 34px rgba(0, 0, 0, 0.16);\n}",
    usage: "用于工具栏溢出菜单、行内操作集合与编辑器上下文动作列表。",
    targetStyles: ["soft-product-minimal", "default", "nordic-frost", "retro-mac"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:command-workspace",
    name: "指令工作台 (Command Workspace)",
    category: "layout",
    description: "面向 Pro 工具的三区指令中枢：左侧作用域轨道、中部可模糊过滤的指令队列、右侧结果预览，全键盘可驱动。",
    author: "Setup Center Design Lab",
    tags: ["指令中枢", "三区布局", "键盘优先", "Pro工具"],
    codeSnippet: "<div className=\"cw-root\">\n  <nav className=\"cw-rail\" aria-label=\"Command scopes\">...</nav>\n  <section className=\"cw-list\">...</section>\n  <aside className=\"cw-preview\">...</aside>\n</div>",
    cssRules: ".cw-root {\n  display: grid;\n  grid-template-columns: 176px 320px 1fr;\n  height: 100%;\n  min-height: 420px;\n  background: var(--surface-inset, #09090b);\n  color: var(--text-strong, #e4e4e7);\n}\n.cw-rail {\n  display: flex;\n  flex-direction: column;\n  gap: 2px;\n  padding: 12px 8px;\n  border-right: 1px solid var(--line-subtle, #27272a);\n}\n.cw-list {\n  display: flex;\n  flex-direction: column;\n  border-right: 1px solid var(--line-subtle, #27272a);\n  overflow: hidden;\n}\n.cw-preview {\n  padding: 24px;\n  overflow-y: auto;\n}",
    usage: "用于桌面端控制台、内部工具主页与需要批量触发动作的运维面板。",
    targetStyles: ["swiss-dark", "nordic-frost", "dos-utility", "default"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:data-explorer-table",
    name: "数据浏览器表格 (Data Explorer Table)",
    category: "dashboard",
    description: "带列排序、行选择、粘性表头、空态与批量操作栏的高密度数据表格，是数据库客户端的核心工作面板。",
    author: "Setup Center Design Lab",
    tags: ["数据表格", "列排序", "行选择", "批量操作"],
    codeSnippet: "<div className=\"dex-root\">\n  <div className=\"dex-scroll\">\n    <table>\n      <thead><tr><th>Name</th><th>Status</th></tr></thead>\n      <tbody><tr><td>Item 1</td><td>Active</td></tr></tbody>\n    </table>\n  </div>\n</div>",
    cssRules: ".dex-root {\n  display: flex;\n  flex-direction: column;\n  min-height: 240px;\n  border: 1px solid var(--line-subtle, #e4e4e7);\n  border-radius: 8px;\n  overflow: hidden;\n  background: var(--surface-base, #ffffff);\n  font-size: 12px;\n  color: var(--text-strong, #18181b);\n}\n.dex-root table {\n  width: 100%;\n  border-collapse: collapse;\n}\n.dex-root thead th {\n  position: sticky;\n  top: 0;\n  background: var(--surface-inset, #f4f4f5);\n  padding: 7px 10px;\n  text-align: left;\n}\n.dex-root td {\n  padding: 6px 10px;\n  border-bottom: 1px solid var(--line-subtle, #f1f1f3);\n}",
    usage: "用于数据库客户端结果集、后台管理列表与安装清单盘点表。",
    targetStyles: ["academic-lab", "swiss-dark", "monochrome-research", "industrial-console"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:desktop-window-frame",
    name: "桌面窗口边框 (Desktop Window Frame)",
    category: "layout",
    description: "模拟原生桌面窗口的标题栏、窗口控件、边框焦点环与内容区的可复用外框，用于在 Web 中承载伪窗口面板。",
    author: "Setup Center Design Lab",
    tags: ["窗口隐喻", "标题栏", "焦点环", "桌面系统"],
    codeSnippet: "<section className=\"dwin\" data-active=\"true\">\n  <header className=\"dwin-bar\">\n    <div className=\"dwin-controls\">\n      <button type=\"button\" className=\"dwin-control\" data-control=\"close\" />\n      <button type=\"button\" className=\"dwin-control\" data-control=\"minimize\" />\n      <button type=\"button\" className=\"dwin-control\" data-control=\"zoom\" />\n    </div>\n    <h3 className=\"dwin-title\">App Window</h3>\n  </header>\n  <div className=\"dwin-body\">Window content...</div>\n</section>",
    cssRules: ".dwin {\n  display: flex;\n  flex-direction: column;\n  min-width: 280px;\n  border-radius: 10px;\n  overflow: hidden;\n  background: var(--surface-raised, #ffffff);\n  border: 1px solid var(--line-subtle, #d4d4d8);\n  box-shadow: 0 16px 40px rgba(0, 0, 0, 0.24);\n}\n.dwin-bar {\n  position: relative;\n  display: flex;\n  align-items: center;\n  justify-content: center;\n  height: 32px;\n  padding: 0 10px;\n  background: var(--surface-inset, #f4f4f5);\n  border-bottom: 1px solid var(--line-subtle, #d4d4d8);\n}\n.dwin-controls {\n  position: absolute;\n  left: 10px;\n  display: flex;\n  gap: 6px;\n}\n.dwin-control {\n  width: 11px;\n  height: 11px;\n  border-radius: 50%;\n  border: 1px solid rgba(0, 0, 0, 0.14);\n}\n.dwin-control[data-control='close'] { background: #ff5f57; }\n.dwin-control[data-control='minimize'] { background: #febc2e; }\n.dwin-control[data-control='zoom'] { background: #28c840; }\n.dwin-title {\n  margin: 0;\n  font-size: 12px;\n  font-weight: 500;\n  color: var(--text-muted, #52525b);\n}\n.dwin-body {\n  flex: 1;\n  padding: 16px;\n}",
    usage: "用于产品展示中的窗口拼贴、多窗口工作台与拖拽式浮层容器。",
    targetStyles: ["retro-mac", "bauhaus", "neo-brutalism", "default"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:diff-review-thread",
    name: "差异行内评审线程 (Diff Review Thread)",
    category: "feedback",
    description: "在代码差异块上挂载行内评审评论线程：锚定行号、折叠回复、解决／重开状态与逐行归属色条。",
    author: "Setup Center Design Lab",
    tags: ["代码评审", "行内评论", "线程折叠", "解决状态"],
    codeSnippet: "<div className=\"drt-root\">\n  <div className=\"drt-code\" data-kind=\"add\">\n    <span className=\"drt-gutter\">42</span>\n    <code className=\"drt-line\">+ const valid = true;</code>\n  </div>\n  <div className=\"drt-thread\">\n    <article className=\"drt-comment\">Comment body...</article>\n  </div>\n</div>",
    cssRules: ".drt-root {\n  border: 1px solid var(--line-subtle, #e4e4e7);\n  border-radius: 8px;\n  overflow: hidden;\n  background: var(--surface-base, #ffffff);\n  font-size: 12px;\n}\n.drt-code {\n  display: flex;\n  gap: 10px;\n  padding: 6px 12px;\n  font-family: ui-monospace, monospace;\n}\n.drt-code[data-kind='add'] {\n  background: rgba(34, 197, 94, 0.1);\n  border-left: 3px solid #22c55e;\n}\n.drt-thread {\n  padding: 10px 12px;\n  border-top: 1px dashed var(--line-subtle, #e4e4e7);\n  background: var(--surface-inset, #fafafa);\n}",
    usage: "用于代码评审页面、配置变更审批与文档批注审阅流程。",
    targetStyles: ["monochrome-research", "nordic-frost", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:editorial-index-page",
    name: "排印字母索引页 (Editorial Index Page)",
    category: "navigation",
    description: "以巨型字母分节、粘性字母头与密集多栏条目组成的书刊式索引页，适合超大目录的可扫读浏览。",
    author: "Setup Center Design Lab",
    tags: ["字母索引", "多栏排印", "粘性标题", "书刊式"],
    codeSnippet: "<div className=\"eidx-root\">\n  <nav className=\"eidx-jump\">A B C D E F...</nav>\n  <section className=\"eidx-section\">\n    <h3 className=\"eidx-letter\">A</h3>\n    <ul className=\"eidx-list\"><li>Entry 1</li></ul>\n  </section>\n</div>",
    cssRules: ".eidx-root {\n  max-width: 1080px;\n  margin: 0 auto;\n  padding: 32px 24px;\n  font-family: serif;\n  color: var(--text-strong, #141414);\n}\n.eidx-section {\n  display: grid;\n  grid-template-columns: 96px 1fr;\n  gap: 24px;\n  padding: 24px 0;\n  border-bottom: 1px solid var(--line-subtle, #e4e4e7);\n}\n.eidx-letter {\n  font-size: 56px;\n  font-weight: 700;\n}\n.eidx-list {\n  columns: 3 220px;\n  gap: 32px;\n  list-style: none;\n}",
    usage: "用于术语表、资源总目录、字体／图标库检索页与文档附录。",
    targetStyles: ["swiss-editorial", "newspaper-editorial", "japanese-editorial", "academic-lab"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:graph-canvas-network",
    name: "关系图谱画布 (Graph Canvas Network)",
    category: "dashboard",
    description: "以 SVG 力导向布局渲染节点与连边的关系画布，支持节点拖拽、选中高亮与邻接关系弱化。",
    author: "Setup Center Design Lab",
    tags: ["关系图谱", "力导向布局", "SVG连线", "邻接高亮"],
    codeSnippet: "<svg className=\"gcn-root\" viewBox=\"0 0 640 400\">\n  <g className=\"gcn-edges\"><line x1=\"100\" y1=\"100\" x2=\"200\" y2=\"200\" /></g>\n  <g className=\"gcn-nodes\"><circle cx=\"100\" cy=\"100\" r=\"18\" /></g>\n</svg>",
    cssRules: ".gcn-root {\n  width: 100%;\n  background: var(--surface-inset, #0a0b10);\n  border: 1px solid var(--line-subtle, #1e2230);\n  border-radius: 10px;\n}\n.gcn-edges line {\n  stroke: var(--line-strong, #334155);\n  stroke-width: 1.2;\n}\n.gcn-node circle {\n  fill: var(--surface-raised, #171c26);\n  stroke: var(--accent, #6366f1);\n  stroke-width: 1.5;\n  cursor: grab;\n}",
    usage: "用于依赖关系图、知识图谱浏览模块与模块耦合可视化。",
    targetStyles: ["cyber-neon", "swiss-dark", "blueprint", "academic-lab"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:ide-layout",
    name: "集成开发环境三区布局 (IDE Layout)",
    category: "layout",
    description: "完整的 IDE 骨架：细窄活动栏、可折叠资源侧栏、带标签页的编辑主区与底部输出面板，适合承载高密度工程信息。",
    author: "Setup Center Design Lab",
    tags: ["IDE布局", "多面板", "标签页", "工程化"],
    codeSnippet: "<div className=\"ide-root\">\n  <nav className=\"ide-activity\">...</nav>\n  <aside className=\"ide-sidebar\">...</aside>\n  <main className=\"ide-editor\">...</main>\n  <section className=\"ide-panel\">...</section>\n</div>",
    cssRules: ".ide-root {\n  display: grid;\n  grid-template-columns: 48px 260px 1fr;\n  grid-template-rows: 1fr auto;\n  height: 100%;\n  min-height: 460px;\n  background: var(--surface-inset, #0b0d12);\n  color: var(--text-strong, #d5dae6);\n}\n.ide-activity {\n  background: var(--surface-base, #0e1116);\n  border-right: 1px solid var(--line-subtle, #1e2230);\n}\n.ide-sidebar {\n  overflow-y: auto;\n  border-right: 1px solid var(--line-subtle, #1e2230);\n}\n.ide-editor {\n  display: flex;\n  flex-direction: column;\n}\n.ide-panel {\n  grid-column: 1 / -1;\n  border-top: 1px solid var(--line-subtle, #1e2230);\n}",
    usage: "用于代码编辑器、日志分析台与任何需要同时呈现导航／内容／输出的专业工具。",
    targetStyles: ["swiss-dark", "retro-mac", "monochrome-research", "nordic-frost"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:inspector-panel",
    name: "属性检查器面板 (Inspector Panel)",
    category: "inspector",
    description: "按语义分组展示选中对象全部可编辑属性的侧栏检查器，支持分段、切换、数值步进与只读元数据行。",
    author: "Setup Center Design Lab",
    tags: ["属性检查器", "表单分组", "元数据", "设计工具"],
    codeSnippet: "<div className=\"insp-root\">\n  <header className=\"insp-head\"><strong>1 object</strong></header>\n  <section className=\"insp-group\">\n    <div className=\"insp-row\"><label>Width</label><input type=\"number\" value={120} /></div>\n  </section>\n</div>",
    cssRules: ".insp-root {\n  width: 280px;\n  height: 100%;\n  overflow-y: auto;\n  padding: 16px;\n  background: var(--surface-base, #ffffff);\n  border-left: 1px solid var(--line-subtle, #e6e7eb);\n  font-size: 12px;\n}\n.insp-row {\n  display: grid;\n  grid-template-columns: 88px 1fr;\n  align-items: center;\n  gap: 8px;\n  padding: 3px 0;\n}\n.insp-row input {\n  width: 100%;\n  padding: 4px 6px;\n  border-radius: 5px;\n  border: 1px solid var(--line-subtle, #e6e7eb);\n}",
    usage: "用于设计工具属性栏、选中节点配置面板与对象详情编辑区。",
    targetStyles: ["soft-product-minimal", "spatial-glass", "nordic-frost", "swiss-editorial"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:knowledge-browser-wiki",
    name: "知识库浏览视图 (Knowledge Browser)",
    category: "navigation",
    description: "由面包屑导航、目录侧栏、正文排版区与反向链接页脚组成的知识库阅读视图，适合长文档与术语互联。",
    author: "Setup Center Design Lab",
    tags: ["知识库", "面包屑", "目录导航", "反向链接"],
    codeSnippet: "<div className=\"kbw-root\">\n  <nav className=\"kbw-breadcrumb\">Docs / Guide</nav>\n  <div className=\"kbw-body\">\n    <aside className=\"kbw-toc\">Table of Contents...</aside>\n    <article className=\"kbw-prose\">Article body...</article>\n  </div>\n</div>",
    cssRules: ".kbw-root {\n  max-width: 1100px;\n  margin: 0 auto;\n  padding: 24px;\n  color: var(--text-strong, #1a1a1a);\n}\n.kbw-body {\n  display: grid;\n  grid-template-columns: 200px 1fr;\n  gap: 40px;\n  padding-top: 28px;\n}\n.kbw-toc {\n  position: sticky;\n  top: 24px;\n  font-size: 11px;\n}\n.kbw-prose {\n  max-width: 68ch;\n  font-size: 15px;\n  line-height: 1.75;\n}",
    usage: "用于内部 Wiki、术语解释页、模式文档详读与学习资料阅读器。",
    targetStyles: ["academic-lab", "japanese-editorial", "swiss-editorial", "monochrome-research"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:resizable-split-view",
    name: "可拖拽分割视窗 (Resizable Split View)",
    category: "layout",
    description: "带可抓取分隔条的等比双区视图，支持指针拖拽、键盘微调、比例钳制与双击复位，是最基础的桌面级空间分配原语。",
    author: "Setup Center Design Lab",
    tags: ["分割视窗", "拖拽分隔条", "比例钳制", "可访问性"],
    codeSnippet: "<div className=\"rsv-root\">\n  <div className=\"rsv-pane\" style={{ flexBasis: '36%' }}>Left</div>\n  <div className=\"rsv-handle\" role=\"separator\" tabIndex={0} />\n  <div className=\"rsv-pane\" style={{ flexBasis: '64%' }}>Right</div>\n</div>",
    cssRules: ".rsv-root {\n  display: flex;\n  height: 100%;\n  overflow: hidden;\n}\n.rsv-pane {\n  min-width: 0;\n  overflow: auto;\n  padding: 16px;\n}\n.rsv-handle {\n  flex: 0 0 6px;\n  cursor: col-resize;\n  background: var(--line-subtle, #e5e7eb);\n  transition: background 0.15s ease;\n}\n.rsv-handle:hover, .rsv-handle:focus-visible {\n  background: var(--accent, #6366f1);\n  outline: none;\n}",
    usage: "用于编辑器多栏、配置对比、主从视图以及任何需要用户自定义空间分配的界面。",
    targetStyles: ["default", "swiss-dark", "nordic-frost", "retro-mac"],
    updatedAt: "2026-10-04",
  },
  {
    id: "pat:timeline-ruler",
    name: "水平时间刻度尺 (Timeline Ruler)",
    category: "timeline",
    description: "带刻度线、主次二级标签、可拖拽游标与跨度区间高亮的时间标尺，用于在时间轴上定位与选取区间。",
    author: "Setup Center Design Lab",
    tags: ["时间轴", "刻度尺", "区间选择", "游标"],
    codeSnippet: "<div className=\"tlr-root\">\n  <div className=\"tlr-track\" role=\"slider\" tabIndex={0}>\n    <div className=\"tlr-cursor\"><span className=\"tlr-readout\">50</span></div>\n  </div>\n  <div className=\"tlr-labels\"><span>0</span><span>50</span><span>100</span></div>\n</div>",
    cssRules: ".tlr-root {\n  position: relative;\n  padding: 24px 0;\n  background: var(--surface-inset, #0c0e13);\n  border-radius: 8px;\n  border: 1px solid var(--line-subtle, #1e2230);\n}\n.tlr-track {\n  position: relative;\n  height: 34px;\n  margin: 0 16px;\n  cursor: crosshair;\n}\n.tlr-cursor {\n  position: absolute;\n  width: 2px;\n  background: var(--accent, #e2e8f0);\n}",
    usage: "用于性能火焰图、部署历史回溯、音视频剪辑轨与监控时间窗选择。",
    targetStyles: ["industrial-console", "monochrome-research", "swiss-dark", "academic-lab"],
    updatedAt: "2026-10-04",
  },
];
