import type { VaultSkillItem } from "../types";

export const BUNDLED_SKILLS: VaultSkillItem[] = [
  {
    id: "skill:transfer-resource",
    name: "Transfer External Resource to Setup Vault",
    description: "Agent recipe for fetching an external URL, extracting metadata (name, description, author, license, repo, stars), classifying category, and generating a normalized resource entry.",
    author: "Setup Center Agent Guide",
    tags: ["agent", "transfer", "resource", "normalization"],
    prompt: "When given a URL to transfer into Setup Center:\n1. Fetch the webpage content or GitHub repository metadata.\n2. Extract: name, description (concise Chinese translation/summary), author, license, stars, tags, actionType.\n3. Write a recommendedReason highlighting why this tool is indispensable.\n4. Save as a JSON entry adhering to schemas/resource.schema.json.\n5. Append to the corresponding category JSON and update manifest.json.",
    tools: ["read_url_content", "write_to_file"],
    updatedAt: "2026-10-02",
  },
  {
    id: "skill:code-review-audit",
    name: "代码审查与架构坏味道侦测 (Code Review & Architecture Audit)",
    description: "自动化走查代码库中的耦合异味、未捕获异常、反模式以及并发/内存安全隐患，输出可执行重构方案。",
    author: "Setup Center Agent Guide",
    tags: ["代码审查", "架构重构", "异味消除", "工程质量"],
    prompt: "作为资深架构师执行代码审查：\n1. 检查是否存在全局状态污染、循环依赖或违反关注点分离（SoC）的设计。\n2. 检查异步流（async/await）是否有未处理的 reject，资源句柄（文件/网络连接）是否有显式释放。\n3. 重点标注魔数、长函数（>60行）、深层嵌套（>3层），给出具体抽取函数或模式重构的 diff 示范。",
    tools: ["read_file", "search_code"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:ui-ux-distill",
    name: "前端界面走查与去玩具化精修 (UI/UX Distill & De-Toying)",
    description: "系统化消除界面中的廉价 Emoji 堆砌、同质化卡片布局与粗糙内边距，确立严谨字阶、微对比与触感微交互。",
    author: "Setup Center Design Lab",
    tags: ["UI走查", "去玩具化", "设计系统", "排印节律"],
    prompt: "对指定前端页面执行精修审计：\n1. 移除滥用 Emoji 的装饰，替换为语义化微指示器或精细 SVG 状态点。\n2. 检查字阶比例（Type Scale），确保标题、正文、小说明之间字重与对比度明确。\n3. 检查卡片和容器的 Padding 与 Gap 节律（统一采用 4px/8px 网格系统）。\n4. 确认在极端分辨率或长文本下的换行与省略策略，避免破卡与溢出。",
    tools: ["read_file", "replace_file_content"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:git-workflow-triage",
    name: "Git 历史清理与分支规范审计 (Git Workflow Triage)",
    description: "规范化 Conventional Commits 提交历史，排查误提交的大文件或敏感配置，确保版本标签与发布分支一致性。",
    author: "Setup Center Agent Guide",
    tags: ["Git规范", "Conventional Commits", "分支治理", "发布审计"],
    prompt: "对当前代码仓库执行 Git 历史与状态排查：\n1. 检查是否存在未加入 .gitignore 的构建临时文件（如 dist/、target/、.log）。\n2. 验证近期 Commit 是否严格遵循 Conventional Commits 格式（feat: / fix: / refactor: / docs:）。\n3. 检查远程分支与本地主干是否同步，确保无未合并的落后变更。",
    tools: ["run_command"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:dependency-upgrade",
    name: "依赖安全升级与破坏性改动迁移 (Dependency Upgrade & Migration)",
    description: "扫描项目中的过时或存在已知 CVE 漏洞的第三方包，评估重大版本升级破坏性改动并自动生成平滑升级方案。",
    author: "Setup Center Agent Guide",
    tags: ["依赖审计", "版本升级", "安全漏洞", "破坏性迁移"],
    prompt: "对项目的 package.json / Cargo.toml 进行升级与安全性分析：\n1. 检查各依赖包的当前版本与最新稳定版本差值，识别是否存在 Major 跨大版本跃迁。\n2. 阅读主流核心依赖（如 React 19、Vite 6、Tauri v2）官方 Migration Guide，提炼出破损 API 的对应新语法替换表。\n3. 在隔离分支中更新锁文件并运行构建测试套件，确认无构建回归后合并。",
    tools: ["run_command", "read_file", "replace_file_content"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:style-extractor",
    name: "视觉灵感风格提炼与 Token 规范化 (Style Extraction & Tokenization)",
    description: "分析优质网站或设计作品的调色盘、几何轮廓、字体层级与质感硬阴影，直接抽取生成 Setup Center 规范的 SetupStyle 清单与 CSS 文件。",
    author: "Setup Center Design Lab",
    tags: ["视觉提炼", "设计Token", "CSS生成", "风格规范"],
    prompt: "从指定设计作品或网页中提取完整设计语言：\n1. 提炼 5 个核心基础色彩：bg-primary, surface, text-primary, accent, border。\n2. 确定圆角（Border Radius）与投影（Box Shadow）策略：例如硬黑实心阴影、零圆角或大圆角高透毛玻璃。\n3. 生成匹配 SetupStyle 契约的 manifest.json 与同名 CSS 覆盖规则，确保在全局容器上作用于 [data-style='...']。",
    tools: ["read_url_content", "write_to_file"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:perf-lighthouse-audit",
    name: "Web 性能与关键渲染路径分析 (Web Perf & Critical Rendering Path)",
    description: "分析前端应用首屏载入耗时、首内容绘制（FCP）、最大内容绘制（LCP）与累计布局偏移（CLS），优化静态资源与分块策略。",
    author: "Setup Center Agent Guide",
    tags: ["性能分析", "Web性能", "LCP", "代码分割"],
    prompt: "对前端打包输出与渲染路径执行诊断：\n1. 审查打包产物体积（dist 目录 chunk 分析），标记单文件超过 500kB 的模块。\n2. 引入路由级懒加载与动态 import()，将大型低频模块（如三维引擎、重型画板）拆解为独立分块。\n3. 优化静态图片格式与尺寸（转换为 WebP / AVIF），减少首屏网络阻塞与资源争用。",
    tools: ["run_command", "view_file"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:tauri-bundle-optimize",
    name: "Tauri 桌面端安装包体积与 CSP 审计 (Tauri Bundle & CSP Audit)",
    description: "精简 Tauri 应用的打包体积，检查 Windows NSIS 与 Linux AppImage 构建配置，严格审计 Content Security Policy 与 IPC 权限边界。",
    author: "Setup Center Agent Guide",
    tags: ["Tauri", "桌面端打包", "体积优化", "CSP安全"],
    prompt: "审计 Tauri 桌面端工程架构配置：\n1. 检查 `src-tauri/Cargo.toml` 中 release profile 设置（启用 `lto = true`, `opt-level = 'z'`, `strip = true`）。\n2. 审查 `tauri.conf.json` 中的 `security.csp`，消除过于宽泛的 `*` 允许域，精准限制外部请求白名单。\n3. 检查 NSIS 安装器资源包含规则，避免多余测试 fixtures 或无用静态图打包入最终安装包。",
    tools: ["view_file", "replace_file_content"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:agent-prompt-craft",
    name: "高自主权 Agent 系统提示词工程 (Autonomous Agent Prompt Craft)",
    description: "编写自解释、具备严密上下文局部性（Context Locality）与长周期自主执行策略的 Agent 规范与规则提示词。",
    author: "Setup Center Agent Guide",
    tags: ["Agent系统", "系统提示词", "上下文局部性", "自主执行"],
    prompt: "设计面向复杂工程的 Agent 指南：\n1. 明确定义项目定位与统一生命周期，防止 Agent 在执行中发生定位漂移。\n2. 设立路由表（Task Routing），引导 Agent 优先读取最小局部文档，禁止暴力全仓扫描。\n3. 制定 Golden Rules，明确禁止与推荐的反模式（如页面禁止硬编码 style 判断，必须由样式契约声明式驱动）。",
    tools: ["write_to_file"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:api-design-restful",
    name: "RESTful 与 RPC 接口契约设计规范 (API Contract Design)",
    description: "基于 OpenAPI 3.1 或 Type-safe RPC 制定高自解释、无歧义的跨服务数据交换契约与统一错误状态码。",
    author: "Setup Center Agent Guide",
    tags: ["API契约", "OpenAPI", "Type-safe RPC", "自解释规范"],
    prompt: "设计微服务与客户端数据交互协议：\n1. 采用名词复数代表资源路径（如 `/api/v1/resources`），HTTP 动词映射 CRUD 语义。\n2. 错误响应统一包含：`code` (机器可识别错误枚举)、`message` (人类友好说明)、`details` (字段校验错误列表)。\n3. 导出 TypeScript 纯类型声明或生成 SDK，实现前后端联调时的编译期类型约束。",
    tools: ["write_to_file"],
    updatedAt: "2026-10-03",
  },
  {
    id: "skill:accessibility-audit",
    name: "Accessibility Audit & Remediation",
    description: "Audit a UI for WCAG 2.2 AA compliance — keyboard reachability, semantics, contrast, focus management and screen-reader output — then produce concrete patches.",
    author: "Setup Center Agent Guide",
    tags: ["accessibility", "wcag", "a11y", "keyboard", "screen-reader"],
    prompt: "You are performing a WCAG 2.2 AA accessibility audit. For each finding, give the criterion number, the offending code with file and line, and the exact replacement.\n1. SEMANTICS: every interactive thing must be a real button, link, input or select — not a div with onClick. Check for `<div onClick>` and `<span onClick>` and replace with `<button type=\"button\">`. Heading levels must not skip (h1 → h3).\n2. KEYBOARD: tab through every interactive element. Confirm no keyboard trap, visible focus on every stop, and that focus order matches visual order. Custom widgets need `tabIndex={0}` plus arrow-key handling and `role=\"separator\"` / `role=\"listbox\"` / `role=\"menu\"` as appropriate.\n3. NAMES: every control needs an accessible name — visible text, `aria-label`, or `aria-labelledby`. Icon-only buttons are the usual offender. Every `<img>` needs a meaningful `alt` (or `alt=\"\"` for decorative). Form inputs need a real `<label htmlFor>`.\n4. STATE: toggles must expose `aria-pressed` or `aria-checked`; expanders `aria-expanded`; current page `aria-current`; live regions `aria-live=\"polite\"` for async status. Errors must be linked with `aria-describedby` and announced, not just coloured.\n5. CONTRAST: body text needs 4.5:1, large text (≥24px or ≥19px bold) 3:1, and UI boundaries 3:1. Name the exact foreground/background pairs that fail and give a corrected hex for each.\n6. MOTION & TIME: honour `prefers-reduced-motion`; give a pause control for anything auto-playing longer than 5 seconds.\nOutput a severity-ranked table (Critical / Serious / Moderate / Minor), then the patch for each Critical and Serious item. Re-read your patch and confirm it introduces no new focusable-but-unlabelled element.",
    tools: ["read_file", "grep_search", "write_to_file"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:cli-tool-authoring",
    name: "CLI Tool Authoring",
    description: "Design and implement a command-line tool with composable subcommands, correct exit codes, machine-readable output, and a discoverable help system.",
    author: "Setup Center Agent Guide",
    tags: ["cli", "argument-parsing", "exit-codes", "stdout", "developer-tools"],
    prompt: "You are building a command-line tool. A CLI is an interface with contracts — treat stdout, stderr, exit codes and flags as API surface.\n1. SHAPE: decide one tool with subcommands (`tool verify`, `tool sync`) versus many tools. Prefer subcommands when the verbs share config and state. Name flags with the GNU convention and provide a long form for every short form.\n2. STREAMS: machine-readable output goes to stdout and nothing else does. Progress, warnings, prompts and diagnostics go to stderr. This is what makes `tool list --json | jq` work — verify it by actually piping the output.\n3. EXIT CODES: 0 success, 1 general failure, 2 usage error, and distinct codes for distinct failure classes your callers must branch on. Never exit 0 after a partial failure.\n4. CONFIG RESOLUTION: define precedence explicitly — flag > environment variable > project config > user config > default. Print the resolved configuration under a `--verbose` flag so users can see which layer won.\n5. NON-INTERACTIVE MODE: detect a non-TTY (`!process.stdout.isTTY`) and disable colour, spinners and prompts; fail with a clear message rather than hanging when input is required. Honour `NO_COLOR`, `CI` and `--yes`.\n6. HELP: every command answers `--help` with usage, description, every flag and a real example. The top-level help lists subcommands. Test the help path — it is the most-run command and the least tested.\n7. IDEMPOTENCE: destructive operations need a dry-run flag and a confirmation that the caller can bypass non-interactively. Make re-running safe.\nDeliver the implementation plus the exact shell commands that prove each contract above (piped stdout, non-TTY run, bad-flag exit code, dry run).",
    tools: ["read_file", "write_to_file", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:db-schema-migration",
    name: "Database Schema Migration",
    description: "Plan and execute a safe, reversible schema migration for a relational database, including backfill strategy, lock analysis and rollback path.",
    author: "Setup Center Agent Guide",
    tags: ["database", "migration", "sql", "rollback", "zero-downtime"],
    prompt: "You are performing a production database schema migration. Work through the following before writing any SQL:\n1. INVENTORY: read the current schema (migrations directory, models, or `\\d+` output). List every table, column, index and foreign key the change touches.\n2. CLASSIFY the change: additive (new nullable column, new table, new index) vs destructive (drop, rename, type narrowing, NOT NULL on existing column). Destructive changes require a multi-step, multi-deploy sequence.\n3. EXPAND/CONTRACT: for anything destructive, split into (a) expand — add the new shape and dual-write, (b) backfill — copy data in bounded batches (LIMIT 1000 with a sleep, never one UPDATE over the whole table), (c) contract — drop the old shape only after the application no longer reads it.\n4. LOCK RISK: state the lock each DDL statement takes. Flag `ALTER TABLE ... SET NOT NULL`, adding a non-concurrent index, and column type changes — on PostgreSQL use CREATE INDEX CONCURRENTLY, add NOT NULL via a CHECK constraint validated separately.\n5. MIGRATION FILE: emit the migration in the project's existing tool (Prisma / Alembic / Knex / Flyway / raw .sql), matching the file naming convention already in the repo.\n6. ROLLBACK: write the down-migration and prove it is the exact inverse. If a step cannot be reversed (dropped column), say so explicitly and propose a backup step instead.\n7. VERIFY: give the exact queries that confirm success — row counts before/after, orphan check for new foreign keys, and a sample SELECT across the new shape.\nOutput the migration file, the rollback file, and a numbered runbook of the deploy steps with the verification query after each step.",
    tools: ["read_file", "write_to_file", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:design-token-extraction",
    name: "Design Token Extraction",
    description: "Mine a codebase or design source for colour, spacing, typography and radius values, then emit a normalised three-layer token set with CSS variables.",
    author: "Setup Center Agent Guide",
    tags: ["design-tokens", "css-variables", "theming", "audit", "design-system"],
    prompt: "You are extracting a design-token set from an existing codebase. The goal is a system that explains the values, not a dump of every hex you found.\n1. HARVEST: grep every hard-coded value — hex colours, `rgb()`/`hsl()`/`oklch()`, `px`/`rem` spacing, `font-size`, `font-weight`, `border-radius`, `box-shadow`, `z-index`, and transition durations. Collect frequencies; the design system is hiding in the values that repeat.\n2. CLUSTER: group near-duplicates (`#1a1a1a` and `#1b1b1b` and `#181818` are one token). Report the merge and the count of occurrences each absorbed — a value used once is probably not a token.\n3. THREE LAYERS: emit primitive tokens (raw scale: `--gray-900: #18181b`), semantic tokens (`--surface-base: var(--gray-50)`, `--text-muted: var(--gray-600)`), and component tokens only where a component genuinely diverges. Semantic tokens are what themes swap; components must never reference primitives directly.\n4. NAME BY ROLE, NOT APPEARANCE: `--state-danger` not `--red`. A theme that swaps light for dark must not need to rename tokens.\n5. DARK MODE: express theming by remapping semantic tokens under a selector, never by duplicating component CSS. Verify every semantic token has a dark counterpart and that contrast still passes in both modes.\n6. MIGRATE: give the replacement table (old literal → token name) and the count of replacements per file, ordered by file, so the change can be applied incrementally and reviewed.\n7. EMIT: CSS custom properties in `:root`, plus a JSON manifest of the same tokens for tooling. Report any value you could not confidently tokenise with the reason (one-off layout arithmetic, vendor overrides).",
    tools: ["read_file", "grep_search", "write_to_file"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:fuzzing-property-tests",
    name: "Fuzzing & Property-Based Testing",
    description: "Replace example-based tests with property-based and fuzz tests — identify invariants, generate inputs, shrink failures, and pin regressions.",
    author: "Setup Center Agent Guide",
    tags: ["testing", "fuzzing", "property-based", "invariants", "shrinking"],
    prompt: "You are hardening a module with property-based and fuzz testing. The value is in the invariants, not the coverage number.\n1. FIND INVARIANTS: read the module and state properties that must hold for ALL inputs — round-trip (`decode(encode(x)) === x`), idempotence (`f(f(x)) === f(x)`), commutativity, monotonicity, ordering, size bounds, and the algebraic laws of any abstraction (monoid identity, functor laws for map).\n2. CHOOSE THE FRAMEWORK the project already uses or the ecosystem default — fast-check (TS/JS), Hypothesis (Python), proptest/quickcheck (Rust), jqwik (Java), go test -fuzz (Go). Do not add a second property-test library if one is present.\n3. GENERATORS: build inputs from primitives up with combinators, and constrain them to the valid domain (non-empty strings, sorted arrays, bounded integers). Include the hard cases: empty collections, zero, negative, maximum, unicode including astral-plane characters, and duplicate keys.\n4. FIND THE COUNTEREXAMPLE, THEN SHRINK: when a property fails, let the framework shrink and report the minimal case. Reproduce that minimal case as a plain deterministic unit test — the property test proves the law, the regression test pins the exact bug.\n5. FOR PARSERS AND DECODERS add a true fuzz target that feeds arbitrary bytes and asserts only two outcomes: success or a clean error. A panic, hang, or unbounded memory on malformed input is a bug — record the crashing input as a corpus seed.\n6. BOUND THE SEARCH: set a run count and a seed so failures are reproducible in CI, and print the seed on failure.\nReport each property you tested, whether it held, and for every failure the minimized counterexample and the regression test you added.",
    tools: ["read_file", "write_to_file", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:i18n-localisation",
    name: "Internationalisation & Localisation",
    description: "Extract hard-coded strings into a message catalogue, wire a runtime i18n layer, and handle plurals, dates, numbers, RTL and layout expansion.",
    author: "Setup Center Agent Guide",
    tags: ["i18n", "l10n", "translation", "rtl", "pluralisation"],
    prompt: "You are internationalising an application. Do the mechanics correctly rather than transliterating English word-for-word.\n1. EXTRACT: find every user-visible hard-coded string (JSX text, `placeholder`, `title`, `aria-label`, toast and error copy). Produce a key per string in the project's existing catalogue format (JSON, .po, ARB — match what exists). Use namespaced, semantic keys (`vault.sync.failed`), never English sentences as keys.\n2. INTERPOLATE, DON'T CONCATENATE: replace `\"Found \" + n + \" items\"` with a single message containing named placeholders (`{count}`). String concatenation is the primary cause of untranslatable UI.\n3. PLURALS: use the platform plural mechanism (ICU MessageFormat, `Intl.PluralRules`, i18next `_one`/`_other`) with `one` and `other` at minimum; add `few`/`many` where the target language needs them (Polish, Russian, Arabic). Never `n === 1 ? a : b`.\n4. FORMATTING: dates, times, numbers and currency must go through `Intl.DateTimeFormat` / `Intl.NumberFormat` with the active locale — never `toLocaleString()` with no argument and never hand-rolled `MM/DD/YYYY`.\n5. RTL: replace physical CSS (`margin-left`, `left`, `text-align: left`) with logical properties (`margin-inline-start`, `inset-inline-start`, `text-align: start`). Set `dir=\"rtl\"` on the root and verify icons that imply direction (arrows, chevrons) are mirrored.\n6. LAYOUT: translated text expands up to ~35% versus English and German compounds can double. Replace fixed widths and `white-space: nowrap` on labels with min-width plus wrapping, and confirm no truncation.\n7. VERIFY: run the build with a pseudo-locale that pads strings, then confirm no clipped text, no missing key and no leaked placeholder.\nOutput the extraction diff, the new catalogue file, and a list of any string you deliberately left untranslated (log formats, CSS class names, API keys) with the reason.",
    tools: ["read_file", "grep_search", "write_to_file"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:llm-cost-perf-profiling",
    name: "LLM Cost & Performance Profiling",
    description: "Measure and reduce the cost and latency of an LLM-backed feature — token accounting, prompt-cache economics, routing, and verified before/after numbers.",
    author: "Setup Center Agent Guide",
    tags: ["llm", "cost", "latency", "caching", "profiling"],
    prompt: "You are profiling an LLM-backed feature for cost and latency. Every recommendation must come with a measured before/after number, not an estimate.\n1. ACCOUNT TOKENS PROPERLY: separate input, cached-input, and output tokens. They are priced differently — often by an order of magnitude. A 90% cache hit rate on input changes the bill far more than shaving prose.\n2. BUILD A COST MODEL before optimising: tokens per call × calls per user action × calls per session, priced at the current rates. State which term dominates. Optimising the small term is the classic waste.\n3. CACHE ECONOMICS: prompt caching has a write cost, a read discount and a TTL. Compute the breakeven number of reuses. If the prefix is reused fewer times than the breakeven, caching loses money — say so and do not enable it.\n4. LOCATE THE LATENCY: measure time-to-first-token separately from total duration. TTFT is dominated by prefill (input length, cache misses); total is dominated by decode (output tokens). Fixing the wrong one leaves the user experience unchanged.\n5. REDUCE THE DOMINANT TERM: trim or retrieve context instead of stuffing; stream so perceived latency tracks TTFT; cap `max_tokens` to the task's real ceiling; batch independent calls; route easy requests to a smaller model and reserve the large model for the hard tail.\n6. VERIFY QUALITY: cost cuts that degrade output are not savings. Hold a fixed eval set and report the quality delta alongside the cost delta. A 40% cheaper path that drops accuracy 15 points is a regression.\n7. REPORT: a table of input/output tokens, cache hit rate, TTFT, total latency, cost per call and cost per user action — before and after, with the eval score in the same table.",
    tools: ["read_file", "run_command", "write_to_file"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:log-diff-forensics",
    name: "Log & Diff Forensics",
    description: "Diagnose an unexplained change by forensic comparison — normalise and diff logs, trace a value back through the code, and identify the exact introducing change.",
    author: "Setup Center Agent Guide",
    tags: ["forensics", "logs", "diff", "regression", "root-cause"],
    prompt: "You are doing forensic diagnosis — something changed and nobody knows why. Work from evidence to cause, never cause to evidence.\n1. NORMALISE FIRST: raw log diffing produces noise. Strip timestamps, pids, threads, request ids, durations, memory addresses and ports; sort where order is not meaningful. Only after normalisation is a diff readable.\n2. BISECT THE AXIS: is the change temporal (worked yesterday), environmental (works on my machine), data-dependent (fails on one tenant), or version-dependent? Pick whichever axis is cheapest to bisect and eliminate the others by evidence, not assumption.\n3. VALUE TRACE: take one concrete failing value and trace it backwards — where was it written, what transformed it, where did it first become wrong? Stop at the first point where the value is already incorrect; that is your suspect.\n4. BLAME WITH EVIDENCE: `git log -S'<string>'`, `git log -L:<start>,<end>:<file>` and `git blame` locate the introducing commit. Read that commit's full diff, not just the matching line, and check whether it changed an assumption elsewhere.\n5. ENVIRONMENT DELTA: diff dependency lockfiles, config files and runtime versions between working and failing. A patch-level dependency bump or a changed default is a common cause and is invisible in application code.\n6. STATE YOUR CONFIDENCE: for each conclusion say whether it is proven by a reproduction, supported by a log line, or merely the leading hypothesis. Propose the single experiment that would distinguish the top two hypotheses.\nOutput: the normalised diff excerpt that shows the change, the suspect commit or config delta with evidence, the causal chain, and the one experiment that would confirm it.",
    tools: ["read_file", "grep_search", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:observability-incident-triage",
    name: "Observability & Incident Triage",
    description: "Triage a production incident from logs, metrics and traces — establish a timeline, isolate the failing dependency, and produce a blameless postmortem skeleton.",
    author: "Setup Center Agent Guide",
    tags: ["observability", "incident", "logs", "metrics", "postmortem"],
    prompt: "You are triaging a live production incident. Do not guess — every claim must cite a log line, metric name or trace id.\n1. TIMELINE: establish T0. Find the first anomalous log line or alert and the last known-good minute. Build a timestamped list of events (deploy, config change, traffic shift, dependency error) in UTC.\n2. CORRELATE: pull the error signature (exact message + stack frame) and count occurrences over time. Distinguish a step change from a gradual drift. A step change within minutes of a deploy points at that deploy; a gradual rise points at a leak, disk fill or dependency latency.\n3. BLAST RADIUS: which endpoints, tenants, regions and versions are affected? Which are explicitly healthy? State the boundary — this constrains cause more than anything else.\n4. BISECT: if a deploy is implicated, identify the smallest change set between the last good and first bad release. Check whether the failure reproduces on a rollback.\n5. MITIGATE FIRST: propose the fastest reversible action (rollback, feature-flag off, scale out, circuit-break, drain). Only after mitigation, work the root cause.\n6. POSTMORTEM: write a blameless skeleton — Impact (who was affected, how long, how badly), Root cause (one paragraph, mechanism not blame), Detection (what noticed it and how late), Response (what worked, what was manual), and Action items each with an owner-shaped description and a class (prevent / detect / mitigate).\nNever state a root cause as fact unless you have a reproduction or a direct log line proving the causal chain. Mark hypotheses as hypotheses.",
    tools: ["read_file", "grep_search", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:refactor-in-place",
    name: "Refactor In Place (Behaviour Preserving)",
    description: "Restructure existing code without changing observable behaviour — lock behaviour with tests first, refactor in small verified steps, and prove equivalence.",
    author: "Setup Center Agent Guide",
    tags: ["refactor", "behaviour-preserving", "tests", "incremental", "safety"],
    prompt: "You are refactoring existing working code. The invariant is: observable behaviour does not change. Functionality changes are out of scope — if you find a bug, note it and fix it separately.\n1. LOCK BEHAVIOUR FIRST: before touching the code, ensure tests cover the paths you will move. If coverage is thin, write characterisation tests that record current output — including the current quirks. A refactor that changes a quirk is a behaviour change.\n2. GET A BASELINE: run the full test suite and record the exact result. A refactor that starts from a red suite cannot prove anything.\n3. SMALL STEPS: each step is independently compilable and testable — extract function, introduce parameter, move to module, replace conditional with polymorphism, collapse hierarchy. Do not combine rename + move + signature change in one step.\n4. MECHANICAL TRANSFORMS: prefer the language server / codemod / IDE rename over hand editing. When editing by hand, grep for every reference (including string references, dynamic imports, reflection, serialised names and config files) before renaming.\n5. TEST AFTER EVERY STEP: keep the suite green throughout. If it goes red, revert that one step rather than fixing forward — fixing forward risks silently changing behaviour.\n6. PROVE EQUIVALENCE at the end: run the same tests, the same type check, and the same lint as the baseline. Report bench numbers before/after if the code is on a hot path — a refactor that makes it 3× slower is a regression even if tests pass.\nReport: the baseline result, each step with its position on the hot path or not, the final test/type/lint result, and every reference you had to update manually because a tool could not find it.",
    tools: ["read_file", "write_to_file", "run_command"],
    updatedAt: "2026-10-04",
  },
  {
    id: "skill:release-engineering",
    name: "Release Engineering & Versioning",
    description: "Cut a release correctly — determine the semantic version bump from the change set, generate the changelog, tag, and verify the published artifact.",
    author: "Setup Center Agent Guide",
    tags: ["release", "semver", "changelog", "tagging", "publishing"],
    prompt: "You are cutting a release. Do not invent a version number — derive it.\n1. CHANGE SET: diff from the last tag to HEAD (`git log <last-tag>..HEAD --oneline`, `git diff --stat`). Classify every commit as breaking, feature or fix.\n2. VERSION: apply semver to the classification. Breaking → major, feature → minor, fix only → patch. For 0.x versions state explicitly that minor may break and confirm the project's own convention. If a commit is ambiguous or a commit message is uninformative (`wip`, `fix stuff`), read the diff before guessing.\n3. CHANGELOG: write entries grouped Added / Changed / Fixed / Removed / Security, in the project's existing Keep-a-Changelog style. Each entry describes user-visible behaviour, not the commit subject. Credit breaking changes with a migration note.\n4. VERSION FILES: bump every place the version lives (package.json, Cargo.toml, pyproject.toml, tauri.conf.json, VERSION) — grep for the old version string to make sure none is missed.\n5. TAG & NOTES: create an annotated tag naming the exact version. Release notes must contain the highlights, the breaking changes and the upgrade command.\n6. VERIFY THE ARTIFACT, NOT THE BUILD LOG: after publish, confirm the artifact exists at its public URL, check its size is plausible, download it, and verify the checksum matches the one you published. A green CI job is not proof the artifact is fetchable.\nState clearly what you could not verify. Never report a release as shipped when the public URL has not been fetched.",
    tools: ["read_file", "run_command", "write_to_file"],
    updatedAt: "2026-10-04",
  },
];
