import type { VaultTemplateItem } from "../types";

export const BUNDLED_TEMPLATES: VaultTemplateItem[] = [
  {
    id: "tpl:tauri-v2-react",
    name: "Tauri v2 + React 桌面端脚手架",
    category: "desktop",
    description: "基于 Tauri 2.0、React 19、Vite 与 Tailwind CSS 构建的高性能、极小包体跨平台桌面应用模板。",
    author: "Setup Center Team",
    license: "MIT",
    tags: ["Tauri v2", "React", "Desktop", "Rust", "Tailwind"],
    homepage: "https://v2.tauri.app",
    repository: "https://github.com/tauri-apps/create-tauri-app",
    scaffold: {
      type: "command",
      command: "npm create tauri-app@latest {{projectName}} -- --template react-ts",
      defaultDir: "my-tauri-app",
      postInstallNotice: "进入目录后执行 `npm install`，然后执行 `npm run tauri dev` 启动桌面调试环境。",
      steps: [
        {
          id: "create-tauri",
          program: "npm",
          args: ["create", "tauri-app@latest", "{{projectName}}", "--", "--template", "react-ts"],
          cwd: "{{parentDir}}",
          description: "创建 Tauri v2 + React 桌面应用模板",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "rust"],
      preparedOnly: true,
    },
    requirements: ["Node.js 18+", "Rust toolchain (cargo, rustc)"],
    featured: true,
    updatedAt: "2026-10-02",
  },
  {
    id: "tpl:create-t3-app",
    name: "T3 Stack 全栈脚手架",
    category: "fullstack",
    description: "包含 Next.js App Router、tRPC、Tailwind CSS、Prisma/Drizzle 的端到端强类型全栈起步工程。",
    author: "T3 OSS",
    license: "MIT",
    tags: ["Next.js", "TypeScript", "tRPC", "Prisma", "Tailwind"],
    homepage: "https://create.t3.gg",
    repository: "https://github.com/t3-oss/create-t3-app",
    scaffold: {
      type: "command",
      command: "npx create-t3-app@latest {{projectName}}",
      defaultDir: "my-t3-app",
      postInstallNotice: "运行 `npm run dev` 启动 Next.js 极速开发服务。",
      steps: [
        {
          id: "create-t3",
          program: "npx",
          args: ["create-t3-app@latest", "{{projectName}}"],
          cwd: "{{parentDir}}",
          description: "初始化 T3 Stack 端到端全栈工程",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node"],
      preparedOnly: true,
    },
    requirements: ["Node.js 18.17+"],
    featured: true,
    updatedAt: "2026-10-02",
  },
  {
    id: "tpl:rust-cli-starter",
    name: "Rust 现代命令行工具脚手架",
    category: "cli",
    description: "基于 Clap v4 派生宏、Tokio 异步运行时与 Anyhow 错误处理的 Rust 命令行工具 cargo-generate 模板。",
    author: "thesurlydev",
    license: "Apache-2.0",
    tags: ["Rust", "Clap", "CLI", "Tokio", "cargo-generate"],
    homepage: "https://github.com/thesurlydev/clap-cli-template",
    repository: "https://github.com/thesurlydev/clap-cli-template",
    scaffold: {
      type: "command",
      command: "cargo generate --git https://github.com/thesurlydev/clap-cli-template --name {{projectName}}",
      defaultDir: "my-rust-cli",
      postInstallNotice: "执行 `cargo run -- --help` 查看自动生成的 CLI 帮助与参数解析。",
      steps: [
        {
          id: "cargo-generate",
          program: "cargo",
          args: ["generate", "--git", "https://github.com/thesurlydev/clap-cli-template", "--name", "{{projectName}}"],
          cwd: "{{parentDir}}",
          description: "基于 cargo-generate 实例化 Clap CLI 模板",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["rust"],
      preparedOnly: true,
    },
    requirements: ["Rust toolchain (cargo, rustc 1.74+)"],
    featured: false,
    updatedAt: "2026-10-02",
  },
  {
    id: "tpl:python-uv-fastapi",
    name: "Python uv + FastAPI 微服务工程",
    category: "backend",
    description: "基于 Astral uv 超高速包管理器的现代 FastAPI 异步后端模板，包含 Pydantic v2 与热重载。",
    author: "Setup Center Team",
    license: "MIT",
    tags: ["Python", "FastAPI", "uv", "Pydantic", "Async"],
    homepage: "https://fastapi.tiangolo.com",
    scaffold: {
      type: "command",
      command: "uv init {{projectName}} --app && cd {{projectName}} && uv add fastapi uvicorn",
      defaultDir: "my-fastapi-service",
      postInstallNotice: "执行 `uv run uvicorn main:app --reload` 启动极速异步 API 服务与 Swagger 文档。",
      steps: [
        {
          id: "uv-init",
          program: "uv",
          args: ["init", "{{projectName}}", "--app"],
          cwd: "{{parentDir}}",
          description: "初始化 uv 应用工程结构",
        },
        {
          id: "uv-add-deps",
          program: "uv",
          args: ["add", "fastapi", "uvicorn"],
          cwd: "{{targetPath}}",
          description: "安装 FastAPI 与 Uvicorn 异步依赖",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["uv", "python"],
      preparedOnly: true,
    },
    requirements: ["Astral uv (可在 Setup Center 软件库直接安装)", "Python 3.10+"],
    featured: true,
    updatedAt: "2026-10-02",
  },
  {
    id: "tpl:nextjs-app-router",
    name: "Next.js 15 App Router 全栈脚手架",
    category: "web-frontend",
    description: "基于 Next.js 15 App Router、React 19、Tailwind CSS 与 TypeScript 的生产级现代全栈工程脚手架。",
    author: "Vercel / Community",
    license: "MIT",
    tags: ["Next.js", "React 19", "App Router", "Tailwind CSS", "TypeScript"],
    homepage: "https://nextjs.org",
    repository: "https://github.com/vercel/next.js",
    scaffold: {
      type: "command",
      command: "pnpm create next-app@latest {{projectName}} --ts --tailwind --eslint --app --src-dir --import-alias '@/*'",
      defaultDir: "my-next-app",
      postInstallNotice: "运行 `pnpm dev` 启动本地开发服务：http://localhost:3000",
      steps: [
        {
          id: "create-next",
          program: "pnpm",
          args: ["create", "next-app@latest", "{{projectName}}", "--ts", "--tailwind", "--eslint", "--app", "--src-dir", "--import-alias", "@/*"],
          cwd: "{{parentDir}}",
          description: "初始化 Next.js 15 App Router 生产级脚手架",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:astro-content-blog",
    name: "Astro 5 内容驱动博客脚手架",
    category: "content-site",
    description: "基于 Astro 5 孤岛架构的极速静态内容与博客脚手架，零 JavaScript 默认载入，原生支持 Markdown / MDX 与 Content Collections。",
    author: "Astro Community",
    license: "MIT",
    tags: ["Astro", "博客", "Content Collections", "MDX", "极速静态"],
    homepage: "https://astro.build",
    repository: "https://github.com/withastro/astro",
    scaffold: {
      type: "command",
      command: "pnpm create astro@latest {{projectName}} --template blog --install --git",
      defaultDir: "astro-blog",
      postInstallNotice: "运行 `pnpm dev` 并在浏览器打开 http://localhost:4321",
      steps: [
        {
          id: "create-astro",
          program: "pnpm",
          args: ["create", "astro@latest", "{{projectName}}", "--template", "blog", "--install", "--git"],
          cwd: "{{parentDir}}",
          description: "创建 Astro 5 内容博客工程",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:vite-react-ts-minimal",
    name: "Vite 6 + React 19 + TS 纯净工程",
    category: "web-frontend",
    description: "零冗余的极速客户端 SPA 基础模板，搭载 Vite 6、React 19、TypeScript 与 Tailwind CSS v4，秒级冷启动与毫秒级 HMR。",
    author: "Vite Core Team",
    license: "MIT",
    tags: ["Vite", "React 19", "SPA", "TypeScript", "Tailwind v4"],
    homepage: "https://vite.dev",
    repository: "https://github.com/vitejs/vite",
    scaffold: {
      type: "command",
      command: "pnpm create vite {{projectName}} --template react-ts && cd {{projectName}} && pnpm add -D @tailwindcss/vite tailwindcss",
      defaultDir: "vite-react-spa",
      postInstallNotice: "运行 `pnpm install` 后 `pnpm dev` 开启本地开发体验。",
      steps: [
        {
          id: "create-vite",
          program: "pnpm",
          args: ["create", "vite", "{{projectName}}", "--template", "react-ts"],
          cwd: "{{parentDir}}",
          description: "创建 Vite + React 19 + TypeScript SPA 基础骨架",
        },
        {
          id: "add-tailwind",
          program: "pnpm",
          args: ["add", "-D", "@tailwindcss/vite", "tailwindcss"],
          cwd: "{{targetPath}}",
          description: "配置 Tailwind CSS 样式引擎",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:hono-cloudflare-workers",
    name: "Hono 边缘微服务与 API 脚手架",
    category: "backend-api",
    description: "基于 Hono Web 框架与 Cloudflare Workers 的超轻量边缘计算工程，毫秒级响应、类型安全 RPC 与零冷启动。",
    author: "Yusuke Wada (Hono)",
    license: "MIT",
    tags: ["Hono", "Cloudflare Workers", "边缘计算", "TypeScript", "微服务"],
    homepage: "https://hono.dev",
    repository: "https://github.com/honojs/hono",
    scaffold: {
      type: "command",
      command: "pnpm create hono@latest {{projectName}} --template cloudflare-workers --install",
      defaultDir: "hono-edge-api",
      postInstallNotice: "运行 `pnpm dev` 启动 Wrangler 本地 Workers 仿真环境。",
      steps: [
        {
          id: "create-hono",
          program: "pnpm",
          args: ["create", "hono@latest", "{{projectName}}", "--template", "cloudflare-workers", "--install"],
          cwd: "{{parentDir}}",
          description: "生成 Hono Cloudflare Workers 边缘 API 模板",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:sveltekit-zero-config",
    name: "SvelteKit 2 极简响应式全栈",
    category: "web-frontend",
    description: "基于 Svelte 5 Runes 响应式体系与 SvelteKit 2 的下一代 Web 应用脚手架，极度精简的样板代码与出色的运行效率。",
    author: "Svelte Team",
    license: "MIT",
    tags: ["Svelte 5", "SvelteKit", "Runes", "全栈框架", "极简"],
    homepage: "https://svelte.dev",
    repository: "https://github.com/sveltejs/kit",
    scaffold: {
      type: "command",
      command: "pnpm create svelte@latest {{projectName}}",
      defaultDir: "my-svelte-app",
      postInstallNotice: "按引导选择 Skeleton project 与 TypeScript，完成后运行 `pnpm dev`。",
      steps: [
        {
          id: "create-svelte",
          program: "pnpm",
          args: ["create", "svelte@latest", "{{projectName}}"],
          cwd: "{{parentDir}}",
          description: "初始化 SvelteKit 2 全栈脚手架",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: false,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:rust-axum-backend",
    name: "Rust Axum + Tokio 高性能服务端",
    category: "backend-api",
    description: "基于 Tokio 生态 Axum 框架的现代 Rust Web 服务端基础脚手架，具备 Tower 中间件栈、Tracing 结构化日志与 JSON 路由契约。",
    author: "Tokio Contributors",
    license: "MIT",
    tags: ["Rust", "Axum", "Tokio", "高性能API", "异步编程"],
    homepage: "https://github.com/tokio-rs/axum",
    repository: "https://github.com/tokio-rs/axum",
    scaffold: {
      type: "command",
      command: "cargo new --bin {{projectName}} && cd {{projectName}} && cargo add axum tokio --features tokio/full && cargo add tracing tracing-subscriber serde --features serde/derive",
      defaultDir: "my-axum-service",
      postInstallNotice: "运行 `cargo run` 启动 Axum HTTP 服务，默认端口监听 0.0.0.0:3000。",
      steps: [
        {
          id: "cargo-new",
          program: "cargo",
          args: ["new", "--bin", "{{projectName}}"],
          cwd: "{{parentDir}}",
          description: "创建 Rust 独立二进制应用",
        },
        {
          id: "add-axum",
          program: "cargo",
          args: ["add", "axum", "tokio", "--features", "tokio/full"],
          cwd: "{{targetPath}}",
          description: "添加 Axum 与 Tokio 运行时依赖",
        },
        {
          id: "add-tracing",
          program: "cargo",
          args: ["add", "tracing", "tracing-subscriber", "serde", "--features", "serde/derive"],
          cwd: "{{targetPath}}",
          description: "添加日志追踪与 Serde 序列化库",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["rust"],
      preparedOnly: true,
    },
    requirements: ["rust"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:python-cli-typer",
    name: "Python Typer + Rich 终端工具模板",
    category: "cli-tool",
    description: "基于 FastAPI 创作者打造的 Typer 框架与 Rich 富文本终端库，搭配 uv 高速虚拟环境管理的现代 Python CLI 工程。",
    author: "Tiangolo (Sebastián Ramírez)",
    license: "MIT",
    tags: ["Python", "Typer", "Rich", "CLI", "uv包管理"],
    homepage: "https://typer.tiangolo.com",
    repository: "https://github.com/fastapi/typer",
    scaffold: {
      type: "command",
      command: "uv init {{projectName}} && cd {{projectName}} && uv add typer rich",
      defaultDir: "my-cli-tool",
      postInstallNotice: "运行 `uv run python main.py --help` 自动查看生成的终端色彩帮助文档。",
      steps: [
        {
          id: "uv-init-cli",
          program: "uv",
          args: ["init", "{{projectName}}"],
          cwd: "{{parentDir}}",
          description: "初始化 Python CLI 工作区",
        },
        {
          id: "add-cli-deps",
          program: "uv",
          args: ["add", "typer", "rich"],
          cwd: "{{targetPath}}",
          description: "添加 Typer 与 Rich 终端工具库",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["python", "uv"],
      preparedOnly: true,
    },
    requirements: ["python", "uv"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:threejs-r3f-canvas",
    name: "React Three Fiber 3D 视觉交互脚手架",
    category: "3d-creative",
    description: "基于 React Three Fiber、Drei 辅助库与 Three.js 的声明式 Web 3D / WebGL 渲染工程模板，开箱即用支持相机控制、光源与阴影管线。",
    author: "Poimandres",
    license: "MIT",
    tags: ["Three.js", "R3F", "WebGL", "3D视觉", "Poimandres"],
    homepage: "https://r3f.docs.pmnd.rs",
    repository: "https://github.com/pmndrs/react-three-fiber",
    scaffold: {
      type: "command",
      command: "pnpm create vite {{projectName}} --template react-ts && cd {{projectName}} && pnpm add three @types/three @react-three/fiber @react-three/drei",
      defaultDir: "my-3d-scene",
      postInstallNotice: "运行 `pnpm dev` 并在浏览器体验 60FPS 声明式三维网格与空间粒子。",
      steps: [
        {
          id: "create-vite-3d",
          program: "pnpm",
          args: ["create", "vite", "{{projectName}}", "--template", "react-ts"],
          cwd: "{{parentDir}}",
          description: "创建 Vite + React 3D 宿主工程",
        },
        {
          id: "add-three-deps",
          program: "pnpm",
          args: ["add", "three", "@types/three", "@react-three/fiber", "@react-three/drei"],
          cwd: "{{targetPath}}",
          description: "安装 Three.js 与 React Three Fiber 3D 渲染库",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn", "bun"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-03",
  },
  {
    id: "tpl:astro-starlight-docs",
    name: "Starlight 文档站主题 (Astro Starlight Docs)",
    category: "content-site",
    description: "Astro 官方文档站主题 Starlight，内置侧栏导航、全文检索、i18n 与深色模式，开箱即用的技术文档骨架。",
    author: "Astro Team",
    license: "MIT",
    tags: ["Astro", "Starlight", "文档站", "全文检索", "i18n"],
    homepage: "https://starlight.astro.build",
    repository: "https://github.com/withastro/starlight",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/withastro/starlight.git",
      command: "git clone https://github.com/withastro/starlight.git {{projectName}} && cd {{projectName}} && pnpm install",
      defaultDir: "starlight-docs",
      postInstallNotice: "仓库为 monorepo，docs/ 内即为 Starlight 官方文档站实例，运行 `pnpm dev` 预览。",
      steps: [
        {
          id: "git-clone-starlight",
          program: "git",
          args: ["clone", "https://github.com/withastro/starlight.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Starlight 官方文档站仓库",
        },
        {
          id: "install-deps",
          program: "pnpm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装项目工作区依赖",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["git", "node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "pnpm"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:cookiecutter-django",
    name: "Cookiecutter Django 生产级模板 (Cookiecutter Django)",
    category: "backend",
    description: "面向生产环境的 Django 项目生成器：自定义用户模型、Docker 化部署、Celery、PostgreSQL 与安全默认配置。",
    author: "Cookiecutter Django",
    license: "BSD-3-Clause",
    tags: ["Django", "Cookiecutter", "PostgreSQL", "Celery", "Docker"],
    homepage: "https://cookiecutter-django.readthedocs.io",
    repository: "https://github.com/cookiecutter/cookiecutter-django",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/cookiecutter/cookiecutter-django.git",
      command: "git clone https://github.com/cookiecutter/cookiecutter-django.git {{projectName}} && cd {{projectName}} && pip install cookiecutter",
      defaultDir: "cookiecutter-django",
      postInstallNotice: "生成后用 `docker compose -f local.yml up` 起本地全栈环境，含 PostgreSQL 与 Redis。",
      steps: [
        {
          id: "clone-django",
          program: "git",
          args: ["clone", "https://github.com/cookiecutter/cookiecutter-django.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Cookiecutter Django 模板代码",
        },
        {
          id: "pip-install",
          program: "pip",
          args: ["install", "cookiecutter"],
          cwd: "{{targetPath}}",
          description: "安装 cookiecutter CLI 工具",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["git", "python", "docker"],
      preparedOnly: true,
    },
    requirements: ["python", "docker", "git"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:create-t3-turbo",
    name: "T3 Turbo 全栈单体仓库 (T3 Turbo Monorepo)",
    category: "monorepo",
    description: "T3 团队官方 monorepo 模板，Next.js + Expo + tRPC + Prisma 共享类型与业务逻辑，Turborepo 统一调度任务。",
    author: "T3 Open Source",
    license: "MIT",
    tags: ["Turborepo", "tRPC", "Prisma", "Next.js", "monorepo"],
    homepage: "https://turbo.t3.gg",
    repository: "https://github.com/t3-oss/create-t3-turbo",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/t3-oss/create-t3-turbo.git",
      command: "git clone https://github.com/t3-oss/create-t3-turbo.git {{projectName}} && cd {{projectName}} && pnpm install",
      defaultDir: "my-turbo-app",
      postInstallNotice: "复制 .env.example 为 .env 并填写 DATABASE_URL 后再运行 `pnpm dev`。",
      steps: [
        {
          id: "clone-turbo",
          program: "git",
          args: ["clone", "https://github.com/t3-oss/create-t3-turbo.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 T3 Turbo 单体仓库",
        },
        {
          id: "install-turbo",
          program: "pnpm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装 Monorepo 依赖",
        },
      ],
      supportedPackageManagers: ["pnpm"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["git", "node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:deno-fresh-app",
    name: "Deno Fresh 岛屿架构应用 (Deno Fresh App)",
    category: "web-frontend",
    description: "Deno 官方 Fresh 框架仓库，默认零客户端 JavaScript，通过岛屿组件按需注水，配合 Deno KV 做边缘数据存储。",
    author: "Deno Land",
    license: "MIT",
    tags: ["Deno", "Fresh", "岛屿架构", "边缘计算", "TypeScript"],
    homepage: "https://usefresh.dev",
    repository: "https://github.com/freshframework/fresh",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/freshframework/fresh.git",
      command: "git clone https://github.com/freshframework/fresh.git {{projectName}} && cd {{projectName}}",
      defaultDir: "fresh-app",
      postInstallNotice: "需要先安装 Deno；仓库自带 demo/ 应用可直接运行，无需 npm install。",
      steps: [
        {
          id: "clone-fresh",
          program: "git",
          args: ["clone", "https://github.com/freshframework/fresh.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Fresh 框架工程",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["git", "deno"],
      preparedOnly: true,
    },
    requirements: ["git", "deno"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:docusaurus-docs-site",
    name: "Docusaurus 文档与博客站 (Docusaurus Site)",
    category: "content-site",
    description: "Meta 的 Docusaurus 仓库，把 Markdown／MDX 编译为带版本管理、搜索与博客能力的静态文档站点。",
    author: "Meta Open Source",
    license: "MIT",
    tags: ["Docusaurus", "MDX", "文档站", "版本管理", "React"],
    homepage: "https://docusaurus.io",
    repository: "https://github.com/facebook/docusaurus",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/facebook/docusaurus.git",
      command: "git clone https://github.com/facebook/docusaurus.git {{projectName}} && cd {{projectName}}",
      defaultDir: "docusaurus-site",
      postInstallNotice: "仓库自带官网实例 website/，`cd website && yarn && yarn start` 即可本地预览。",
      steps: [
        {
          id: "clone-docusaurus",
          program: "git",
          args: ["clone", "https://github.com/facebook/docusaurus.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Docusaurus 仓库",
        },
      ],
      supportedPackageManagers: ["yarn", "npm", "pnpm"],
      defaultPackageManager: "yarn",
      requiredCapabilities: ["git", "node"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "yarn"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:electron-forge-app",
    name: "Electron Forge 桌面应用 (Electron Forge App)",
    category: "desktop",
    description: "Electron 官方工具链 Forge 仓库，覆盖脚手架、打包、签名与多平台分发流程，是桌面壳工程的起点。",
    author: "Electron",
    license: "MIT",
    tags: ["Electron", "Electron Forge", "桌面应用", "打包", "多平台"],
    homepage: "https://electronforge.io",
    repository: "https://github.com/electron/forge",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/electron/forge.git",
      command: "git clone https://github.com/electron/forge.git {{projectName}} && cd {{projectName}}",
      defaultDir: "forge-desktop",
      postInstallNotice: "仓库为 monorepo；推荐改用 `npx create-electron-app@latest my-app` 生成独立工程。",
      steps: [
        {
          id: "clone-forge",
          program: "git",
          args: ["clone", "https://github.com/electron/forge.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Electron Forge 仓库",
        },
      ],
      supportedPackageManagers: ["npm", "yarn", "pnpm"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:electron-vite-react",
    name: "Electron + Vite + React 桌面模板 (Electron Vite React)",
    category: "desktop",
    description: "Electron 与 Vite 结合的最小可运行桌面模板，主进程／预加载／渲染进程三端分工清晰，热更新开箱可用。",
    author: "electron-vite",
    license: "MIT",
    tags: ["Electron", "Vite", "React", "桌面应用", "热更新"],
    homepage: "https://electron-vite.org",
    repository: "https://github.com/electron-vite/electron-vite-react",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/electron-vite/electron-vite-react.git",
      command: "git clone https://github.com/electron-vite/electron-vite-react.git {{projectName}} && cd {{projectName}} && npm install",
      defaultDir: "my-electron-app",
      postInstallNotice: "运行 `npm run dev` 同时启动 Vite 与 Electron 窗口。",
      steps: [
        {
          id: "clone-electron-vite",
          program: "git",
          args: ["clone", "https://github.com/electron-vite/electron-vite-react.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Electron + Vite + React 模板",
        },
        {
          id: "install-deps",
          program: "npm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装桌面端依赖",
        },
      ],
      supportedPackageManagers: ["npm", "pnpm", "yarn"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:fastapi-full-stack",
    name: "FastAPI 全栈脚手架 (FastAPI Full Stack)",
    category: "backend",
    description: "FastAPI 官方全栈模板，含 SQLModel 数据层、JWT 鉴权、Alembic 迁移、Celery 任务与自动生成的 TypeScript 前端客户端。",
    author: "FastAPI",
    license: "MIT",
    tags: ["FastAPI", "SQLModel", "Alembic", "Docker", "JWT"],
    homepage: "https://fastapi.tiangolo.com",
    repository: "https://github.com/fastapi/full-stack-fastapi-template",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/fastapi/full-stack-fastapi-template.git",
      command: "git clone https://github.com/fastapi/full-stack-fastapi-template.git {{projectName}} && cd {{projectName}} && docker compose up -d",
      defaultDir: "fastapi-fullstack",
      postInstallNotice: "先用 `python -c \"import secrets;print(secrets.token_urlsafe(32))\"` 生成 SECRET_KEY 写入 .env。",
      steps: [
        {
          id: "clone-fastapi-fullstack",
          program: "git",
          args: ["clone", "https://github.com/fastapi/full-stack-fastapi-template.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 FastAPI 官方全栈模板",
        },
        {
          id: "docker-compose-up",
          program: "docker",
          args: ["compose", "up", "-d"],
          cwd: "{{targetPath}}",
          description: "启动全栈服务容器",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["git", "python", "docker"],
      preparedOnly: true,
    },
    requirements: ["git", "python", "docker"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:laravel-app-skeleton",
    name: "Laravel 应用骨架 (Laravel Skeleton)",
    category: "backend",
    description: "Laravel 官方应用骨架，含路由、Eloquent ORM、Blade 模板、队列与 Artisan 命令行，PHP 全栈的第一块地基。",
    author: "Laravel",
    license: "MIT",
    tags: ["Laravel", "PHP", "Eloquent", "Blade", "Artisan"],
    homepage: "https://laravel.com",
    repository: "https://github.com/laravel/laravel",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/laravel/laravel.git",
      command: "git clone https://github.com/laravel/laravel.git {{projectName}} && cd {{projectName}} && composer install",
      defaultDir: "my-laravel-app",
      postInstallNotice: "复制 .env.example 为 .env，运行 `php artisan key:generate` 后 `php artisan serve` 启动。",
      steps: [
        {
          id: "clone-laravel",
          program: "git",
          args: ["clone", "https://github.com/laravel/laravel.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Laravel 官方应用骨架",
        },
        {
          id: "composer-install",
          program: "composer",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装 PHP 依赖包",
        },
      ],
      supportedPackageManagers: [],
      requiredCapabilities: ["git", "php"],
      preparedOnly: true,
    },
    requirements: ["git", "php", "composer"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:nestjs-typescript-api",
    name: "NestJS TypeScript 服务骨架 (NestJS Starter)",
    category: "backend-api",
    description: "NestJS 官方 TypeScript 起步仓库，模块／控制器／服务分层清晰，内置依赖注入、守卫、拦截器与测试脚手架。",
    author: "NestJS",
    license: "MIT",
    tags: ["NestJS", "TypeScript", "依赖注入", "REST", "Node.js"],
    homepage: "https://nestjs.com",
    repository: "https://github.com/nestjs/typescript-starter",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/nestjs/typescript-starter.git",
      command: "git clone https://github.com/nestjs/typescript-starter.git {{projectName}} && cd {{projectName}} && npm install",
      defaultDir: "my-nest-api",
      postInstallNotice: "运行 `npm run start:dev` 启动带热重载的服务：http://localhost:3000",
      steps: [
        {
          id: "clone-nest",
          program: "git",
          args: ["clone", "https://github.com/nestjs/typescript-starter.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 NestJS TypeScript 起步工程",
        },
        {
          id: "install-deps",
          program: "npm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装服务端依赖",
        },
      ],
      supportedPackageManagers: ["npm", "pnpm", "yarn"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:nuxt-starter",
    name: "Nuxt 4 起步工程 (Nuxt Starter)",
    category: "web-frontend",
    description: "Nuxt 官方起步仓库，内置文件路由、自动导入、服务端渲染与 Nitro 服务层，含 TypeScript 与 ESLint 预设。",
    author: "Nuxt Team",
    license: "MIT",
    tags: ["Nuxt", "Vue 3", "SSR", "Nitro", "TypeScript"],
    homepage: "https://nuxt.com",
    repository: "https://github.com/nuxt/starter",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/nuxt/starter.git",
      command: "git clone https://github.com/nuxt/starter.git {{projectName}} && cd {{projectName}} && npm install",
      defaultDir: "nuxt-app",
      postInstallNotice: "运行 `npm run dev` 启动开发服务器：http://localhost:3000",
      steps: [
        {
          id: "clone-nuxt",
          program: "git",
          args: ["clone", "https://github.com/nuxt/starter.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Nuxt 4 官方起步仓库",
        },
        {
          id: "install-deps",
          program: "npm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装 Nuxt 全栈依赖",
        },
      ],
      supportedPackageManagers: ["npm", "pnpm", "yarn", "bun"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:remix-fullstack-app",
    name: "Remix 全栈应用骨架 (Remix Fullstack App)",
    category: "fullstack",
    description: "Remix 官方仓库，含嵌套路由、loader／action 数据流、渐进增强表单与服务端渲染的全栈工程结构。",
    author: "Remix / Shopify",
    license: "MIT",
    tags: ["Remix", "React", "全栈", "嵌套路由", "SSR"],
    homepage: "https://remix.run",
    repository: "https://github.com/remix-run/remix",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/remix-run/remix.git",
      command: "git clone https://github.com/remix-run/remix.git {{projectName}}",
      defaultDir: "remix-app",
      postInstallNotice: "仓库为 monorepo；示例应用位于 templates/ 目录，进入后运行 `npm install && npm run dev`。",
      steps: [
        {
          id: "clone-remix",
          program: "git",
          args: ["clone", "https://github.com/remix-run/remix.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Remix 全栈仓库",
        },
      ],
      supportedPackageManagers: ["npm", "pnpm", "yarn"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:solid-start-app",
    name: "SolidStart 应用 (SolidStart App)",
    category: "web-frontend",
    description: "SolidStart 官方仓库，基于细粒度响应式与流式 SSR 的应用框架，支持文件路由、服务器函数与多种部署适配器。",
    author: "SolidJS",
    license: "MIT",
    tags: ["SolidJS", "SolidStart", "SSR", "响应式", "Vite"],
    homepage: "https://start.solidjs.com",
    repository: "https://github.com/solidjs/solid-start",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/solidjs/solid-start.git",
      command: "git clone https://github.com/solidjs/solid-start.git {{projectName}} && cd {{projectName}} && npm install",
      defaultDir: "solid-app",
      postInstallNotice: "运行 `npm run dev` 启动开发服务器。",
      steps: [
        {
          id: "clone-solid",
          program: "git",
          args: ["clone", "https://github.com/solidjs/solid-start.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 SolidStart 官方应用模板",
        },
        {
          id: "install-deps",
          program: "npm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装 SolidJS 响应式依赖",
        },
      ],
      supportedPackageManagers: ["npm", "pnpm", "yarn"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "npm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:turborepo-starter",
    name: "Turborepo 任务编排工程 (Turborepo Starter)",
    category: "monorepo",
    description: "Vercel 的 Turborepo 仓库，提供增量构建、远程缓存与多包任务图的 monorepo 工程范式与示例配置。",
    author: "Vercel",
    license: "MIT",
    tags: ["Turborepo", "monorepo", "增量构建", "远程缓存", "Vercel"],
    homepage: "https://turborepo.dev/",
    repository: "https://github.com/vercel/turborepo",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/vercel/turborepo.git",
      command: "git clone https://github.com/vercel/turborepo.git {{projectName}} && cd {{projectName}}",
      defaultDir: "turborepo-starter",
      postInstallNotice: "仓库包含 docs/、examples/、packages/ 三个工作区，可从 examples/basic 入手。",
      steps: [
        {
          id: "clone-turbo",
          program: "git",
          args: ["clone", "https://github.com/vercel/turborepo.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Turborepo 任务图与示例仓库",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["git", "node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "pnpm"],
    featured: false,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:vitesse-vue-starter",
    name: "Vitesse Vue 精致起步模板 (Vitesse Vue Starter)",
    category: "web-frontend",
    description: "Anthony Fu 出品的 Vue 3 起步模板，集成 Vite、UnoCSS、Vue Router、Pinia、自动导入与按需组件加载。",
    author: "Anthony Fu",
    license: "MIT",
    tags: ["Vue 3", "Vite", "UnoCSS", "Pinia", "起步模板"],
    homepage: "https://github.com/antfu-collective/vitesse",
    repository: "https://github.com/antfu-collective/vitesse",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/antfu-collective/vitesse.git",
      command: "git clone https://github.com/antfu-collective/vitesse.git {{projectName}} && cd {{projectName}} && pnpm install",
      defaultDir: "my-vitesse-app",
      postInstallNotice: "运行 `pnpm dev` 启动开发服务器；首次运行会生成类型声明。",
      steps: [
        {
          id: "clone-vitesse",
          program: "git",
          args: ["clone", "https://github.com/antfu-collective/vitesse.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 Vitesse Vue 3 起步仓库",
        },
        {
          id: "install-deps",
          program: "pnpm",
          args: ["install"],
          cwd: "{{targetPath}}",
          description: "安装 Vue 生态与 UnoCSS 依赖",
        },
      ],
      supportedPackageManagers: ["pnpm", "npm", "yarn"],
      defaultPackageManager: "pnpm",
      requiredCapabilities: ["git", "node", "pnpm"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "pnpm"],
    featured: true,
    updatedAt: "2026-10-04",
  },
  {
    id: "tpl:vscode-extension-sample",
    name: "VS Code 扩展示例集 (VS Code Extension Samples)",
    category: "cli-tool",
    description: "微软官方 VS Code 扩展示例仓库，覆盖命令、语言服务、Webview、TreeView、调试适配器等完整扩展能力样例。",
    author: "Microsoft",
    license: "MIT",
    tags: ["VS Code", "扩展开发", "Language Server", "Webview", "TypeScript"],
    homepage: "https://code.visualstudio.com/api",
    repository: "https://github.com/microsoft/vscode-extension-samples",
    scaffold: {
      type: "git-clone",
      gitUrl: "https://github.com/microsoft/vscode-extension-samples.git",
      command: "git clone https://github.com/microsoft/vscode-extension-samples.git {{projectName}} && cd {{projectName}}",
      defaultDir: "vscode-extension-samples",
      postInstallNotice: "每个子目录是一个独立扩展，进入所需样例后执行 `npm install`，按 F5 启动扩展开发宿主。",
      steps: [
        {
          id: "clone-samples",
          program: "git",
          args: ["clone", "https://github.com/microsoft/vscode-extension-samples.git", "{{targetPath}}"],
          cwd: "{{parentDir}}",
          description: "克隆 VS Code 官方扩展示例仓库",
        },
      ],
      supportedPackageManagers: ["npm", "yarn", "pnpm"],
      defaultPackageManager: "npm",
      requiredCapabilities: ["git", "node", "vscode"],
      preparedOnly: true,
    },
    requirements: ["git", "node", "npm", "VS Code"],
    featured: false,
    updatedAt: "2026-10-04",
  },
];
