import type { SetupStyle } from "../types";

export const dataAtlasStyle: SetupStyle = {
  id: "data-atlas",
  name: "Data Atlas",
  version: "3.0.0",
  subtitle: "坐标标尺矩阵 · 十六进制遥测流 · 科学实验室仪器",
  description:
    "基于精密科学实验室仪器、地理信息系统（GIS）与高密度测绘图纸构建的硬核工程体系。顶部与左侧贯穿严密的物理刻度尺标与像素准星，模块呈现为紧凑的十六进制数据矩阵与传感器仪表盘，赋予开发者极致的机器掌控力。",
  inspiration: "CERN ATLAS Experiment Dashboard, NASA Mission Control, Bloomberg Terminal",
  author: "Setup Center Architecture",
  tags: ["科学仪器", "遥测数据", "双向标尺", "高密度等宽", "工程蓝图"],
  implemented: true,
  palette: {
    baseBg: "#0f172a",
    surface: "#1e293b",
    cardBorder: "#334155",
    accent: "#10b981",
    accentSecondary: "#f59e0b",
    text: "#f1f5f9",
  },
  features: [
    "双轴笛卡尔物理坐标刻度线（000 - 999 像素步长与精准刻度钉）",
    "全界面统一采用等宽工程字体与十六进制数据块标识符 (HEX 0x4F)",
    "传感器状态遥测绿 (#10b981) 与实验告警琥珀 (#f59e0b) 双通道告警灯",
    "虚线工程参考线贯穿卡片间隙，营造实验室仪表板的精密工整度",
  ],
  designPrinciples: [
    "Information Density as Respect: 绝不刻意空置屏幕，每一平方厘米都提供高信噪比数据",
    "Measurement Transparency: 任何组件的位置、尺寸与状态都带有精准量化指示",
    "Laboratory Rigor: 告别模棱两可的情感化修饰，以严苛的科研规格交付确定性",
  ],
  experience: {
    tier: "experience",
    family: "terminal",
    scene: "coordinate-atlas",
    contentFlow: "cartesian-matrix",
    navigationFlow: "coordinate-ruler",
    pageTransition: "telemetry-glitch",
    heroMode: "data-readout",
    layering: "blueprint-grid",
    shell: "dual-pane",
    navigation: "keyboard-menu",
    detail: "rail",
    card: "terminal-line",
    composition: "drafting-index",
    density: "compact",
    motion: "reduced",
    typography: {
      headingFamily: "ui-monospace, 'JetBrains Mono', Consolas, monospace",
      bodyFamily: "ui-monospace, 'JetBrains Mono', Consolas, monospace",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 700,
      headingTracking: "-0.01em",
      bodyLeading: 1.45,
    },
    ornament: {
      rule: "ascii",
      corner: "square",
      decoration: "blueprint",
      chrome: "status",
    },
    tokens: {
      panelRadius: "0px",
      controlRadius: "0px",
      borderWidth: "1px",
      shadow: {
        offsetX: "0px",
        offsetY: "0px",
        blur: "0px",
        spread: "1px",
        color: "#334155",
      },
      accent: "#10b981",
      accentSecondary: "#f59e0b",
      surface: "#1e293b",
      text: "#f1f5f9",
      density: "compact",
      headingScale: 1.0,
      bodyScale: 0.95,
      motion: "reduced",
    },
    locked: {
      panelRadius: "精密仪器坐标刻度线强制要求 0px 直角对齐",
    },
    specimenNote: "剪影特征：外围双轴等距刻度尺标 + 双栏数据密集表格 + 全等宽绿色高亮",
  },
};

export default dataAtlasStyle;
