import type { ResourceItem } from "../types";

export const aiResources: ResourceItem[] = [
  {
    id: "res:ollama",
    name: "Ollama",
    category: "ai",
    description: "在本地快速运行 DeepSeek、Llama 3、Qwen、Gemma 等大型语言模型的事实标准工具。",
    recommendedReason: "单行命令 `ollama run deepseek-r1` 即可本地离线体验前沿模型，提供标准 OpenAI 兼容 API。",
    author: "Ollama Inc.",
    tags: ["本地模型", "离线AI", "DeepSeek", "API服务"],
    actionType: "github",
    repository: "https://github.com/ollama/ollama",
    homepage: "https://ollama.com",
    stars: "128k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:open-webui",
    name: "Open WebUI",
    category: "ai",
    description: "功能极其完备、用户体验媲美商业产品的本地离线 AI 私有化 Web 对话平台。",
    recommendedReason: "支持多模型对比、RAG 文档检索增强、代码沙箱执行、多用户权限，与 Ollama 完美搭配。",
    author: "Open WebUI Community",
    tags: ["私有化UI", "多模型对话", "RAG知识库", "自托管"],
    actionType: "github",
    repository: "https://github.com/open-webui/open-webui",
    homepage: "https://openwebui.com",
    stars: "88k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:chatbox",
    name: "Chatbox AI",
    category: "ai",
    description: "全平台开源的桌面端 AI 客户端，支持本地模型与各家商业 API 统一管理接入。",
    recommendedReason: "无需在网页端频繁登录，本地密钥存储，多提示词预设，日常提效极度顺手。",
    author: "Bento (Bigtall)",
    tags: ["桌面端客户端", "全平台", "多API聚合", "提示词管理"],
    actionType: "github",
    repository: "https://github.com/Bin-Huang/chatbox",
    homepage: "https://chatboxai.app",
    stars: "31k+",
    license: "GPL-3.0",
    featured: true,
  },
  {
    id: "res:vllm",
    name: "vLLM",
    category: "ai",
    description: "专为大模型推理服务打造的高吞吐、低延迟开源 Serving 引擎，提出 PagedAttention。",
    recommendedReason: "自建大模型线上高并发 API 服务的工业界首选标准框架，显存利用率达到极限。",
    author: "vLLM Project",
    tags: ["大模型推理", "高吞吐Serving", "PagedAttention", "生产级部署"],
    actionType: "github",
    repository: "https://github.com/vllm-project/vllm",
    homepage: "https://vllm.ai",
    stars: "38k+",
    license: "Apache-2.0",
  },
  {
    id: "res:cursor-directory",
    name: "Cursor Directory",
    category: "ai",
    description: "精选全球顶级工程师与开源项目实战打磨的 Cursor Rules 规范与 System Prompts。",
    recommendedReason: "为特定框架（Next.js、Tauri、Rust、Tailwind）直接装载专家级编码约束指令。",
    author: "Pontus Abrahamsson",
    tags: ["CursorRules", "编码指令", "系统提示词", "框架规范"],
    actionType: "external",
    homepage: "https://cursor.directory",
    featured: true,
  },
  {
    id: "res:model-context-protocol",
    name: "Model Context Protocol (MCP)",
    category: "ai",
    description: "由 Anthropic 发起并开源的开放式标准化协议，将 AI Agent 安全连接到本地数据与工具。",
    recommendedReason: "正在成为所有 AI 编码助手连接本地数据库、文件系统、终端工具的工业互联标准。",
    author: "Anthropic & Open Source",
    tags: ["MCP标准", "Agent互联", "工具协议", "上下文扩展"],
    actionType: "github",
    repository: "https://github.com/modelcontextprotocol",
    homepage: "https://modelcontextprotocol.io",
    stars: "18k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:dify",
    name: "Dify.AI",
    category: "ai",
    description: "易用的开源大语言模型应用开发平台，可视化编排复杂多智能体（Agent）工作流。",
    recommendedReason: "无需手写大量粘合代码，通过画布即可搭建企业级知识库问答、工作流与 Agent 编排。",
    author: "LangGenius Inc.",
    tags: ["Agent编排", "工作流画布", "应用平台", "知识库RAG"],
    actionType: "github",
    repository: "https://github.com/langgenius/dify",
    homepage: "https://dify.ai",
    stars: "66k+",
    license: "Apache-2.0",
  },
  {
    id: "res:fabric",
    name: "Fabric",
    category: "ai",
    description: "模块化增强人类认知能力的开源 AI 提示词（Patterns）与日常任务命令行框架。",
    recommendedReason: "提取长文核心论点、代码安全审查、技术文档提炼等数百个经过反复微调的高质量 Pattern。",
    author: "Daniel Miessler",
    tags: ["提示词体系", "认知增强", "命令行AI", "高质量模式"],
    actionType: "github",
    repository: "https://github.com/danielmiessler/fabric",
    stars: "31k+",
    license: "MIT",
  },
  {
    id: "res:continue",
    name: "Continue",
    category: "ai",
    description: "领先的完全开源自主控制 VS Code / JetBrains 伴生 AI 编程助手扩展。",
    recommendedReason: "自主连接任何本地或自建大模型，支持代码补全、跨文件上下文问答与编辑，数据安全可控。",
    author: "Continue Dev",
    tags: ["IDE扩展", "开源Copilot", "本地代码补全", "自主可控"],
    actionType: "github",
    repository: "https://github.com/continuedev/continue",
    homepage: "https://continue.dev",
    stars: "23k+",
    license: "Apache-2.0",
  },
  {
    id: "res:vercel-ai-sdk",
    name: "Vercel AI SDK",
    category: "ai",
    description: "专为 TypeScript 与 React/Next.js 全栈开发者构建的统一大模型流式调用与工具调用标准库。",
    recommendedReason: "一网打尽 OpenAI、Anthropic、DeepSeek、Google 等主流模型，首选的现代 Web AI 流式开发 SDK。",
    author: "Vercel",
    tags: ["TypeScript", "流式输出", "工具调用", "全栈标准"],
    actionType: "github",
    repository: "https://github.com/vercel/ai",
    homepage: "https://sdk.vercel.ai",
    stars: "14k+",
    license: "Apache-2.0",
    featured: true,
  },
  {
    id: "res:langchain",
    name: "LangChain",
    category: "ai",
    description: "用于构建具备上下文感知与自主推理能力的 Agent 与 LLM 链路级工业标准框架。",
    recommendedReason: "拥有业界最完备的向量库集成、工具扩展与记忆模块，是学习 AI 架构的必修参考。",
    author: "Harrison Chase & LangChain Inc.",
    tags: ["Agent架构", "链式调用", "RAG框架", "生态庞大"],
    actionType: "github",
    repository: "https://github.com/langchain-ai/langchain",
    homepage: "https://www.langchain.com",
    stars: "98k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:llamaindex",
    name: "LlamaIndex",
    category: "ai",
    description: "专注于外部数据摄取、切分索引与高质量 RAG 知识检索增强的大模型数据底座。",
    recommendedReason: "处理复杂的企业 PDF、代码仓库、数据库混合检索时准确率与上下文相关度极高。",
    author: "Jerry Liu & LlamaIndex",
    tags: ["RAG索引", "向量检索", "私域数据", "知识库专家"],
    actionType: "github",
    repository: "https://github.com/run-llama/llama_index",
    homepage: "https://www.llamaindex.ai",
    stars: "39k+",
    license: "MIT",
  },
  {
    id: "res:browser-use",
    name: "Browser Use",
    category: "ai",
    description: "让 AI Agent 能够像真人一样自主浏览网页、点击表单、提取信息的下一代自动化框架。",
    recommendedReason: "融合视觉感知与 DOM 树定位，轻松驱动大模型执行跨网页自主调研与自动化流程。",
    author: "Browser Use Community",
    tags: ["Agent自主浏览", "Web自动化", "视觉定位", "先锋开源"],
    actionType: "github",
    repository: "https://github.com/browser-use/browser-use",
    homepage: "https://browser-use.com",
    stars: "28k+",
    license: "MIT",
    featured: true,
  },
];

