import type { ResourceItem } from "../types";

export const aiResources: ResourceItem[] = [
  {
    id: "res:ollama",
    name: "Ollama",
    category: "ai",
    description: "在本地快速运行 DeepSeek、Llama 3、Qwen、Gemma 等大型语言模型的事实标准工具。",
    recommendedReason: "单行命令 `ollama run deepseek-r1` 即可本地离线体验前沿模型，提供标准 OpenAI 兼容 API。",
    author: "Ollama Inc.",
    tags: ["本地模型", "离线AI", "DeepSeek", "API服务"],
    actionType: "github",
    repository: "https://github.com/ollama/ollama",
    homepage: "https://ollama.com",
    stars: "128k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:open-webui",
    name: "Open WebUI",
    category: "ai",
    description: "功能极其完备、用户体验媲美商业产品的本地离线 AI 私有化 Web 对话平台。",
    recommendedReason: "支持多模型对比、RAG 文档检索增强、代码沙箱执行、多用户权限，与 Ollama 完美搭配。",
    author: "Open WebUI Community",
    tags: ["私有化UI", "多模型对话", "RAG知识库", "自托管"],
    actionType: "github",
    repository: "https://github.com/open-webui/open-webui",
    homepage: "https://openwebui.com",
    stars: "88k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:chatbox",
    name: "Chatbox AI",
    category: "ai",
    description: "全平台开源的桌面端 AI 客户端，支持本地模型与各家商业 API 统一管理接入。",
    recommendedReason: "无需在网页端频繁登录，本地密钥存储，多提示词预设，日常提效极度顺手。",
    author: "Bento (Bigtall)",
    tags: ["桌面端客户端", "全平台", "多API聚合", "提示词管理"],
    actionType: "github",
    repository: "https://github.com/Bin-Huang/chatbox",
    homepage: "https://chatboxai.app",
    stars: "31k+",
    license: "GPL-3.0",
    featured: true,
  },
  {
    id: "res:vllm",
    name: "vLLM",
    category: "ai",
    description: "专为大模型推理服务打造的高吞吐、低延迟开源 Serving 引擎，提出 PagedAttention。",
    recommendedReason: "自建大模型线上高并发 API 服务的工业界首选标准框架，显存利用率达到极限。",
    author: "vLLM Project",
    tags: ["大模型推理", "高吞吐Serving", "PagedAttention", "生产级部署"],
    actionType: "github",
    repository: "https://github.com/vllm-project/vllm",
    homepage: "https://vllm.ai",
    stars: "38k+",
    license: "Apache-2.0",
  },
  {
    id: "res:cursor-directory",
    name: "Cursor Directory",
    category: "ai",
    description: "精选全球顶级工程师与开源项目实战打磨的 Cursor Rules 规范与 System Prompts。",
    recommendedReason: "为特定框架（Next.js、Tauri、Rust、Tailwind）直接装载专家级编码约束指令。",
    author: "Pontus Abrahamsson",
    tags: ["CursorRules", "编码指令", "系统提示词", "框架规范"],
    actionType: "external",
    homepage: "https://cursor.directory",
    featured: true,
  },
  {
    id: "res:model-context-protocol",
    name: "Model Context Protocol (MCP)",
    category: "ai",
    description: "由 Anthropic 发起并开源的开放式标准化协议，将 AI Agent 安全连接到本地数据与工具。",
    recommendedReason: "正在成为所有 AI 编码助手连接本地数据库、文件系统、终端工具的工业互联标准。",
    author: "Anthropic & Open Source",
    tags: ["MCP标准", "Agent互联", "工具协议", "上下文扩展"],
    actionType: "github",
    repository: "https://github.com/modelcontextprotocol",
    homepage: "https://modelcontextprotocol.io",
    stars: "18k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:dify",
    name: "Dify.AI",
    category: "ai",
    description: "易用的开源大语言模型应用开发平台，可视化编排复杂多智能体（Agent）工作流。",
    recommendedReason: "无需手写大量粘合代码，通过画布即可搭建企业级知识库问答、工作流与 Agent 编排。",
    author: "LangGenius Inc.",
    tags: ["Agent编排", "工作流画布", "应用平台", "知识库RAG"],
    actionType: "github",
    repository: "https://github.com/langgenius/dify",
    homepage: "https://dify.ai",
    stars: "66k+",
    license: "Apache-2.0",
  },
  {
    id: "res:fabric",
    name: "Fabric",
    category: "ai",
    description: "模块化增强人类认知能力的开源 AI 提示词（Patterns）与日常任务命令行框架。",
    recommendedReason: "提取长文核心论点、代码安全审查、技术文档提炼等数百个经过反复微调的高质量 Pattern。",
    author: "Daniel Miessler",
    tags: ["提示词体系", "认知增强", "命令行AI", "高质量模式"],
    actionType: "github",
    repository: "https://github.com/danielmiessler/fabric",
    stars: "31k+",
    license: "MIT",
  },
  {
    id: "res:continue",
    name: "Continue",
    category: "ai",
    description: "领先的完全开源自主控制 VS Code / JetBrains 伴生 AI 编程助手扩展。",
    recommendedReason: "自主连接任何本地或自建大模型，支持代码补全、跨文件上下文问答与编辑，数据安全可控。",
    author: "Continue Dev",
    tags: ["IDE扩展", "开源Copilot", "本地代码补全", "自主可控"],
    actionType: "github",
    repository: "https://github.com/continuedev/continue",
    homepage: "https://continue.dev",
    stars: "23k+",
    license: "Apache-2.0",
  },
  {
    id: "res:vercel-ai-sdk",
    name: "Vercel AI SDK",
    category: "ai",
    description: "专为 TypeScript 与 React/Next.js 全栈开发者构建的统一大模型流式调用与工具调用标准库。",
    recommendedReason: "一网打尽 OpenAI、Anthropic、DeepSeek、Google 等主流模型，首选的现代 Web AI 流式开发 SDK。",
    author: "Vercel",
    tags: ["TypeScript", "流式输出", "工具调用", "全栈标准"],
    actionType: "github",
    repository: "https://github.com/vercel/ai",
    homepage: "https://sdk.vercel.ai",
    stars: "14k+",
    license: "Apache-2.0",
    featured: true,
  },
  {
    id: "res:langchain",
    name: "LangChain",
    category: "ai",
    description: "用于构建具备上下文感知与自主推理能力的 Agent 与 LLM 链路级工业标准框架。",
    recommendedReason: "拥有业界最完备的向量库集成、工具扩展与记忆模块，是学习 AI 架构的必修参考。",
    author: "Harrison Chase & LangChain Inc.",
    tags: ["Agent架构", "链式调用", "RAG框架", "生态庞大"],
    actionType: "github",
    repository: "https://github.com/langchain-ai/langchain",
    homepage: "https://www.langchain.com",
    stars: "98k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:llamaindex",
    name: "LlamaIndex",
    category: "ai",
    description: "专注于外部数据摄取、切分索引与高质量 RAG 知识检索增强的大模型数据底座。",
    recommendedReason: "处理复杂的企业 PDF、代码仓库、数据库混合检索时准确率与上下文相关度极高。",
    author: "Jerry Liu & LlamaIndex",
    tags: ["RAG索引", "向量检索", "私域数据", "知识库专家"],
    actionType: "github",
    repository: "https://github.com/run-llama/llama_index",
    homepage: "https://www.llamaindex.ai",
    stars: "39k+",
    license: "MIT",
  },
  {
    id: "res:browser-use",
    name: "Browser Use",
    category: "ai",
    description: "让 AI Agent 能够像真人一样自主浏览网页、点击表单、提取信息的下一代自动化框架。",
    recommendedReason: "融合视觉感知与 DOM 树定位，轻松驱动大模型执行跨网页自主调研与自动化流程。",
    author: "Browser Use Community",
    tags: ["Agent自主浏览", "Web自动化", "视觉定位", "先锋开源"],
    actionType: "github",
    repository: "https://github.com/browser-use/browser-use",
    homepage: "https://browser-use.com",
    stars: "28k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:llama-cpp",
    name: "llama.cpp",
    category: "ai",
    description: "纯 C/C++ 实现、零外部依赖、可在 CPU 与各类 GPU 后端高效运行 GGUF 量化模型的推理引擎。",
    recommendedReason: "几乎所有本地大模型桌面工具（Ollama、LM Studio、Jan）的底层算力内核，是理解量化与推理底层机制的最佳入口。",
    author: "Georgi Gerganov (ggml-org)",
    tags: ["GGUF量化", "C++推理", "本地部署内核", "CPU推理"],
    actionType: "github",
    repository: "https://github.com/ggml-org/llama.cpp",
    stars: "75k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:lm-studio",
    name: "LM Studio",
    category: "ai",
    description: "面向普通开发者与设计师的可视化本地大模型桌面应用，内置模型市场与 OpenAI 兼容服务端。",
    recommendedReason: "无需命令行即可下载模型、量化切换并对外暴露 localhost 接口，是把本地模型接进自己项目最快的一条路。",
    author: "Element Labs",
    tags: ["桌面GUI", "模型市场", "本地API", "零配置"],
    actionType: "external",
    homepage: "https://lmstudio.ai",
  },
  {
    id: "res:jan",
    name: "Jan",
    category: "ai",
    description: "可完全私有化部署的 ChatGPT 替代桌面客户端，离线运行本地模型并支持接入远程 API。",
    recommendedReason: "对话数据全部留在本机，配合本地推理后端即可获得不依赖任何云服务的个人 AI 工作台。",
    author: "Menlo Research",
    tags: ["离线客户端", "隐私优先", "本地模型", "开源"],
    actionType: "external",
    homepage: "https://jan.ai",
  },
  {
    id: "res:llama-factory",
    name: "LLaMA-Factory",
    category: "ai",
    description: "统一微调 100 余个大语言模型与多模态模型的零代码训练与部署一体化框架。",
    recommendedReason: "在 WebUI 里点选数据集与 LoRA 参数即可完成 SFT/DPO 全流程，中文社区微调实战使用最广的工具。",
    author: "hiyouga (郑耀威)",
    tags: ["模型微调", "LoRA", "零代码WebUI", "中文友好"],
    actionType: "github",
    repository: "https://github.com/hiyouga/LLaMA-Factory",
    homepage: "https://llamafactory.readthedocs.io",
    stars: "45k+",
    license: "Apache-2.0",
  },
  {
    id: "res:unsloth",
    name: "Unsloth",
    category: "ai",
    description: "将 Llama、Qwen、Gemma 等模型微调速度提升 2~5 倍并大幅降低显存占用的开源加速库。",
    recommendedReason: "单张消费级显卡即可微调 7B 量级模型，是个人研究者低成本做 LoRA 与蒸馏的首选方案。",
    author: "Unsloth AI",
    tags: ["微调加速", "省显存", "LoRA", "单卡可跑"],
    actionType: "github",
    repository: "https://github.com/unslothai/unsloth",
    homepage: "https://unsloth.ai",
    stars: "30k+",
    license: "Apache-2.0",
  },
  {
    id: "res:localai",
    name: "LocalAI",
    category: "ai",
    description: "自托管的 OpenAI API 直接替代品，可在消费级硬件上运行文本、图像与语音模型。",
    recommendedReason: "接口与 OpenAI 完全兼容，现有代码通常只需改 base_url 即可切换到本地私有推理服务。",
    author: "Ettore Di Giacinto (mudler)",
    tags: ["OpenAI兼容", "自托管", "多模态", "无GPU可用"],
    actionType: "github",
    repository: "https://github.com/mudler/LocalAI",
    homepage: "https://localai.io",
    stars: "32k+",
    license: "MIT",
  },
  {
    id: "res:text-generation-webui",
    name: "Text Generation WebUI (oobabooga)",
    category: "ai",
    description: "功能最完整的本地大模型 Gradio 交互界面，支持多种加载器、LoRA 热插拔与扩展插件。",
    recommendedReason: "采样参数与提示词模板的调节颗粒度极细，是研究工作模型行为与对比实验的实验室级工具。",
    author: "oobabooga",
    tags: ["Gradio界面", "多加载器", "LoRA热插拔", "实验调试"],
    actionType: "github",
    repository: "https://github.com/oobabooga/text-generation-webui",
    stars: "42k+",
    license: "AGPL-3.0",
  },
  {
    id: "res:langgraph",
    name: "LangGraph",
    category: "ai",
    description: "用有向图与显式状态机编排可控、可持久化、可人工介入的多智能体工作流的底层框架。",
    recommendedReason: "把 Agent 的每一步状态与分支都暴露成图结构，是构建生产级可靠 Agent 的当前主流选择。",
    author: "LangChain Inc.",
    tags: ["Agent状态机", "可控编排", "可持久化", "生产级"],
    actionType: "github",
    repository: "https://github.com/langchain-ai/langgraph",
    homepage: "https://langchain-ai.github.io/langgraph/",
    stars: "12k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:crewai",
    name: "CrewAI",
    category: "ai",
    description: "以角色（Role）、任务（Task）与协作流程为核心的轻量级多智能体编排框架。",
    recommendedReason: "概念模型贴近真实团队分工，几百行代码即可搭出研究员加撰稿人加审校的自动化内容流水线。",
    author: "CrewAI Inc.",
    tags: ["多智能体", "角色协作", "轻量框架", "快速原型"],
    actionType: "github",
    repository: "https://github.com/crewAIInc/crewAI",
    homepage: "https://www.crewai.com",
    stars: "30k+",
    license: "MIT",
  },
  {
    id: "res:autogen",
    name: "Microsoft AutoGen",
    category: "ai",
    description: "微软研究院开源的以多智能体对话为核心范式的 Agent 应用开发框架。",
    recommendedReason: "对话即编排的设计天然支持代码执行、群聊协商与人类回环，是学术论文里最常被复现的 Agent 框架之一。",
    author: "Microsoft Research",
    tags: ["微软开源", "多智能体对话", "代码执行", "研究级"],
    actionType: "github",
    repository: "https://github.com/microsoft/autogen",
    stars: "48k+",
    license: "MIT",
  },
  {
    id: "res:openai-agents-sdk",
    name: "OpenAI Agents SDK",
    category: "ai",
    description: "OpenAI 官方推出的极简多智能体编排 SDK，内置 Handoff 交接、护栏与执行追踪。",
    recommendedReason: "API 面积极小、核心概念只有几个，是把单体 LLM 调用升级为可分工 Agent 系统成本最低的路径。",
    author: "OpenAI",
    tags: ["官方SDK", "Handoff交接", "护栏机制", "极简API"],
    actionType: "github",
    repository: "https://github.com/openai/openai-agents-python",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:pydantic-ai",
    name: "Pydantic AI",
    category: "ai",
    description: "由 Pydantic 团队打造的、以类型安全为第一原则的 Python Agent 开发框架。",
    recommendedReason: "返回值由 Pydantic 模型强约束，彻底消除大模型输出解析的脏活，最适合工程化后端团队。",
    author: "Pydantic",
    tags: ["类型安全", "结构化输出", "Python Agent", "工程化"],
    actionType: "github",
    repository: "https://github.com/pydantic/pydantic-ai",
    homepage: "https://ai.pydantic.dev",
    stars: "10k+",
    license: "MIT",
  },
  {
    id: "res:litellm",
    name: "LiteLLM",
    category: "ai",
    description: "用统一 OpenAI 格式调用上百家模型供应商的 Python SDK 与代理网关。",
    recommendedReason: "一个 base_url 即可切换全部模型商，并自带成本统计、限流与密钥管理，是多模型工程的必备中间层。",
    author: "BerriAI",
    tags: ["统一接口", "多模型商", "成本统计", "代理网关"],
    actionType: "github",
    repository: "https://github.com/BerriAI/litellm",
    homepage: "https://litellm.ai",
    stars: "24k+",
    license: "MIT",
  },
  {
    id: "res:openrouter",
    name: "OpenRouter",
    category: "ai",
    description: "聚合数百个模型的统一 API 网关，提供自动路由、价格对比与统一额度计费。",
    recommendedReason: "无需注册各家账号，就能横向对比同一提示词在不同模型上的表现与真实调用成本。",
    author: "OpenRouter Inc.",
    tags: ["模型聚合", "统一计费", "价格对比", "自动路由"],
    actionType: "external",
    homepage: "https://openrouter.ai",
  },
  {
    id: "res:qdrant",
    name: "Qdrant",
    category: "ai",
    description: "用 Rust 编写的高性能向量数据库，支持富载荷过滤与稀疏稠密混合检索。",
    recommendedReason: "过滤条件与向量检索联合查询性能突出，单二进制部署简单，是自建 RAG 服务的主流选择。",
    author: "Qdrant Team",
    tags: ["向量数据库", "Rust高性能", "载荷过滤", "RAG底座"],
    actionType: "github",
    repository: "https://github.com/qdrant/qdrant",
    homepage: "https://qdrant.tech",
    stars: "23k+",
    license: "Apache-2.0",
  },
  {
    id: "res:milvus",
    name: "Milvus",
    category: "ai",
    description: "面向十亿级向量规模的云原生分布式向量数据库。",
    recommendedReason: "存算分离架构与多种索引类型，是从原型平滑扩展到超大检索量的工业级方案。",
    author: "Zilliz & LF AI & Data",
    tags: ["十亿级向量", "云原生", "分布式", "工业级"],
    actionType: "github",
    repository: "https://github.com/milvus-io/milvus",
    homepage: "https://milvus.io",
    stars: "32k+",
    license: "Apache-2.0",
  },
  {
    id: "res:chroma",
    name: "Chroma",
    category: "ai",
    description: "为 AI 应用设计的轻量级开源向量数据库，API 极简且支持嵌入式运行。",
    recommendedReason: "三行代码即可建立本地向量检索，是学习 RAG 与做原型验证时阻力最小的起点。",
    author: "Chroma Inc.",
    tags: ["轻量向量库", "嵌入式", "易上手", "RAG入门"],
    actionType: "github",
    repository: "https://github.com/chroma-core/chroma",
    homepage: "https://www.trychroma.com",
    stars: "20k+",
    license: "Apache-2.0",
  },
  {
    id: "res:pgvector",
    name: "pgvector",
    category: "ai",
    description: "为 PostgreSQL 增加向量类型与近似最近邻索引的开源扩展。",
    recommendedReason: "无需引入新数据库，直接用已有的 Postgres 事务、备份与 SQL 能力完成向量检索。",
    author: "Andrew Kane",
    tags: ["Postgres扩展", "向量索引", "一体化存储", "SQL检索"],
    actionType: "github",
    repository: "https://github.com/pgvector/pgvector",
    stars: "15k+",
    license: "PostgreSQL",
  },
  {
    id: "res:langfuse",
    name: "Langfuse",
    category: "ai",
    description: "开源的 LLM 工程可观测性平台，追踪调用链、Token 成本与用户反馈评分。",
    recommendedReason: "把每次提问的提示词、耗时与费用落成可视化链路，是调试 RAG 与 Agent 效果不可替代的一环。",
    author: "Langfuse GmbH",
    tags: ["LLM可观测", "调用链追踪", "成本分析", "效果评测"],
    actionType: "github",
    repository: "https://github.com/langfuse/langfuse",
    homepage: "https://langfuse.com",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:promptfoo",
    name: "Promptfoo",
    category: "ai",
    description: "面向提示词与模型的声明式测试、评测与红队渗透命令行工具。",
    recommendedReason: "用 YAML 定义断言与测试集，把提示词改动纳入 CI，像写单测一样防止模型输出回归。",
    author: "Promptfoo Inc.",
    tags: ["提示词评测", "CI集成", "红队测试", "回归防护"],
    actionType: "github",
    repository: "https://github.com/promptfoo/promptfoo",
    homepage: "https://www.promptfoo.dev",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:comfyui",
    name: "ComfyUI",
    category: "ai",
    description: "基于节点图的模块化扩散模型图像与视频生成工作流界面。",
    recommendedReason: "节点化编排让每一步采样、ControlNet 与后处理都可替换复用，是玩转本地图像生成的终极形态。",
    author: "Comfy Org",
    tags: ["节点工作流", "扩散模型", "图像生成", "可扩展"],
    actionType: "github",
    repository: "https://github.com/comfyanonymous/ComfyUI",
    homepage: "https://www.comfy.org",
    stars: "70k+",
    license: "GPL-3.0",
  },
];

