import type { ResourceItem } from "../types";

export const animationResources: ResourceItem[] = [
  {
    id: "res:motion",
    name: "Motion (Framer Motion)",
    category: "animation",
    description: "专为 React 打造的生产级声明式物理与弹簧动画库，现已支持原生 JS。",
    recommendedReason: "手感自然舒适的弹性物理引擎、Layout 布局平滑形变、手势拖拽首选解决方案。",
    author: "Motion Software Inc.",
    tags: ["React动画", "物理弹簧", "布局形变", "手势交互"],
    actionType: "github",
    repository: "https://github.com/motiondivision/motion",
    homepage: "https://motion.dev",
    stars: "26k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:gsap",
    name: "GSAP (GreenSock)",
    category: "animation",
    description: "行业标准级超高性能 JavaScript 时间轴与复杂多阶段连贯动画引擎。",
    recommendedReason: "ScrollTrigger 滚动视差、复杂 SVG 路径形变以及任何需要精准帧控制的史诗级特效。",
    author: "GreenSock",
    tags: ["时间轴", "滚动视差", "高性能", "工业级标准"],
    actionType: "github",
    repository: "https://github.com/greensock/GSAP",
    homepage: "https://gsap.com",
    stars: "18k+",
    license: "Standard GreenSock License",
    featured: true,
  },
  {
    id: "res:threejs",
    name: "Three.js",
    category: "animation",
    description: "让 Web 开发者能够在浏览器 Canvas 中轻松创建与展示 3D 图形的标准库。",
    recommendedReason: "构建三维模型展示、数字孪生、全景交互与沉浸式空间界面不可替代的顶梁柱。",
    author: "Ricardo Cabello (mrdoob)",
    tags: ["3D图形", "WebGL", "计算机图形学", "沉浸空间"],
    actionType: "github",
    repository: "https://github.com/mrdoob/three.js",
    homepage: "https://threejs.org",
    stars: "102k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:react-three-fiber",
    name: "React Three Fiber",
    category: "animation",
    description: "Three.js 的声明式 React 渲染器，将 3D 物体转变为可复用的 JSX 组件。",
    recommendedReason: "将 React 的状态驱动与组件化思想完美融入 3D 世界，生态（Drei）极为庞大。",
    author: "Poimandres",
    tags: ["3D React", "R3F", "声明式三维", "Poimandres"],
    actionType: "github",
    repository: "https://github.com/pmndrs/react-three-fiber",
    homepage: "https://r3f.docs.pmnd.rs",
    stars: "27k+",
    license: "MIT",
  },
  {
    id: "res:lenis",
    name: "Lenis",
    category: "animation",
    description: "极度轻量、平滑丝滑且完全不牺牲浏览器原生可访问性的现代平滑滚动库。",
    recommendedReason: "解决传统平滑滚动卡顿与破坏原生快捷键的痛点，Awwwards 获奖网站标配。",
    author: "Studio Freight (Darkroom)",
    tags: ["平滑滚动", "丝滑体验", "轻量极速", "无障碍友好"],
    actionType: "github",
    repository: "https://github.com/darkroomengineering/lenis",
    homepage: "https://lenis.darkroom.engineering",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:anime-js",
    name: "Anime.js",
    category: "animation",
    description: "轻量级 JavaScript 动画引擎，能够操作 CSS 属性、SVG、DOM 与 JS 对象。",
    recommendedReason: "API 极为优雅精炼，适合不需要大型时间轴的快速微动效与数字翻牌动画。",
    author: "Julian Garnier",
    tags: ["微动效", "轻量引擎", "SVG动画", "API优雅"],
    actionType: "github",
    repository: "https://github.com/juliangarnier/anime",
    homepage: "https://animejs.com",
    stars: "49k+",
    license: "MIT",
  },
  {
    id: "res:tsparticles",
    name: "tsParticles",
    category: "animation",
    description: "跨框架的高性能粒子系统，轻松实现星空、连线网格与动态背景烟雾。",
    recommendedReason: "极简配置生成震撼的大气环境背景，为暗黑风格产品注入静止之上的动态生命力。",
    author: "Matteo Bruni",
    tags: ["粒子系统", "星空特效", "动态背景", "Canvas"],
    actionType: "github",
    repository: "https://github.com/tsparticles/tsparticles",
    homepage: "https://particles.js.org",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:canvas-confetti",
    name: "Canvas Confetti",
    category: "animation",
    description: "在浏览器中发射五彩纸屑庆祝动画的高性能纯原生 Canvas 库。",
    recommendedReason: "在用户完成安装、完成初始化或达成目标那一刻，送上最直观的即时正向情绪价值。",
    author: "Kiril Vatev",
    tags: ["彩带特效", "情绪价值", "即时反馈", "轻量单文件"],
    actionType: "github",
    repository: "https://github.com/catdad/canvas-confetti",
    homepage: "https://www.kirilv.com/canvas-confetti",
    stars: "7k+",
    license: "ISC",
  },
  {
    id: "res:rive-app",
    name: "Rive",
    category: "animation",
    description: "革命性的交互式矢量动效设计与实时跨平台渲染运行环境，支持状态机控制。",
    recommendedReason: "替代传统视频或庞大 GIF，动效体积仅数 KB，且代码可通过状态机驱动每一个骨骼与眼睛眨动。",
    author: "Rive Inc.",
    tags: ["交互动效", "状态机驱动", "矢量骨骼", "次世代交互"],
    actionType: "external",
    homepage: "https://rive.app",
    featured: true,
  },
  {
    id: "res:auto-animate",
    name: "FormKit AutoAnimate",
    category: "animation",
    description: "只需单行代码即可为任何列表的增删改查添加平滑过渡动画的零配置动效工具。",
    recommendedReason: "无需手动编写繁琐的 CSS Transition 或复杂的 Exit 动画，DOM 变动时自动计算补间。",
    author: "FormKit",
    tags: ["零配置", "列表动效", "单行启用", "轻量实用"],
    actionType: "github",
    repository: "https://github.com/formkit/auto-animate",
    homepage: "https://auto-animate.formkit.com",
    stars: "12k+",
    license: "MIT",
  },
  {
    id: "res:react-spring",
    name: "React Spring",
    category: "animation",
    description: "基于弹簧物理模型而非固定时长的 React 动画库。",
    recommendedReason: "动画参数由刚度与阻尼描述，交互打断时可自然接续，是手势驱动动效最顺滑的解法。",
    author: "Paul Henschel (pmndrs)",
    tags: ["弹簧物理", "手势驱动", "可打断", "React"],
    actionType: "github",
    repository: "https://github.com/pmndrs/react-spring",
    homepage: "https://react-spring.dev",
    stars: "28k+",
    license: "MIT",
  },
  {
    id: "res:lottie-web",
    name: "Lottie",
    category: "animation",
    description: "在 Web 与移动端原生渲染 Adobe After Effects 导出动画的开源引擎。",
    recommendedReason: "矢量动画体积小且可无损缩放，是把设计师的 AE 成品直接搬进产品界面最成熟的工业方案。",
    author: "Airbnb",
    tags: ["AE动画", "矢量渲染", "跨平台", "设计师协作"],
    actionType: "github",
    repository: "https://github.com/airbnb/lottie-web",
    homepage: "https://airbnb.io/lottie",
    stars: "30k+",
    license: "MIT",
  },
  {
    id: "res:dotlottie-web",
    name: "dotLottie",
    category: "animation",
    description: "Lottie 官方推出的开放 .lottie 格式与高性能跨平台播放器。",
    recommendedReason: "把动画资源与主题打包成单文件，加载更快且支持多主题切换，是 Lottie 的现代替代实现。",
    author: "LottieFiles",
    tags: ["lottie格式", "单文件资源", "多主题", "官方播放器"],
    actionType: "github",
    repository: "https://github.com/LottieFiles/dotlottie-web",
    homepage: "https://dotlottie.io",
    license: "MIT",
  },
  {
    id: "res:shadertoy",
    name: "Shadertoy",
    category: "animation",
    description: "在浏览器中编写与分享 GLSL 片元着色器的在线社区与实时预览环境。",
    recommendedReason: "海量可运行的着色器案例可直接抄改，是学习 WebGL 与程序化视觉最快的一条实践路径。",
    author: "Inigo Quilez & Pol Jeremias",
    tags: ["GLSL着色器", "在线预览", "程序化视觉", "案例丰富"],
    actionType: "external",
    homepage: "https://www.shadertoy.com",
  },
  {
    id: "res:thebookofshaders",
    name: "The Book of Shaders",
    category: "animation",
    description: "面向设计师与前端工程师的片元着色器渐进式系统教程。",
    recommendedReason: "从颜色与形状逐章推导到噪声与生成艺术，每章都内嵌可实时编辑的着色器沙盒。",
    author: "Patricio Gonzalez Vivo & Jen Lowe",
    tags: ["着色器教程", "交互式学习", "生成艺术", "GLSL入门"],
    actionType: "external",
    homepage: "https://thebookofshaders.com",
  },
  {
    id: "res:drei",
    name: "Drei",
    category: "animation",
    description: "为 React Three Fiber 提供的大量实用 3D 辅助组件与抽象封装集合。",
    recommendedReason: "相机控制、环境光照、后期处理与加载器都有现成组件，可省掉数百行 Three.js 样板代码。",
    author: "pmndrs",
    tags: ["R3F生态", "3D辅助组件", "相机控制", "后期处理"],
    actionType: "github",
    repository: "https://github.com/pmndrs/drei",
    homepage: "https://drei.docs.pmnd.rs",
    stars: "9k+",
    license: "MIT",
  },
  {
    id: "res:babylonjs",
    name: "Babylon.js",
    category: "animation",
    description: "微软开源的功能完备的 Web 3D 与游戏引擎，内置物理、材质与节点编辑器。",
    recommendedReason: "开箱提供游戏级的场景、粒子与 PBR 材质能力，适合做复杂交互式 3D 应用而非单纯展示页。",
    author: "Microsoft",
    tags: ["3D引擎", "游戏级能力", "物理系统", "节点编辑器"],
    actionType: "github",
    repository: "https://github.com/BabylonJS/Babylon.js",
    homepage: "https://www.babylonjs.com",
    stars: "24k+",
    license: "Apache-2.0",
  },
  {
    id: "res:playcanvas",
    name: "PlayCanvas",
    category: "animation",
    description: "主打轻量与高性能的 WebGL 3D 引擎，配有在线协同编辑器。",
    recommendedReason: "引擎体积小、移动端表现优秀，团队可以在浏览器里共同编辑场景并一键发布。",
    author: "PlayCanvas Ltd.",
    tags: ["WebGL引擎", "轻量高性能", "在线编辑器", "移动端友好"],
    actionType: "github",
    repository: "https://github.com/playcanvas/engine",
    homepage: "https://playcanvas.com",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:model-viewer",
    name: "model-viewer",
    category: "animation",
    description: "Google 推出的用一行 HTML 标签在网页中展示可交互 3D 模型与 AR 的 Web Component。",
    recommendedReason: "内置相机轨道、环境光照与 AR 投放能力，做产品 3D 展示基本不需要写 JavaScript。",
    author: "Google",
    tags: ["Web Component", "3D展示", "AR投放", "一行接入"],
    actionType: "github",
    repository: "https://github.com/google/model-viewer",
    homepage: "https://modelviewer.dev",
    stars: "7k+",
    license: "Apache-2.0",
  },
  {
    id: "res:video-js",
    name: "Video.js",
    category: "animation",
    description: "老牌且生态成熟的 HTML5 视频播放器框架，支持插件与自定义皮肤。",
    recommendedReason: "统一各浏览器原生视频控件的差异并支持 HLS 流媒体扩展，是网页视频播放的稳妥基座。",
    author: "Video.js Contributors",
    tags: ["视频播放器", "插件生态", "HLS支持", "跨浏览器一致"],
    actionType: "github",
    repository: "https://github.com/videojs/video.js",
    homepage: "https://videojs.com",
    stars: "38k+",
    license: "Apache-2.0",
  },
  {
    id: "res:remotion",
    name: "Remotion",
    category: "animation",
    description: "用 React 组件与 TypeScript 以代码方式生成 MP4 视频的框架。",
    recommendedReason: "视频变成可版本化、可传参、可批量渲染的代码，做数据驱动的宣传片与自动化内容极强。",
    author: "Remotion GmbH",
    tags: ["代码生视频", "React", "批量渲染", "可编程内容"],
    actionType: "github",
    repository: "https://github.com/remotion-dev/remotion",
    homepage: "https://www.remotion.dev",
    stars: "22k+",
    license: "Remotion License",
    featured: true,
  },
  {
    id: "res:theatre-js",
    name: "Theatre.js",
    category: "animation",
    description: "带可视化时间轴编辑器的 JavaScript 动效设计工具与运行时。",
    recommendedReason: "像用专业动画软件一样拖拽关键帧编排复杂序列，再把结果序列化进项目，兼顾手感与工程化。",
    author: "Theatre.js",
    tags: ["可视化时间轴", "关键帧编辑", "动效设计", "序列化"],
    actionType: "github",
    repository: "https://github.com/theatre-js/theatre",
    homepage: "https://www.theatrejs.com",
    stars: "11k+",
    license: "Apache-2.0",
  },
  {
    id: "res:matter-js",
    name: "Matter.js",
    category: "animation",
    description: "轻量稳定的 JavaScript 2D 刚体物理引擎，可做碰撞、约束与重力模拟。",
    recommendedReason: "API 简单直观，是做物理沙盒、拖拽交互与趣味加载动画时最省心的物理层方案。",
    author: "Liam Brummitt",
    tags: ["2D物理", "刚体碰撞", "交互沙盒", "轻量"],
    actionType: "github",
    repository: "https://github.com/liabru/matter-js",
    homepage: "https://brm.io/matter-js",
    stars: "17k+",
    license: "MIT",
  },
  {
    id: "res:manim",
    name: "Manim",
    category: "animation",
    description: "Python 编写的数学动画引擎，以几何变换与公式推导为核心表现力。",
    recommendedReason: "3Blue1Brown 的视觉风格正出自它，讲解算法流程与数学直觉几乎没有更合适的工具。",
    author: "Manim Community",
    tags: ["数学动画", "Python", "公式推演", "知识讲解"],
    actionType: "github",
    repository: "https://github.com/ManimCommunity/manim",
    homepage: "https://www.manim.community",
    stars: "32k+",
    license: "MIT",
  },
];

