import type { ResourceItem } from "../types";

export const animationResources: ResourceItem[] = [
  {
    id: "res:motion",
    name: "Motion (Framer Motion)",
    category: "animation",
    description: "专为 React 打造的生产级声明式物理与弹簧动画库，现已支持原生 JS。",
    recommendedReason: "手感自然舒适的弹性物理引擎、Layout 布局平滑形变、手势拖拽首选解决方案。",
    author: "Motion Software Inc.",
    tags: ["React动画", "物理弹簧", "布局形变", "手势交互"],
    actionType: "github",
    repository: "https://github.com/motiondivision/motion",
    homepage: "https://motion.dev",
    stars: "26k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:gsap",
    name: "GSAP (GreenSock)",
    category: "animation",
    description: "行业标准级超高性能 JavaScript 时间轴与复杂多阶段连贯动画引擎。",
    recommendedReason: "ScrollTrigger 滚动视差、复杂 SVG 路径形变以及任何需要精准帧控制的史诗级特效。",
    author: "GreenSock",
    tags: ["时间轴", "滚动视差", "高性能", "工业级标准"],
    actionType: "github",
    repository: "https://github.com/greensock/GSAP",
    homepage: "https://gsap.com",
    stars: "18k+",
    license: "Standard GreenSock License",
    featured: true,
  },
  {
    id: "res:threejs",
    name: "Three.js",
    category: "animation",
    description: "让 Web 开发者能够在浏览器 Canvas 中轻松创建与展示 3D 图形的标准库。",
    recommendedReason: "构建三维模型展示、数字孪生、全景交互与沉浸式空间界面不可替代的顶梁柱。",
    author: "Ricardo Cabello (mrdoob)",
    tags: ["3D图形", "WebGL", "计算机图形学", "沉浸空间"],
    actionType: "github",
    repository: "https://github.com/mrdoob/three.js",
    homepage: "https://threejs.org",
    stars: "102k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:react-three-fiber",
    name: "React Three Fiber",
    category: "animation",
    description: "Three.js 的声明式 React 渲染器，将 3D 物体转变为可复用的 JSX 组件。",
    recommendedReason: "将 React 的状态驱动与组件化思想完美融入 3D 世界，生态（Drei）极为庞大。",
    author: "Poimandres",
    tags: ["3D React", "R3F", "声明式三维", "Poimandres"],
    actionType: "github",
    repository: "https://github.com/pmndrs/react-three-fiber",
    homepage: "https://r3f.docs.pmnd.rs",
    stars: "27k+",
    license: "MIT",
  },
  {
    id: "res:lenis",
    name: "Lenis",
    category: "animation",
    description: "极度轻量、平滑丝滑且完全不牺牲浏览器原生可访问性的现代平滑滚动库。",
    recommendedReason: "解决传统平滑滚动卡顿与破坏原生快捷键的痛点，Awwwards 获奖网站标配。",
    author: "Studio Freight (Darkroom)",
    tags: ["平滑滚动", "丝滑体验", "轻量极速", "无障碍友好"],
    actionType: "github",
    repository: "https://github.com/darkroomengineering/lenis",
    homepage: "https://lenis.darkroom.engineering",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:anime-js",
    name: "Anime.js",
    category: "animation",
    description: "轻量级 JavaScript 动画引擎，能够操作 CSS 属性、SVG、DOM 与 JS 对象。",
    recommendedReason: "API 极为优雅精炼，适合不需要大型时间轴的快速微动效与数字翻牌动画。",
    author: "Julian Garnier",
    tags: ["微动效", "轻量引擎", "SVG动画", "API优雅"],
    actionType: "github",
    repository: "https://github.com/juliangarnier/anime",
    homepage: "https://animejs.com",
    stars: "49k+",
    license: "MIT",
  },
  {
    id: "res:tsparticles",
    name: "tsParticles",
    category: "animation",
    description: "跨框架的高性能粒子系统，轻松实现星空、连线网格与动态背景烟雾。",
    recommendedReason: "极简配置生成震撼的大气环境背景，为暗黑风格产品注入静止之上的动态生命力。",
    author: "Matteo Bruni",
    tags: ["粒子系统", "星空特效", "动态背景", "Canvas"],
    actionType: "github",
    repository: "https://github.com/tsparticles/tsparticles",
    homepage: "https://particles.js.org",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:canvas-confetti",
    name: "Canvas Confetti",
    category: "animation",
    description: "在浏览器中发射五彩纸屑庆祝动画的高性能纯原生 Canvas 库。",
    recommendedReason: "在用户完成安装、完成初始化或达成目标那一刻，送上最直观的即时正向情绪价值。",
    author: "Kiril Vatev",
    tags: ["彩带特效", "情绪价值", "即时反馈", "轻量单文件"],
    actionType: "github",
    repository: "https://github.com/catdad/canvas-confetti",
    homepage: "https://www.kirilv.com/canvas-confetti",
    stars: "7k+",
    license: "ISC",
  },
  {
    id: "res:rive-app",
    name: "Rive",
    category: "animation",
    description: "革命性的交互式矢量动效设计与实时跨平台渲染运行环境，支持状态机控制。",
    recommendedReason: "替代传统视频或庞大 GIF，动效体积仅数 KB，且代码可通过状态机驱动每一个骨骼与眼睛眨动。",
    author: "Rive Inc.",
    tags: ["交互动效", "状态机驱动", "矢量骨骼", "次世代交互"],
    actionType: "external",
    homepage: "https://rive.app",
    featured: true,
  },
  {
    id: "res:auto-animate",
    name: "FormKit AutoAnimate",
    category: "animation",
    description: "只需单行代码即可为任何列表的增删改查添加平滑过渡动画的零配置动效工具。",
    recommendedReason: "无需手动编写繁琐的 CSS Transition 或复杂的 Exit 动画，DOM 变动时自动计算补间。",
    author: "FormKit",
    tags: ["零配置", "列表动效", "单行启用", "轻量实用"],
    actionType: "github",
    repository: "https://github.com/formkit/auto-animate",
    homepage: "https://auto-animate.formkit.com",
    stars: "12k+",
    license: "MIT",
  },
];

