import type { ResourceItem } from "../types";

export const collectionResources: ResourceItem[] = [
  {
    id: "res:awesome-design-systems",
    name: "Awesome Design Systems",
    category: "collections",
    description: "精心挑选的全球顶尖公司（Apple, IBM Carbon, Polaris, Atlassian 等）公开设计系统集合。",
    recommendedReason: "学习大厂如何规范色彩阶梯、文字字阶、无障碍对比度与交互响应令牌。",
    author: "Alexey Shenin",
    tags: ["设计系统", "大厂规范", "DesignTokens", "视觉资产"],
    actionType: "github",
    repository: "https://github.com/alexpate/awesome-design-systems",
    stars: "8k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:awesome-selfhosted",
    name: "Awesome Self-Hosted",
    category: "collections",
    description: "全球最全面、每日更新的自建网络服务、私有云存储、敏捷看板与开发平台权威清单。",
    recommendedReason: "不再依赖第三方高昂按月订阅服务，在本地局域网或 VPS 搭建自己专属的生产力数字城堡。",
    author: "Awesome Self-Hosted Community",
    tags: ["自建服务", "私有云", "开源替代", "极客首选"],
    actionType: "github",
    repository: "https://github.com/awesome-selfhosted/awesome-selfhosted",
    homepage: "https://awesome-selfhosted.net",
    stars: "220k+",
    license: "CC-BY-SA-3.0",
    featured: true,
  },
  {
    id: "res:awesome-rust",
    name: "Awesome Rust",
    category: "collections",
    description: "由 Rust 官方社区精挑细选的生产级 Rust 代码库、网络框架、图形库与命令行工具目录。",
    recommendedReason: "选型 Rust 依赖库时的必备索引，避免使用年久失修或处于实验性阶段的代码包。",
    author: "Rust Community",
    tags: ["Rust生态", "依赖选型", "高质量包", "社区权威"],
    actionType: "github",
    repository: "https://github.com/rust-unofficial/awesome-rust",
    stars: "45k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:awesome-tailwind",
    name: "Awesome Tailwind CSS",
    category: "collections",
    description: "Tailwind CSS 生态插件、工具、扩展、组件库与学习资源的终极聚合目录。",
    recommendedReason: "发现优秀 Tailwind Typography 排版插件、Forms 表单重置库与主题配色生成器。",
    author: "Anindya Dey",
    tags: ["Tailwind", "生态聚合", "常用插件", "主题工具"],
    actionType: "github",
    repository: "https://github.com/aniftyco/awesome-tailwindcss",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:awesome-python",
    name: "Awesome Python",
    category: "collections",
    description: "包含 80+ 个分类的精选 Python 卓越框架、自动化利器、数据工程与科学计算工具索引。",
    recommendedReason: "从 FastAPI、Pydantic 到 PyTorch、uv，全面掌控 Python 最新现代工程生态全貌。",
    author: "Vinta Software",
    tags: ["Python生态", "卓越框架", "自动化", "数据分析"],
    actionType: "github",
    repository: "https://github.com/vinta/awesome-python",
    stars: "230k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-mac",
    name: "Awesome Mac",
    category: "collections",
    description: "专为程序员与创作者准备的 macOS 优质开源软件、工具箱与高级效率应用精选清单。",
    recommendedReason: "Window 管理器、截图标记工具、剪贴板增强器与终端利器一网打尽。",
    author: "Jaywcjlove & Contributors",
    tags: ["macOS工具", "开源软件", "开发者生产力", "效率神器"],
    actionType: "github",
    repository: "https://github.com/jaywcjlove/awesome-mac",
    stars: "76k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-creative-coding",
    name: "Awesome Creative Coding",
    category: "collections",
    description: "为视觉艺术家、创意程序员与生成艺术从业者精心整理的工具库与教学资源清单。",
    recommendedReason: "探索 Processing, Shaders, WebGL, TouchDesigner 与算法艺术的无限奇妙可能。",
    author: "Terkel Gjervig",
    tags: ["创意编程", "生成艺术", "Shader着色器", "视觉艺术"],
    actionType: "github",
    repository: "https://github.com/terkelg/awesome-creative-coding",
    stars: "13k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-ai-agents",
    name: "Awesome AI Agents",
    category: "collections",
    description: "聚焦前沿自主 AI Agent、多智能体协同框架、记忆机制与环境评估的最新开源项目全景图。",
    recommendedReason: "紧跟 2025-2026 年自主智能体（Autonomous Agents）架构演进，寻找灵感与实战脚手架。",
    author: "Wong2",
    tags: ["AI Agent", "多智能体", "自主规划", "前沿技术"],
    actionType: "github",
    repository: "https://github.com/Wong2/awesome-ai-agents",
    stars: "7k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-react",
    name: "Awesome React",
    category: "collections",
    description: "React 生态最完整的资源索引，覆盖框架、组件、状态管理、测试与工具链。",
    recommendedReason: "遇到任何 React 需求先在这里检索一遍，通常能直接找到已被社区筛选过的成熟方案。",
    author: "enaqx",
    tags: ["React生态", "资源索引", "组件与工具", "长期维护"],
    actionType: "github",
    repository: "https://github.com/enaqx/awesome-react",
    stars: "65k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-vue",
    name: "Awesome Vue",
    category: "collections",
    description: "Vue 官方组织维护的生态资源与库汇总清单。",
    recommendedReason: "由 Vue 核心团队背书、去重严格，是判断某个 Vue 库是否值得使用的第一道筛选。",
    author: "Vue.js Community",
    tags: ["Vue生态", "官方维护", "库筛选", "资源汇总"],
    actionType: "github",
    repository: "https://github.com/vuejs/awesome-vue",
    stars: "72k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-nodejs",
    name: "Awesome Node.js",
    category: "collections",
    description: "Sindre Sorhus 维护的 Node.js 生态高质量包与工具精选。",
    recommendedReason: "收录标准极严（几乎只保留生产级库），选依赖时能有效避开年久失修的包。",
    author: "Sindre Sorhus",
    tags: ["Node生态", "严格筛选", "依赖选型", "生产级"],
    actionType: "github",
    repository: "https://github.com/sindresorhus/awesome-nodejs",
    stars: "58k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-typescript",
    name: "Awesome TypeScript",
    category: "collections",
    description: "TypeScript 语言、类型体操与工程实践的资源清单。",
    recommendedReason: "集中收录类型进阶材料与工具，是突破「只会写基础类型注解」瓶颈的索引。",
    author: "dzharii",
    tags: ["TypeScript", "类型进阶", "工程实践", "学习资源"],
    actionType: "github",
    repository: "https://github.com/dzharii/awesome-typescript",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:awesome-go",
    name: "Awesome Go",
    category: "collections",
    description: "Go 语言最权威的库、框架与工具分类索引，带活跃度与星标标注。",
    recommendedReason: "每个条目都标注了最近提交时间，能直观判断一个 Go 库是否仍在维护。",
    author: "Avelino",
    tags: ["Go生态", "分类索引", "维护状态", "权威清单"],
    actionType: "github",
    repository: "https://github.com/avelino/awesome-go",
    stars: "135k+",
    license: "MIT",
  },
  {
    id: "res:awesome-cpp",
    name: "Awesome C++",
    category: "collections",
    description: "C 与 C++ 生态的框架、库、编译器与学习资源分类清单。",
    recommendedReason: "系统编程与高性能计算选型时的对照表，覆盖音频、图形、并发与网络等细分领域。",
    author: "fffaraz",
    tags: ["C++生态", "系统编程", "领域分类", "选型参考"],
    actionType: "github",
    repository: "https://github.com/fffaraz/awesome-cpp",
    stars: "61k+",
    license: "MIT",
  },
  {
    id: "res:awesome-javascript",
    name: "Awesome JavaScript",
    category: "collections",
    description: "JavaScript 语言层面的库、工具与规范精选清单。",
    recommendedReason: "不绑定具体框架，用来系统补齐对语言生态全貌（打包、测试、格式化、CLI）的认知。",
    author: "sorrycc",
    tags: ["JavaScript生态", "语言工具", "框架无关", "全景认知"],
    actionType: "github",
    repository: "https://github.com/sorrycc/awesome-javascript",
    stars: "34k+",
    license: "MIT",
  },
  {
    id: "res:awesome-nextjs",
    name: "Awesome Next.js",
    category: "collections",
    description: "Next.js 生态的模板、插件、示例与学习资源索引。",
    recommendedReason: "找生产可用的 Next.js 起步模板与部署方案，比在 GitHub 上盲目搜索效率高得多。",
    author: "unicodeveloper",
    tags: ["Next.js生态", "模板与插件", "部署方案", "资源索引"],
    actionType: "github",
    repository: "https://github.com/unicodeveloper/awesome-nextjs",
    stars: "10k+",
    license: "MIT",
  },
  {
    id: "res:awesome-vite",
    name: "Awesome Vite",
    category: "collections",
    description: "Vite 官方组织维护的插件、模板与社区资源索引。",
    recommendedReason: "插件按功能分类且标注官方/社区来源，接入构建能力时可直接定位可信插件。",
    author: "Vite Community",
    tags: ["Vite插件", "官方组织", "构建扩展", "模板资源"],
    actionType: "github",
    repository: "https://github.com/vitejs/awesome-vite",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:awesome-tauri",
    name: "Awesome Tauri",
    category: "collections",
    description: "Tauri 官方维护的插件、模板、示例与生态工具索引。",
    recommendedReason: "桌面端权限配置、自动更新与打包发布等踩坑点，基本都能在这里找到现成方案。",
    author: "Tauri Apps",
    tags: ["Tauri生态", "桌面开发", "插件模板", "官方维护"],
    actionType: "github",
    repository: "https://github.com/tauri-apps/awesome-tauri",
    stars: "5k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-docker",
    name: "Awesome Docker",
    category: "collections",
    description: "Docker 与容器生态的工具、编排方案与最佳实践清单。",
    recommendedReason: "从本地开发镜像瘦身到生产编排方案一应俱全，是容器化落地时的路线图式参考。",
    author: "veggiemonk",
    tags: ["Docker", "容器生态", "编排方案", "最佳实践"],
    actionType: "github",
    repository: "https://github.com/veggiemonk/awesome-docker",
    stars: "32k+",
    license: "Apache-2.0",
  },
  {
    id: "res:awesome-kubernetes",
    name: "Awesome Kubernetes",
    category: "collections",
    description: "Kubernetes 学习资料、运维工具与发行版分类索引。",
    recommendedReason: "把庞杂的 K8s 生态按学习路径与运维场景拆开，适合作为系统性补课的地图。",
    author: "Ramit Surana",
    tags: ["Kubernetes", "云原生", "学习路径", "运维工具"],
    actionType: "github",
    repository: "https://github.com/ramitsurana/awesome-kubernetes",
    stars: "15k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-shell",
    name: "Awesome Shell",
    category: "collections",
    description: "命令行框架、Shell 插件、提示符与终端工具的精选清单。",
    recommendedReason: "一次性看到整个终端生产力生态，是系统性替换掉原始 bash 体验的高效起点。",
    author: "alebcay",
    tags: ["Shell生态", "终端工具", "命令行框架", "生产力"],
    actionType: "github",
    repository: "https://github.com/alebcay/awesome-shell",
    stars: "34k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-command-line-apps",
    name: "Awesome Command Line Apps",
    category: "collections",
    description: "按功能分类的现代命令行应用精选清单。",
    recommendedReason: "聚焦「装完就能立刻提效」的终端应用，比读长篇教程更快获得实际收益。",
    author: "herrbischoff",
    tags: ["命令行应用", "按功能分类", "即装即用", "效率工具"],
    actionType: "github",
    repository: "https://github.com/herrbischoff/awesome-command-line-apps",
    stars: "3k+",
    license: "MIT",
  },
  {
    id: "res:awesome-windows",
    name: "Awesome Windows",
    category: "collections",
    description: "Windows 平台开发与效率工具的分类精选清单。",
    recommendedReason: "Windows 开发者常常缺少好工具的索引，这里把终端、效率与系统工具集中补齐。",
    author: "Awesome-Windows Community",
    tags: ["Windows工具", "开发环境", "效率软件", "平台专属"],
    actionType: "github",
    repository: "https://github.com/Awesome-Windows/Awesome",
    stars: "28k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-llm",
    name: "Awesome LLM",
    category: "collections",
    description: "大语言模型论文、训练框架、评测基准与部署工具的系统性索引。",
    recommendedReason: "把论文线索与工程工具放在同一份清单里，是快速建立 LLM 技术全景认知的入口。",
    author: "Hannibal046",
    tags: ["大语言模型", "论文索引", "训练框架", "评测基准"],
    actionType: "github",
    repository: "https://github.com/Hannibal046/Awesome-LLM",
    stars: "22k+",
    license: "MIT",
  },
  {
    id: "res:awesome-mcp-servers",
    name: "Awesome MCP Servers",
    category: "collections",
    description: "Model Context Protocol 官方与社区 MCP 服务器的完整索引。",
    recommendedReason: "想知道某个工具（数据库、浏览器、Git）有没有现成 MCP 接入，查这一份就够了。",
    author: "punkpeye",
    tags: ["MCP服务器", "Agent工具链", "协议生态", "即插即用"],
    actionType: "github",
    repository: "https://github.com/punkpeye/awesome-mcp-servers",
    stars: "25k+",
    license: "MIT",
  },
  {
    id: "res:awesome-generative-ai",
    name: "Awesome Generative AI",
    category: "collections",
    description: "生成式 AI 领域模型、产品与工具的分类汇总清单。",
    recommendedReason: "按模态（文本、图像、音频、视频）横向铺开，适合快速判断某个方向上有哪些可用产品。",
    author: "steven2358",
    tags: ["生成式AI", "多模态", "产品索引", "方向概览"],
    actionType: "github",
    repository: "https://github.com/steven2358/awesome-generative-ai",
    stars: "9k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-cursorrules",
    name: "Awesome Cursor Rules",
    category: "collections",
    description: "面向 Cursor 等 AI 编辑器的项目规则（.cursorrules）精选集合。",
    recommendedReason: "可直接复制成熟项目的 Agent 编码约束，显著减少 AI 生成代码偏离团队规范的情况。",
    author: "PatrickJS",
    tags: ["AI编码规范", "Cursor规则", "Agent约束", "工程习惯"],
    actionType: "github",
    repository: "https://github.com/PatrickJS/awesome-cursorrules",
    stars: "26k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-react-components",
    name: "Awesome React Components",
    category: "collections",
    description: "按组件类型（表格、图表、拖拽、富文本）组织的 React 组件库索引。",
    recommendedReason: "按具体组件需求检索而不是按库名，做技术选型时能一次看到所有同类竞品。",
    author: "brillout",
    tags: ["React组件", "按类型检索", "选型对比", "组件库索引"],
    actionType: "github",
    repository: "https://github.com/brillout/awesome-react-components",
    stars: "43k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-free-for-dev",
    name: "Free for Developers",
    category: "collections",
    description: "面向开发者永久免费（或含免费额度）的 SaaS 服务与基础设施清单。",
    recommendedReason: "个人项目与原型阶段几乎能白嫖整套基础设施，从托管部署到数据库与监控全覆盖。",
    author: "Ripienaar",
    tags: ["免费额度", "SaaS清单", "基础设施", "个人项目"],
    actionType: "github",
    repository: "https://github.com/ripienaar/free-for-dev",
    stars: "95k+",
    license: "MIT",
  },
  {
    id: "res:awesome-oss-alternatives",
    name: "Awesome OSS Alternatives",
    category: "collections",
    description: "按被替代商业产品组织的开源替代方案索引，附带融资与热度数据。",
    recommendedReason: "评估自建替代商业服务时，可直接看到同类开源项目的成熟度与社区规模。",
    author: "Runa Capital",
    tags: ["开源替代", "商业软件对照", "自建方案", "成熟度评估"],
    actionType: "github",
    repository: "https://github.com/RunaCapital/awesome-oss-alternatives",
    stars: "18k+",
    license: "MIT",
  },
  {
    id: "res:codecrafters-build-your-own-x",
    name: "Build Your Own X",
    category: "collections",
    description: "从零手写数据库、编译器、操作系统、Git 与 Docker 等系统的分步教程汇总。",
    recommendedReason: "真正理解底层系统的最有效方式，挑一个方向跟着做完，技术深度会有质变。",
    author: "CodeCrafters (Daniel Stefanovic)",
    tags: ["从零实现", "底层原理", "分步教程", "深度提升"],
    actionType: "github",
    repository: "https://github.com/codecrafters-io/build-your-own-x",
    stars: "330k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:project-based-learning",
    name: "Project Based Learning",
    category: "collections",
    description: "按语言与方向组织的实战项目教程索引，每个条目都是一个可完成的完整项目。",
    recommendedReason: "摆脱只看不写的学习方式，直接挑一个项目跟做，学习留存率远高于阅读文档。",
    author: "Practical Tutorials",
    tags: ["项目驱动", "实战教程", "按语言分类", "动手学习"],
    actionType: "github",
    repository: "https://github.com/practical-tutorials/project-based-learning",
    stars: "220k+",
    license: "MIT",
  },
  {
    id: "res:coding-interview-university",
    name: "Coding Interview University",
    category: "collections",
    description: "把计算机科学核心课程整理成可执行多周计划的算法与系统面试自学路线。",
    recommendedReason: "从数据结构、复杂度到操作系统与系统设计逐项打勾，是转岗与求职准备最完整的路线图。",
    author: "John Washam",
    tags: ["面试准备", "计算机基础", "自学路线", "系统设计"],
    actionType: "github",
    repository: "https://github.com/jwasham/coding-interview-university",
    stars: "310k+",
    license: "CC-BY-SA-4.0",
  },
  {
    id: "res:free-programming-books",
    name: "Free Programming Books",
    category: "collections",
    description: "Free Ebook Foundation 维护的多语言免费编程书籍与课程资源索引。",
    recommendedReason: "按语言与主题检索即可找到官方或高质量免费教材，含大量中文资料。",
    author: "Free Ebook Foundation",
    tags: ["免费书籍", "多语言", "课程资源", "官方教材"],
    actionType: "github",
    repository: "https://github.com/EbookFoundation/free-programming-books",
    stars: "350k+",
    license: "CC-BY-4.0",
  },
  {
    id: "res:awesome-cheatsheets",
    name: "Awesome Cheatsheets",
    category: "collections",
    description: "覆盖数十种语言与框架的单页速查表集合，含中文版。",
    recommendedReason: "复习陌生语言的常用语法与命令时查阅最快，也可当作随身参考挂在项目文档里。",
    author: "LeCoupa",
    tags: ["速查表", "多语言覆盖", "中文版", "随身参考"],
    actionType: "github",
    repository: "https://github.com/LeCoupa/awesome-cheatsheets",
    stars: "41k+",
    license: "MIT",
  },
  {
    id: "res:awesome-actions",
    name: "Awesome Actions",
    category: "collections",
    description: "GitHub Actions 官方与社区 Action 的分类精选清单。",
    recommendedReason: "搭建 CI/CD 时不必自己写每一步，绝大多数常见任务都有经过验证的现成 Action。",
    author: "sdras (Sarah Drasner)",
    tags: ["GitHub Actions", "CI/CD", "自动化", "现成脚本"],
    actionType: "github",
    repository: "https://github.com/sdras/awesome-actions",
    stars: "26k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-sysadmin",
    name: "Awesome Sysadmin",
    category: "collections",
    description: "开源系统管理、监控、备份与网络工具的精选清单。",
    recommendedReason: "自建服务器与个人云时按运维环节查找工具，把散落的最佳实践一次性补齐。",
    author: "Awesome FOSS",
    tags: ["系统运维", "监控备份", "网络工具", "自建服务"],
    actionType: "github",
    repository: "https://github.com/awesome-foss/awesome-sysadmin",
    stars: "32k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-css",
    name: "Awesome CSS",
    category: "collections",
    description: "CSS 方法论、框架、工具与学习资料的精简精选清单。",
    recommendedReason: "条目少而精，适合快速了解原子化、容器查询与现代 CSS 能力的关键资源。",
    author: "Awesome CSS Group",
    tags: ["CSS生态", "精简清单", "方法论", "现代CSS"],
    actionType: "github",
    repository: "https://github.com/awesome-css-group/awesome-css",
    stars: "5k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-devops",
    name: "Awesome DevOps",
    category: "collections",
    description: "DevOps 实践中云平台、CI/CD、容器与基础设施即代码的工具清单。",
    recommendedReason: "把交付链路各环节的工具串成完整视图，适合规划团队工程效率体系时做参照。",
    author: "wmariuss",
    tags: ["DevOps", "交付链路", "IaC", "工程效率"],
    actionType: "github",
    repository: "https://github.com/wmariuss/awesome-devops",
    stars: "5k+",
    license: "MIT",
  },
];
