import type { ResourceItem } from "../types";

export const collectionResources: ResourceItem[] = [
  {
    id: "res:awesome-design-systems",
    name: "Awesome Design Systems",
    category: "collections",
    description: "精心挑选的全球顶尖公司（Apple, IBM Carbon, Polaris, Atlassian 等）公开设计系统集合。",
    recommendedReason: "学习大厂如何规范色彩阶梯、文字字阶、无障碍对比度与交互响应令牌。",
    author: "Alexey Shenin",
    tags: ["设计系统", "大厂规范", "DesignTokens", "视觉资产"],
    actionType: "github",
    repository: "https://github.com/alexpate/awesome-design-systems",
    stars: "8k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:awesome-selfhosted",
    name: "Awesome Self-Hosted",
    category: "collections",
    description: "全球最全面、每日更新的自建网络服务、私有云存储、敏捷看板与开发平台权威清单。",
    recommendedReason: "不再依赖第三方高昂按月订阅服务，在本地局域网或 VPS 搭建自己专属的生产力数字城堡。",
    author: "Awesome Self-Hosted Community",
    tags: ["自建服务", "私有云", "开源替代", "极客首选"],
    actionType: "github",
    repository: "https://github.com/awesome-selfhosted/awesome-selfhosted",
    homepage: "https://awesome-selfhosted.net",
    stars: "220k+",
    license: "CC-BY-SA-3.0",
    featured: true,
  },
  {
    id: "res:awesome-rust",
    name: "Awesome Rust",
    category: "collections",
    description: "由 Rust 官方社区精挑细选的生产级 Rust 代码库、网络框架、图形库与命令行工具目录。",
    recommendedReason: "选型 Rust 依赖库时的必备索引，避免使用年久失修或处于实验性阶段的代码包。",
    author: "Rust Community",
    tags: ["Rust生态", "依赖选型", "高质量包", "社区权威"],
    actionType: "github",
    repository: "https://github.com/rust-unofficial/awesome-rust",
    stars: "45k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:awesome-tailwind",
    name: "Awesome Tailwind CSS",
    category: "collections",
    description: "Tailwind CSS 生态插件、工具、扩展、组件库与学习资源的终极聚合目录。",
    recommendedReason: "发现优秀 Tailwind Typography 排版插件、Forms 表单重置库与主题配色生成器。",
    author: "Anindya Dey",
    tags: ["Tailwind", "生态聚合", "常用插件", "主题工具"],
    actionType: "github",
    repository: "https://github.com/aniftyco/awesome-tailwindcss",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:awesome-python",
    name: "Awesome Python",
    category: "collections",
    description: "包含 80+ 个分类的精选 Python 卓越框架、自动化利器、数据工程与科学计算工具索引。",
    recommendedReason: "从 FastAPI、Pydantic 到 PyTorch、uv，全面掌控 Python 最新现代工程生态全貌。",
    author: "Vinta Software",
    tags: ["Python生态", "卓越框架", "自动化", "数据分析"],
    actionType: "github",
    repository: "https://github.com/vinta/awesome-python",
    stars: "230k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-mac",
    name: "Awesome Mac",
    category: "collections",
    description: "专为程序员与创作者准备的 macOS 优质开源软件、工具箱与高级效率应用精选清单。",
    recommendedReason: "Window 管理器、截图标记工具、剪贴板增强器与终端利器一网打尽。",
    author: "Jaywcjlove & Contributors",
    tags: ["macOS工具", "开源软件", "开发者生产力", "效率神器"],
    actionType: "github",
    repository: "https://github.com/jaywcjlove/awesome-mac",
    stars: "76k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-creative-coding",
    name: "Awesome Creative Coding",
    category: "collections",
    description: "为视觉艺术家、创意程序员与生成艺术从业者精心整理的工具库与教学资源清单。",
    recommendedReason: "探索 Processing, Shaders, WebGL, TouchDesigner 与算法艺术的无限奇妙可能。",
    author: "Terkel Gjervig",
    tags: ["创意编程", "生成艺术", "Shader着色器", "视觉艺术"],
    actionType: "github",
    repository: "https://github.com/terkelg/awesome-creative-coding",
    stars: "13k+",
    license: "CC0-1.0",
  },
  {
    id: "res:awesome-ai-agents",
    name: "Awesome AI Agents",
    category: "collections",
    description: "聚焦前沿自主 AI Agent、多智能体协同框架、记忆机制与环境评估的最新开源项目全景图。",
    recommendedReason: "紧跟 2025-2026 年自主智能体（Autonomous Agents）架构演进，寻找灵感与实战脚手架。",
    author: "Wong2",
    tags: ["AI Agent", "多智能体", "自主规划", "前沿技术"],
    actionType: "github",
    repository: "https://github.com/Wong2/awesome-ai-agents",
    stars: "7k+",
    license: "CC0-1.0",
  },
];
