import type { ResourceItem } from "../types";

export const componentResources: ResourceItem[] = [
  {
    id: "res:shadcn-ui",
    name: "shadcn/ui",
    category: "components",
    description: "设计精巧、完全开源且可直接复制源码进项目的现代 React 组件代码库。",
    recommendedReason: "彻底改变了前端组件库分发方式，代码归属于你，随心所欲定制样式与逻辑。",
    author: "shadcn",
    tags: ["Radix UI", "Tailwind CSS", "复制源码", "全栈标准"],
    actionType: "github",
    repository: "https://github.com/shadcn-ui/ui",
    homepage: "https://ui.shadcn.com",
    stars: "80k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:radix-primitives",
    name: "Radix Primitives",
    category: "components",
    description: "经过无障碍标准 WAI-ARIA 深度验证的底层无样式（Unstyled）UI 组件集合。",
    recommendedReason: "打造自研 Design System 的坚固基石，无需费心处理键盘焦点与屏幕阅读器兼容。",
    author: "WorkOS",
    tags: ["无样式", "无障碍", "ARIA规范", "底层原语"],
    actionType: "github",
    repository: "https://github.com/radix-ui/primitives",
    homepage: "https://www.radix-ui.com",
    stars: "16k+",
    license: "MIT",
  },
  {
    id: "res:ark-ui",
    name: "Ark UI",
    category: "components",
    description: "由 Chakra 团队打造的跨 React/Vue/Solid 框架的高性能无头组件库。",
    recommendedReason: "基于有限状态机（Zag.js）驱动交互逻辑，无论切换什么前端框架契约完全一致。",
    author: "Chakra Systems",
    tags: ["跨框架", "状态机", "无头组件", "Zag.js"],
    actionType: "github",
    repository: "https://github.com/chakra-ui/ark",
    homepage: "https://ark-ui.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:daisyui",
    name: "daisyUI",
    category: "components",
    description: "最受欢迎的 Tailwind CSS 纯语义化类名组件扩展，零 JavaScript 依赖。",
    recommendedReason: "用 `btn`, `card`, `modal` 等纯语义化类快速写出高颜值页面，内置数十套主题切换。",
    author: "Pouya Saadeghi",
    tags: ["Tailwind扩展", "纯CSS组件", "主题引擎", "极速开发"],
    actionType: "github",
    repository: "https://github.com/saadeghi/daisyui",
    homepage: "https://daisyui.com",
    stars: "34k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:mantine",
    name: "Mantine",
    category: "components",
    description: "拥有 100+ 生产级核心控件、50+ 实战 Hooks 的一站式全功能 React 框架库。",
    recommendedReason: "企业后台与工具型桌面端首选，表单校验、通知系统、模态堆栈应有尽有。",
    author: "Vitaly Rtishchev",
    tags: ["全功能库", "实战Hooks", "企业级后台", "TypeScript"],
    actionType: "github",
    repository: "https://github.com/mantinedev/mantine",
    homepage: "https://mantine.dev",
    stars: "26k+",
    license: "MIT",
  },
  {
    id: "res:heroui",
    name: "HeroUI (NextUI)",
    category: "components",
    description: "极具现代动感美学、半透明渐变微光与流畅过渡动效的 React UI 库。",
    recommendedReason: "告别千篇一律的企业后台中规中矩风格，为现代年轻用户提供精致酷炫视觉体验。",
    author: "Junior García & Team",
    tags: ["现代视觉", "微光渐变", "Tailwind Variants", "酷炫设计"],
    actionType: "github",
    repository: "https://github.com/heroui-inc/heroui",
    homepage: "https://heroui.com",
    stars: "22k+",
    license: "MIT",
  },
  {
    id: "res:aceternity-ui",
    name: "Aceternity UI",
    category: "components",
    description: "采用 Framer Motion 与 Tailwind 打造的极具震撼视觉的落地页动效组件库。",
    recommendedReason: "灯光追踪卡片、3D 视差网格、极光背景，一键复制源码直接让产品出彩。",
    author: "Manu Arora",
    tags: ["动效组件", "3D视差", "发光追踪", "爆款落地页"],
    actionType: "external",
    homepage: "https://ui.aceternity.com",
    featured: true,
  },
  {
    id: "res:magic-ui",
    name: "Magic UI",
    category: "components",
    description: "超过 50+ 专为初创产品与独立开发者打磨的高质感交互与动画 UI 构件。",
    recommendedReason: "轻量干净，无缝融入 shadcn/ui 项目结构，包含大量精巧的微交互细节。",
    author: "Dillion Verma",
    tags: ["微交互", "Shadcn生态", "动效按钮", "独立开发"],
    actionType: "github",
    repository: "https://github.com/magicuidesign/magicui",
    homepage: "https://magicui.design",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:ant-design",
    name: "Ant Design",
    category: "components",
    description: "服务于企业级中后台产品的经典设计系统与业界最成熟 React 组件库。",
    recommendedReason: "超大规模数据表格、树形选择与复杂表单场景下的经年验证事实标准。",
    author: "Ant Group",
    tags: ["企业后台", "中台标准", "复杂表格", "工业级可靠"],
    actionType: "github",
    repository: "https://github.com/ant-design/ant-design",
    homepage: "https://ant.design",
    stars: "92k+",
    license: "MIT",
  },
  {
    id: "res:tremor",
    name: "Tremor",
    category: "components",
    description: "专为打造现代化仪表盘与数据可视化设计的 React + Tailwind 极速分析组件库。",
    recommendedReason: "开箱即用的 KPI 指标卡片、折线图、条形图与追踪面板，助你极速构建商业分析前台。",
    author: "Tremor Labs",
    tags: ["仪表盘", "数据图表", "KPI卡片", "Tailwind"],
    actionType: "github",
    repository: "https://github.com/tremorlabs/tremor",
    homepage: "https://www.tremor.so",
    stars: "16k+",
    license: "Apache-2.0",
    featured: true,
  },
  {
    id: "res:ariakit",
    name: "Ariakit",
    category: "components",
    description: "极致性能、100% 遵循 W3C 规范的无约束无头无障碍 UI 组件基石。",
    recommendedReason: "体积超轻、无过度工程包袱，是许多专业前端工程师替代繁重库的清爽选择。",
    author: "Diego Haz",
    tags: ["无样式", "极轻量", "无障碍", "底层原语"],
    actionType: "github",
    repository: "https://github.com/ariakit/ariakit",
    homepage: "https://ariakit.org",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:headless-ui",
    name: "Headless UI",
    category: "components",
    description: "由 Tailwind Labs 官方打造的完全无样式、无障碍访问优先的 React 原语组件集合。",
    recommendedReason: "官方出品，与 Tailwind CSS 语法天然契合，下拉菜单、模态框与过渡动效零缝隙集成。",
    author: "Tailwind Labs",
    tags: ["Tailwind官方", "无样式", "下拉菜单", "模态框"],
    actionType: "github",
    repository: "https://github.com/tailwindlabs/headlessui",
    homepage: "https://headlessui.com",
    stars: "25k+",
    license: "MIT",
  },
  {
    id: "res:base-ui",
    name: "Base UI",
    category: "components",
    description: "来自 MUI 团队的新一代无头设计系统基础构件，重新构思无障碍与状态流转。",
    recommendedReason: "集成了顶尖工程团队在生产环境中提炼的弹层定位、手势捕获与焦点管理实践。",
    author: "MUI Core Team",
    tags: ["MUI新一代", "无头基石", "定位引擎", "无障碍"],
    actionType: "github",
    repository: "https://github.com/mui/base-ui",
    homepage: "https://base-ui.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:park-ui",
    name: "Park UI",
    category: "components",
    description: "基于 Ark UI 无头原语构建、同时提供 Tailwind 与 Panda CSS 两套主题方案的组件库。",
    recommendedReason: "同一套无障碍行为可自由选择样式引擎，方便在既有设计体系里渐进接入而不必推倒重来。",
    author: "Chakra Systems",
    tags: ["Ark UI", "Panda CSS", "双样式引擎", "设计体系"],
    actionType: "github",
    repository: "https://github.com/cschroeter/park-ui",
    homepage: "https://park-ui.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:chakra-ui",
    name: "Chakra UI",
    category: "components",
    description: "以样式属性（Style Props）与主题令牌为核心的 React 组件库。",
    recommendedReason: "直接在 JSX 上传入样式属性即可完成响应式布局，是中型后台项目平衡开发速度与一致性的稳妥选择。",
    author: "Segun Adebayo",
    tags: ["React组件库", "样式属性", "主题令牌", "后台友好"],
    actionType: "github",
    repository: "https://github.com/chakra-ui/chakra-ui",
    homepage: "https://chakra-ui.com",
    stars: "38k+",
    license: "MIT",
  },
  {
    id: "res:ant-design-mobile",
    name: "Ant Design Mobile",
    category: "components",
    description: "蚂蚁集团为移动端 Web 场景打造的 React 组件库。",
    recommendedReason: "针对手指触控优化了点击热区与手势反馈，做 H5 业务页比通用桌面组件库省去大量适配工作。",
    author: "Ant Design Team",
    tags: ["移动端", "React组件", "触控优化", "蚂蚁开源"],
    actionType: "github",
    repository: "https://github.com/ant-design/ant-design-mobile",
    homepage: "https://mobile.ant.design",
    stars: "12k+",
    license: "MIT",
  },
  {
    id: "res:primereact",
    name: "PrimeReact",
    category: "components",
    description: "包含 90 余个企业级组件、覆盖复杂数据表格与图表场景的 React 组件套件。",
    recommendedReason: "高级表格的虚拟滚动、列冻结与分组能力开箱可用，适合数据密度极高的管理后台。",
    author: "PrimeTek",
    tags: ["企业级组件", "高级数据表格", "主题皮肤", "后台系统"],
    actionType: "github",
    repository: "https://github.com/primefaces/primereact",
    homepage: "https://primereact.org",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:flowbite-react",
    name: "Flowbite React",
    category: "components",
    description: "基于 Tailwind CSS 构建的开源 React 组件库，附带大量整页区块模板。",
    recommendedReason: "组件与营销区块共用同一套设计语言，搭建落地页时可直接拼装而无需自己对齐视觉。",
    author: "Flowbite",
    tags: ["Tailwind", "整页区块", "营销落地页", "React组件"],
    actionType: "github",
    repository: "https://github.com/themesberg/flowbite-react",
    homepage: "https://flowbite-react.com",
    stars: "2k+",
    license: "MIT",
  },
  {
    id: "res:origin-ui",
    name: "Origin UI",
    category: "components",
    description: "基于 shadcn/ui 与 Tailwind 扩展出的开源组件集合，含大量表单与交互变体。",
    recommendedReason: "同一组件提供多种视觉与交互版本，做横向对比与选型时可快速替换试错。",
    author: "Davide Pacilio & Pasquale Vitiello",
    tags: ["shadcn生态", "多视觉变体", "表单组件", "开源可复制"],
    actionType: "external",
    homepage: "https://originui.com",
  },
  {
    id: "res:floating-ui",
    name: "Floating UI",
    category: "components",
    description: "解决弹层、下拉与工具提示精准定位问题的无头定位引擎。",
    recommendedReason: "自动处理翻转、溢出裁剪、箭头对齐与虚拟元素锚点，是所有高质量弹出层组件的底层依赖。",
    author: "Floating UI Contributors",
    tags: ["弹层定位", "无头引擎", "翻转避让", "Popper继任者"],
    actionType: "github",
    repository: "https://github.com/floating-ui/floating-ui",
    homepage: "https://floating-ui.com",
    stars: "31k+",
    license: "MIT",
  },
  {
    id: "res:cmdk",
    name: "cmdk",
    category: "components",
    description: "为 React 设计的快速、可组合、带模糊搜索的命令面板（Command Menu）组件。",
    recommendedReason: "几十行代码即可复刻 Linear 与 Raycast 那种 ⌘K 全局命令面板，是提升应用专业感的高性价比细节。",
    author: "Paco Coursey",
    tags: ["命令面板", "快捷键搜索", "可组合", "键盘驱动"],
    actionType: "github",
    repository: "https://github.com/pacocoursey/cmdk",
    homepage: "https://cmdk.paco.me",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:vaul",
    name: "Vaul",
    category: "components",
    description: "为 React 打造的带拖拽手势与惯性吸附的抽屉（Drawer）组件。",
    recommendedReason: "手势跟随与回弹曲线还原了原生移动端底部面板的质感，是目前 Web 上最接近原生的 Drawer 实现。",
    author: "Emil Kowalski",
    tags: ["抽屉组件", "手势拖拽", "惯性吸附", "原生质感"],
    actionType: "github",
    repository: "https://github.com/emilkowalski/vaul",
    homepage: "https://vaul.emilkowal.ski",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:sonner",
    name: "Sonner",
    category: "components",
    description: "为 React 设计的带堆叠动画与无障碍支持的高质感 Toast 通知组件。",
    recommendedReason: "默认动画与视觉已足够精致，一行调用即可替换各组件库自带 Toast，显著提升细节完成度。",
    author: "Emil Kowalski",
    tags: ["Toast通知", "堆叠动画", "无障碍", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/emilkowalski/sonner",
    homepage: "https://sonner.emilkowal.ski",
    stars: "9k+",
    license: "MIT",
  },
  {
    id: "res:number-flow",
    name: "NumberFlow",
    category: "components",
    description: "为数字变化提供逐位滚动动画的 React 组件，支持本地化格式化。",
    recommendedReason: "让仪表盘与统计卡片的数字跳动变得平滑可读，比瞬间替换数字的反馈质感高一个层级。",
    author: "Maxwell Barvian",
    tags: ["数字动画", "逐位滚动", "本地化格式", "仪表盘"],
    actionType: "github",
    repository: "https://github.com/barvian/number-flow",
    homepage: "https://number-flow.barvian.me",
    stars: "3k+",
    license: "MIT",
  },
  {
    id: "res:assistant-ui",
    name: "assistant-ui",
    category: "components",
    description: "面向 React 的开源 AI 对话界面组件库，内置流式渲染与工具调用展示。",
    recommendedReason: "把流式文本、思考过程、代码块与工具调用结果的 UI 状态全部封装好，省去从零设计聊天体验的成本。",
    author: "Assistant UI",
    tags: ["AI对话界面", "流式渲染", "工具调用展示", "React组件"],
    actionType: "github",
    repository: "https://github.com/assistant-ui/assistant-ui",
    homepage: "https://www.assistant-ui.com",
    stars: "3k+",
    license: "MIT",
  },
];

