import type { ResourceItem } from "../types";

export const componentResources: ResourceItem[] = [
  {
    id: "res:shadcn-ui",
    name: "shadcn/ui",
    category: "components",
    description: "设计精巧、完全开源且可直接复制源码进项目的现代 React 组件代码库。",
    recommendedReason: "彻底改变了前端组件库分发方式，代码归属于你，随心所欲定制样式与逻辑。",
    author: "shadcn",
    tags: ["Radix UI", "Tailwind CSS", "复制源码", "全栈标准"],
    actionType: "github",
    repository: "https://github.com/shadcn-ui/ui",
    homepage: "https://ui.shadcn.com",
    stars: "80k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:radix-primitives",
    name: "Radix Primitives",
    category: "components",
    description: "经过无障碍标准 WAI-ARIA 深度验证的底层无样式（Unstyled）UI 组件集合。",
    recommendedReason: "打造自研 Design System 的坚固基石，无需费心处理键盘焦点与屏幕阅读器兼容。",
    author: "WorkOS",
    tags: ["无样式", "无障碍", "ARIA规范", "底层原语"],
    actionType: "github",
    repository: "https://github.com/radix-ui/primitives",
    homepage: "https://www.radix-ui.com",
    stars: "16k+",
    license: "MIT",
  },
  {
    id: "res:ark-ui",
    name: "Ark UI",
    category: "components",
    description: "由 Chakra 团队打造的跨 React/Vue/Solid 框架的高性能无头组件库。",
    recommendedReason: "基于有限状态机（Zag.js）驱动交互逻辑，无论切换什么前端框架契约完全一致。",
    author: "Chakra Systems",
    tags: ["跨框架", "状态机", "无头组件", "Zag.js"],
    actionType: "github",
    repository: "https://github.com/chakra-ui/ark",
    homepage: "https://ark-ui.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:daisyui",
    name: "daisyUI",
    category: "components",
    description: "最受欢迎的 Tailwind CSS 纯语义化类名组件扩展，零 JavaScript 依赖。",
    recommendedReason: "用 `btn`, `card`, `modal` 等纯语义化类快速写出高颜值页面，内置数十套主题切换。",
    author: "Pouya Saadeghi",
    tags: ["Tailwind扩展", "纯CSS组件", "主题引擎", "极速开发"],
    actionType: "github",
    repository: "https://github.com/saadeghi/daisyui",
    homepage: "https://daisyui.com",
    stars: "34k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:mantine",
    name: "Mantine",
    category: "components",
    description: "拥有 100+ 生产级核心控件、50+ 实战 Hooks 的一站式全功能 React 框架库。",
    recommendedReason: "企业后台与工具型桌面端首选，表单校验、通知系统、模态堆栈应有尽有。",
    author: "Vitaly Rtishchev",
    tags: ["全功能库", "实战Hooks", "企业级后台", "TypeScript"],
    actionType: "github",
    repository: "https://github.com/mantinedev/mantine",
    homepage: "https://mantine.dev",
    stars: "26k+",
    license: "MIT",
  },
  {
    id: "res:heroui",
    name: "HeroUI (NextUI)",
    category: "components",
    description: "极具现代动感美学、半透明渐变微光与流畅过渡动效的 React UI 库。",
    recommendedReason: "告别千篇一律的企业后台中规中矩风格，为现代年轻用户提供精致酷炫视觉体验。",
    author: "Junior García & Team",
    tags: ["现代视觉", "微光渐变", "Tailwind Variants", "酷炫设计"],
    actionType: "github",
    repository: "https://github.com/heroui-inc/heroui",
    homepage: "https://heroui.com",
    stars: "22k+",
    license: "MIT",
  },
  {
    id: "res:aceternity-ui",
    name: "Aceternity UI",
    category: "components",
    description: "采用 Framer Motion 与 Tailwind 打造的极具震撼视觉的落地页动效组件库。",
    recommendedReason: "灯光追踪卡片、3D 视差网格、极光背景，一键复制源码直接让产品出彩。",
    author: "Manu Arora",
    tags: ["动效组件", "3D视差", "发光追踪", "爆款落地页"],
    actionType: "external",
    homepage: "https://ui.aceternity.com",
    featured: true,
  },
  {
    id: "res:magic-ui",
    name: "Magic UI",
    category: "components",
    description: "超过 50+ 专为初创产品与独立开发者打磨的高质感交互与动画 UI 构件。",
    recommendedReason: "轻量干净，无缝融入 shadcn/ui 项目结构，包含大量精巧的微交互细节。",
    author: "Dillion Verma",
    tags: ["微交互", "Shadcn生态", "动效按钮", "独立开发"],
    actionType: "github",
    repository: "https://github.com/magicuidesign/magicui",
    homepage: "https://magicui.design",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:ant-design",
    name: "Ant Design",
    category: "components",
    description: "服务于企业级中后台产品的经典设计系统与业界最成熟 React 组件库。",
    recommendedReason: "超大规模数据表格、树形选择与复杂表单场景下的经年验证事实标准。",
    author: "Ant Group",
    tags: ["企业后台", "中台标准", "复杂表格", "工业级可靠"],
    actionType: "github",
    repository: "https://github.com/ant-design/ant-design",
    homepage: "https://ant.design",
    stars: "92k+",
    license: "MIT",
  },
];
