import type { ResourceItem } from "../types";

export const fontResources: ResourceItem[] = [
  {
    id: "res:jetbrains-mono",
    name: "JetBrains Mono",
    category: "fonts",
    description: "JetBrains 专为开发者日常舒适编码量身设计的免费开源等宽代码字体。",
    recommendedReason: "加大字怀高度、清晰区分 1/l/I/0/O/Q 等易混淆字符，程序连字（Ligatures）极为克制得体。",
    author: "JetBrains",
    tags: ["代码字体", "程序连字", "等宽排版", "顶级舒适度"],
    actionType: "github",
    repository: "https://github.com/JetBrains/JetBrainsMono",
    homepage: "https://www.jetbrains.com/lp/mono",
    stars: "14k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:cascadia-code",
    name: "Cascadia Code",
    category: "fonts",
    description: "微软专为 Windows Terminal 与 Visual Studio 打造的全新开源等宽字体。",
    recommendedReason: "支持完整连字、Curvy 草书变体与 Powerline 符号，在 Windows 渲染清晰锐利。",
    author: "Microsoft",
    tags: ["微软开源", "终端字体", "ClearType优化", "Powerline支持"],
    actionType: "github",
    repository: "https://github.com/microsoft/cascadia-code",
    stars: "26k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:fira-code",
    name: "Fira Code",
    category: "fonts",
    description: "开创现代编程连字潮流的经典开源等宽字体，支持 ->, =>, !=, === 等上百种优雅连字。",
    recommendedReason: "阅读代码如同阅读数学公式，大幅降低眼睛扫读符号时的解析认知负担。",
    author: "Nikita Prokopov (tonsky)",
    tags: ["编程连字", "经典之作", "符号清晰", "广泛兼容"],
    actionType: "github",
    repository: "https://github.com/tonsky/FiraCode",
    stars: "76k+",
    license: "OFL-1.1",
  },
  {
    id: "res:inter-font",
    name: "Inter Font Family",
    category: "fonts",
    description: "专为计算机显示屏阅读打造的世界级几何无衬线可变字体（Variable Font）。",
    recommendedReason: "GitHub、Linear、Figma 等几乎所有顶级科技产品的默认排印字体，高 PPI 下可读性无可挑剔。",
    author: "Rasmus Andersson",
    tags: ["可变字体", "屏幕排印", "科技感无衬线", "现代标准"],
    actionType: "github",
    repository: "https://github.com/rsms/inter",
    homepage: "https://rsms.me/inter",
    stars: "18k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:geist-font",
    name: "Geist & Geist Mono",
    category: "fonts",
    description: "Vercel 与 Basement 联合打造的专属于现代开发者与设计工匠的极致排印字体。",
    recommendedReason: "将瑞士国际主义的严谨无衬线几何与开发者工坊的沉静微光完美融合。",
    author: "Vercel",
    tags: ["Vercel字体", "瑞士现代主义", "工匠排版", "极简美学"],
    actionType: "github",
    repository: "https://github.com/vercel/geist-font",
    homepage: "https://vercel.com/font",
    stars: "7k+",
    license: "OFL-1.1",
  },
  {
    id: "res:nerd-fonts",
    name: "Nerd Fonts",
    category: "fonts",
    description: "为各大流行开发者字体注入海量 Glyph 图标（Font Awesome、Octicons 等）的终极补丁库。",
    recommendedReason: "Starship、Lazygit、Neovim 等终端 TUI 工具显示文件图标与 Git 分支符号必备字体基石。",
    author: "Ryan L McIntyre",
    tags: ["终端图标", "字体补丁", "Powerline", "Devicons"],
    actionType: "github",
    repository: "https://github.com/ryanoasis/nerd-fonts",
    homepage: "https://www.nerdfonts.com",
    stars: "57k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:fontsource",
    name: "Fontsource",
    category: "fonts",
    description: "将 Google Fonts 与开源字体一键打包为自托管 npm 包的极速工具链。",
    recommendedReason: "完全告别外部 Google CDN 阻断与网络延迟，直接 `import '@fontsource/inter'` 纯本地离线分发。",
    author: "Ayuhito",
    tags: ["自托管字体", "离线部署", "零外部依赖", "npm包"],
    actionType: "github",
    repository: "https://github.com/fontsource/fontsource",
    homepage: "https://fontsource.org",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:source-han-sans",
    name: "思源黑体 (Source Han Sans)",
    category: "fonts",
    description: "Adobe 与 Google 联合开发的跨中日韩统一表意文字开源无衬线超级字体家族。",
    recommendedReason: "7 个字重覆盖极全，中文屏显规范、排版平稳，全平台免版权商业使用的中文字体标杆。",
    author: "Adobe & Google",
    tags: ["中文字体", "思源黑体", "7种字重", "免版权商用"],
    actionType: "github",
    repository: "https://github.com/adobe-fonts/source-han-sans",
    homepage: "https://source.typekit.com/source-han-serif",
    stars: "11k+",
    license: "OFL-1.1",
  },
  {
    id: "res:monaspace",
    name: "Monaspace",
    category: "fonts",
    description: "GitHub 历时数年倾力打造的下一代革命性代码字体超家族，包含五大风格变体。",
    recommendedReason: "首创「Texture Healing」字距纹理微愈技术，解决传统等宽字体字空过大或过挤的弊端。",
    author: "GitHub Next",
    tags: ["GitHub官方", "次时代代码字体", "TextureHealing", "五大变体"],
    actionType: "github",
    repository: "https://github.com/githubnext/monaspace",
    homepage: "https://monaspace.githubnext.com",
    stars: "34k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:ibm-plex",
    name: "IBM Plex",
    category: "fonts",
    description: "IBM 官方开源企业品牌超字体族，包含 Mono、Sans、Serif 与跨语种完整覆盖。",
    recommendedReason: "纯正人机工程学结合国际企业工业风范，特别适合技术控制台、数据密集界面与专业文档。",
    author: "IBM Design",
    tags: ["IBM官方", "企业级字体族", "工业风范", "PlexMono"],
    actionType: "github",
    repository: "https://github.com/IBM/plex",
    homepage: "https://www.ibm.com/plex",
    stars: "20k+",
    license: "OFL-1.1",
  },
  {
    id: "res:space-grotesk",
    name: "Space Grotesk",
    category: "fonts",
    description: "基于 Space Mono 比例改良的富有技术未来主义韵味的比例无衬线展示字体。",
    recommendedReason: "科技初创、Web3 与未来主义设计界最受追捧的大标题与关键视觉排印字体之一。",
    author: "Florian Karsten",
    tags: ["未来主义", "技术美学", "大标题字体", "Web3必备"],
    actionType: "github",
    repository: "https://github.com/floriankarsten/space-grotesk",
    homepage: "https://floriankarsten.github.io/space-grotesk",
    stars: "2k+",
    license: "OFL-1.1",
  },
  {
    id: "res:recursive-font",
    name: "Recursive Sans & Mono",
    category: "fonts",
    description: "单文件可变字体，可在无衬线、休闲手写与等宽三轴之间连续变化。",
    recommendedReason: "一枚字体覆盖代码与界面两套语气，用可变轴表达品牌性格的同时大幅减少字体文件体积。",
    author: "Arrow Type",
    tags: ["可变字体", "三轴切换", "等宽衬线一体", "单文件"],
    actionType: "github",
    repository: "https://github.com/arrowtype/recursive",
    homepage: "https://www.recursive.design",
    stars: "1k+",
    license: "OFL-1.1",
  },
  {
    id: "res:figtree-font",
    name: "Figtree",
    category: "fonts",
    description: "几何风格、中性友好的开源无衬线字体，覆盖完整字重与斜体。",
    recommendedReason: "在几何感与可读性之间平衡得极好，适合做既想有设计感又不能牺牲正文易读性的产品界面。",
    author: "Erik Kennedy",
    tags: ["几何无衬线", "完整字重", "高可读性", "界面正文"],
    actionType: "github",
    repository: "https://github.com/erikdkennedy/figtree",
    homepage: "https://www.figtreefont.com",
    license: "OFL-1.1",
  },
  {
    id: "res:atkinson-hyperlegible",
    name: "Atkinson Hyperlegible",
    category: "fonts",
    description: "Braille Institute 为低视力读者设计、刻意强化字形差异度的无衬线字体。",
    recommendedReason: "在易混字符（I l 1、O 0）上做了明确区分，是无障碍与长文本阅读场景的可靠默认选项。",
    author: "Braille Institute",
    tags: ["无障碍设计", "低视力友好", "字形易辨识", "长文本"],
    actionType: "github",
    repository: "https://github.com/brailleinstitute/atkinson-hyperlegible",
    homepage: "https://www.brailleinstitute.org/freefont",
    license: "OFL-1.1",
  },
  {
    id: "res:manrope-font",
    name: "Manrope",
    category: "fonts",
    description: "现代几何无衬线字体，拥有从 ExtraLight 到 ExtraBold 的完整字重谱系。",
    recommendedReason: "字腔开放且大字号下极具秩序感，做数据看板与科技产品标题的性价比极高。",
    author: "Mikhail Sharanda",
    tags: ["几何无衬线", "完整字重", "数据看板", "科技感"],
    actionType: "github",
    repository: "https://github.com/sharanda/manrope",
    homepage: "https://manropefont.com",
    stars: "1k+",
    license: "OFL-1.1",
  },
  {
    id: "res:public-sans",
    name: "Public Sans",
    category: "fonts",
    description: "美国政府 USWDS 设计系统推出的开源中立无衬线字体。",
    recommendedReason: "为政府级公共信息发布而设计，字形克制、中性且已通过大规模真实场景检验。",
    author: "USWDS (GSA)",
    tags: ["政府设计系统", "中性字形", "公共信息", "开源"],
    actionType: "github",
    repository: "https://github.com/uswds/public-sans",
    homepage: "https://public-sans.digital.gov",
    stars: "1k+",
    license: "OFL-1.1",
  },
  {
    id: "res:lexend-font",
    name: "Lexend",
    category: "fonts",
    description: "基于阅读流畅度研究、以提升阅读速度为目标的七级可变字体家族。",
    recommendedReason: "被大量教育类与阅读类产品验证能减少视觉拥挤感，适合长文阅读型应用。",
    author: "Bonnie Shaver-Troup & Thomas Jockin",
    tags: ["阅读流畅度", "可变字体", "教育场景", "长文优化"],
    actionType: "github",
    repository: "https://github.com/googlefonts/lexend",
    homepage: "https://www.lexend.com",
    license: "OFL-1.1",
  },
  {
    id: "res:noto-fonts",
    name: "Noto Fonts",
    category: "fonts",
    description: "Google 主导、覆盖全球所有书写系统且保证字形无缺字（No Tofu）的超大字体家族。",
    recommendedReason: "多语言与多语种混排项目的最终兜底方案，可彻底消灭界面上的豆腐块方框。",
    author: "Google",
    tags: ["全语种覆盖", "无缺字", "多语言排版", "兜底字体"],
    actionType: "github",
    repository: "https://github.com/notofonts/noto-fonts",
    homepage: "https://fonts.google.com/noto",
    stars: "5k+",
    license: "OFL-1.1",
  },
  {
    id: "res:bricolage-grotesque",
    name: "Bricolage Grotesque",
    category: "fonts",
    description: "带有手工拼贴气质的可变展示字体，宽高轴与光学尺寸轴均可自由调节。",
    recommendedReason: "同一字体可通过可变轴做出从克制正文到夸张海报的跨度，做有个性的品牌标题极省事。",
    author: "Mathieu Triay",
    tags: ["可变展示字体", "个性强烈", "品牌标题", "多轴调节"],
    actionType: "github",
    repository: "https://github.com/ateliertriay/bricolage",
    homepage: "https://ateliertriay.github.io/bricolage",
    license: "OFL-1.1",
  },
  {
    id: "res:instrument-serif",
    name: "Instrument Serif",
    category: "fonts",
    description: "高对比度、带有古典杂志气质的现代衬线展示字体。",
    recommendedReason: "大标题下极具编辑感与高级感，是给技术产品注入杂志式审美的低成本手段。",
    author: "Instrument",
    tags: ["高对比衬线", "杂志气质", "编辑感", "大标题"],
    actionType: "github",
    repository: "https://github.com/Instrument/instrument-serif",
    homepage: "https://instrument.com",
    license: "OFL-1.1",
  },
  {
    id: "res:cal-sans",
    name: "Cal Sans",
    category: "fonts",
    description: "Cal.com 开源的几何风格无衬线展示字体。",
    recommendedReason: "字重厚实、字形圆润，做 SaaS 首屏大标题能立刻拉开与系统字体的视觉差距。",
    author: "Cal.com",
    tags: ["SaaS首屏", "几何展示字体", "字形圆润", "开源"],
    actionType: "github",
    repository: "https://github.com/calcom/font",
    stars: "2k+",
    license: "OFL-1.1",
  },
  {
    id: "res:opendyslexic",
    name: "OpenDyslexic",
    category: "fonts",
    description: "专为阅读障碍人群设计、加重字底以增强方向感的开源字体。",
    recommendedReason: "在可访问性选项中提供它，能让阅读障碍用户显著降低阅读疲劳与串行错误。",
    author: "Abbie Gonzalez",
    tags: ["阅读障碍友好", "无障碍", "加重字底", "可访问性选项"],
    actionType: "github",
    repository: "https://github.com/antijingoist/opendyslexic",
    homepage: "https://opendyslexic.org",
    license: "OFL-1.1",
  },
  {
    id: "res:source-han-serif",
    name: "思源宋体 (Source Han Serif)",
    category: "fonts",
    description: "Adobe 与 Google 联合发布的泛 CJK 开源宋体，覆盖简繁日韩全套字形。",
    recommendedReason: "中文长文阅读体验远超黑体，做出版物、文档与高端资讯页面时的标准正文选择。",
    author: "Adobe & Google",
    tags: ["中文宋体", "泛CJK", "出版物排版", "正文首选"],
    actionType: "github",
    repository: "https://github.com/adobe-fonts/source-han-serif",
    homepage: "https://source.typekit.com/source-han-serif/",
    stars: "5k+",
    license: "OFL-1.1",
  },
  {
    id: "res:lxgw-wenkai",
    name: "霞鹜文楷 (LXGW WenKai)",
    category: "fonts",
    description: "基于 Klee One 改造、兼具楷体韵味与现代屏幕可读性的中文开源字体。",
    recommendedReason: "在代码编辑器与笔记软件中做中文等宽显示格外温润，是中文开发者最爱的阅读型字体之一。",
    author: "LXGW (落霞孤鹜)",
    tags: ["中文楷体", "屏幕可读", "编辑器适用", "开源"],
    actionType: "github",
    repository: "https://github.com/lxgw/LxgwWenKai",
    stars: "19k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:maple-mono",
    name: "Maple Mono",
    category: "fonts",
    description: "带圆角设计、支持连字与中英文等宽对齐的开源编程字体。",
    recommendedReason: "中文注释与英文代码宽度对齐良好，是国内开发者终端与编辑器场景少见的原生适配字体。",
    author: "subframe7536",
    tags: ["编程字体", "中文对齐", "圆角设计", "连字支持"],
    actionType: "github",
    repository: "https://github.com/subframe7536/maple-font",
    homepage: "https://font.subf.dev",
    stars: "10k+",
    license: "OFL-1.1",
  },
  {
    id: "res:fontshare",
    name: "Fontshare",
    category: "fonts",
    description: "印度字体设计工作室 Indian Type Foundry 提供的免费商用字体发布平台。",
    recommendedReason: "数十套质量接近商业授权的免费字体可直接用于产品，弥补开源字体在展示风格上的缺口。",
    author: "Indian Type Foundry",
    tags: ["免费商用", "展示字体", "高质量字库", "设计机构出品"],
    actionType: "external",
    homepage: "https://www.fontshare.com",
  },
  {
    id: "res:fontpair",
    name: "Fontpair",
    category: "fonts",
    description: "按风格与场景整理的字体搭配灵感库，直接给出可用的字体组合方案。",
    recommendedReason: "跳过反复试错，用现成的高质量搭配方案直接确定标题与正文的字体对。",
    author: "Fontpair",
    tags: ["字体搭配", "方案库", "灵感参考", "快速决策"],
    actionType: "external",
    homepage: "https://fontpair.co",
  },
  {
    id: "res:typescale",
    name: "Typescale",
    category: "fonts",
    description: "可视化调节模块化比例并即时输出 CSS 字号与行高变量的排版标尺工具。",
    recommendedReason: "几十秒即可从零推导出一套数学自洽的排印层级，并直接拿到可粘贴进项目的 CSS 变量。",
    author: "Typescale",
    tags: ["排版标尺", "模块化比例", "CSS变量", "排印层级"],
    actionType: "external",
    homepage: "https://typescale.com",
  },
  {
    id: "res:modern-font-stacks",
    name: "Modern Font Stacks",
    category: "fonts",
    description: "按视觉风格分类、全部使用系统内置字体且零网络请求的现代 font-family 方案集合。",
    recommendedReason: "不加载任何字体文件即可获得经过设计的排版观感，首屏性能与视觉质感两不误。",
    author: "Dan Klammer",
    tags: ["系统字体栈", "零网络请求", "首屏性能", "风格分类"],
    actionType: "github",
    repository: "https://github.com/system-fonts/modern-font-stacks",
    homepage: "https://modernfontstacks.com",
    stars: "3k+",
    license: "MIT",
  },
  {
    id: "res:fonttools",
    name: "fontTools",
    category: "fonts",
    description: "Python 编写的字体处理库，可解析、子集化、转换与检查 OpenType 字体文件。",
    recommendedReason: "做中文字体子集化与格式转换的唯一成熟方案，能把几十兆字体压到几百 KB。",
    author: "Just van Rossum & fontTools Contributors",
    tags: ["字体子集化", "Python库", "OpenType处理", "体积优化"],
    actionType: "github",
    repository: "https://github.com/fonttools/fonttools",
    homepage: "https://fonttools.readthedocs.io",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:opentype-js",
    name: "opentype.js",
    category: "fonts",
    description: "在浏览器与 Node 中解析并生成 OpenType/TrueType 字体的 JavaScript 库。",
    recommendedReason: "可在前端动态读取字形轮廓与度量数据，做字体预览、路径导出与自动排版校验。",
    author: "Frederik De Bleser",
    tags: ["字体解析", "JS字体库", "字形轮廓", "前端字体工具"],
    actionType: "github",
    repository: "https://github.com/opentypejs/opentype.js",
    homepage: "https://opentype.js.org",
    stars: "5k+",
    license: "MIT",
  },
];

