import type { ResourceItem } from "../types";

export const fontResources: ResourceItem[] = [
  {
    id: "res:jetbrains-mono",
    name: "JetBrains Mono",
    category: "fonts",
    description: "JetBrains 专为开发者日常舒适编码量身设计的免费开源等宽代码字体。",
    recommendedReason: "加大字怀高度、清晰区分 1/l/I/0/O/Q 等易混淆字符，程序连字（Ligatures）极为克制得体。",
    author: "JetBrains",
    tags: ["代码字体", "程序连字", "等宽排版", "顶级舒适度"],
    actionType: "github",
    repository: "https://github.com/JetBrains/JetBrainsMono",
    homepage: "https://www.jetbrains.com/lp/mono",
    stars: "14k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:cascadia-code",
    name: "Cascadia Code",
    category: "fonts",
    description: "微软专为 Windows Terminal 与 Visual Studio 打造的全新开源等宽字体。",
    recommendedReason: "支持完整连字、Curvy 草书变体与 Powerline 符号，在 Windows 渲染清晰锐利。",
    author: "Microsoft",
    tags: ["微软开源", "终端字体", "ClearType优化", "Powerline支持"],
    actionType: "github",
    repository: "https://github.com/microsoft/cascadia-code",
    stars: "26k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:fira-code",
    name: "Fira Code",
    category: "fonts",
    description: "开创现代编程连字潮流的经典开源等宽字体，支持 ->, =>, !=, === 等上百种优雅连字。",
    recommendedReason: "阅读代码如同阅读数学公式，大幅降低眼睛扫读符号时的解析认知负担。",
    author: "Nikita Prokopov (tonsky)",
    tags: ["编程连字", "经典之作", "符号清晰", "广泛兼容"],
    actionType: "github",
    repository: "https://github.com/tonsky/FiraCode",
    stars: "76k+",
    license: "OFL-1.1",
  },
  {
    id: "res:inter-font",
    name: "Inter Font Family",
    category: "fonts",
    description: "专为计算机显示屏阅读打造的世界级几何无衬线可变字体（Variable Font）。",
    recommendedReason: "GitHub、Linear、Figma 等几乎所有顶级科技产品的默认排印字体，高 PPI 下可读性无可挑剔。",
    author: "Rasmus Andersson",
    tags: ["可变字体", "屏幕排印", "科技感无衬线", "现代标准"],
    actionType: "github",
    repository: "https://github.com/rsms/inter",
    homepage: "https://rsms.me/inter",
    stars: "18k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:geist-font",
    name: "Geist & Geist Mono",
    category: "fonts",
    description: "Vercel 与 Basement 联合打造的专属于现代开发者与设计工匠的极致排印字体。",
    recommendedReason: "将瑞士国际主义的严谨无衬线几何与开发者工坊的沉静微光完美融合。",
    author: "Vercel",
    tags: ["Vercel字体", "瑞士现代主义", "工匠排版", "极简美学"],
    actionType: "github",
    repository: "https://github.com/vercel/geist-font",
    homepage: "https://vercel.com/font",
    stars: "7k+",
    license: "OFL-1.1",
  },
  {
    id: "res:nerd-fonts",
    name: "Nerd Fonts",
    category: "fonts",
    description: "为各大流行开发者字体注入海量 Glyph 图标（Font Awesome、Octicons 等）的终极补丁库。",
    recommendedReason: "Starship、Lazygit、Neovim 等终端 TUI 工具显示文件图标与 Git 分支符号必备字体基石。",
    author: "Ryan L McIntyre",
    tags: ["终端图标", "字体补丁", "Powerline", "Devicons"],
    actionType: "github",
    repository: "https://github.com/ryanoasis/nerd-fonts",
    homepage: "https://www.nerdfonts.com",
    stars: "57k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:fontsource",
    name: "Fontsource",
    category: "fonts",
    description: "将 Google Fonts 与开源字体一键打包为自托管 npm 包的极速工具链。",
    recommendedReason: "完全告别外部 Google CDN 阻断与网络延迟，直接 `import '@fontsource/inter'` 纯本地离线分发。",
    author: "Ayuhito",
    tags: ["自托管字体", "离线部署", "零外部依赖", "npm包"],
    actionType: "github",
    repository: "https://github.com/fontsource/fontsource",
    homepage: "https://fontsource.org",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:source-han-sans",
    name: "思源黑体 (Source Han Sans)",
    category: "fonts",
    description: "Adobe 与 Google 联合开发的跨中日韩统一表意文字开源无衬线超级字体家族。",
    recommendedReason: "7 个字重覆盖极全，中文屏显规范、排版平稳，全平台免版权商业使用的中文字体标杆。",
    author: "Adobe & Google",
    tags: ["中文字体", "思源黑体", "7种字重", "免版权商用"],
    actionType: "github",
    repository: "https://github.com/adobe-fonts/source-han-sans",
    homepage: "https://source.typekit.com/source-han-serif",
    stars: "11k+",
    license: "OFL-1.1",
  },
  {
    id: "res:monaspace",
    name: "Monaspace",
    category: "fonts",
    description: "GitHub 历时数年倾力打造的下一代革命性代码字体超家族，包含五大风格变体。",
    recommendedReason: "首创「Texture Healing」字距纹理微愈技术，解决传统等宽字体字空过大或过挤的弊端。",
    author: "GitHub Next",
    tags: ["GitHub官方", "次时代代码字体", "TextureHealing", "五大变体"],
    actionType: "github",
    repository: "https://github.com/githubnext/monaspace",
    homepage: "https://monaspace.githubnext.com",
    stars: "34k+",
    license: "OFL-1.1",
    featured: true,
  },
  {
    id: "res:ibm-plex",
    name: "IBM Plex",
    category: "fonts",
    description: "IBM 官方开源企业品牌超字体族，包含 Mono、Sans、Serif 与跨语种完整覆盖。",
    recommendedReason: "纯正人机工程学结合国际企业工业风范，特别适合技术控制台、数据密集界面与专业文档。",
    author: "IBM Design",
    tags: ["IBM官方", "企业级字体族", "工业风范", "PlexMono"],
    actionType: "github",
    repository: "https://github.com/IBM/plex",
    homepage: "https://www.ibm.com/plex",
    stars: "20k+",
    license: "OFL-1.1",
  },
  {
    id: "res:space-grotesk",
    name: "Space Grotesk",
    category: "fonts",
    description: "基于 Space Mono 比例改良的富有技术未来主义韵味的比例无衬线展示字体。",
    recommendedReason: "科技初创、Web3 与未来主义设计界最受追捧的大标题与关键视觉排印字体之一。",
    author: "Florian Karsten",
    tags: ["未来主义", "技术美学", "大标题字体", "Web3必备"],
    actionType: "github",
    repository: "https://github.com/floriankarsten/space-grotesk",
    homepage: "https://floriankarsten.github.io/space-grotesk",
    stars: "2k+",
    license: "OFL-1.1",
  },
];

