import type { ResourceItem } from "../types";

export const frontendResources: ResourceItem[] = [
  {
    id: "res:godly-website",
    name: "Godly Website",
    category: "frontend",
    description: "每日更新的世界顶级现代 Web 设计、排版与微交互精选画廊。",
    recommendedReason: "寻找现代产品主页、暗黑界面与极致版面留白灵感的第一去处。",
    author: "Godly Team",
    tags: ["设计灵感", "落地页", "版式排版", "微交互"],
    actionType: "external",
    homepage: "https://godly.website",
    featured: true,
  },
  {
    id: "res:awwwards",
    name: "Awwwards",
    category: "frontend",
    description: "全球顶尖数字设计师与开发者的年度/每日获奖作品评选平台。",
    recommendedReason: "了解当下世界最高技术力 3D WebGL、复杂动效与突破性网页叙事。",
    author: "Awwwards Jury",
    tags: ["行业大奖", "前沿交互", "3D Web", "创新排版"],
    actionType: "external",
    homepage: "https://www.awwwards.com",
    featured: true,
  },
  {
    id: "res:component-gallery",
    name: "The Component Gallery",
    category: "frontend",
    description: "收录全球一线真实设计系统（Design System）中的真实组件模式库。",
    recommendedReason: "设计具体控件（如 DatePicker、Combobox）时参考数十家顶级公司的真实方案。",
    author: "Iain Bean",
    tags: ["设计系统", "组件模式", "UI规范", "无障碍"],
    actionType: "external",
    homepage: "https://component.gallery",
  },
  {
    id: "res:checklist-design",
    name: "Checklist Design",
    category: "frontend",
    description: "为 UI/UX 设计师与全栈开发者准备的最佳实践检查清单集合。",
    recommendedReason: "构建表单、登录流、弹窗和空状态时避免遗漏关键体验与极端情况边界。",
    author: "George Hatzis",
    tags: ["设计清单", "体验规范", "表单设计", "空状态"],
    actionType: "external",
    homepage: "https://www.checklist.design",
  },
  {
    id: "res:shadcn-ui-inspiration",
    name: "Shadcn UI Showcase",
    category: "frontend",
    description: "基于 shadcn/ui 生态构建的优质开源 Web 应用、控制台与仪表盘展示。",
    recommendedReason: "观察现代深色工作台产品如何克制优雅地运用无头组件打造高级感。",
    author: "Shadcn Community",
    tags: ["Shadcn", "Dashboard", "极简控制台", "实战样板"],
    actionType: "external",
    homepage: "https://ui.shadcn.com/examples",
    featured: true,
  },
  {
    id: "res:mobbin",
    name: "Mobbin",
    category: "frontend",
    description: "全球最大规模的移动端与 Web 端真实商业产品界面截图与用户旅程库。",
    recommendedReason: "逆向分析 Linear、Raycast、Spotify 等顶级产品的完整操作流程与微细节。",
    author: "Mobbin Design",
    tags: ["真实流程", "用户旅程", "交互细节", "界面参考"],
    actionType: "external",
    homepage: "https://mobbin.com",
  },
  {
    id: "res:land-book",
    name: "Land-book",
    category: "frontend",
    description: "精心挑选的开发者工具、SaaS 产品与设计机构官方 Landing Page 画廊。",
    recommendedReason: "学习如何写出抓人的 Hero 文案与清晰的技术产品功能对比网格。",
    author: "Land-book Curators",
    tags: ["Landing Page", "SaaS设计", "文案排版", "视觉层次"],
    actionType: "external",
    homepage: "https://land-book.com",
  },
  {
    id: "res:darkmode-design",
    name: "Dark Mode Design",
    category: "frontend",
    description: "专注收集真正具有设计感的全暗黑（Pure Dark）产品与网站范本。",
    recommendedReason: "学习如何不用纯黑死黑，而是通过多阶低明度冷暖灰度打造深邃立体层次。",
    author: "Alexis Collado",
    tags: ["暗黑模式", "灰度阶梯", "护眼层次", "夜间视觉"],
    actionType: "external",
    homepage: "https://www.darkmodedesign.com",
  },
];
