import type { ResourceItem } from "../types";

export const frontendResources: ResourceItem[] = [
  {
    id: "res:godly-website",
    name: "Godly Website",
    category: "frontend",
    description: "每日更新的世界顶级现代 Web 设计、排版与微交互精选画廊。",
    recommendedReason: "寻找现代产品主页、暗黑界面与极致版面留白灵感的第一去处。",
    author: "Godly Team",
    tags: ["设计灵感", "落地页", "版式排版", "微交互"],
    actionType: "external",
    homepage: "https://godly.website",
    featured: true,
  },
  {
    id: "res:awwwards",
    name: "Awwwards",
    category: "frontend",
    description: "全球顶尖数字设计师与开发者的年度/每日获奖作品评选平台。",
    recommendedReason: "了解当下世界最高技术力 3D WebGL、复杂动效与突破性网页叙事。",
    author: "Awwwards Jury",
    tags: ["行业大奖", "前沿交互", "3D Web", "创新排版"],
    actionType: "external",
    homepage: "https://www.awwwards.com",
    featured: true,
  },
  {
    id: "res:webby-awards",
    name: "The Webby Awards",
    category: "frontend",
    description: "被《纽约时报》誉为「互联网最高荣誉」的国际数字艺术与科学大奖。",
    recommendedReason: "洞悉全球最高规格数字产品、文化叙事与品牌交互的年度风向标。",
    author: "IADAS (国际数字艺术与科学学院)",
    tags: ["国际大奖", "数字奥斯卡", "品牌体验", "全景评审"],
    actionType: "external",
    homepage: "https://www.webbyawards.com",
    featured: true,
  },
  {
    id: "res:fwa",
    name: "FWA (Favorite Website Awards)",
    category: "frontend",
    description: "自 2000 年创立、见证现代 Web 交互进化史的前沿数字创新大奖。",
    recommendedReason: "探索技术突破极限：WebGL 着色器、生成式音频与沉浸式空间界面实验。",
    author: "FWA Jury",
    tags: ["行业大奖", "技术突破", "前沿WebGL", "沉浸交互"],
    actionType: "external",
    homepage: "https://thefwa.com",
    featured: true,
  },
  {
    id: "res:siteinspire",
    name: "SiteInspire",
    category: "frontend",
    description: "严选真正具备克制美感、清晰架构与优秀排版的 Web 视觉样本档案库。",
    recommendedReason: "支持按行业、构图类型、交互风格与色彩多维交叉筛选，审美极高。",
    author: "Daniel Howells",
    tags: ["设计样本", "多维筛选", "克制美感", "版面架构"],
    actionType: "external",
    homepage: "https://www.siteinspire.com",
    featured: true,
  },
  {
    id: "res:saas-interfaces",
    name: "SaaS Interfaces",
    category: "frontend",
    description: "专注于世界顶尖 B2B 与开发工具类商业软件界面排版与交互细节分析。",
    recommendedReason: "参考 Linear、Stripe、Vercel、Raycast 的复杂信息架构与微交互处理。",
    author: "SaaS Interfaces Curators",
    tags: ["SaaS产品", "B2B界面", "控制台", "微细节"],
    actionType: "external",
    homepage: "https://saasinterface.com",
  },
  {
    id: "res:refero",
    name: "Refero",
    category: "frontend",
    description: "收录数千款优质真实 Web 与 iOS 应用的像素级界面与真实交互流截图。",
    recommendedReason: "按具体页面类型（Onboarding、Pricing、Settings、Table）检索设计参考。",
    author: "Refero Team",
    tags: ["真实截屏", "按页面分类", "交互流程", "设计参考"],
    actionType: "external",
    homepage: "https://refero.design",
  },
  {
    id: "res:one-page-love",
    name: "One Page Love",
    category: "frontend",
    description: "全球最具声誉的单页网站（Single Page）、个人作品集与高转化落地页画廊。",
    recommendedReason: "学习如何在单个滚动视图内讲好一个产品故事，节奏感与转化动线极佳。",
    author: "Rob Hope",
    tags: ["单页设计", "作品集", "落地页", "转化节奏"],
    actionType: "external",
    homepage: "https://onepagelove.com",
  },
  {
    id: "res:collect-ui",
    name: "Collect UI",
    category: "frontend",
    description: "按 Daily UI 与具体设计控件分类（如登录表单、购物车、搜索框）的界面库。",
    recommendedReason: "遇到具体小组件设计缺乏思路时，快速横向对比上百种视觉解法。",
    author: "Panda Network",
    tags: ["Daily UI", "小组件灵感", "表单设计", "控件解法"],
    actionType: "external",
    homepage: "https://collectui.com",
  },
  {
    id: "res:creative-boom",
    name: "Creative Boom",
    category: "frontend",
    description: "英国顶级创意艺术设计杂志，覆盖平面设计、排版工坊、品牌识别与插画艺术。",
    recommendedReason: "跳出纯软件工程视角，从国际前沿平面设计与字体艺术中汲取跨界灵感。",
    author: "Katy Cowan",
    tags: ["创意杂志", "平面排版", "品牌系统", "跨界灵感"],
    actionType: "external",
    homepage: "https://www.creativeboom.com",
  },
  {
    id: "res:component-gallery",
    name: "The Component Gallery",
    category: "frontend",
    description: "收录全球一线真实设计系统（Design System）中的真实组件模式库。",
    recommendedReason: "设计具体控件（如 DatePicker、Combobox）时参考数十家顶级公司的真实方案。",
    author: "Iain Bean",
    tags: ["设计系统", "组件模式", "UI规范", "无障碍"],
    actionType: "external",
    homepage: "https://component.gallery",
  },
  {
    id: "res:checklist-design",
    name: "Checklist Design",
    category: "frontend",
    description: "为 UI/UX 设计师与全栈开发者准备的最佳实践检查清单集合。",
    recommendedReason: "构建表单、登录流、弹窗和空状态时避免遗漏关键体验与极端情况边界。",
    author: "George Hatzis",
    tags: ["设计清单", "体验规范", "表单设计", "空状态"],
    actionType: "external",
    homepage: "https://www.checklist.design",
  },
  {
    id: "res:shadcn-ui-inspiration",
    name: "Shadcn UI Showcase",
    category: "frontend",
    description: "基于 shadcn/ui 生态构建的优质开源 Web 应用、控制台与仪表盘展示。",
    recommendedReason: "观察现代深色工作台产品如何克制优雅地运用无头组件打造高级感。",
    author: "Shadcn Community",
    tags: ["Shadcn", "Dashboard", "极简控制台", "实战样板"],
    actionType: "external",
    homepage: "https://ui.shadcn.com/examples",
    featured: true,
  },
  {
    id: "res:mobbin",
    name: "Mobbin",
    category: "frontend",
    description: "全球最大规模的移动端与 Web 端真实商业产品界面截图与用户旅程库。",
    recommendedReason: "逆向分析 Linear、Raycast、Spotify 等顶级产品的完整操作流程与微细节。",
    author: "Mobbin Design",
    tags: ["真实流程", "用户旅程", "交互细节", "界面参考"],
    actionType: "external",
    homepage: "https://mobbin.com",
  },
  {
    id: "res:land-book",
    name: "Land-book",
    category: "frontend",
    description: "精心挑选的开发者工具、SaaS 产品与设计机构官方 Landing Page 画廊。",
    recommendedReason: "学习如何写出抓人的 Hero 文案与清晰的技术产品功能对比网格。",
    author: "Land-book Curators",
    tags: ["Landing Page", "SaaS设计", "文案排版", "视觉层次"],
    actionType: "external",
    homepage: "https://land-book.com",
  },
  {
    id: "res:darkmode-design",
    name: "Dark Mode Design",
    category: "frontend",
    description: "专注收集真正具有设计感的全暗黑（Pure Dark）产品与网站范本。",
    recommendedReason: "学习如何不用纯黑死黑，而是通过多阶低明度冷暖灰度打造深邃立体层次。",
    author: "Alexis Collado",
    tags: ["暗黑模式", "灰度阶梯", "护眼层次", "夜间视觉"],
    actionType: "external",
    homepage: "https://www.darkmodedesign.com",
  },
  {
    id: "res:react",
    name: "React",
    category: "frontend",
    description: "以组件与单向数据流为核心、由 Meta 维护的声明式 UI 库。",
    recommendedReason: "生态规模与人才存量仍是第一，组件抽象、并发渲染与 Server Components 演进方向也在持续定义前端标准。",
    author: "Meta & React Contributors",
    tags: ["UI库", "组件化", "并发渲染", "生态最广"],
    actionType: "github",
    repository: "https://github.com/facebook/react",
    homepage: "https://react.dev",
    stars: "232k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:vue",
    name: "Vue.js",
    category: "frontend",
    description: "渐进式 JavaScript 框架，单文件组件把模板、逻辑与样式收拢在一个文件内。",
    recommendedReason: "响应式系统与模板语法对新手友好，文档质量极高，中型项目上手成本明显低于同类框架。",
    author: "Evan You & Vue Team",
    tags: ["渐进式框架", "单文件组件", "响应式", "中文文档"],
    actionType: "github",
    repository: "https://github.com/vuejs/core",
    homepage: "https://vuejs.org",
    stars: "48k+",
    license: "MIT",
  },
  {
    id: "res:svelte",
    name: "Svelte",
    category: "frontend",
    description: "在编译期把组件编译为直接操作 DOM 的原生 JavaScript、运行时开销极小的框架。",
    recommendedReason: "无需虚拟 DOM 与手写依赖数组，产出体积小、运行快，做交互密集的轻量应用优势明显。",
    author: "Rich Harris & Svelte Team",
    tags: ["编译期优化", "无虚拟DOM", "体积小", "语法简洁"],
    actionType: "github",
    repository: "https://github.com/sveltejs/svelte",
    homepage: "https://svelte.dev",
    stars: "80k+",
    license: "MIT",
  },
  {
    id: "res:solid-js",
    name: "SolidJS",
    category: "frontend",
    description: "采用细粒度响应式信号（Signal）机制、无虚拟 DOM 的高性能 UI 库。",
    recommendedReason: "保留 JSX 写法却拿到接近原生的更新性能，是研究响应式底层原理时最值得读源码的框架之一。",
    author: "Ryan Carniato",
    tags: ["细粒度响应式", "Signal", "无虚拟DOM", "极致性能"],
    actionType: "github",
    repository: "https://github.com/solidjs/solid",
    homepage: "https://www.solidjs.com",
    stars: "32k+",
    license: "MIT",
  },
  {
    id: "res:nextjs",
    name: "Next.js",
    category: "frontend",
    description: "由 Vercel 维护的全栈 React 框架，涵盖路由、服务端渲染、数据获取与构建优化。",
    recommendedReason: "App Router 与 Server Components 把前后端边界收进同一个工程，是当前 React 生产项目的默认选择。",
    author: "Vercel",
    tags: ["全栈框架", "SSR", "Server Components", "文件路由"],
    actionType: "github",
    repository: "https://github.com/vercel/next.js",
    homepage: "https://nextjs.org",
    stars: "128k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:nuxt",
    name: "Nuxt",
    category: "frontend",
    description: "构建在 Vue 之上的全栈元框架，提供约定式路由、自动导入与服务端渲染。",
    recommendedReason: "约定优于配置的设计把大量样板代码消掉，Vue 团队做 SEO 与首屏性能优化的首选方案。",
    author: "Nuxt Team",
    tags: ["Vue元框架", "约定式路由", "自动导入", "SSR"],
    actionType: "github",
    repository: "https://github.com/nuxt/nuxt",
    homepage: "https://nuxt.com",
    stars: "55k+",
    license: "MIT",
  },
  {
    id: "res:sveltekit",
    name: "SvelteKit",
    category: "frontend",
    description: "Svelte 官方全栈应用框架，统一处理路由、数据加载、表单动作与多种渲染模式。",
    recommendedReason: "同一套代码可切换 SSR、SSG 与 CSR，渐进增强的表单处理几乎不需要额外状态管理。",
    author: "Svelte Team",
    tags: ["Svelte官方", "全栈框架", "渐进增强", "多渲染模式"],
    actionType: "github",
    repository: "https://github.com/sveltejs/kit",
    homepage: "https://kit.svelte.dev",
    stars: "19k+",
    license: "MIT",
  },
  {
    id: "res:astro",
    name: "Astro",
    category: "frontend",
    description: "以内容为中心的 Web 框架，默认输出零客户端 JavaScript 的静态页面。",
    recommendedReason: "群岛架构让静态页面加载极快，同时可局部混入 React、Vue、Svelte 组件而不牺牲性能。",
    author: "Astro Technology Company",
    tags: ["内容优先", "岛屿架构", "零JS默认", "多框架混用"],
    actionType: "github",
    repository: "https://github.com/withastro/astro",
    homepage: "https://astro.build",
    stars: "46k+",
    license: "MIT",
  },
  {
    id: "res:vite",
    name: "Vite",
    category: "frontend",
    description: "基于原生 ESM 与 Rollup 的新一代前端构建工具，开发态按需编译。",
    recommendedReason: "冷启动几乎瞬时、热更新不受项目规模影响，已是绝大多数现代前端脚手架的默认构建底座。",
    author: "Evan You & Vite Team",
    tags: ["构建工具", "原生ESM", "极速热更新", "生态标准"],
    actionType: "github",
    repository: "https://github.com/vitejs/vite",
    homepage: "https://vite.dev",
    stars: "70k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:tailwindcss",
    name: "Tailwind CSS",
    category: "frontend",
    description: "以工具类（Utility Class）直接在标记中表达样式的原子化 CSS 框架。",
    recommendedReason: "样式与结构同处一处、产物只保留用到的类，配合设计令牌即可实现高度一致的界面系统。",
    author: "Tailwind Labs",
    tags: ["原子化CSS", "工具类", "设计令牌", "零冗余产物"],
    actionType: "github",
    repository: "https://github.com/tailwindlabs/tailwindcss",
    homepage: "https://tailwindcss.com",
    stars: "84k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:unocss",
    name: "UnoCSS",
    category: "frontend",
    description: "即时按需生成的原子化 CSS 引擎，支持属性化模式与自定义规则预设。",
    recommendedReason: "规则可编程且支持 Tailwind 兼容语法，构建速度与产物体积控制比传统原子框架更激进。",
    author: "Anthony Fu",
    tags: ["原子化引擎", "按需生成", "可编程规则", "属性化模式"],
    actionType: "github",
    repository: "https://github.com/unocss/unocss",
    homepage: "https://unocss.dev",
    stars: "17k+",
    license: "MIT",
  },
  {
    id: "res:panda-css",
    name: "Panda CSS",
    category: "frontend",
    description: "在构建期生成类型安全样式的 CSS-in-JS 引擎，输出静态样式表而非运行时注入。",
    recommendedReason: "既能写类型安全的样式对象，又拿到零运行时代价，兼顾开发体验与首屏性能。",
    author: "Chakra Systems",
    tags: ["类型安全样式", "构建期生成", "零运行时", "设计令牌"],
    actionType: "github",
    repository: "https://github.com/chakra-ui/panda",
    homepage: "https://panda-css.com",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:open-props",
    name: "Open Props",
    category: "frontend",
    description: "由精心调校的 CSS 自定义属性组成的设计令牌与动画缓动集合。",
    recommendedReason: "开箱即用全套色彩、间距、阴影与缓动变量，不引入任何构建步骤就能获得自洽的视觉标尺。",
    author: "Adam Argyle",
    tags: ["CSS变量", "设计令牌", "零构建", "缓动曲线"],
    actionType: "github",
    repository: "https://github.com/argyleink/open-props",
    homepage: "https://open-props.style",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:tanstack-query",
    name: "TanStack Query",
    category: "frontend",
    description: "为 Web 与 React Native 提供异步状态获取、缓存、重试与后台同步的数据层库。",
    recommendedReason: "把加载态、错误态、缓存失效与乐观更新一次性解决，服务端状态不再需要手写进全局 store。",
    author: "Tanner Linsley (TanStack)",
    tags: ["数据请求", "缓存管理", "乐观更新", "服务端状态"],
    actionType: "github",
    repository: "https://github.com/TanStack/query",
    homepage: "https://tanstack.com/query",
    stars: "43k+",
    license: "MIT",
  },
  {
    id: "res:zustand",
    name: "Zustand",
    category: "frontend",
    description: "极简、无样板代码的 React 轻量状态管理库，基于外部 store 与选择器订阅。",
    recommendedReason: "几十行即可替代 Redux 的大量模板代码，且天然避免 Provider 嵌套与不必要重渲染。",
    author: "Poimandres (pmndrs)",
    tags: ["状态管理", "极简API", "选择器订阅", "无样板"],
    actionType: "github",
    repository: "https://github.com/pmndrs/zustand",
    homepage: "https://zustand.docs.pmnd.rs",
    stars: "49k+",
    license: "MIT",
  },
  {
    id: "res:jotai",
    name: "Jotai",
    category: "frontend",
    description: "以原子（Atom）为最小单位自下而上组合状态的 React 状态管理库。",
    recommendedReason: "状态按原子拆分后按需订阅，复杂表单与派生计算不再需要引入繁琐的 reducer 结构。",
    author: "Daishi Kato",
    tags: ["原子化状态", "自下而上", "按需订阅", "React"],
    actionType: "github",
    repository: "https://github.com/pmndrs/jotai",
    homepage: "https://jotai.org",
    stars: "19k+",
    license: "MIT",
  },
  {
    id: "res:trpc",
    name: "tRPC",
    category: "frontend",
    description: "让 TypeScript 前后端在不生成代码、不使用 schema 的前提下获得端到端类型安全调用的 RPC 框架。",
    recommendedReason: "后端函数签名改动会直接在编辑器里爆红到前端调用处，是个人与团队全栈项目最省心的接口契约方案。",
    author: "Alex Johansson (tRPC)",
    tags: ["端到端类型安全", "无代码生成", "全栈TypeScript", "接口契约"],
    actionType: "github",
    repository: "https://github.com/trpc/trpc",
    homepage: "https://trpc.io",
    stars: "35k+",
    license: "MIT",
  },
  {
    id: "res:zod",
    name: "Zod",
    category: "frontend",
    description: "以 TypeScript 优先设计的 schema 声明与运行时校验库。",
    recommendedReason: "一份 schema 同时产出静态类型与运行时校验，并可直接生成表单校验与 API 契约。",
    author: "Colin McDonnell",
    tags: ["运行时校验", "类型推导", "Schema声明", "表单与API"],
    actionType: "github",
    repository: "https://github.com/colinhacks/zod",
    homepage: "https://zod.dev",
    stars: "35k+",
    license: "MIT",
  },
  {
    id: "res:tauri",
    name: "Tauri",
    category: "frontend",
    description: "用 Rust 作为后端、系统原生 WebView 作为渲染层的轻量跨平台桌面应用框架。",
    recommendedReason: "安装包可控制在几 MB 量级且内存占用远低于打包 Chromium 的方案，是本项目 Setup Center 的技术底座。",
    author: "Tauri Contributors",
    tags: ["桌面应用", "Rust后端", "系统WebView", "安装包极小"],
    actionType: "github",
    repository: "https://github.com/tauri-apps/tauri",
    homepage: "https://tauri.app",
    stars: "89k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:electron",
    name: "Electron",
    category: "frontend",
    description: "把 Chromium 与 Node.js 打包进同一运行时的跨平台桌面应用框架。",
    recommendedReason: "生态与工具链最成熟，需要深度依赖 Chromium 特性或大量 Node 原生模块时仍是最稳的选择。",
    author: "OpenJS Foundation",
    tags: ["桌面应用", "Chromium", "Node.js", "生态成熟"],
    actionType: "github",
    repository: "https://github.com/electron/electron",
    homepage: "https://www.electronjs.org",
    stars: "116k+",
    license: "MIT",
  },
  {
    id: "res:capacitor",
    name: "Capacitor",
    category: "frontend",
    description: "把任意 Web 前端工程包装为可发布 iOS 与 Android 原生应用的跨平台运行时。",
    recommendedReason: "复用已有 Web 代码又能通过原生插件访问相机、文件与推送，是移动端成本最低的落地路径。",
    author: "Ionic",
    tags: ["移动端", "Web转原生", "原生插件", "跨平台"],
    actionType: "github",
    repository: "https://github.com/ionic-team/capacitor",
    homepage: "https://capacitorjs.com",
    stars: "13k+",
    license: "MIT",
  },
  {
    id: "res:react-native",
    name: "React Native",
    category: "frontend",
    description: "用 React 组件模型与原生控件构建 iOS 与 Android 应用的移动开发框架。",
    recommendedReason: "前端工程师可直接复用 React 心智模型产出真原生体验，新架构下的同步渲染能力已大幅改善。",
    author: "Meta",
    tags: ["移动开发", "React模型", "原生控件", "跨平台"],
    actionType: "github",
    repository: "https://github.com/facebook/react-native",
    homepage: "https://reactnative.dev",
    stars: "120k+",
    license: "MIT",
  },
  {
    id: "res:expo",
    name: "Expo",
    category: "frontend",
    description: "围绕 React Native 构建的全托管工具链与云构建服务。",
    recommendedReason: "省掉 Xcode 与 Android Studio 的环境配置，手机上扫码即可预览，是把移动应用跑通的最短路径。",
    author: "Expo (650 Industries)",
    tags: ["React Native工具链", "云构建", "扫码预览", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/expo/expo",
    homepage: "https://expo.dev",
    stars: "38k+",
    license: "MIT",
  },
  {
    id: "res:flutter",
    name: "Flutter",
    category: "frontend",
    description: "Google 推出的自绘 UI 引擎，用 Dart 一套代码构建移动、桌面与 Web 应用。",
    recommendedReason: "自绘引擎保证各端像素级一致，动画与滚动性能稳定，是强视觉一致性产品的可靠方案。",
    author: "Google",
    tags: ["自绘UI", "Dart", "多端一致", "高性能动画"],
    actionType: "github",
    repository: "https://github.com/flutter/flutter",
    homepage: "https://flutter.dev",
    stars: "169k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:dribbble",
    name: "Dribbble",
    category: "frontend",
    description: "全球规模最大的 UI 视觉与插画作品分享社区。",
    recommendedReason: "搜索具体界面类型（如仪表盘、定价页）即可获得大量高完成度视觉方案，适合确定配色与视觉方向阶段。",
    author: "Dribbble Holdings",
    tags: ["视觉灵感", "UI作品", "配色参考", "全球社区"],
    actionType: "external",
    homepage: "https://dribbble.com",
  },
  {
    id: "res:behance",
    name: "Behance",
    category: "frontend",
    description: "Adobe 旗下的完整项目案例展示社区，覆盖品牌、界面与整站设计。",
    recommendedReason: "以完整项目而非单张图为单位呈现，能看到从视觉概念到落地页面的完整推导过程。",
    author: "Adobe",
    tags: ["项目案例", "品牌设计", "完整流程", "Adobe"],
    actionType: "external",
    homepage: "https://www.behance.net",
  },
  {
    id: "res:minimal-gallery",
    name: "Minimal Gallery",
    category: "frontend",
    description: "只收录极简主义风格网站的设计画廊。",
    recommendedReason: "风格筛选极其严格，在做克制、留白充足的界面时是最直接的对标样本库。",
    author: "Minimal Gallery",
    tags: ["极简风格", "留白布局", "网站画廊", "风格严格"],
    actionType: "external",
    homepage: "https://minimal.gallery",
  },
  {
    id: "res:landingfolio",
    name: "Landingfolio",
    category: "frontend",
    description: "按区块拆解收录真实产品落地页的设计参考库。",
    recommendedReason: "提供 Hero、定价表、客户评价等具体区块截图，搭建落地页时可直接按区块找参考。",
    author: "Landingfolio",
    tags: ["落地页", "区块拆解", "定价表参考", "SaaS"],
    actionType: "external",
    homepage: "https://www.landingfolio.com",
  },
  {
    id: "res:pageflows",
    name: "Page Flows",
    category: "frontend",
    description: "以录屏形式记录真实产品端到端交互流程的 UX 参考库。",
    recommendedReason: "看得到注册、引导、结算等完整流程如何一步步引导用户，是设计交互而非单页的关键素材。",
    author: "Page Flows",
    tags: ["交互流程", "录屏参考", "用户体验", "端到端"],
    actionType: "external",
    homepage: "https://pageflows.com",
  },
  {
    id: "res:savee",
    name: "Savee",
    category: "frontend",
    description: "面向设计师的高质量视觉素材收藏与检索平台。",
    recommendedReason: "信息流噪音低、审美水准稳定，适合长期积累个人情绪板与视觉参考库。",
    author: "Savee",
    tags: ["情绪板", "视觉收藏", "审美参考", "低噪音"],
    actionType: "external",
    homepage: "https://savee.it",
  },
  {
    id: "res:httpster",
    name: "Httpster",
    category: "frontend",
    description: "长期更新的独立网站设计展示与推荐目录。",
    recommendedReason: "偏向非商业化的创意站点，能看到很多不依赖模板套路的大胆版式与交互。",
    author: "Httpster",
    tags: ["创意站点", "独立设计", "版式灵感", "长期更新"],
    actionType: "external",
    homepage: "https://httpster.net",
  },
  {
    id: "res:web-design-museum",
    name: "Web Design Museum",
    category: "frontend",
    description: "收录 1990 年代至今经典网站界面截图的 Web 设计历史档案馆。",
    recommendedReason: "理解界面语言如何逐代演化，能帮助判断今天的「流行」哪些是短暂潮流哪些是长期规律。",
    author: "Web Design Museum",
    tags: ["设计史", "经典界面", "怀旧档案", "演化脉络"],
    actionType: "external",
    homepage: "https://www.webdesignmuseum.org",
  },
  {
    id: "res:design-spells",
    name: "Design Spells",
    category: "frontend",
    description: "专注收集界面中那些令人惊喜的细节微交互与动画彩蛋的灵感库。",
    recommendedReason: "专门针对「缝隙里的魔法」，是给已完成界面补充高价值微交互细节时的精确素材来源。",
    author: "Design Spells",
    tags: ["微交互", "细节灵感", "动画彩蛋", "界面质感"],
    actionType: "external",
    homepage: "https://www.designspells.com",
  },
  {
    id: "res:hoverstat-es",
    name: "Hoverstat.es",
    category: "frontend",
    description: "专门收录具有独特悬停、加载与导航交互的网站目录。",
    recommendedReason: "逐站拆解「动效如何服务信息层级」，是做有辨识度导航与悬停态时的高密度参考。",
    author: "Hoverstat.es",
    tags: ["悬停交互", "导航设计", "动效参考", "独特体验"],
    actionType: "external",
    homepage: "https://www.hoverstat.es",
  },
  {
    id: "res:are-na",
    name: "Are.na",
    category: "frontend",
    description: "以频道（Channel）组织内容的无广告视觉收藏与协作平台。",
    recommendedReason: "可按主题建立互联的参考频道并与他人共建，适合长期沉淀跨领域的视觉研究素材。",
    author: "Are.na",
    tags: ["视觉收藏", "频道组织", "协作研究", "无广告"],
    actionType: "external",
    homepage: "https://www.are.na",
  },
];
