import type { ResourceItem } from "../types";

export const frontendResources: ResourceItem[] = [
  {
    id: "res:godly-website",
    name: "Godly Website",
    category: "frontend",
    description: "每日更新的世界顶级现代 Web 设计、排版与微交互精选画廊。",
    recommendedReason: "寻找现代产品主页、暗黑界面与极致版面留白灵感的第一去处。",
    author: "Godly Team",
    tags: ["设计灵感", "落地页", "版式排版", "微交互"],
    actionType: "external",
    homepage: "https://godly.website",
    featured: true,
  },
  {
    id: "res:awwwards",
    name: "Awwwards",
    category: "frontend",
    description: "全球顶尖数字设计师与开发者的年度/每日获奖作品评选平台。",
    recommendedReason: "了解当下世界最高技术力 3D WebGL、复杂动效与突破性网页叙事。",
    author: "Awwwards Jury",
    tags: ["行业大奖", "前沿交互", "3D Web", "创新排版"],
    actionType: "external",
    homepage: "https://www.awwwards.com",
    featured: true,
  },
  {
    id: "res:webby-awards",
    name: "The Webby Awards",
    category: "frontend",
    description: "被《纽约时报》誉为「互联网最高荣誉」的国际数字艺术与科学大奖。",
    recommendedReason: "洞悉全球最高规格数字产品、文化叙事与品牌交互的年度风向标。",
    author: "IADAS (国际数字艺术与科学学院)",
    tags: ["国际大奖", "数字奥斯卡", "品牌体验", "全景评审"],
    actionType: "external",
    homepage: "https://www.webbyawards.com",
    featured: true,
  },
  {
    id: "res:fwa",
    name: "FWA (Favorite Website Awards)",
    category: "frontend",
    description: "自 2000 年创立、见证现代 Web 交互进化史的前沿数字创新大奖。",
    recommendedReason: "探索技术突破极限：WebGL 着色器、生成式音频与沉浸式空间界面实验。",
    author: "FWA Jury",
    tags: ["行业大奖", "技术突破", "前沿WebGL", "沉浸交互"],
    actionType: "external",
    homepage: "https://thefwa.com",
    featured: true,
  },
  {
    id: "res:siteinspire",
    name: "SiteInspire",
    category: "frontend",
    description: "严选真正具备克制美感、清晰架构与优秀排版的 Web 视觉样本档案库。",
    recommendedReason: "支持按行业、构图类型、交互风格与色彩多维交叉筛选，审美极高。",
    author: "Daniel Howells",
    tags: ["设计样本", "多维筛选", "克制美感", "版面架构"],
    actionType: "external",
    homepage: "https://www.siteinspire.com",
    featured: true,
  },
  {
    id: "res:saas-interfaces",
    name: "SaaS Interfaces",
    category: "frontend",
    description: "专注于世界顶尖 B2B 与开发工具类商业软件界面排版与交互细节分析。",
    recommendedReason: "参考 Linear、Stripe、Vercel、Raycast 的复杂信息架构与微交互处理。",
    author: "SaaS Interfaces Curators",
    tags: ["SaaS产品", "B2B界面", "控制台", "微细节"],
    actionType: "external",
    homepage: "https://saasinterface.com",
  },
  {
    id: "res:refero",
    name: "Refero",
    category: "frontend",
    description: "收录数千款优质真实 Web 与 iOS 应用的像素级界面与真实交互流截图。",
    recommendedReason: "按具体页面类型（Onboarding、Pricing、Settings、Table）检索设计参考。",
    author: "Refero Team",
    tags: ["真实截屏", "按页面分类", "交互流程", "设计参考"],
    actionType: "external",
    homepage: "https://refero.design",
  },
  {
    id: "res:one-page-love",
    name: "One Page Love",
    category: "frontend",
    description: "全球最具声誉的单页网站（Single Page）、个人作品集与高转化落地页画廊。",
    recommendedReason: "学习如何在单个滚动视图内讲好一个产品故事，节奏感与转化动线极佳。",
    author: "Rob Hope",
    tags: ["单页设计", "作品集", "落地页", "转化节奏"],
    actionType: "external",
    homepage: "https://onepagelove.com",
  },
  {
    id: "res:collect-ui",
    name: "Collect UI",
    category: "frontend",
    description: "按 Daily UI 与具体设计控件分类（如登录表单、购物车、搜索框）的界面库。",
    recommendedReason: "遇到具体小组件设计缺乏思路时，快速横向对比上百种视觉解法。",
    author: "Panda Network",
    tags: ["Daily UI", "小组件灵感", "表单设计", "控件解法"],
    actionType: "external",
    homepage: "https://collectui.com",
  },
  {
    id: "res:magic-ui",
    name: "Magic UI",
    category: "frontend",
    description: "专为打造令人惊叹的现代 Landing Page 构建的 React + Tailwind 高表现力组件库。",
    recommendedReason: "一键复制光束边框、流光文字、拟物网格与平滑卡片，显著提升产品吸睛度。",
    author: "Dillion Verma",
    tags: ["LandingPage", "高表现力", "流光动画", "Tailwind"],
    actionType: "external",
    homepage: "https://magicui.design",
    featured: true,
  },
  {
    id: "res:aceternity-ui",
    name: "Aceternity UI",
    category: "frontend",
    description: "当下最热门的高风格化前端动效组件库，包含未来主义背景、悬停卡片与先锋排版。",
    recommendedReason: "为开发者提供开箱即用的高阶 Framer Motion 与 Tailwind 交互组件，直接复制源码。",
    author: "Manu Arora",
    tags: ["先锋动效", "未来感", "Framer Motion", "复制代码"],
    actionType: "external",
    homepage: "https://ui.aceternity.com",
    featured: true,
  },
  {
    id: "res:creative-boom",
    name: "Creative Boom",
    category: "frontend",
    description: "英国顶级创意艺术设计杂志，覆盖平面设计、排版工坊、品牌识别与插画艺术。",
    recommendedReason: "跳出纯软件工程视角，从国际前沿平面设计与字体艺术中汲取跨界灵感。",
    author: "Katy Cowan",
    tags: ["创意杂志", "平面排版", "品牌系统", "跨界灵感"],
    actionType: "external",
    homepage: "https://www.creativeboom.com",
  },
  {
    id: "res:component-gallery",
    name: "The Component Gallery",
    category: "frontend",
    description: "收录全球一线真实设计系统（Design System）中的真实组件模式库。",
    recommendedReason: "设计具体控件（如 DatePicker、Combobox）时参考数十家顶级公司的真实方案。",
    author: "Iain Bean",
    tags: ["设计系统", "组件模式", "UI规范", "无障碍"],
    actionType: "external",
    homepage: "https://component.gallery",
  },
  {
    id: "res:checklist-design",
    name: "Checklist Design",
    category: "frontend",
    description: "为 UI/UX 设计师与全栈开发者准备的最佳实践检查清单集合。",
    recommendedReason: "构建表单、登录流、弹窗和空状态时避免遗漏关键体验与极端情况边界。",
    author: "George Hatzis",
    tags: ["设计清单", "体验规范", "表单设计", "空状态"],
    actionType: "external",
    homepage: "https://www.checklist.design",
  },
  {
    id: "res:shadcn-ui-inspiration",
    name: "Shadcn UI Showcase",
    category: "frontend",
    description: "基于 shadcn/ui 生态构建的优质开源 Web 应用、控制台与仪表盘展示。",
    recommendedReason: "观察现代深色工作台产品如何克制优雅地运用无头组件打造高级感。",
    author: "Shadcn Community",
    tags: ["Shadcn", "Dashboard", "极简控制台", "实战样板"],
    actionType: "external",
    homepage: "https://ui.shadcn.com/examples",
    featured: true,
  },
  {
    id: "res:mobbin",
    name: "Mobbin",
    category: "frontend",
    description: "全球最大规模的移动端与 Web 端真实商业产品界面截图与用户旅程库。",
    recommendedReason: "逆向分析 Linear、Raycast、Spotify 等顶级产品的完整操作流程与微细节。",
    author: "Mobbin Design",
    tags: ["真实流程", "用户旅程", "交互细节", "界面参考"],
    actionType: "external",
    homepage: "https://mobbin.com",
  },
  {
    id: "res:land-book",
    name: "Land-book",
    category: "frontend",
    description: "精心挑选的开发者工具、SaaS 产品与设计机构官方 Landing Page 画廊。",
    recommendedReason: "学习如何写出抓人的 Hero 文案与清晰的技术产品功能对比网格。",
    author: "Land-book Curators",
    tags: ["Landing Page", "SaaS设计", "文案排版", "视觉层次"],
    actionType: "external",
    homepage: "https://land-book.com",
  },
  {
    id: "res:darkmode-design",
    name: "Dark Mode Design",
    category: "frontend",
    description: "专注收集真正具有设计感的全暗黑（Pure Dark）产品与网站范本。",
    recommendedReason: "学习如何不用纯黑死黑，而是通过多阶低明度冷暖灰度打造深邃立体层次。",
    author: "Alexis Collado",
    tags: ["暗黑模式", "灰度阶梯", "护眼层次", "夜间视觉"],
    actionType: "external",
    homepage: "https://www.darkmodedesign.com",
  },
];
