import type { ResourceItem } from "../types";

export const iconResources: ResourceItem[] = [
  {
    id: "res:lucide-icons",
    name: "Lucide Icons",
    category: "icons",
    description: "社区驱动、风格极致统一且支持所有现代框架的 1400+ 开源矢量图标库。",
    recommendedReason: "当今现代前端事实标准，基于 Feather 深度重构，笔触粗细可控，无缝契合各风格。",
    author: "Lucide Project",
    tags: ["现代标准", "一致性", "全框架支持", "可控笔触"],
    actionType: "github",
    repository: "https://github.com/lucide-icons/lucide",
    homepage: "https://lucide.dev",
    stars: "18k+",
    license: "ISC",
    featured: true,
  },
  {
    id: "res:tabler-icons",
    name: "Tabler Icons",
    category: "icons",
    description: "超过 5200+ 个像素对齐的免费高质量 SVG 图标套件，涵盖你能想象的所有分类。",
    recommendedReason: "体量庞大，分类极其细致，无论是工业仪器、数学公式还是日常操作均有覆盖。",
    author: "Paweł Kuna",
    tags: ["海量图标", "像素对齐", "工业覆盖", "高自由度"],
    actionType: "github",
    repository: "https://github.com/tabler/tabler-icons",
    homepage: "https://tabler.io/icons",
    stars: "17k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:phosphor-icons",
    name: "Phosphor Icons",
    category: "icons",
    description: "灵活且极具辨识度的开源图标家族，原生提供 6 种不同粗细与填充形态变体。",
    recommendedReason: "Thin, Light, Regular, Bold, Fill, Duotone 六档粗细无缝切换，适配任何设计系统。",
    author: "Helena Zhang & Tobias Fried",
    tags: ["6种形态", "双色调Duotone", "极简灵活", "设计系统好伴侣"],
    actionType: "github",
    repository: "https://github.com/phosphor-icons/core",
    homepage: "https://phosphoricons.com",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:heroicons",
    name: "Heroicons",
    category: "icons",
    description: "Tailwind CSS 官方团队纯手工打磨的精美开源 SVG 图标套件。",
    recommendedReason: "专为搭配 Tailwind 24px/20px/16px 视口量身定制，轮廓平衡感极佳。",
    author: "Tailwind Labs",
    tags: ["Tailwind官方", "手工打磨", "微尺寸优化", "精致小巧"],
    actionType: "github",
    repository: "https://github.com/tailwindlabs/heroicons",
    homepage: "https://heroicons.com",
    stars: "20k+",
    license: "MIT",
  },
  {
    id: "res:simple-icons",
    name: "Simple Icons",
    category: "icons",
    description: "收录 3100+ 个知名品牌、编程语言、开源软件与开发工具的官方正版矢量 Logo。",
    recommendedReason: "展示技术栈、软件徽标、集成连接器时必备的官方标准 Logo 权威来源。",
    author: "Simple Icons Contributors",
    tags: ["品牌Logo", "官方徽标", "技术栈图标", "SVG集合"],
    actionType: "github",
    repository: "https://github.com/simple-icons/simple-icons",
    homepage: "https://simpleicons.org",
    stars: "20k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:iconoir",
    name: "Iconoir",
    category: "icons",
    description: "1500+ 个完全开源、零外部依赖且支持 CSS/SVG/React/Vue 的极简纤细线条图标。",
    recommendedReason: "无多余杂饰，极度适合追求克制工业风与极简编辑排版风格的软件系统。",
    author: "Luca Burgio",
    tags: ["纤细线条", "零依赖", "极简主义", "高通用性"],
    actionType: "github",
    repository: "https://github.com/iconoir-icons/iconoir",
    homepage: "https://iconoir.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:remix-icon",
    name: "Remix Icon",
    category: "icons",
    description: "精心设计且中立开阔的开源图标库，每一个图标都拥有线性与面性两种风格。",
    recommendedReason: "亚洲及全球中文开发者极其常用，中文语义化搜索体验极佳。",
    author: "Remix Design",
    tags: ["线面双版", "中文友好", "开阔中立", "日常办公"],
    actionType: "github",
    repository: "https://github.com/Remix-Design/RemixIcon",
    homepage: "https://remixicon.com",
    stars: "11k+",
    license: "Apache-2.0",
  },
  {
    id: "res:hugeicons",
    name: "Hugeicons",
    category: "icons",
    description: "超过 4000+ 免费图标，提供 5 种不同设计笔触，专为现代产品与设计稿打造。",
    recommendedReason: "笔触饱满圆润，极适合现代移动端与现代消费级工具软件的活泼界面。",
    author: "Hugeicons",
    tags: ["5种笔触", "现代圆润", "高质感", "消费级体验"],
    actionType: "external",
    homepage: "https://hugeicons.com",
  },
  {
    id: "res:svgl",
    name: "svgl",
    category: "icons",
    description: "超高质量、精美统一的现代科技公司与开源项目高精度 SVG Logo 资源库。",
    recommendedReason: "React 组件与直链 SVG 开箱即用，是搭建技术栈墙、集成目录与合作方展示的利器。",
    author: "Pheralb",
    tags: ["Logo库", "科技品牌", "高精度SVG", "开发者标配"],
    actionType: "github",
    repository: "https://github.com/pheralb/svgl",
    homepage: "https://svgl.app",
    stars: "7k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:iconify",
    name: "Iconify",
    category: "icons",
    description: "统一封装 150 余个开源图标集、总计 20 万枚以上图标的跨框架图标引擎。",
    recommendedReason: "一套 API 调用全部图标集且支持按需加载，彻底摆脱「换图标库就要重写一遍引用」的困境。",
    author: "Vjacheslav Trushkin",
    tags: ["统一图标引擎", "20万枚图标", "按需加载", "跨框架"],
    actionType: "github",
    repository: "https://github.com/iconify/iconify",
    homepage: "https://iconify.design",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:material-symbols",
    name: "Material Symbols",
    category: "icons",
    description: "Google 官方维护、支持可变字重与填充轴调节的现代界面图标体系。",
    recommendedReason: "同一枚图标可通过可变字体参数连续调节粗细与填充状态，是产品状态反馈最省事的视觉语言。",
    author: "Google",
    tags: ["Google官方", "可变字体图标", "字重可调", "界面语义"],
    actionType: "github",
    repository: "https://github.com/google/material-design-icons",
    homepage: "https://fonts.google.com/icons",
    stars: "52k+",
    license: "Apache-2.0",
  },
  {
    id: "res:feather-icons",
    name: "Feather Icons",
    category: "icons",
    description: "以 24px 网格、2px 描边与圆角端点统一规格的极简线性图标集。",
    recommendedReason: "风格克制且几何一致性极强，做线框稿与低干扰界面时几乎不会出错。",
    author: "Cole Bemis",
    tags: ["极简线性", "统一规格", "低干扰", "经典图标集"],
    actionType: "github",
    repository: "https://github.com/feathericons/feather",
    homepage: "https://feathericons.com",
    stars: "26k+",
    license: "MIT",
  },
  {
    id: "res:bootstrap-icons",
    name: "Bootstrap Icons",
    category: "icons",
    description: "Bootstrap 团队维护的 2000 余枚开源 SVG 图标库。",
    recommendedReason: "覆盖大量业务语义图标且风格中性，适合快速铺满管理后台的表单与状态图标。",
    author: "Bootstrap Team",
    tags: ["2000+图标", "业务语义", "中性风格", "后台友好"],
    actionType: "github",
    repository: "https://github.com/twbs/icons",
    homepage: "https://icons.getbootstrap.com",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:font-awesome",
    name: "Font Awesome Free",
    category: "icons",
    description: "历史最悠久、覆盖面最广的开源图标字体与 SVG 库。",
    recommendedReason: "大量老项目与模板默认依赖它，维护既有系统时保持图标体系一致的首选。",
    author: "Fonticons Inc.",
    tags: ["图标字体", "历史悠久", "覆盖面广", "兼容既有项目"],
    actionType: "github",
    repository: "https://github.com/FortAwesome/Font-Awesome",
    homepage: "https://fontawesome.com",
    stars: "75k+",
    license: "CC BY 4.0 / SIL OFL 1.1",
  },
  {
    id: "res:radix-icons",
    name: "Radix Icons",
    category: "icons",
    description: "Radix UI 团队出品的 15px 网格精确对齐的紧凑型图标集。",
    recommendedReason: "为搭配 Radix 组件与密集工具栏设计，小尺寸下依然笔画清晰不发虚。",
    author: "WorkOS (Radix UI)",
    tags: ["15px网格", "小尺寸清晰", "Radix配套", "紧凑界面"],
    actionType: "github",
    repository: "https://github.com/radix-ui/icons",
    homepage: "https://www.radix-ui.com/icons",
    stars: "2k+",
    license: "MIT",
  },
  {
    id: "res:octicons",
    name: "Octicons",
    category: "icons",
    description: "GitHub 官方界面使用的开源图标集，含 16px 与 24px 两套尺寸。",
    recommendedReason: "开发者工具场景下的 Git、分支、PR 与终端语义图标最齐全，直接复用省去自绘成本。",
    author: "GitHub (Primer)",
    tags: ["GitHub官方", "开发工具语义", "双尺寸", "开源"],
    actionType: "github",
    repository: "https://github.com/primer/octicons",
    homepage: "https://primer.style/octicons",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:solar-icons",
    name: "Solar Icon Set",
    category: "icons",
    description: "包含 7000 余枚图标、每枚提供线性与粗体填充等六种风格变体的超大型图标集。",
    recommendedReason: "同一图标的多风格变体是设计探索与状态切换（默认/激活）的现成素材。",
    author: "480 Design",
    tags: ["7000+图标", "六种风格", "状态切换", "设计探索"],
    actionType: "github",
    repository: "https://github.com/480-Design/Solar-Icon-Set",
    homepage: "https://solar-icons.vercel.app",
    license: "CC BY 4.0",
  },
  {
    id: "res:css-gg",
    name: "css.gg",
    category: "icons",
    description: "纯 CSS 与 SVG 双形态、统一 24px 网格的开源迷你图标库。",
    recommendedReason: "图标可用伪元素纯 CSS 绘制，无需引入任何图标文件即可实现零请求加载。",
    author: "Astrit",
    tags: ["纯CSS图标", "零请求", "24px网格", "轻量"],
    actionType: "github",
    repository: "https://github.com/astrit/css.gg",
    homepage: "https://css.gg",
    stars: "9k+",
    license: "MIT",
  },
  {
    id: "res:unicons",
    name: "Unicons",
    category: "icons",
    description: "Iconscout 维护的跨框架开源线性、单色与多色三套风格图标库。",
    recommendedReason: "提供多色版本图标，做插画风界面时不必再手工给图标上色。",
    author: "Iconscout",
    tags: ["多色图标", "跨框架", "三套风格", "插画感"],
    actionType: "github",
    repository: "https://github.com/Iconscout/unicons",
    homepage: "https://iconscout.com/unicons",
    stars: "1k+",
    license: "Apache-2.0",
  },
  {
    id: "res:iconbuddy",
    name: "Iconbuddy",
    category: "icons",
    description: "聚合 20 万余枚开源图标并支持一键改色、调整粗细与复制格式的在线图标搜索平台。",
    recommendedReason: "在同一个搜索框里比较多个图标集对同一语义的处理，是快速定风格的高效入口。",
    author: "Iconbuddy",
    tags: ["图标聚合搜索", "在线改色", "多格式导出", "选型对比"],
    actionType: "external",
    homepage: "https://iconbuddy.com",
  },
  {
    id: "res:streamline",
    name: "Streamline",
    category: "icons",
    description: "提供数十万枚高一致性图标、插画与 Emoji 的商用设计资源平台。",
    recommendedReason: "同一套视觉体系同时覆盖图标与插画，做品牌级界面时能保证风格完全统一。",
    author: "Streamline",
    tags: ["图标插画一体", "海量资源", "风格统一", "商用授权"],
    actionType: "external",
    homepage: "https://www.streamlinehq.com",
  },
  {
    id: "res:icons8",
    name: "Icons8",
    category: "icons",
    description: "提供图标、插画、照片与音效的大型设计素材库，含多种风格图标包。",
    recommendedReason: "风格包粒度细（如手绘、拟物、彩色描边），做非标准界面的视觉主题时素材最全。",
    author: "Icons8",
    tags: ["设计素材库", "风格包丰富", "插画音效", "商用"],
    actionType: "external",
    homepage: "https://icons8.com",
  },
];

