import type { ResourceItem } from "../types";

export const iconResources: ResourceItem[] = [
  {
    id: "res:lucide-icons",
    name: "Lucide Icons",
    category: "icons",
    description: "社区驱动、风格极致统一且支持所有现代框架的 1400+ 开源矢量图标库。",
    recommendedReason: "当今现代前端事实标准，基于 Feather 深度重构，笔触粗细可控，无缝契合各风格。",
    author: "Lucide Project",
    tags: ["现代标准", "一致性", "全框架支持", "可控笔触"],
    actionType: "github",
    repository: "https://github.com/lucide-icons/lucide",
    homepage: "https://lucide.dev",
    stars: "18k+",
    license: "ISC",
    featured: true,
  },
  {
    id: "res:tabler-icons",
    name: "Tabler Icons",
    category: "icons",
    description: "超过 5200+ 个像素对齐的免费高质量 SVG 图标套件，涵盖你能想象的所有分类。",
    recommendedReason: "体量庞大，分类极其细致，无论是工业仪器、数学公式还是日常操作均有覆盖。",
    author: "Paweł Kuna",
    tags: ["海量图标", "像素对齐", "工业覆盖", "高自由度"],
    actionType: "github",
    repository: "https://github.com/tabler/tabler-icons",
    homepage: "https://tabler.io/icons",
    stars: "17k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:phosphor-icons",
    name: "Phosphor Icons",
    category: "icons",
    description: "灵活且极具辨识度的开源图标家族，原生提供 6 种不同粗细与填充形态变体。",
    recommendedReason: "Thin, Light, Regular, Bold, Fill, Duotone 六档粗细无缝切换，适配任何设计系统。",
    author: "Helena Zhang & Tobias Fried",
    tags: ["6种形态", "双色调Duotone", "极简灵活", "设计系统好伴侣"],
    actionType: "github",
    repository: "https://github.com/phosphor-icons/core",
    homepage: "https://phosphoricons.com",
    stars: "8k+",
    license: "MIT",
  },
  {
    id: "res:heroicons",
    name: "Heroicons",
    category: "icons",
    description: "Tailwind CSS 官方团队纯手工打磨的精美开源 SVG 图标套件。",
    recommendedReason: "专为搭配 Tailwind 24px/20px/16px 视口量身定制，轮廓平衡感极佳。",
    author: "Tailwind Labs",
    tags: ["Tailwind官方", "手工打磨", "微尺寸优化", "精致小巧"],
    actionType: "github",
    repository: "https://github.com/tailwindlabs/heroicons",
    homepage: "https://heroicons.com",
    stars: "20k+",
    license: "MIT",
  },
  {
    id: "res:simple-icons",
    name: "Simple Icons",
    category: "icons",
    description: "收录 3100+ 个知名品牌、编程语言、开源软件与开发工具的官方正版矢量 Logo。",
    recommendedReason: "展示技术栈、软件徽标、集成连接器时必备的官方标准 Logo 权威来源。",
    author: "Simple Icons Contributors",
    tags: ["品牌Logo", "官方徽标", "技术栈图标", "SVG集合"],
    actionType: "github",
    repository: "https://github.com/simple-icons/simple-icons",
    homepage: "https://simpleicons.org",
    stars: "20k+",
    license: "CC0-1.0",
    featured: true,
  },
  {
    id: "res:iconoir",
    name: "Iconoir",
    category: "icons",
    description: "1500+ 个完全开源、零外部依赖且支持 CSS/SVG/React/Vue 的极简纤细线条图标。",
    recommendedReason: "无多余杂饰，极度适合追求克制工业风与极简编辑排版风格的软件系统。",
    author: "Luca Burgio",
    tags: ["纤细线条", "零依赖", "极简主义", "高通用性"],
    actionType: "github",
    repository: "https://github.com/iconoir-icons/iconoir",
    homepage: "https://iconoir.com",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:remix-icon",
    name: "Remix Icon",
    category: "icons",
    description: "精心设计且中立开阔的开源图标库，每一个图标都拥有线性与面性两种风格。",
    recommendedReason: "亚洲及全球中文开发者极其常用，中文语义化搜索体验极佳。",
    author: "Remix Design",
    tags: ["线面双版", "中文友好", "开阔中立", "日常办公"],
    actionType: "github",
    repository: "https://github.com/Remix-Design/RemixIcon",
    homepage: "https://remixicon.com",
    stars: "11k+",
    license: "Apache-2.0",
  },
  {
    id: "res:hugeicons",
    name: "Hugeicons",
    category: "icons",
    description: "超过 4000+ 免费图标，提供 5 种不同设计笔触，专为现代产品与设计稿打造。",
    recommendedReason: "笔触饱满圆润，极适合现代移动端与现代消费级工具软件的活泼界面。",
    author: "Hugeicons",
    tags: ["5种笔触", "现代圆润", "高质感", "消费级体验"],
    actionType: "external",
    homepage: "https://hugeicons.com",
  },
  {
    id: "res:svgl",
    name: "svgl",
    category: "icons",
    description: "超高质量、精美统一的现代科技公司与开源项目高精度 SVG Logo 资源库。",
    recommendedReason: "React 组件与直链 SVG 开箱即用，是搭建技术栈墙、集成目录与合作方展示的利器。",
    author: "Pheralb",
    tags: ["Logo库", "科技品牌", "高精度SVG", "开发者标配"],
    actionType: "github",
    repository: "https://github.com/pheralb/svgl",
    homepage: "https://svgl.app",
    stars: "7k+",
    license: "MIT",
    featured: true,
  },
];

