import type { ResourceItem } from "../types";

export const learningResources: ResourceItem[] = [
  {
    id: "res:developer-roadmap",
    name: "Developer Roadmaps",
    category: "learning",
    description: "全面、细致且社区共同维护的前端、后端、DevOps、AI 与计算机领域全景技能树。",
    recommendedReason: "迷茫时打开，清晰了解掌握某技术栈需要补足的上下游核心知识节点。",
    author: "Kamran Ahmed & Community",
    tags: ["技能树", "学习路径", "职业进阶", "计算机全景"],
    actionType: "github",
    repository: "https://github.com/kamranahmedse/developer-roadmap",
    homepage: "https://roadmap.sh",
    stars: "305k+",
    license: "CC-BY-NC-SA-4.0",
    featured: true,
  },
  {
    id: "res:system-design-primer",
    name: "System Design Primer",
    category: "learning",
    description: "学习如何设计大规模、高并发、高可用与高可扩展系统的经典开创性架构指南。",
    recommendedReason: "深入浅出拆解缓存策略、负载均衡、分库分表、微服务异步通信等分布式核心命题。",
    author: "Donne Martin",
    tags: ["系统设计", "高并发", "分布式架构", "架构师必读"],
    actionType: "github",
    repository: "https://github.com/donnemartin/system-design-primer",
    stars: "288k+",
    license: "CC-BY-SA-4.0",
    featured: true,
  },
  {
    id: "res:missing-semester",
    name: "The Missing Semester of Your CS Education",
    category: "learning",
    description: "MIT 计算机系知名公开课：大学课程中往往忽略但至关重要的命令行与工具链实战课程。",
    recommendedReason: "掌握 Shell 脚本、Vim 高效编辑、Git 数据模型与命令行调试器，事半功倍。",
    author: "MIT (Anish, Jon, Jose)",
    tags: ["MIT公开课", "工具链哲学", "命令行精进", "终身受用"],
    actionType: "external",
    homepage: "https://missing.csail.mit.edu",
    featured: true,
  },
  {
    id: "res:patterns-dev",
    name: "Patterns.dev",
    category: "learning",
    description: "关于使用现代 Web 技术构建高性能、弹性和可维护应用的免费设计模式电子书。",
    recommendedReason: "系统讲解渲染模式（SSR/SSG/ISR）、组件设计模式与前端代码拆分优化哲学。",
    author: "Lydia Hallie & Addy Osmani",
    tags: ["设计模式", "架构思维", "性能优化", "Web技术"],
    actionType: "external",
    homepage: "https://www.patterns.dev",
    featured: true,
  },
  {
    id: "res:rust-by-example",
    name: "Rust By Example",
    category: "learning",
    description: "通过丰富精炼、可直接在浏览器运行编辑的简明代码实例学习 Rust 核心语言概念。",
    recommendedReason: "避开长篇抽象理论，在边改代码边跑编译报错中快速建立所有权、生命周期与特征肌肉记忆。",
    author: "Rust Community",
    tags: ["Rust实战", "交互示例", "官方教程", "零痛苦上手"],
    actionType: "external",
    homepage: "https://doc.rust-lang.org/rust-by-example",
  },
  {
    id: "res:cs-video-courses",
    name: "CS Video Courses",
    category: "learning",
    description: "整理 MIT、CMU、Stanford、UC Berkeley 等全球世界名校公开计算机视频与讲义目录。",
    recommendedReason: "操作系统（CS162）、计算机体系结构（CS61C）、分布式系统（6.824）精品课程汇总导航。",
    author: "Developer Community",
    tags: ["名校公开课", "计算机基础", "操作系统", "分布式系统"],
    actionType: "github",
    repository: "https://github.com/Developer-Y/cs-video-courses",
    stars: "66k+",
    license: "MIT",
  },
  {
    id: "res:clean-code-javascript",
    name: "Clean Code JavaScript",
    category: "learning",
    description: "将 Robert C. Martin《代码整洁之道》工程原则深度适配到现代 JavaScript 的实践手册。",
    recommendedReason: "学习如何写出可读性极高、无副作用、命名精准且利于团队长线维护的优质工程代码。",
    author: "Ryan McDermott",
    tags: ["整洁代码", "可维护性", "重构哲学", "代码异味消除"],
    actionType: "github",
    repository: "https://github.com/ryanmcdermott/clean-code-javascript",
    stars: "91k+",
    license: "MIT",
  },
  {
    id: "res:freecodecamp",
    name: "freeCodeCamp",
    category: "learning",
    description: "完全免费且全球规模最大的开源互动式全栈编程学习社区与项目实践平台。",
    recommendedReason: "从零基础到独立做出真实商业级 Web 应用程序，包含成千上万道阶梯式编码闯关题。",
    author: "freeCodeCamp.org",
    tags: ["交互闯关", "全栈实战", "零基础友好", "完全免费"],
    actionType: "github",
    repository: "https://github.com/freeCodeCamp/freeCodeCamp",
    homepage: "https://www.freecodecamp.org",
    stars: "408k+",
    license: "BSD-3-Clause",
  },
];
