import type { ResourceItem } from "../types";

export const learningResources: ResourceItem[] = [
  {
    id: "res:developer-roadmap",
    name: "Developer Roadmaps",
    category: "learning",
    description: "全面、细致且社区共同维护的前端、后端、DevOps、AI 与计算机领域全景技能树。",
    recommendedReason: "迷茫时打开，清晰了解掌握某技术栈需要补足的上下游核心知识节点。",
    author: "Kamran Ahmed & Community",
    tags: ["技能树", "学习路径", "职业进阶", "计算机全景"],
    actionType: "github",
    repository: "https://github.com/kamranahmedse/developer-roadmap",
    homepage: "https://roadmap.sh",
    stars: "305k+",
    license: "CC-BY-NC-SA-4.0",
    featured: true,
  },
  {
    id: "res:system-design-primer",
    name: "System Design Primer",
    category: "learning",
    description: "学习如何设计大规模、高并发、高可用与高可扩展系统的经典开创性架构指南。",
    recommendedReason: "深入浅出拆解缓存策略、负载均衡、分库分表、微服务异步通信等分布式核心命题。",
    author: "Donne Martin",
    tags: ["系统设计", "高并发", "分布式架构", "架构师必读"],
    actionType: "github",
    repository: "https://github.com/donnemartin/system-design-primer",
    stars: "288k+",
    license: "CC-BY-SA-4.0",
    featured: true,
  },
  {
    id: "res:missing-semester",
    name: "The Missing Semester of Your CS Education",
    category: "learning",
    description: "MIT 计算机系知名公开课：大学课程中往往忽略但至关重要的命令行与工具链实战课程。",
    recommendedReason: "掌握 Shell 脚本、Vim 高效编辑、Git 数据模型与命令行调试器，事半功倍。",
    author: "MIT (Anish, Jon, Jose)",
    tags: ["MIT公开课", "工具链哲学", "命令行精进", "终身受用"],
    actionType: "external",
    homepage: "https://missing.csail.mit.edu",
    featured: true,
  },
  {
    id: "res:patterns-dev",
    name: "Patterns.dev",
    category: "learning",
    description: "关于使用现代 Web 技术构建高性能、弹性和可维护应用的免费设计模式电子书。",
    recommendedReason: "系统讲解渲染模式（SSR/SSG/ISR）、组件设计模式与前端代码拆分优化哲学。",
    author: "Lydia Hallie & Addy Osmani",
    tags: ["设计模式", "架构思维", "性能优化", "Web技术"],
    actionType: "external",
    homepage: "https://www.patterns.dev",
    featured: true,
  },
  {
    id: "res:rust-by-example",
    name: "Rust By Example",
    category: "learning",
    description: "通过丰富精炼、可直接在浏览器运行编辑的简明代码实例学习 Rust 核心语言概念。",
    recommendedReason: "避开长篇抽象理论，在边改代码边跑编译报错中快速建立所有权、生命周期与特征肌肉记忆。",
    author: "Rust Community",
    tags: ["Rust实战", "交互示例", "官方教程", "零痛苦上手"],
    actionType: "external",
    homepage: "https://doc.rust-lang.org/rust-by-example",
  },
  {
    id: "res:cs-video-courses",
    name: "CS Video Courses",
    category: "learning",
    description: "整理 MIT、CMU、Stanford、UC Berkeley 等全球世界名校公开计算机视频与讲义目录。",
    recommendedReason: "操作系统（CS162）、计算机体系结构（CS61C）、分布式系统（6.824）精品课程汇总导航。",
    author: "Developer Community",
    tags: ["名校公开课", "计算机基础", "操作系统", "分布式系统"],
    actionType: "github",
    repository: "https://github.com/Developer-Y/cs-video-courses",
    stars: "66k+",
    license: "MIT",
  },
  {
    id: "res:clean-code-javascript",
    name: "Clean Code JavaScript",
    category: "learning",
    description: "将 Robert C. Martin《代码整洁之道》工程原则深度适配到现代 JavaScript 的实践手册。",
    recommendedReason: "学习如何写出可读性极高、无副作用、命名精准且利于团队长线维护的优质工程代码。",
    author: "Ryan McDermott",
    tags: ["整洁代码", "可维护性", "重构哲学", "代码异味消除"],
    actionType: "github",
    repository: "https://github.com/ryanmcdermott/clean-code-javascript",
    stars: "91k+",
    license: "MIT",
  },
  {
    id: "res:freecodecamp",
    name: "freeCodeCamp",
    category: "learning",
    description: "完全免费且全球规模最大的开源互动式全栈编程学习社区与项目实践平台。",
    recommendedReason: "从零基础到独立做出真实商业级 Web 应用程序，包含成千上万道阶梯式编码闯关题。",
    author: "freeCodeCamp.org",
    tags: ["交互闯关", "全栈实战", "零基础友好", "完全免费"],
    actionType: "github",
    repository: "https://github.com/freeCodeCamp/freeCodeCamp",
    homepage: "https://www.freecodecamp.org",
    stars: "408k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:cs-notes",
    name: "CS-Notes",
    category: "learning",
    description: "技术面试必备基础知识、LeetCode 题解、计算机网络、操作系统与系统设计全景提炼。",
    recommendedReason: "中文技术社区知名度与整理深度极高的计算机核心知识体系开源笔记。",
    author: "CyC2018",
    tags: ["技术面试", "计算机基础", "LeetCode", "中文必读"],
    actionType: "github",
    repository: "https://github.com/CyC2018/CS-Notes",
    homepage: "http://www.cyc2018.xyz",
    stars: "172k+",
    license: "CC-BY-NC-SA-4.0",
    featured: true,
  },
  {
    id: "res:visualizing-git",
    name: "Visualizing Git",
    category: "learning",
    description: "在交互式动态拓扑图中直观观察 Git commit、branch、checkout、rebase 的生动演化过程。",
    recommendedReason: "告别抽象晦涩的命令行黑盒，用最直观的可视化图解彻底吃透 Git 底层 DAG 数据结构。",
    author: "GitKraken / Jason Long",
    tags: ["Git可视化", "交互教学", "图解DAG", "新手利器"],
    actionType: "external",
    homepage: "https://git-school.github.io/visualizing-git",
    featured: true,
  },
  {
    id: "res:full-stack-open",
    name: "Full Stack Open",
    category: "learning",
    description: "芬兰赫尔辛基大学享誉全球的现代 Web 全栈深度开源课程，涵盖 React、Node、GraphQL、CI/CD 与容器。",
    recommendedReason: "大学顶尖教研团队持续按当年最新规范重构课程，代码严谨规范度极高。",
    author: "University of Helsinki",
    tags: ["名校课程", "现代全栈", "React深度", "免费认证"],
    actionType: "external",
    homepage: "https://fullstackopen.com/zh",
    featured: true,
  },
  {
    id: "res:ossu-computer-science",
    name: "Open Source Society University",
    category: "learning",
    description: "完全使用免费公开课拼装出的一套等效于四年制计算机科学本科学位的完整自学课程表。",
    recommendedReason: "按学期划分先修关系，明确告诉你什么时候学离散数学、什么时候才能碰操作系统。",
    author: "OSSU Community",
    tags: ["计算机本科", "课程表", "自学路径", "免费学位"],
    actionType: "github",
    repository: "https://github.com/ossu/computer-science",
    homepage: "https://cs.ossu.dev",
    stars: "185k+",
    license: "MIT",
  },
  {
    id: "res:teach-yourself-cs",
    name: "Teach Yourself Computer Science",
    category: "learning",
    description: "用九门核心课程与指定教材回答「自学计算机到底该学什么、按什么顺序学」的浓缩答案。",
    recommendedReason: "每个方向只推荐一到两本最佳教材并说明取舍理由，避免在资料海洋里反复横跳。",
    author: "Oz Nova & Myles Byrne",
    tags: ["自学指南", "教材推荐", "计算机基础", "精简路线"],
    actionType: "external",
    homepage: "https://teachyourselfcs.com",
  },
  {
    id: "res:cs50",
    name: "CS50: Introduction to Computer Science",
    category: "learning",
    description: "哈佛大学全校最受欢迎的通识编程入门课，从 C 语言内存模型一路讲到 Python 与 SQL。",
    recommendedReason: "问题集设计极富挑战且配套自动判题环境，是极少能真正锤炼计算思维的入门课。",
    author: "Harvard University (David J. Malan)",
    tags: ["哈佛公开课", "编程入门", "C语言", "算法思维"],
    actionType: "external",
    homepage: "https://cs50.harvard.edu/x",
  },
  {
    id: "res:nand2tetris",
    name: "Nand2Tetris",
    category: "learning",
    description: "从单个与非门出发，逐层构建出 ALU、CPU、汇编器、虚拟机、编译器和操作系统。",
    recommendedReason: "唯一一门能让你在一次课程内亲手把「硬件如何一路支撑起高级语言」彻底打通的项目课。",
    author: "Noam Nisan & Shimon Schocken",
    tags: ["计算机体系结构", "从零造计算机", "编译器", "项目驱动"],
    actionType: "external",
    homepage: "https://www.nand2tetris.org",
  },
  {
    id: "res:crafting-interpreters",
    name: "Crafting Interpreters",
    category: "learning",
    description: "用 Java 与 C 两种语言各写一遍完整解释器，讲透词法扫描、解析、字节码虚拟机与垃圾回收。",
    recommendedReason: "全书在线免费且每章末尾都能跑通真实代码，是编译器方向最能落地的自学路径。",
    author: "Robert Nystrom",
    tags: ["编译器", "解释器", "虚拟机", "在线免费书"],
    actionType: "github",
    repository: "https://github.com/munificent/craftinginterpreters",
    homepage: "https://craftinginterpreters.com",
    stars: "9k+",
  },
  {
    id: "res:csapp-labs",
    name: "Computer Systems: A Programmer's Perspective",
    category: "learning",
    description: "CMU 经典教材《深入理解计算机系统》及其 Data Lab、Bomb Lab、Malloc Lab 等九个硬核实验。",
    recommendedReason: "通过手写位运算、拆二进制炸弹、实现内存分配器，把机器级表示与虚拟内存真正刻进直觉。",
    author: "Randal E. Bryant & David R. O'Hallaron",
    tags: ["深入理解计算机系统", "机器级表示", "虚拟内存", "CMU实验"],
    actionType: "external",
    homepage: "https://csapp.cs.cmu.edu",
  },
  {
    id: "res:ostep",
    name: "Operating Systems: Three Easy Pieces",
    category: "learning",
    description: "以虚拟化、并发、持久化三条主线串起操作系统的免费在线教材与配套作业代码。",
    recommendedReason: "语言幽默、章节短小，配合课后模拟器作业能把调度、锁与文件系统真正跑一遍。",
    author: "Remzi & Andrea Arpaci-Dusseau",
    tags: ["操作系统", "并发编程", "文件系统", "免费教材"],
    actionType: "external",
    homepage: "https://pages.cs.wisc.edu/~remzi/OSTEP",
  },
  {
    id: "res:mit-6-824",
    name: "MIT 6.824 Distributed Systems",
    category: "learning",
    description: "MIT 分布式系统研究生课程，通过 Raft、KV 服务与分片实验理解共识与容错。",
    recommendedReason: "实验要求用 Go 从零实现 Raft 并通过严苛的随机故障测试，是分布式入门最硬的一次实战。",
    author: "MIT PDOS (Robert Morris)",
    tags: ["分布式系统", "Raft共识", "Go语言", "硬核实验"],
    actionType: "external",
    homepage: "https://pdos.csail.mit.edu/6.824",
  },
  {
    id: "res:cmu-15-445",
    name: "CMU 15-445 Database Systems",
    category: "learning",
    description: "CMU 数据库系统课程，从缓冲池管理器开始逐周实现一个支持并发与恢复的存储引擎。",
    recommendedReason: "把 B+ 树、哈希索引、查询执行与日志恢复从课本概念变成可运行且可压测的真实代码。",
    author: "CMU (Andy Pavlo)",
    tags: ["数据库内核", "B+树", "查询执行", "存储引擎"],
    actionType: "external",
    homepage: "https://15445.courses.cs.cmu.edu",
  },
  {
    id: "res:database-internals",
    name: "Database Internals",
    category: "learning",
    description: "深入剖析 B 树与 LSM 树、页缓存、写放大、复制与共识协议的现代数据库内核专著。",
    recommendedReason: "补齐「会用数据库」到「能设计存储引擎」之间最关键的分页与日志结构存储认知。",
    author: "Alex Petrov",
    tags: ["数据库原理", "LSM树", "存储引擎", "分布式一致性"],
    actionType: "external",
    homepage: "https://www.databass.dev",
  },
  {
    id: "res:ddia",
    name: "Designing Data-Intensive Applications",
    category: "learning",
    description: "被业界称为「数据系统圣经」的专著，系统讲解复制、分区、事务、一致性与流批处理。",
    recommendedReason: "读完能准确判断何时该用 Kafka、何时该上分布式事务，以及每一种取舍背后真实的代价。",
    author: "Martin Kleppmann",
    tags: ["数据密集型应用", "分布式事务", "流处理", "架构圣经"],
    actionType: "external",
    homepage: "https://dataintensive.net",
  },
  {
    id: "res:sqlbolt",
    name: "SQLBolt",
    category: "learning",
    description: "在浏览器中边写边跑交互式练习学习 SQL 的极简教程，从 SELECT 到 JOIN 与聚合逐步推进。",
    recommendedReason: "零安装、零配置，二十分钟内就能获得第一次真实查询结果的正反馈。",
    author: "SQLBolt",
    tags: ["SQL入门", "交互练习", "零配置", "查询语言"],
    actionType: "external",
    homepage: "https://sqlbolt.com",
  },
  {
    id: "res:postgresql-tutorial",
    name: "PostgreSQL Tutorial",
    category: "learning",
    description: "覆盖 PostgreSQL 基础查询、连接、索引、窗口函数、触发器与性能调优的完整实操教程站。",
    recommendedReason: "示例数据库随站附带，每个语法点都有可直接复制的建表与查询语句。",
    author: "PostgreSQL Tutorial",
    tags: ["PostgreSQL", "窗口函数", "索引优化", "实战示例"],
    actionType: "external",
    homepage: "https://www.postgresqltutorial.com",
  },
  {
    id: "res:pro-git",
    name: "Pro Git Book",
    category: "learning",
    description: "Git 官方文档站上免费开源的权威 Git 教程书，从基础提交一路讲到内部对象与自定义服务端。",
    recommendedReason: "由 Git 维护者团队审校，是厘清 rebase、reset、cherry-pick 语义差异最可靠的参考。",
    author: "Scott Chacon & Ben Straub",
    tags: ["Git权威", "免费电子书", "分支模型", "版本控制"],
    actionType: "external",
    homepage: "https://git-scm.com/book/zh/v2",
  },
  {
    id: "res:git-internals-pdf",
    name: "Git Internals (PDF)",
    category: "learning",
    description: "Scott Chacon 撰写的 Git 内部原理 PDF，用真实对象图讲清 blob、tree、commit 与引用。",
    recommendedReason: "读完后 .git 目录不再是黑盒，任何「诡异」的 Git 状态你都能自行推理出原因。",
    author: "Scott Chacon / Pluralsight",
    tags: ["Git内部原理", "对象模型", "PDF手册", "底层机制"],
    actionType: "github",
    repository: "https://github.com/pluralsight/git-internals-pdf",
    stars: "2k+",
  },
  {
    id: "res:linux-journey",
    name: "Linux Journey",
    category: "learning",
    description: "从命令行基础、文件权限到包管理、进程管理与网络的分级式 Linux 交互学习网站。",
    recommendedReason: "内容按新手到进阶分阶编排，每节都短小精悍，适合每天通勤时推进一小节。",
    author: "LabEx / Linux Journey",
    tags: ["Linux入门", "分级课程", "命令行", "系统管理"],
    actionType: "external",
    homepage: "https://linuxjourney.com",
  },
  {
    id: "res:the-linux-command-line",
    name: "The Linux Command Line",
    category: "learning",
    description: "William Shotts 编写的免费完整 Linux 命令行教材，覆盖重定向、管道、Shell 脚本与正则。",
    recommendedReason: "把管道与文本流处理讲成一套组合思维方式，而不是零散命令的记忆清单。",
    author: "William Shotts",
    tags: ["命令行", "Shell脚本", "免费教材", "文本处理"],
    actionType: "external",
    homepage: "https://linuxcommand.org/tlcl.php",
  },
  {
    id: "res:docker-curriculum",
    name: "Docker Curriculum",
    category: "learning",
    description: "面向零基础开发者的 Docker 实战教程，从第一个容器一路构建到多容器 Compose 应用。",
    recommendedReason: "以真实项目推进教学，学完即可独立把本地应用容器化并发布镜像。",
    author: "Prakhar Srivastava",
    tags: ["Docker入门", "容器化", "Compose编排", "项目实战"],
    actionType: "github",
    repository: "https://github.com/prakhar1989/docker-curriculum",
    homepage: "https://docker-curriculum.com",
    stars: "6k+",
    license: "MIT",
  },
  {
    id: "res:kubernetes-the-hard-way",
    name: "Kubernetes The Hard Way",
    category: "learning",
    description: "Kelsey Hightower 撰写的教程，不使用任何一键脚本，手工逐证书搭建一个 Kubernetes 集群。",
    recommendedReason: "亲手配齐证书、etcd、控制平面与 kubelet 之后，K8s 的报错信息将不再是天书。",
    author: "Kelsey Hightower",
    tags: ["Kubernetes", "集群搭建", "手工配置", "云原生"],
    actionType: "github",
    repository: "https://github.com/kelseyhightower/kubernetes-the-hard-way",
    stars: "43k+",
    license: "Apache-2.0",
  },
  {
    id: "res:rust-book",
    name: "The Rust Programming Language",
    category: "learning",
    description: "Rust 官方权威教材（俗称 The Book），系统讲解所有权、生命周期、Trait 与并发安全。",
    recommendedReason: "唯一由语言团队维护并随版本持续更新的第一手学习路径，避开大量过时二手教程。",
    author: "Steve Klabnik, Carol Nichols & Rust Team",
    tags: ["Rust官方", "所有权模型", "Trait泛型", "并发安全"],
    actionType: "github",
    repository: "https://github.com/rust-lang/book",
    homepage: "https://doc.rust-lang.org/book",
    stars: "16k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:rustlings",
    name: "Rustlings",
    category: "learning",
    description: "由官方维护的数百道小型 Rust 练习题，全部以「让编译报错消失」的方式驱动学习。",
    recommendedReason: "每道题都配有精准提示，是读完 The Book 后巩固语法最快见效的练习集。",
    author: "Rust Community",
    tags: ["Rust练习", "编译驱动学习", "官方题库", "巩固语法"],
    actionType: "github",
    repository: "https://github.com/rust-lang/rustlings",
    stars: "56k+",
    license: "MIT",
  },
  {
    id: "res:comprehensive-rust",
    name: "Comprehensive Rust",
    category: "learning",
    description: "Google 内部用于工程师 Rust 培训的四天课程教材，涵盖基础语法到异步、并发与 unsafe。",
    recommendedReason: "每个知识点都有讲师笔记与学生练习，特别适合有 C++/Java 背景的工程师快速迁移。",
    author: "Google Android Team",
    tags: ["Google出品", "四天课程", "Rust进阶", "异步并发"],
    actionType: "github",
    repository: "https://github.com/google/comprehensive-rust",
    homepage: "https://google.github.io/comprehensive-rust",
    stars: "30k+",
    license: "Apache-2.0",
  },
  {
    id: "res:too-many-linked-lists",
    name: "Learn Rust With Entirely Too Many Linked Lists",
    category: "learning",
    description: "通过实现六种不同复杂度的链表，把 Rust 中 Rc、RefCell、Box 与 unsafe 的边界讲透。",
    recommendedReason: "数据结构是检验所有权理解程度最好的试纸，这本书会精准暴露你的每一个认知漏洞。",
    author: "Aria Beingessner",
    tags: ["Rust进阶", "智能指针", "unsafe边界", "数据结构"],
    actionType: "github",
    repository: "https://github.com/rust-unofficial/too-many-lists",
    homepage: "https://rust-unofficial.github.io/too-many-lists",
    stars: "6k+",
  },
  {
    id: "res:beej-network-guide",
    name: "Beej's Guide to Network Programming",
    category: "learning",
    description: "用 C 语言 socket API 讲清 TCP/IP 编程的长青经典指南，覆盖地址转换、阻塞与多路复用。",
    recommendedReason: "语言轻松但对 getaddrinfo、select、poll 的讲解异常扎实，是网络编程最有效的入门读物。",
    author: "Brian 'Beej Jorgensen' Hall",
    tags: ["网络编程", "Socket API", "TCP/IP", "C语言"],
    actionType: "external",
    homepage: "https://beej.us/guide/bgnet",
  },
  {
    id: "res:beej-c-guide",
    name: "Beej's Guide to C Programming",
    category: "learning",
    description: "现代 C 语言入门指南，覆盖指针、结构体、动态内存、文件 IO 与多文件工程组织。",
    recommendedReason: "比传统教材更早引入多文件编译与调试实践，学完能直接读懂真实开源 C 代码。",
    author: "Brian 'Beej Jorgensen' Hall",
    tags: ["C语言", "指针内存", "系统编程", "免费指南"],
    actionType: "external",
    homepage: "https://beej.us/guide/bgc",
  },
  {
    id: "res:learn-c-org",
    name: "Learn-C.org",
    category: "learning",
    description: "可在浏览器内直接编译运行 C 代码的交互式教学站，从 Hello World 覆盖到指针与递归。",
    recommendedReason: "免去本地配置 GCC 的门槛，用最短反馈环理解 C 的内存与指针语义。",
    author: "Learn-C.org",
    tags: ["C语言入门", "在线编译", "交互练习", "指针基础"],
    actionType: "external",
    homepage: "https://www.learn-c.org",
  },
  {
    id: "res:python-tutorial",
    name: "The Python Tutorial",
    category: "learning",
    description: "Python 官方教程，系统介绍语法、数据结构、模块、异常、类与标准库概览。",
    recommendedReason: "由语言文档团队维护，措辞精确无历史包袱，是所有第三方 Python 教程的最终校验基准。",
    author: "Python Software Foundation",
    tags: ["Python官方", "标准库", "语法基础", "权威文档"],
    actionType: "external",
    homepage: "https://docs.python.org/zh-cn/3/tutorial",
  },
  {
    id: "res:real-python",
    name: "Real Python",
    category: "learning",
    description: "面向工程实践的高质量 Python 教程站，覆盖虚拟环境、类型标注、测试、异步与打包发布。",
    recommendedReason: "内容以「能用到生产」为筛选标准，不讲玩具示例，很多文章直击真实项目痛点。",
    author: "Real Python Team",
    tags: ["Python实战", "工程实践", "异步编程", "打包发布"],
    actionType: "external",
    homepage: "https://realpython.com",
  },
  {
    id: "res:automate-boring-stuff",
    name: "Automate the Boring Stuff with Python",
    category: "learning",
    description: "Al Sweigart 编写的免费在线书，教你用 Python 处理 Excel、PDF、网页抓取与文件批处理。",
    recommendedReason: "最适合非计算机专业读者的第一本书，学完立刻能自动化掉日常重复劳动。",
    author: "Al Sweigart",
    tags: ["Python自动化", "办公效率", "零基础友好", "免费在线书"],
    actionType: "external",
    homepage: "https://automatetheboringstuff.com",
  },
  {
    id: "res:missing-readme",
    name: "The Missing README",
    category: "learning",
    description: "写给新晋软件工程师的「工程常识」手册，覆盖代码评审、依赖管理、测试、监控与事故处理。",
    recommendedReason: "学校与培训班都不教但每周工作都会用到的隐性规范，这本书一次性补齐。",
    author: "Chris Riccomini & Dmitriy Ryaboy",
    tags: ["工程常识", "职业成长", "代码评审", "生产运维"],
    actionType: "external",
    homepage: "https://missingreadme.com",
  },
  {
    id: "res:twelve-factor-app",
    name: "The Twelve-Factor App",
    category: "learning",
    description: "总结现代可移植云原生服务应遵循的十二条方法论：配置外置、无状态进程、日志事件流等。",
    recommendedReason: "部署踩坑时最常被引用的一份清单，能提前规避配置硬编码与状态耦合的架构债。",
    author: "Adam Wiggins / Heroku",
    tags: ["云原生", "十二要素", "部署规范", "可移植性"],
    actionType: "external",
    homepage: "https://12factor.net/zh_cn",
  },
  {
    id: "res:google-sre-book",
    name: "Google SRE Book",
    category: "learning",
    description: "Google 官方免费公开的站点可靠性工程专著，讲解 SLO、错误预算、容量规划与故障复盘。",
    recommendedReason: "把「运维」提升为可量化工程学科的关键文本，用错误预算替代拍脑袋的发布门禁。",
    author: "Google SRE Team",
    tags: ["SRE", "SLO错误预算", "可靠性工程", "免费公开"],
    actionType: "external",
    homepage: "https://sre.google/sre-book/table-of-contents",
  },
  {
    id: "res:refactoring-guru",
    name: "Refactoring.Guru",
    category: "learning",
    description: "用大量可视化图解讲解二十三种经典设计模式与代码坏味道重构手法的教学站。",
    recommendedReason: "每个模式都配真实重构前后对照，是「知道模式名字但不会用」这一困境的最优解药。",
    author: "Alexander Shvets",
    tags: ["设计模式", "重构手法", "图解教学", "代码坏味道"],
    actionType: "external",
    homepage: "https://refactoring.guru/zh",
  },
  {
    id: "res:a-philosophy-of-software-design",
    name: "A Philosophy of Software Design",
    category: "learning",
    description: "John Ousterhout 在斯坦福授课总结的软件设计哲学，核心议题是降低复杂性与信息隐藏。",
    recommendedReason: "篇幅极短却对「深模块」「注释即设计」等命题给出可操作判据，性价比极高。",
    author: "John Ousterhout",
    tags: ["软件设计", "复杂度治理", "深模块", "斯坦福课程"],
    actionType: "external",
    homepage: "https://web.stanford.edu/~ouster/cgi-bin/book.php",
  },
  {
    id: "res:deep-learning-book",
    name: "Deep Learning",
    category: "learning",
    description: "Goodfellow、Bengio、Courville 合著的花书，系统覆盖线性代数、反向传播、CNN、RNN 与正则化。",
    recommendedReason: "理论推导最完整的深度学习奠基教材，遇到「为什么这样设计损失函数」时最可靠的依据。",
    author: "Ian Goodfellow, Yoshua Bengio & Aaron Courville",
    tags: ["深度学习", "反向传播", "神经网络", "理论奠基"],
    actionType: "external",
    homepage: "https://www.deeplearningbook.org",
  },
  {
    id: "res:fastai-course",
    name: "Practical Deep Learning for Coders",
    category: "learning",
    description: "fast.ai 的实战深度学习课程与配套库，第一课就能训练出可用模型并部署为 Web 应用。",
    recommendedReason: "自上而下的教学顺序先给结果再补原理，极大降低从零到第一个作品的启动成本。",
    author: "Jeremy Howard & fast.ai",
    tags: ["深度学习实战", "自上而下教学", "模型部署", "免费课程"],
    actionType: "github",
    repository: "https://github.com/fastai/fastai",
    homepage: "https://course.fast.ai",
    stars: "27k+",
    license: "Apache-2.0",
  },
  {
    id: "res:nn-zero-to-hero",
    name: "Neural Networks: Zero to Hero",
    category: "learning",
    description: "Andrej Karpathy 的系列课程，从手写反向传播开始逐步实现到完整的 GPT 训练脚本。",
    recommendedReason: "全程代码驱动、无框架黑盒，是理解神经网络与 Transformer 内部最通透的一条路径。",
    author: "Andrej Karpathy",
    tags: ["从零实现", "反向传播", "Transformer", "视频课程"],
    actionType: "github",
    repository: "https://github.com/karpathy/nn-zero-to-hero",
    stars: "18k+",
    license: "MIT",
  },
  {
    id: "res:nanogpt",
    name: "nanoGPT",
    category: "learning",
    description: "约三百行核心代码的极简 GPT 训练与微调实现，附带莎士比亚与 GPT-2 复现脚本。",
    recommendedReason: "在单机即可复现训练过程，非常适合用来真正读懂大模型训练循环的每一行。",
    author: "Andrej Karpathy",
    tags: ["语言模型", "极简实现", "预训练微调", "可复现"],
    actionType: "github",
    repository: "https://github.com/karpathy/nanoGPT",
    stars: "40k+",
    license: "MIT",
  },
  {
    id: "res:llm-c",
    name: "llm.c",
    category: "learning",
    description: "用纯 C/CUDA 从零实现大模型训练的开源项目，不依赖 PyTorch 等框架。",
    recommendedReason: "同时打通「大模型怎么训练」与「CUDA 算子怎么写」，是系统与 AI 交叉方向难得的教材。",
    author: "Andrej Karpathy",
    tags: ["CUDA编程", "大模型训练", "纯C实现", "系统与AI交叉"],
    actionType: "github",
    repository: "https://github.com/karpathy/llm.c",
    stars: "26k+",
    license: "MIT",
  },
  {
    id: "res:huggingface-nlp-course",
    name: "Hugging Face NLP Course",
    category: "learning",
    description: "Hugging Face 官方课程，讲解 Transformers 库、Tokenizer、微调、数据集管道与模型分享。",
    recommendedReason: "直接围绕当前工业界最常用的模型生态讲解，学完即可独立完成模型微调与上线。",
    author: "Hugging Face",
    tags: ["Transformers", "模型微调", "官方课程", "NLP实战"],
    actionType: "external",
    homepage: "https://huggingface.co/learn/nlp-course",
  },
  {
    id: "res:llm-university",
    name: "LLM University",
    category: "learning",
    description: "Cohere 推出的免费大模型大学，覆盖文本生成、Embedding、RAG 检索与语义搜索原理。",
    recommendedReason: "对 RAG 的每个环节都配有可运行 Notebook，是理解检索增强生成架构最系统的路径。",
    author: "Cohere",
    tags: ["大语言模型", "RAG检索增强", "Embedding", "免费课程"],
    actionType: "external",
    homepage: "https://cohere.com/llmu",
  },
  {
    id: "res:prompt-engineering-guide",
    name: "Prompt Engineering Guide",
    category: "learning",
    description: "dair.ai 维护的提示工程指南，系统整理零样本、思维链、ReAct、自洽性等提示技术。",
    recommendedReason: "把散落各处的提示技巧归纳成可复用模式并附论文出处，是提示设计的参考手册。",
    author: "DAIR.AI",
    tags: ["提示工程", "思维链", "论文导读", "实战技巧"],
    actionType: "github",
    repository: "https://github.com/dair-ai/Prompt-Engineering-Guide",
    homepage: "https://www.promptingguide.ai/zh",
    stars: "60k+",
    license: "MIT",
  },
  {
    id: "res:llm-course",
    name: "LLM Course",
    category: "learning",
    description: "Maxime Labonne 整理的大模型学习路线，分为数学基础、模型构建与应用开发三条主线。",
    recommendedReason: "纯 Notebook 驱动，从分词器到 LoRA 微调与量化部署都有可直接运行的分步代码。",
    author: "Maxime Labonne",
    tags: ["大模型路线图", "LoRA微调", "模型量化", "Notebook实战"],
    actionType: "github",
    repository: "https://github.com/mlabonne/llm-course",
    stars: "50k+",
  },
  {
    id: "res:generative-ai-for-beginners",
    name: "Generative AI for Beginners",
    category: "learning",
    description: "微软推出的二十余节生成式 AI 入门课程，涵盖提示工程、RAG、Agent、微调与安全实践。",
    recommendedReason: "每节课都配代码示例与延伸阅读，是希望转做 AI 应用开发者的结构化起点。",
    author: "Microsoft",
    tags: ["生成式AI", "入门课程", "Agent开发", "微软出品"],
    actionType: "github",
    repository: "https://github.com/microsoft/generative-ai-for-beginners",
    stars: "80k+",
    license: "MIT",
  },
  {
    id: "res:cs231n",
    name: "Stanford CS231n",
    category: "learning",
    description: "斯坦福视觉识别卷积神经网络课程，讲解卷积、反向传播、训练技巧与视觉任务体系。",
    recommendedReason: "作业要求手写反向传播与批量归一化，是把「会调库」升级为「懂原理」的经典分水岭。",
    author: "Stanford University (Fei-Fei Li 等)",
    tags: ["计算机视觉", "卷积神经网络", "斯坦福课程", "手写反向传播"],
    actionType: "external",
    homepage: "https://cs231n.stanford.edu",
  },
  {
    id: "res:spinning-up",
    name: "Spinning Up in Deep RL",
    category: "learning",
    description: "OpenAI 推出的深度强化学习入门项目，含核心算法讲解、关键论文清单与可运行实现。",
    recommendedReason: "把 VPG、TRPO、PPO、DDPG 等算法的推导与代码放在一起对照，极大降低强化学习入门门槛。",
    author: "OpenAI",
    tags: ["强化学习", "PPO算法", "论文清单", "可运行实现"],
    actionType: "github",
    repository: "https://github.com/openai/spinningup",
    homepage: "https://spinningup.openai.com",
    stars: "10k+",
  },
  {
    id: "res:build-your-own-x",
    name: "Build Your Own X",
    category: "learning",
    description: "汇总从零构建数据库、编译器、操作系统、Git、Docker、神经网络等系统的分步教程清单。",
    recommendedReason: "把「造轮子」变成可检索的能力地图，任何底层方向都能在此找到第一份落地教程。",
    author: "CodeCrafters & Community",
    tags: ["造轮子", "底层原理", "教程合集", "系统编程"],
    actionType: "github",
    repository: "https://github.com/codecrafters-io/build-your-own-x",
    stars: "320k+",
    license: "CC0-1.0",
  },
  {
    id: "res:codecrafters",
    name: "CodeCrafters",
    category: "learning",
    description: "以「用任意语言实现 Redis、Git、Docker、SQLite」为形式的工程化编程挑战平台。",
    recommendedReason: "每个挑战都有真实测试套件与阶段目标，用工程交付的方式反推对协议与系统设计的理解。",
    author: "CodeCrafters",
    tags: ["工程挑战", "协议实现", "多语言支持", "测试驱动"],
    actionType: "external",
    homepage: "https://codecrafters.io",
  },
  {
    id: "res:exercism",
    name: "Exercism",
    category: "learning",
    description: "覆盖七十余种编程语言的免费练习平台，提供真实人类导师的代码评审反馈。",
    recommendedReason: "相比自动判题，导师评审能指出你代码里不易自察的惯用法与可读性问题。",
    author: "Exercism",
    tags: ["编程练习", "人工代码评审", "多语言", "完全免费"],
    actionType: "github",
    repository: "https://github.com/exercism/exercism",
    homepage: "https://exercism.org",
    stars: "7k+",
    license: "AGPL-3.0",
  },
  {
    id: "res:leetcode-patterns",
    name: "LeetCode Patterns",
    category: "learning",
    description: "按滑动窗口、双指针、单调栈等解题模式归类的 LeetCode 题单，附难度与公司标签。",
    recommendedReason: "用模式归类替代盲目刷题，两百题以内即可覆盖绝大多数面试高频考点。",
    author: "Sean Prashad",
    tags: ["算法刷题", "解题模式", "面试准备", "题单整理"],
    actionType: "github",
    repository: "https://github.com/SeanPrashad/leetcode-patterns",
    homepage: "https://seanprashad.com/leetcode-patterns",
    stars: "20k+",
  },
  {
    id: "res:neetcode",
    name: "NeetCode Roadmap",
    category: "learning",
    description: "按数据结构与算法类别编排的进阶路线图与配套视频讲解，从数组一路推到动态规划与图论。",
    recommendedReason: "每个知识点只保留足够量的代表性题目，避免在相似题上消耗过多时间。",
    author: "NeetCode (Navdeep Singh)",
    tags: ["算法路线图", "视频讲解", "面试刷题", "动态规划"],
    actionType: "external",
    homepage: "https://neetcode.io",
  },
  {
    id: "res:advent-of-code",
    name: "Advent of Code",
    category: "learning",
    description: "每年十二月发布二十五天的双阶段编程谜题，前段偏基础后段考察算法与数据结构综合运用。",
    recommendedReason: "题目自带真实输入的边界情况，用任意语言解答都能显著提升解析与建模能力。",
    author: "Eric Wastl",
    tags: ["编程谜题", "算法训练", "语言无关", "年度挑战"],
    actionType: "external",
    homepage: "https://adventofcode.com",
  },
  {
    id: "res:the-odin-project",
    name: "The Odin Project",
    category: "learning",
    description: "完全免费的开源全栈课程，以大量真实项目串联 Git、HTML/CSS、JavaScript、Node 与数据库。",
    recommendedReason: "以「做完即可写进作品集」为标准设计作业，学习成果可直接用于求职。",
    author: "The Odin Project",
    tags: ["全栈课程", "项目驱动", "开源免费", "作品集"],
    actionType: "github",
    repository: "https://github.com/TheOdinProject/theodinproject",
    homepage: "https://www.theodinproject.com",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:javascript-info",
    name: "The Modern JavaScript Tutorial",
    category: "learning",
    description: "从语言基础、闭包原型到 Promise、异步迭代器与模块系统的系统性 JavaScript 现代教程。",
    recommendedReason: "对事件循环、Promise 状态机等易混淆概念配有图解与可运行示例，深度远超普通博客。",
    author: "Ilya Kantor",
    tags: ["JavaScript", "事件循环", "异步编程", "系统性教程"],
    actionType: "external",
    homepage: "https://zh.javascript.info",
  },
];
