import type { ResourceItem } from "../types";

export const templateResources: ResourceItem[] = [
  {
    id: "res:create-t3-app",
    name: "Create T3 App",
    category: "templates",
    description: "以全栈端到端类型安全为核心的 Next.js + tRPC + Tailwind CSS + Prisma/Drizzle 脚手架。",
    recommendedReason: "前后端接口变更即时触发 TypeScript 静态编译报错，杜绝传统前后端联调接口隐患。",
    author: "Theo Browne & T3 OSS",
    tags: ["Next.js", "端到端类型安全", "tRPC", "现代化全栈"],
    actionType: "github",
    repository: "https://github.com/t3-oss/create-t3-app",
    homepage: "https://create.t3.gg",
    stars: "26k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:tauri-react-template",
    name: "Tauri + React + Vite Starter",
    category: "templates",
    description: "基于 Rust 宿主与 Vite + React 打造的跨平台原生极小体积桌面客户端模板。",
    recommendedReason: "打包体积仅数 MB、内存占用极低，同时享受完整 Web 生态热更新与 Rust 高性能系统级能力。",
    author: "Tauri Apps & Community",
    tags: ["Tauri", "Rust桌面端", "轻量极速", "跨平台"],
    actionType: "github",
    repository: "https://github.com/tauri-apps/tauri",
    homepage: "https://tauri.app",
    stars: "88k+",
    license: "MIT / Apache-2.0",
    featured: true,
  },
  {
    id: "res:electron-vite",
    name: "electron-vite",
    category: "templates",
    description: "下一代现代化、轻快且具备极速热重载的 Electron 开发构建脚手架工具。",
    recommendedReason: "解决传统 Webpack 构建 Electron 耗时漫长与主进程/渲染进程配置晦涩的痛点。",
    author: "Alex Wei",
    tags: ["Electron", "Vite构建", "秒级热重载", "多进程配置"],
    actionType: "github",
    repository: "https://github.com/alex8088/electron-vite",
    homepage: "https://electron-vite.org",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:shadcn-next-template",
    name: "Next.js + Shadcn Admin Template",
    category: "templates",
    description: "开箱即用、具备优雅深色模式与响应式布局的现代化中后台管理面板脚手架。",
    recommendedReason: "包含完善的侧边栏导航、表格分页、数据筛选与图表可视化，省去数周搭建时间。",
    author: "Satnaing (Shadcn Admin)",
    tags: ["管理后台", "Next.js", "Shadcn生态", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/satnaing/shadcn-admin",
    stars: "6k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:rust-cli-template",
    name: "Rust CLI Starter Kit",
    category: "templates",
    description: "整合了 clap 命令行参数解析、anyhow 错误处理与 tracing 日志的生产级 Rust CLI 模版。",
    recommendedReason: "初学者学习如何写出地道、符合工业级标准的 Rust 终端工具与二进制分发项目的最优范本。",
    author: "Rust CLI Working Group",
    tags: ["Rust CLI", "Clap参数解析", "工业级模版", "二进制分发"],
    actionType: "github",
    repository: "https://github.com/rust-cli/template",
    stars: "2k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:python-uv-starter",
    name: "Astral uv Python Starter",
    category: "templates",
    description: "基于 Astral uv（超快 Rust 重构 Python 包管理器）的现代化 Python 极简工程模板。",
    recommendedReason: "依赖解析与虚拟环境创建比传统 pip 快 10-100 倍，完全摒弃过时的 requirements.txt 杂乱管理。",
    author: "Astral Software",
    tags: ["Python工程", "Astral uv", "秒级虚拟环境", "现代包管理"],
    actionType: "github",
    repository: "https://github.com/astral-sh/uv",
    homepage: "https://docs.astral.sh/uv",
    stars: "47k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:turborepo-starter",
    name: "Turborepo Monorepo Starter",
    category: "templates",
    description: "针对 JavaScript 与 TypeScript 单体仓库（Monorepo）的高性能智能缓存构建模版。",
    recommendedReason: "多包共享公共 UI 组件、工具库与统一配置，远程缓存让 CI/CD 构建提速数倍。",
    author: "Vercel",
    tags: ["Monorepo", "智能缓存", "多包仓库", "Turborepo"],
    actionType: "github",
    repository: "https://github.com/vercel/turborepo",
    homepage: "https://turbo.build",
    stars: "27k+",
    license: "MIT",
  },
  {
    id: "res:vite-react-ts-tailwind",
    name: "Vite + React + TS + Tailwind Starter",
    category: "templates",
    description: "零多余冗余、预设最佳路径别名与 ESLint 规范的极简前端轻量快速起步模版。",
    recommendedReason: "快速验证创意或编写独立原型 demo 时，无需等待笨重安装，秒级启动。",
    author: "Vite Community",
    tags: ["极简模版", "秒级热更", "原型利器", "TypeScript"],
    actionType: "github",
    repository: "https://github.com/vitejs/vite",
    homepage: "https://vite.dev",
    stars: "72k+",
    license: "MIT",
  },
  {
    id: "res:hono-starter",
    name: "Hono Web Standards Starter",
    category: "templates",
    description: "超轻量、快如闪电的 Web 标准服务端微框架，可在 Node、Bun、Cloudflare 任意环境运行。",
    recommendedReason: "体积不足 20KB，零外部依赖，内置极速正则路由，构建现代 Edge API 与微服务首选。",
    author: "Yusuke Wada & Hono Community",
    tags: ["Edge计算", "超轻量服务端", "Web标准", "CloudflareWorkers"],
    actionType: "github",
    repository: "https://github.com/honojs/hono",
    homepage: "https://hono.dev",
    stars: "22k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:astro-starter",
    name: "Astro Content-First Template",
    category: "templates",
    description: "专为内容站点、技术文档与博客打造的孤岛架构（Islands Architecture）现代 Web 框架。",
    recommendedReason: "默认零客户端 JavaScript 输出，瞬间获得极致 Lighthouse 100 分加载性能表现。",
    author: "Fred K. Schott & Astro Technology",
    tags: ["内容优先", "孤岛架构", "极致性能", "文档博客"],
    actionType: "github",
    repository: "https://github.com/withastro/astro",
    homepage: "https://astro.build",
    stars: "48k+",
    license: "MIT",
  },
];

