import type { ResourceItem } from "../types";

export const templateResources: ResourceItem[] = [
  {
    id: "res:create-t3-app",
    name: "Create T3 App",
    category: "templates",
    description: "以全栈端到端类型安全为核心的 Next.js + tRPC + Tailwind CSS + Prisma/Drizzle 脚手架。",
    recommendedReason: "前后端接口变更即时触发 TypeScript 静态编译报错，杜绝传统前后端联调接口隐患。",
    author: "Theo Browne & T3 OSS",
    tags: ["Next.js", "端到端类型安全", "tRPC", "现代化全栈"],
    actionType: "github",
    repository: "https://github.com/t3-oss/create-t3-app",
    homepage: "https://create.t3.gg",
    stars: "26k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:tauri-react-template",
    name: "Tauri + React + Vite Starter",
    category: "templates",
    description: "基于 Rust 宿主与 Vite + React 打造的跨平台原生极小体积桌面客户端模板。",
    recommendedReason: "打包体积仅数 MB、内存占用极低，同时享受完整 Web 生态热更新与 Rust 高性能系统级能力。",
    author: "Tauri Apps & Community",
    tags: ["Tauri", "Rust桌面端", "轻量极速", "跨平台"],
    actionType: "github",
    repository: "https://github.com/tauri-apps/tauri",
    homepage: "https://tauri.app",
    stars: "88k+",
    license: "MIT / Apache-2.0",
    featured: true,
  },
  {
    id: "res:electron-vite",
    name: "electron-vite",
    category: "templates",
    description: "下一代现代化、轻快且具备极速热重载的 Electron 开发构建脚手架工具。",
    recommendedReason: "解决传统 Webpack 构建 Electron 耗时漫长与主进程/渲染进程配置晦涩的痛点。",
    author: "Alex Wei",
    tags: ["Electron", "Vite构建", "秒级热重载", "多进程配置"],
    actionType: "github",
    repository: "https://github.com/alex8088/electron-vite",
    homepage: "https://electron-vite.org",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:shadcn-next-template",
    name: "Next.js + Shadcn Admin Template",
    category: "templates",
    description: "开箱即用、具备优雅深色模式与响应式布局的现代化中后台管理面板脚手架。",
    recommendedReason: "包含完善的侧边栏导航、表格分页、数据筛选与图表可视化，省去数周搭建时间。",
    author: "Satnaing (Shadcn Admin)",
    tags: ["管理后台", "Next.js", "Shadcn生态", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/satnaing/shadcn-admin",
    stars: "6k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:rust-cli-template",
    name: "Rust CLI Starter Kit",
    category: "templates",
    description: "整合了 clap 命令行参数解析、anyhow 错误处理与 tracing 日志的生产级 Rust CLI 模版。",
    recommendedReason: "初学者学习如何写出地道、符合工业级标准的 Rust 终端工具与二进制分发项目的最优范本。",
    author: "Rust CLI Working Group",
    tags: ["Rust CLI", "Clap参数解析", "工业级模版", "二进制分发"],
    actionType: "github",
    repository: "https://github.com/rust-cli/template",
    stars: "2k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:python-uv-starter",
    name: "Astral uv Python Starter",
    category: "templates",
    description: "基于 Astral uv（超快 Rust 重构 Python 包管理器）的现代化 Python 极简工程模板。",
    recommendedReason: "依赖解析与虚拟环境创建比传统 pip 快 10-100 倍，完全摒弃过时的 requirements.txt 杂乱管理。",
    author: "Astral Software",
    tags: ["Python工程", "Astral uv", "秒级虚拟环境", "现代包管理"],
    actionType: "github",
    repository: "https://github.com/astral-sh/uv",
    homepage: "https://docs.astral.sh/uv",
    stars: "47k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:turborepo-starter",
    name: "Turborepo Monorepo Starter",
    category: "templates",
    description: "针对 JavaScript 与 TypeScript 单体仓库（Monorepo）的高性能智能缓存构建模版。",
    recommendedReason: "多包共享公共 UI 组件、工具库与统一配置，远程缓存让 CI/CD 构建提速数倍。",
    author: "Vercel",
    tags: ["Monorepo", "智能缓存", "多包仓库", "Turborepo"],
    actionType: "github",
    repository: "https://github.com/vercel/turborepo",
    homepage: "https://turbo.build",
    stars: "27k+",
    license: "MIT",
  },
  {
    id: "res:vite-react-ts-tailwind",
    name: "Vite + React + TS + Tailwind Starter",
    category: "templates",
    description: "零多余冗余、预设最佳路径别名与 ESLint 规范的极简前端轻量快速起步模版。",
    recommendedReason: "快速验证创意或编写独立原型 demo 时，无需等待笨重安装，秒级启动。",
    author: "Vite Community",
    tags: ["极简模版", "秒级热更", "原型利器", "TypeScript"],
    actionType: "github",
    repository: "https://github.com/vitejs/vite",
    homepage: "https://vite.dev",
    stars: "72k+",
    license: "MIT",
  },
  {
    id: "res:hono-starter",
    name: "Hono Web Standards Starter",
    category: "templates",
    description: "超轻量、快如闪电的 Web 标准服务端微框架，可在 Node、Bun、Cloudflare 任意环境运行。",
    recommendedReason: "体积不足 20KB，零外部依赖，内置极速正则路由，构建现代 Edge API 与微服务首选。",
    author: "Yusuke Wada & Hono Community",
    tags: ["Edge计算", "超轻量服务端", "Web标准", "CloudflareWorkers"],
    actionType: "github",
    repository: "https://github.com/honojs/hono",
    homepage: "https://hono.dev",
    stars: "22k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:astro-starter",
    name: "Astro Content-First Template",
    category: "templates",
    description: "专为内容站点、技术文档与博客打造的孤岛架构（Islands Architecture）现代 Web 框架。",
    recommendedReason: "默认零客户端 JavaScript 输出，瞬间获得极致 Lighthouse 100 分加载性能表现。",
    author: "Fred K. Schott & Astro Technology",
    tags: ["内容优先", "孤岛架构", "极致性能", "文档博客"],
    actionType: "github",
    repository: "https://github.com/withastro/astro",
    homepage: "https://astro.build",
    stars: "48k+",
    license: "MIT",
  },
  {
    id: "res:nextjs-app-router-starter",
    name: "Next.js App Router Starter",
    category: "templates",
    description: "React 官方推荐的全栈框架，内置服务端组件、流式渲染、路由缓存与图片优化能力。",
    recommendedReason: "create-next-app 一条命令即可在 App Router 与 Pages Router 之间选择起步，生态与部署配套最成熟。",
    author: "Vercel",
    tags: ["Next.js", "服务端组件", "全栈框架", "App Router"],
    actionType: "github",
    repository: "https://github.com/vercel/next.js",
    homepage: "https://nextjs.org",
    stars: "130k+",
    license: "MIT",
  },
  {
    id: "res:create-vue-starter",
    name: "Create Vue Official Starter",
    category: "templates",
    description: "Vue 官方脚手架，可选 TypeScript、JSX、Vue Router、Pinia 与 Vitest 的渐进式工程模板。",
    recommendedReason: "由 Vue 核心团队直接维护，配置项组合官方解释最准确，避免社区模板长期不更新的坑。",
    author: "Vue.js Team (Evan You)",
    tags: ["Vue 3", "官方脚手架", "组合式API", "Vite构建"],
    actionType: "github",
    repository: "https://github.com/vuejs/create-vue",
    homepage: "https://vuejs.org",
    stars: "4k+",
    license: "MIT",
  },
  {
    id: "res:sveltekit-starter",
    name: "SvelteKit",
    category: "templates",
    description: "Svelte 官方应用框架，内置文件式路由、服务端渲染、表单动作与多种适配器部署方案。",
    recommendedReason: "编译期消除虚拟 DOM 运行时开销，同时提供完整全栈能力，是极简代码量的高性价比选择。",
    author: "Svelte Team (Rich Harris)",
    tags: ["Svelte", "编译期优化", "全栈框架", "文件式路由"],
    actionType: "github",
    repository: "https://github.com/sveltejs/kit",
    homepage: "https://svelte.dev",
    stars: "19k+",
    license: "MIT",
  },
  {
    id: "res:solid-start-starter",
    name: "SolidStart",
    category: "templates",
    description: "基于细粒度响应式信号系统的 SolidJS 元框架，支持 SSR、流式渲染与多环境部署。",
    recommendedReason: "没有虚拟 DOM 的响应式更新路径极短，在保持 React 式写法习惯的同时获得近原生性能。",
    author: "SolidJS Team (Ryan Carniato)",
    tags: ["SolidJS", "细粒度响应式", "无虚拟DOM", "元框架"],
    actionType: "github",
    repository: "https://github.com/solidjs/solid-start",
    homepage: "https://start.solidjs.com",
    stars: "5k+",
    license: "MIT",
  },
  {
    id: "res:react-router-templates",
    name: "React Router Templates",
    category: "templates",
    description: "Remix 与 React Router 合并后官方提供的多套模板，覆盖 SPA、SSR、数据加载与部署场景。",
    recommendedReason: "官方模板随框架版本同步维护，是评估「SPA 还是 SSR」两种架构取舍最省时的起点。",
    author: "Remix / React Router Team",
    tags: ["React Router", "Remix", "SSR模板", "数据加载"],
    actionType: "github",
    repository: "https://github.com/remix-run/react-router-templates",
    homepage: "https://reactrouter.com",
    stars: "2k+",
    license: "MIT",
  },
  {
    id: "res:blues-stack",
    name: "Remix Blues Stack",
    category: "templates",
    description: "Remix 官方长期维护的生产级全栈模板，集成 Prisma、SQLite/PostgreSQL、Fly.io 部署与测试。",
    recommendedReason: "示范了真实产品需要但脚手架常缺的会话、权限、迁移与端到端测试完整闭环。",
    author: "Remix Team",
    tags: ["Remix", "Prisma", "生产级模板", "Fly.io部署"],
    actionType: "github",
    repository: "https://github.com/remix-run/blues-stack",
    stars: "9k+",
    license: "MIT",
  },
  {
    id: "res:nuxt-starter",
    name: "Nuxt",
    category: "templates",
    description: "基于 Vue 的全栈元框架，提供自动导入、文件式路由、服务端渲染与 Nitro 服务端引擎。",
    recommendedReason: "约定优于配置的自动导入体系显著减少样板代码，是 Vue 生态做 SSR 与 SEO 站点的默认答案。",
    author: "Nuxt Team (Sébastien Chopin)",
    tags: ["Nuxt", "Vue全栈", "自动导入", "Nitro引擎"],
    actionType: "github",
    repository: "https://github.com/nuxt/nuxt",
    homepage: "https://nuxt.com",
    stars: "56k+",
    license: "MIT",
  },
  {
    id: "res:qwik-starter",
    name: "Qwik",
    category: "templates",
    description: "以可恢复性（Resumability）替代水合的 Web 框架，页面无需重新执行框架代码即可交互。",
    recommendedReason: "从架构层面消解水合成本，是研究「如何让巨型应用首屏瞬时可交互」的前沿参照实现。",
    author: "Builder.io (Miško Hevery)",
    tags: ["Qwik", "可恢复性", "零水合", "极致首屏"],
    actionType: "github",
    repository: "https://github.com/QwikDev/qwik",
    homepage: "https://qwik.dev",
    stars: "21k+",
    license: "MIT",
  },
  {
    id: "res:angular-cli-starter",
    name: "Angular CLI Starter",
    category: "templates",
    description: "Angular 官方命令行工具，一键生成模块、组件、服务、路由与测试的标准工程骨架。",
    recommendedReason: "自带依赖注入、路由、表单与 RxJS 的强约束架构，适合大型团队需要长期一致性的项目。",
    author: "Google Angular Team",
    tags: ["Angular", "依赖注入", "企业级框架", "官方CLI"],
    actionType: "github",
    repository: "https://github.com/angular/angular-cli",
    homepage: "https://angular.dev",
    stars: "27k+",
    license: "MIT",
  },
  {
    id: "res:create-tauri-app-starter",
    name: "Create Tauri App",
    category: "templates",
    description: "Tauri 官方交互式脚手架，可自由组合 React、Vue、Svelte、Solid 与原生 JS 前端。",
    recommendedReason: "官方脚手架自动处理 Rust 侧与前端构建链的联调细节，比手工配置节省大量踩坑时间。",
    author: "Tauri Apps",
    tags: ["Tauri", "官方脚手架", "多前端支持", "桌面应用"],
    actionType: "github",
    repository: "https://github.com/tauri-apps/create-tauri-app",
    homepage: "https://tauri.app/start",
    stars: "1k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:wails-starter",
    name: "Wails",
    category: "templates",
    description: "用 Go 作为后端、Web 技术作为前端的桌面应用框架，可直接调用 Go 结构体与方法。",
    recommendedReason: "无需编写复杂绑定胶水代码即可把现有 Go 库直接暴露给前端，是 Go 开发者做客户端的捷径。",
    author: "Wails Team (Lea Anthony)",
    tags: ["Wails", "Go桌面端", "原生绑定", "跨平台"],
    actionType: "github",
    repository: "https://github.com/wailsapp/wails",
    homepage: "https://wails.io",
    stars: "25k+",
    license: "MIT",
  },
  {
    id: "res:electron-forge-starter",
    name: "Electron Forge",
    category: "templates",
    description: "Electron 官方推荐的统一脚手架与打包工具链，覆盖开发、签名、制作安装器与发布流程。",
    recommendedReason: "官方维护的打包链路对 Windows、macOS、Linux 三平台产物配置最完整，避免社区方案断更。",
    author: "Electron Team (OpenJS Foundation)",
    tags: ["Electron", "官方工具链", "安装包制作", "跨平台发布"],
    actionType: "github",
    repository: "https://github.com/electron/forge",
    homepage: "https://www.electronforge.io",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:flutter-starter",
    name: "Flutter",
    category: "templates",
    description: "Google 的跨平台 UI 工具包，用同一套 Dart 代码构建 iOS、Android、桌面与 Web 应用。",
    recommendedReason: "自绘渲染引擎保证多端像素级一致，热重载调试体验目前仍是移动端开发效率天花板。",
    author: "Google Flutter Team",
    tags: ["Flutter", "Dart", "跨端UI", "自绘引擎"],
    actionType: "github",
    repository: "https://github.com/flutter/flutter",
    homepage: "https://flutter.dev",
    stars: "168k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:expo-starter",
    name: "Expo",
    category: "templates",
    description: "React Native 官方推荐的开发框架与工具链，提供托管构建、OTA 更新与原生模块体系。",
    recommendedReason: "用 Expo Router 与 EAS 构建可以完全绕开 Xcode 与 Gradle 配置，把 RN 门槛降到接近 Web 开发。",
    author: "Expo Team (650 Industries)",
    tags: ["React Native", "Expo", "移动端跨平台", "OTA热更新"],
    actionType: "github",
    repository: "https://github.com/expo/expo",
    homepage: "https://expo.dev",
    stars: "39k+",
    license: "MIT",
  },
  {
    id: "res:fastify-starter",
    name: "Fastify",
    category: "templates",
    description: "以极低开销著称的 Node.js Web 框架，内置基于 JSON Schema 的序列化与校验加速。",
    recommendedReason: "在需要高吞吐的 Node 服务中，Schema 编译带来的性能与自动文档收益远超 Express 方案。",
    author: "Matteo Collina & Fastify Team",
    tags: ["Fastify", "高性能Node", "JSON Schema", "插件体系"],
    actionType: "github",
    repository: "https://github.com/fastify/fastify",
    homepage: "https://fastify.dev",
    stars: "34k+",
    license: "MIT",
  },
  {
    id: "res:nestjs-typescript-starter",
    name: "NestJS TypeScript Starter",
    category: "templates",
    description: "官方 NestJS 起步模板，内置模块、控制器、服务分层结构、依赖注入与 Jest 测试配置。",
    recommendedReason: "Angular 式的装饰器架构让 Node 后端具备清晰的模块边界，适合规模化团队维护。",
    author: "Kamil Myśliwiec & NestJS",
    tags: ["NestJS", "依赖注入", "企业级Node", "分层架构"],
    actionType: "github",
    repository: "https://github.com/nestjs/typescript-starter",
    homepage: "https://nestjs.com",
    stars: "1k+",
    license: "MIT",
  },
  {
    id: "res:django-starter",
    name: "Django",
    category: "templates",
    description: "Python 生态最成熟的 Web 全栈框架，内置 ORM、迁移、Admin 后台、鉴权与表单系统。",
    recommendedReason: "自带管理后台让数据模型一写完就能得到可用运维界面，是快速交付内容型产品的最短路径。",
    author: "Django Software Foundation",
    tags: ["Django", "Python Web", "ORM迁移", "自带Admin"],
    actionType: "github",
    repository: "https://github.com/django/django",
    homepage: "https://www.djangoproject.com",
    stars: "81k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:fastapi-starter",
    name: "FastAPI",
    category: "templates",
    description: "基于 Pydantic 与类型标注的现代 Python API 框架，自动生成 OpenAPI 与交互式文档。",
    recommendedReason: "类型标注即校验即文档，异步原生支持配合 Pydantic v2 的性能是 Python 后端的当前最优解。",
    author: "Sebastián Ramírez (tiangolo)",
    tags: ["FastAPI", "Python API", "OpenAPI文档", "Pydantic校验"],
    actionType: "github",
    repository: "https://github.com/fastapi/fastapi",
    homepage: "https://fastapi.tiangolo.com",
    stars: "82k+",
    license: "MIT",
  },
  {
    id: "res:flask-starter",
    name: "Flask",
    category: "templates",
    description: "极简的 Python 微框架，只提供路由与请求上下文，其余扩展全部按需自由选择。",
    recommendedReason: "代码量与心智负担都最小，适合做内部工具、Webhook 服务与快速验证的技术原型。",
    author: "Pallets Team (Armin Ronacher)",
    tags: ["Flask", "Python微框架", "极简路由", "灵活扩展"],
    actionType: "github",
    repository: "https://github.com/pallets/flask",
    homepage: "https://flask.palletsprojects.com",
    stars: "69k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:axum-starter",
    name: "Axum",
    category: "templates",
    description: "Tokio 团队出品的 Rust Web 框架，基于 Tower 中间件生态与 Hyper，类型安全的提取器设计。",
    recommendedReason: "编译期即可消除大量路由与请求解析错误，是 Rust 做后端服务当前生态兼容性最好的选择。",
    author: "Tokio Team (David Pedersen)",
    tags: ["Rust Web", "Axum", "Tower中间件", "类型安全"],
    actionType: "github",
    repository: "https://github.com/tokio-rs/axum",
    stars: "21k+",
    license: "MIT",
  },
  {
    id: "res:actix-web-starter",
    name: "Actix Web",
    category: "templates",
    description: "高性能 Rust Web 框架，采用 Actor 风格状态管理与高度可组合的提取器、中间件体系。",
    recommendedReason: "长期位居 Web 框架性能基准前列，适合需要把单机吞吐压到极限的 Rust 服务。",
    author: "Nikolay Kim & Actix Team",
    tags: ["Rust Web", "Actix", "极致性能", "Actor模型"],
    actionType: "github",
    repository: "https://github.com/actix/actix-web",
    homepage: "https://actix.rs",
    stars: "22k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:fiber-starter",
    name: "Go Fiber",
    category: "templates",
    description: "构建在 Fasthttp 之上的 Go Web 框架，API 风格高度贴近 Express，零内存分配路由。",
    recommendedReason: "从 Node 迁到 Go 的开发者几乎零学习成本，同时直接获得 Go 的并发与部署优势。",
    author: "Fiber Team (Fenny)",
    tags: ["Go Web", "Fiber", "Express风格", "Fasthttp"],
    actionType: "github",
    repository: "https://github.com/gofiber/fiber",
    homepage: "https://gofiber.io",
    stars: "35k+",
    license: "MIT",
  },
  {
    id: "res:gin-starter",
    name: "Go Gin",
    category: "templates",
    description: "Go 生态使用最广的 HTTP 框架，提供高性能路由、参数绑定校验与中间件机制。",
    recommendedReason: "社区示例与生产案例数量最多，遇到问题时最容易找到可靠答案，适合作为 Go 服务默认起点。",
    author: "Gin Gonic Team",
    tags: ["Go Web", "Gin", "高并发", "中间件"],
    actionType: "github",
    repository: "https://github.com/gin-gonic/gin",
    homepage: "https://gin-gonic.com",
    stars: "80k+",
    license: "MIT",
  },
  {
    id: "res:spring-boot-starter",
    name: "Spring Boot",
    category: "templates",
    description: "Java 企业级应用标准框架，自动配置、起步依赖与内嵌服务器让单 jar 部署成为默认选项。",
    recommendedReason: "金融与大型企业中台的事实标准，Spring 生态的成熟度在依赖治理与可观测性上极难被替代。",
    author: "VMware / Spring Team",
    tags: ["Java", "Spring Boot", "企业级", "自动配置"],
    actionType: "github",
    repository: "https://github.com/spring-projects/spring-boot",
    homepage: "https://spring.io/projects/spring-boot",
    stars: "76k+",
    license: "Apache-2.0",
  },
  {
    id: "res:dotnet-minimal-api-starter",
    name: ".NET Minimal API",
    category: "templates",
    description: "ASP.NET Core 的极简 API 模型，几行代码即可定义端点、依赖注入与 OpenAPI 文档。",
    recommendedReason: "在保持 .NET 高性能与强类型优势的同时摆脱厚重样板，适合微服务与轻量后端场景。",
    author: "Microsoft .NET Team",
    tags: ["C#", ".NET", "Minimal API", "跨平台后端"],
    actionType: "github",
    repository: "https://github.com/dotnet/aspnetcore",
    homepage: "https://learn.microsoft.com/aspnet/core",
    stars: "36k+",
    license: "MIT",
  },
  {
    id: "res:rails-starter",
    name: "Ruby on Rails",
    category: "templates",
    description: "约定优于配置的 Ruby 全栈框架，内置 ActiveRecord、迁移、脚手架生成与多环境配置。",
    recommendedReason: "从零到可演示产品的速度至今仍鲜有对手，是独立开发者做 SaaS 起步的经典选择。",
    author: "David Heinemeier Hansson & Rails Core",
    tags: ["Ruby", "Rails", "约定优于配置", "快速交付"],
    actionType: "github",
    repository: "https://github.com/rails/rails",
    homepage: "https://rubyonrails.org",
    stars: "56k+",
    license: "MIT",
  },
  {
    id: "res:phoenix-starter",
    name: "Phoenix Framework",
    category: "templates",
    description: "Elixir 生态的实时 Web 框架，基于 BEAM 虚拟机与 LiveView 实现服务端驱动的交互界面。",
    recommendedReason: "LiveView 让实时功能无需自建 WebSocket 状态同步，同时天然获得软实时与高容错并发能力。",
    author: "Chris McCord & Phoenix Team",
    tags: ["Elixir", "Phoenix", "LiveView", "实时应用"],
    actionType: "github",
    repository: "https://github.com/phoenixframework/phoenix",
    homepage: "https://www.phoenixframework.org",
    stars: "21k+",
    license: "MIT",
  },
  {
    id: "res:laravel-starter",
    name: "Laravel",
    category: "templates",
    description: "PHP 生态最主流框架，提供 Eloquent ORM、队列、事件、调度与 Blade 模板等完整工具集。",
    recommendedReason: "官方文档与周边生态（Forge、Nova、Sail）覆盖了从开发到部署的整条链路，落地成本极低。",
    author: "Taylor Otwell & Laravel Team",
    tags: ["PHP", "Laravel", "Eloquent ORM", "全栈框架"],
    actionType: "github",
    repository: "https://github.com/laravel/laravel",
    homepage: "https://laravel.com",
    stars: "79k+",
    license: "MIT",
  },
  {
    id: "res:vapor-starter",
    name: "Vapor",
    category: "templates",
    description: "Swift 服务端框架，使用 SwiftNIO 提供非阻塞网络层，可与 iOS 客户端共享模型代码。",
    recommendedReason: "苹果生态团队想复用现有 Swift 技能与数据模型做后端，这是生态内唯一成熟选项。",
    author: "Vapor Team",
    tags: ["Swift", "Vapor", "服务端Swift", "SwiftNIO"],
    actionType: "github",
    repository: "https://github.com/vapor/vapor",
    homepage: "https://vapor.codes",
    stars: "24k+",
    license: "MIT",
  },
  {
    id: "res:ktor-starter",
    name: "Ktor",
    category: "templates",
    description: "JetBrains 推出的 Kotlin 异步 Web 框架，基于协程构建，支持服务端与客户端双端。",
    recommendedReason: "纯 Kotlin 编写并深度利用协程，是 JVM 上编写轻量微服务与移动端后端的现代方案。",
    author: "JetBrains",
    tags: ["Kotlin", "Ktor", "协程异步", "JVM微服务"],
    actionType: "github",
    repository: "https://github.com/ktorio/ktor",
    homepage: "https://ktor.io",
    stars: "13k+",
    license: "Apache-2.0",
  },
  {
    id: "res:fresh-deno-starter",
    name: "Deno Fresh",
    category: "templates",
    description: "Deno 官方全栈框架，默认零客户端 JavaScript，通过岛屿组件按需进行局部水合。",
    recommendedReason: "与 Deno 的权限模型和安全默认值深度集成，无需构建步骤即可部署到边缘平台。",
    author: "Deno Land (Ryan Dahl)",
    tags: ["Deno", "Fresh", "岛屿架构", "零构建部署"],
    actionType: "github",
    repository: "https://github.com/denoland/fresh",
    homepage: "https://fresh.deno.dev",
    stars: "13k+",
    license: "MIT",
  },
  {
    id: "res:bun-runtime-starter",
    name: "Bun Runtime",
    category: "templates",
    description: "集运行时、包管理器、打包器与测试器于一体的 JavaScript/TypeScript 一体化工具链。",
    recommendedReason: "安装依赖与启动脚本速度显著优于 Node 工具链，内置 TypeScript 与测试能力省去大量配置。",
    author: "Oven (Jarred Sumner)",
    tags: ["Bun", "一体化工具链", "极速包管理", "内置测试"],
    actionType: "github",
    repository: "https://github.com/oven-sh/bun",
    homepage: "https://bun.sh",
    stars: "74k+",
    license: "MIT",
  },
  {
    id: "res:docusaurus-starter",
    name: "Docusaurus",
    category: "templates",
    description: "Meta 开源的文档站点生成器，内置版本化文档、国际化、博客与 Algolia 搜索集成。",
    recommendedReason: "为「需要长期维护且多版本并存」的文档场景设计，版本切换与侧边栏自动生成最省心。",
    author: "Meta Open Source",
    tags: ["文档站点", "版本化文档", "国际化", "React驱动"],
    actionType: "github",
    repository: "https://github.com/facebook/docusaurus",
    homepage: "https://docusaurus.io",
    stars: "58k+",
    license: "MIT",
  },
  {
    id: "res:starlight-starter",
    name: "Astro Starlight",
    category: "templates",
    description: "基于 Astro 的官方文档主题，开箱提供侧边栏导航、全文搜索、暗色模式与 SEO 优化。",
    recommendedReason: "默认输出近乎零 JavaScript 的静态页面，文档站点的加载性能与可访问性基线极高。",
    author: "Astro Technology Company",
    tags: ["文档主题", "Astro生态", "极速静态", "开箱搜索"],
    actionType: "github",
    repository: "https://github.com/withastro/starlight",
    homepage: "https://starlight.astro.build",
    stars: "6k+",
    license: "MIT",
  },
  {
    id: "res:next-shadcn-template",
    name: "shadcn/ui Next.js Template",
    category: "templates",
    description: "shadcn 官方 Next.js 起步模板，预配置 Tailwind、路径别名与组件安装命令。",
    recommendedReason: "组件源码直接落入你的仓库而非作为依赖，可自由改造样式，彻底摆脱组件库升级绑架。",
    author: "shadcn (Shadcn UI)",
    tags: ["shadcn/ui", "Tailwind", "组件源码内置", "Next.js"],
    actionType: "github",
    repository: "https://github.com/shadcn-ui/next-template",
    homepage: "https://ui.shadcn.com",
    stars: "2k+",
    license: "MIT",
  },
  {
    id: "res:supabase-auth-saas-starter",
    name: "Next.js Subscription Payments",
    category: "templates",
    description: "Vercel 与 Supabase 联合维护的 SaaS 订阅起步模板，含登录、数据库策略与 Stripe 支付闭环。",
    recommendedReason: "把认证、多租户数据隔离与订阅计费这三件最容易出错的事一次性给出可运行参考实现。",
    author: "Vercel & Supabase",
    tags: ["SaaS模板", "Supabase鉴权", "Stripe订阅", "行级安全策略"],
    actionType: "github",
    repository: "https://github.com/vercel/nextjs-subscription-payments",
    homepage: "https://vercel.com/templates/next.js/subscription-starter",
    stars: "7k+",
    license: "MIT",
  },
  {
    id: "res:playwright-test-starter",
    name: "Playwright",
    category: "templates",
    description: "微软出品的跨浏览器端到端测试框架，支持自动等待、代码生成器、追踪查看与并行执行。",
    recommendedReason: "自动等待机制基本消除了传统 E2E 测试的随机失败，Trace Viewer 让线上复现变得直观。",
    author: "Microsoft",
    tags: ["端到端测试", "跨浏览器", "Trace Viewer", "自动等待"],
    actionType: "github",
    repository: "https://github.com/microsoft/playwright",
    homepage: "https://playwright.dev",
    stars: "73k+",
    license: "Apache-2.0",
  },
  {
    id: "res:vitest-starter",
    name: "Vitest",
    category: "templates",
    description: "与 Vite 共享配置的极速单元测试框架，兼容 Jest API 并内置覆盖率与浏览器模式。",
    recommendedReason: "直接复用 Vite 的转换管线与别名配置，无需为测试重复维护一套构建配置。",
    author: "Vitest Team (Anthony Fu)",
    tags: ["单元测试", "Vite生态", "Jest兼容", "覆盖率"],
    actionType: "github",
    repository: "https://github.com/vitest-dev/vitest",
    homepage: "https://vitest.dev",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:tsup-library-starter",
    name: "tsup",
    category: "templates",
    description: "基于 esbuild 的零配置 TypeScript 库打包工具，一条命令产出 ESM、CJS 与类型声明。",
    recommendedReason: "发布 npm 库常见的双格式与 d.ts 产出问题一站式解决，配置量通常不超过十行。",
    author: "egoist (EGOIST)",
    tags: ["库打包", "esbuild", "双格式产出", "类型声明"],
    actionType: "github",
    repository: "https://github.com/egoist/tsup",
    homepage: "https://tsup.egoist.dev",
    stars: "10k+",
    license: "MIT",
  },
  {
    id: "res:antfu-starter-ts",
    name: "antfu TypeScript Starter",
    category: "templates",
    description: "面向 npm 包发布的 TypeScript 起步模板，内置 tsup/pnpm、Vitest、ESLint 与自动发布工作流。",
    recommendedReason: "把发布一个开源 TS 包所需的构建、测试、类型检查与 CI 发布全部预置好，专注写代码即可。",
    author: "Anthony Fu",
    tags: ["npm包模板", "TypeScript", "自动化发布", "CI工作流"],
    actionType: "github",
    repository: "https://github.com/antfu/starter-ts",
    stars: "1k+",
    license: "MIT",
  },
  {
    id: "res:python-hatch-starter",
    name: "Hatch",
    category: "templates",
    description: "现代 Python 项目管理器，支持多环境矩阵、可复现构建、版本管理与一键发布到 PyPI。",
    recommendedReason: "环境矩阵配置让同一份代码在多个 Python 版本上并行测试，标准化的 pyproject 布局是官方倡导方向。",
    author: "Ofek Lev / PyPA",
    tags: ["Python打包", "Hatch", "多环境矩阵", "pyproject标准"],
    actionType: "github",
    repository: "https://github.com/pypa/hatch",
    homepage: "https://hatch.pypa.io",
    stars: "6k+",
    license: "MIT",
  },
  {
    id: "res:nx-monorepo-starter",
    name: "Nx Monorepo",
    category: "templates",
    description: "支持多语言多框架的 Monorepo 构建系统，提供任务图、增量构建与插件化代码生成。",
    recommendedReason: "任务依赖图可精准判断只需重建哪些受影响项目，在大型仓库中收益远大于配置成本。",
    author: "Nx Team (Narwhal / Victor Savkin)",
    tags: ["Monorepo", "任务依赖图", "增量构建", "代码生成"],
    actionType: "github",
    repository: "https://github.com/nrwl/nx",
    homepage: "https://nx.dev",
    stars: "24k+",
    license: "MIT",
  },
  {
    id: "res:vscode-extension-starter",
    name: "VS Code Extension Samples",
    category: "templates",
    description: "微软官方维护的 VS Code 扩展示例集合，覆盖命令、语言服务器、Webview、TreeView 等能力。",
    recommendedReason: "每个示例都是可独立运行的最小工程，是接入编辑器生态最省时间的第一手参考资料。",
    author: "Microsoft",
    tags: ["VS Code扩展", "官方示例", "语言服务器", "Webview"],
    actionType: "github",
    repository: "https://github.com/microsoft/vscode-extension-samples",
    homepage: "https://code.visualstudio.com/api",
    stars: "9k+",
    license: "MIT",
  },
  {
    id: "res:chrome-extension-mv3-starter",
    name: "Chrome Extensions Samples",
    category: "templates",
    description: "Chrome 扩展开发官方示例库，覆盖 Manifest V3、Service Worker、内容脚本与消息通信。",
    recommendedReason: "MV3 迁移后大量社区教程已过时，官方示例是确认 background、权限与消息机制正确写法的最快途径。",
    author: "Google Chrome Team",
    tags: ["Chrome扩展", "Manifest V3", "Service Worker", "官方示例"],
    actionType: "github",
    repository: "https://github.com/GoogleChrome/chrome-extensions-samples",
    homepage: "https://developer.chrome.com/docs/extensions",
    stars: "16k+",
    license: "Apache-2.0",
  },
  {
    id: "res:astro-paper-blog-starter",
    name: "AstroPaper Blog Starter",
    category: "templates",
    description: "基于 Astro 的极简响应式博客模板，内置全文搜索、标签分类、SEO 元信息与暗色模式。",
    recommendedReason: "默认输出静态页面且首屏体积极小，克隆后改配置即可上线个人技术博客。",
    author: "Satnaing (AstroPaper)",
    tags: ["博客模板", "Astro", "全文搜索", "SEO友好"],
    actionType: "github",
    repository: "https://github.com/satnaing/astro-paper",
    homepage: "https://astro-paper.pages.dev",
    stars: "4k+",
    license: "MIT",
  },
];
