import type { ResourceItem } from "../types";

export const toolResources: ResourceItem[] = [
  {
    id: "res:zed",
    name: "Zed Editor",
    category: "tools",
    description: "由 Atom 与 Tree-sitter 原班团队采用 Rust 与 GPU 硬件渲染构建的超高性能代码编辑器。",
    recommendedReason: "瞬时冷启动、零输入延迟、原生多人实时协作，代表下一代桌面代码编辑器的极致性能方向。",
    author: "Zed Industries",
    tags: ["Rust", "GPU渲染", "零延迟", "次世代编辑器"],
    actionType: "github",
    repository: "https://github.com/zed-industries/zed",
    homepage: "https://zed.dev",
    stars: "52k+",
    license: "GPL-3.0 / Apache-2.0",
    featured: true,
  },
  {
    id: "res:lazygit",
    name: "Lazygit",
    category: "tools",
    description: "简单、直观且让人上瘾的 Git 终端纯文本用户界面（TUI）终极利器。",
    recommendedReason: "交互快捷键流畅，让分支切换、Stash 暂存、Interactive Rebase 和挑选提交快十倍。",
    author: "Jesse Duffield",
    tags: ["Git工具", "终端TUI", "效率神器", "键盘驱动"],
    actionType: "github",
    repository: "https://github.com/jesseduffield/lazygit",
    stars: "53k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:ripgrep",
    name: "ripgrep (rg)",
    category: "tools",
    description: "基于 Rust 编写的高性能递归正则表达式文件与内容搜索命令行工具。",
    recommendedReason: "瞬间穿透百万行代码仓库，速度超越 grep/ag 数倍，VS Code 与各类智能 Agent 底层依赖。",
    author: "Andrew Gallant (BurntSushi)",
    tags: ["Rust性能", "全局检索", "正则匹配", "Agent必备"],
    actionType: "github",
    repository: "https://github.com/BurntSushi/ripgrep",
    stars: "50k+",
    license: "Unlicense / MIT",
    featured: true,
  },
  {
    id: "res:fd-find",
    name: "fd",
    category: "tools",
    description: "现代、极速且易用的跨平台文件路径搜索工具，作为传统 `find` 的友好替代品。",
    recommendedReason: "默认自动忽略 .gitignore 与隐藏目录，色彩高亮清晰，语法符合现代直觉。",
    author: "David Peter (sharkdp)",
    tags: ["文件搜索", "命令行体验", "Rust工具", "快如闪电"],
    actionType: "github",
    repository: "https://github.com/sharkdp/fd",
    stars: "34k+",
    license: "Apache-2.0 / MIT",
  },
  {
    id: "res:starship",
    name: "Starship Prompt",
    category: "tools",
    description: "极速、超高颜值且可深度客制化的跨 Shell 终端提示符引擎。",
    recommendedReason: "自动智能识别当前目录的 Git 分支、Node/Rust/Python 版本与执行耗时，任何 Shell 统一手感。",
    author: "Starship Contributors",
    tags: ["跨Shell", "终端提示符", "环境侦测", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/starship/starship",
    homepage: "https://starship.rs",
    stars: "47k+",
    license: "ISC",
    featured: true,
  },
  {
    id: "res:biome",
    name: "Biome",
    category: "tools",
    description: "专为 Web 开发打造的高性能一体化工具链，单二进制文件集成格式化与 Lint。",
    recommendedReason: "速度比 Prettier 快 35 倍，比 ESLint 快数十倍，零复杂配置瞬间拉齐整个团队规范。",
    author: "Biome Community",
    tags: ["一体化Linter", "超快格式化", "Rust内核", "极速构建"],
    actionType: "github",
    repository: "https://github.com/biomejs/biome",
    homepage: "https://biomejs.dev",
    stars: "18k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:httpie",
    name: "HTTPie Desktop & CLI",
    category: "tools",
    description: "人性化语法、彩色 JSON 高亮与直观交互的现代化 API 调试网络客户端。",
    recommendedReason: "不需要 Postman 的臃肿等待，在命令行以最自然的键值对语法快速完成接口验证。",
    author: "HTTPie Inc.",
    tags: ["API调试", "REST客户端", "简洁语法", "彩色输出"],
    actionType: "github",
    repository: "https://github.com/httpie/cli",
    homepage: "https://httpie.io",
    stars: "34k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:mise",
    name: "mise (formerly rtx)",
    category: "tools",
    description: "专为 Node、Python、Rust、Go 等全栈环境打造的极速多语言版本与环境变量管理工具。",
    recommendedReason: "基于 Rust 重构，瞬时环境注入，完美解决 Windows 与多系统下多版本 SDK 切换的痛点。",
    author: "Jeff Dickey (jdx)",
    tags: ["版本管理", "多语言环境", "环境变量", "Rust极速"],
    actionType: "github",
    repository: "https://github.com/jdx/mise",
    homepage: "https://mise.jdx.dev",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:fastfetch",
    name: "Fastfetch",
    category: "tools",
    description: "类似 Neofetch 但采用高效 C 语言编写、近乎零耗时的系统软硬件看板与环境概览工具。",
    recommendedReason: "在控制台中优雅直观地展示机器架构、显卡、内存与操作系统内核，运行飞快。",
    author: "Linus Dierheimer (fastfetch-cli)",
    tags: ["系统看板", "硬件侦测", "终端美学", "性能卓越"],
    actionType: "github",
    repository: "https://github.com/fastfetch-cli/fastfetch",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:bat",
    name: "bat",
    category: "tools",
    description: "带有完整语法高亮、Git 修改标记与自动分页的现代化 `cat` 命令替代品。",
    recommendedReason: "原生支持数十种语言语法高亮与 Git 行级差异指示，是终端中快速阅读代码的首选。",
    author: "David Peter (sharkdp)",
    tags: ["代码查看", "语法高亮", "Git集成", "Rust神器"],
    actionType: "github",
    repository: "https://github.com/sharkdp/bat",
    stars: "48k+",
    license: "Apache-2.0 / MIT",
  },
  {
    id: "res:eza",
    name: "eza (modern ls)",
    category: "tools",
    description: "采用 Rust 编写的现代化 `ls` 命令，拥有生动图标、色彩分区与 Git 状态指示。",
    recommendedReason: "支持树形目录（--tree）、扩展属性展示与文件大小色彩分阶，终端目录浏览一目了然。",
    author: "eza Community",
    tags: ["目录列表", "图标高亮", "树形视图", "Rust工具"],
    actionType: "github",
    repository: "https://github.com/eza-community/eza",
    stars: "18k+",
    license: "EUPL-1.2",
  },
  {
    id: "res:zoxide",
    name: "zoxide (smarter cd)",
    category: "tools",
    description: "记住你最常访问的目录并在不同路径间毫秒级快速跳转的智能 `cd` 命令替代者。",
    recommendedReason: "输入 `z setup` 即可自动模糊推算并跳转至 `D:\\AI-Vault\\DeepSeek\\setup-center`，效率极高。",
    author: "Ajeet D'Souza",
    tags: ["路径跳转", "模糊匹配", "终端提速", "Shell集成"],
    actionType: "github",
    repository: "https://github.com/ajeetdsouza/zoxide",
    stars: "22k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:oxc",
    name: "Oxc (Oxidation Compiler)",
    category: "tools",
    description: "采用 Rust 编写的 JavaScript / TypeScript 极致性能解析器、Linter 与工具套件集合。",
    recommendedReason: "运行速度比 ESLint 快 50~100 倍，被现代全栈工程大量采用作为下一代代码合规引擎。",
    author: "Boshen & Oxc Team",
    tags: ["Rust编译器", "AST解析", "极致速度", "前端基建"],
    actionType: "github",
    repository: "https://github.com/oxc-project/oxc",
    homepage: "https://oxc.rs",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:rspack",
    name: "Rspack",
    category: "tools",
    description: "字节跳动开源的高性能基于 Rust 的 Web 构建工具，与 Webpack 生态深度兼容。",
    recommendedReason: "毫秒级构建大型复杂前端项目，完美兼容 Webpack 插件与 Loader，平滑实现无痛换代迁移。",
    author: "ByteDance Web Infra",
    tags: ["Rust打包器", "Webpack兼容", "企业级构建", "字节跳动"],
    actionType: "github",
    repository: "https://github.com/web-infra-dev/rspack",
    homepage: "https://rspack.dev",
    stars: "10k+",
    license: "Apache-2.0",
    featured: true,
  },
];

