import type { ResourceItem } from "../types";

export const toolResources: ResourceItem[] = [
  {
    id: "res:zed",
    name: "Zed Editor",
    category: "tools",
    description: "由 Atom 与 Tree-sitter 原班团队采用 Rust 与 GPU 硬件渲染构建的超高性能代码编辑器。",
    recommendedReason: "瞬时冷启动、零输入延迟、原生多人实时协作，代表下一代桌面代码编辑器的极致性能方向。",
    author: "Zed Industries",
    tags: ["Rust", "GPU渲染", "零延迟", "次世代编辑器"],
    actionType: "github",
    repository: "https://github.com/zed-industries/zed",
    homepage: "https://zed.dev",
    stars: "52k+",
    license: "GPL-3.0 / Apache-2.0",
    featured: true,
  },
  {
    id: "res:lazygit",
    name: "Lazygit",
    category: "tools",
    description: "简单、直观且让人上瘾的 Git 终端纯文本用户界面（TUI）终极利器。",
    recommendedReason: "交互快捷键流畅，让分支切换、Stash 暂存、Interactive Rebase 和挑选提交快十倍。",
    author: "Jesse Duffield",
    tags: ["Git工具", "终端TUI", "效率神器", "键盘驱动"],
    actionType: "github",
    repository: "https://github.com/jesseduffield/lazygit",
    stars: "53k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:ripgrep",
    name: "ripgrep (rg)",
    category: "tools",
    description: "基于 Rust 编写的高性能递归正则表达式文件与内容搜索命令行工具。",
    recommendedReason: "瞬间穿透百万行代码仓库，速度超越 grep/ag 数倍，VS Code 与各类智能 Agent 底层依赖。",
    author: "Andrew Gallant (BurntSushi)",
    tags: ["Rust性能", "全局检索", "正则匹配", "Agent必备"],
    actionType: "github",
    repository: "https://github.com/BurntSushi/ripgrep",
    stars: "50k+",
    license: "Unlicense / MIT",
    featured: true,
  },
  {
    id: "res:fd-find",
    name: "fd",
    category: "tools",
    description: "现代、极速且易用的跨平台文件路径搜索工具，作为传统 `find` 的友好替代品。",
    recommendedReason: "默认自动忽略 .gitignore 与隐藏目录，色彩高亮清晰，语法符合现代直觉。",
    author: "David Peter (sharkdp)",
    tags: ["文件搜索", "命令行体验", "Rust工具", "快如闪电"],
    actionType: "github",
    repository: "https://github.com/sharkdp/fd",
    stars: "34k+",
    license: "Apache-2.0 / MIT",
  },
  {
    id: "res:starship",
    name: "Starship Prompt",
    category: "tools",
    description: "极速、超高颜值且可深度客制化的跨 Shell 终端提示符引擎。",
    recommendedReason: "自动智能识别当前目录的 Git 分支、Node/Rust/Python 版本与执行耗时，任何 Shell 统一手感。",
    author: "Starship Contributors",
    tags: ["跨Shell", "终端提示符", "环境侦测", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/starship/starship",
    homepage: "https://starship.rs",
    stars: "47k+",
    license: "ISC",
    featured: true,
  },
  {
    id: "res:biome",
    name: "Biome",
    category: "tools",
    description: "专为 Web 开发打造的高性能一体化工具链，单二进制文件集成格式化与 Lint。",
    recommendedReason: "速度比 Prettier 快 35 倍，比 ESLint 快数十倍，零复杂配置瞬间拉齐整个团队规范。",
    author: "Biome Community",
    tags: ["一体化Linter", "超快格式化", "Rust内核", "极速构建"],
    actionType: "github",
    repository: "https://github.com/biomejs/biome",
    homepage: "https://biomejs.dev",
    stars: "18k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:httpie",
    name: "HTTPie Desktop & CLI",
    category: "tools",
    description: "人性化语法、彩色 JSON 高亮与直观交互的现代化 API 调试网络客户端。",
    recommendedReason: "不需要 Postman 的臃肿等待，在命令行以最自然的键值对语法快速完成接口验证。",
    author: "HTTPie Inc.",
    tags: ["API调试", "REST客户端", "简洁语法", "彩色输出"],
    actionType: "github",
    repository: "https://github.com/httpie/cli",
    homepage: "https://httpie.io",
    stars: "34k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:mise",
    name: "mise (formerly rtx)",
    category: "tools",
    description: "专为 Node、Python、Rust、Go 等全栈环境打造的极速多语言版本与环境变量管理工具。",
    recommendedReason: "基于 Rust 重构，瞬时环境注入，完美解决 Windows 与多系统下多版本 SDK 切换的痛点。",
    author: "Jeff Dickey (jdx)",
    tags: ["版本管理", "多语言环境", "环境变量", "Rust极速"],
    actionType: "github",
    repository: "https://github.com/jdx/mise",
    homepage: "https://mise.jdx.dev",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:fastfetch",
    name: "Fastfetch",
    category: "tools",
    description: "类似 Neofetch 但采用高效 C 语言编写、近乎零耗时的系统软硬件看板与环境概览工具。",
    recommendedReason: "在控制台中优雅直观地展示机器架构、显卡、内存与操作系统内核，运行飞快。",
    author: "Linus Dierheimer (fastfetch-cli)",
    tags: ["系统看板", "硬件侦测", "终端美学", "性能卓越"],
    actionType: "github",
    repository: "https://github.com/fastfetch-cli/fastfetch",
    stars: "14k+",
    license: "MIT",
  },
];
