import type { ResourceItem } from "../types";

export const toolResources: ResourceItem[] = [
  {
    id: "res:zed",
    name: "Zed Editor",
    category: "tools",
    description: "由 Atom 与 Tree-sitter 原班团队采用 Rust 与 GPU 硬件渲染构建的超高性能代码编辑器。",
    recommendedReason: "瞬时冷启动、零输入延迟、原生多人实时协作，代表下一代桌面代码编辑器的极致性能方向。",
    author: "Zed Industries",
    tags: ["Rust", "GPU渲染", "零延迟", "次世代编辑器"],
    actionType: "github",
    repository: "https://github.com/zed-industries/zed",
    homepage: "https://zed.dev",
    stars: "52k+",
    license: "GPL-3.0 / Apache-2.0",
    featured: true,
  },
  {
    id: "res:lazygit",
    name: "Lazygit",
    category: "tools",
    description: "简单、直观且让人上瘾的 Git 终端纯文本用户界面（TUI）终极利器。",
    recommendedReason: "交互快捷键流畅，让分支切换、Stash 暂存、Interactive Rebase 和挑选提交快十倍。",
    author: "Jesse Duffield",
    tags: ["Git工具", "终端TUI", "效率神器", "键盘驱动"],
    actionType: "github",
    repository: "https://github.com/jesseduffield/lazygit",
    stars: "53k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:ripgrep",
    name: "ripgrep (rg)",
    category: "tools",
    description: "基于 Rust 编写的高性能递归正则表达式文件与内容搜索命令行工具。",
    recommendedReason: "瞬间穿透百万行代码仓库，速度超越 grep/ag 数倍，VS Code 与各类智能 Agent 底层依赖。",
    author: "Andrew Gallant (BurntSushi)",
    tags: ["Rust性能", "全局检索", "正则匹配", "Agent必备"],
    actionType: "github",
    repository: "https://github.com/BurntSushi/ripgrep",
    stars: "50k+",
    license: "Unlicense / MIT",
    featured: true,
  },
  {
    id: "res:fd-find",
    name: "fd",
    category: "tools",
    description: "现代、极速且易用的跨平台文件路径搜索工具，作为传统 `find` 的友好替代品。",
    recommendedReason: "默认自动忽略 .gitignore 与隐藏目录，色彩高亮清晰，语法符合现代直觉。",
    author: "David Peter (sharkdp)",
    tags: ["文件搜索", "命令行体验", "Rust工具", "快如闪电"],
    actionType: "github",
    repository: "https://github.com/sharkdp/fd",
    stars: "34k+",
    license: "Apache-2.0 / MIT",
  },
  {
    id: "res:starship",
    name: "Starship Prompt",
    category: "tools",
    description: "极速、超高颜值且可深度客制化的跨 Shell 终端提示符引擎。",
    recommendedReason: "自动智能识别当前目录的 Git 分支、Node/Rust/Python 版本与执行耗时，任何 Shell 统一手感。",
    author: "Starship Contributors",
    tags: ["跨Shell", "终端提示符", "环境侦测", "开箱即用"],
    actionType: "github",
    repository: "https://github.com/starship/starship",
    homepage: "https://starship.rs",
    stars: "47k+",
    license: "ISC",
    featured: true,
  },
  {
    id: "res:biome",
    name: "Biome",
    category: "tools",
    description: "专为 Web 开发打造的高性能一体化工具链，单二进制文件集成格式化与 Lint。",
    recommendedReason: "速度比 Prettier 快 35 倍，比 ESLint 快数十倍，零复杂配置瞬间拉齐整个团队规范。",
    author: "Biome Community",
    tags: ["一体化Linter", "超快格式化", "Rust内核", "极速构建"],
    actionType: "github",
    repository: "https://github.com/biomejs/biome",
    homepage: "https://biomejs.dev",
    stars: "18k+",
    license: "MIT / Apache-2.0",
  },
  {
    id: "res:httpie",
    name: "HTTPie Desktop & CLI",
    category: "tools",
    description: "人性化语法、彩色 JSON 高亮与直观交互的现代化 API 调试网络客户端。",
    recommendedReason: "不需要 Postman 的臃肿等待，在命令行以最自然的键值对语法快速完成接口验证。",
    author: "HTTPie Inc.",
    tags: ["API调试", "REST客户端", "简洁语法", "彩色输出"],
    actionType: "github",
    repository: "https://github.com/httpie/cli",
    homepage: "https://httpie.io",
    stars: "34k+",
    license: "BSD-3-Clause",
  },
  {
    id: "res:mise",
    name: "mise (formerly rtx)",
    category: "tools",
    description: "专为 Node、Python、Rust、Go 等全栈环境打造的极速多语言版本与环境变量管理工具。",
    recommendedReason: "基于 Rust 重构，瞬时环境注入，完美解决 Windows 与多系统下多版本 SDK 切换的痛点。",
    author: "Jeff Dickey (jdx)",
    tags: ["版本管理", "多语言环境", "环境变量", "Rust极速"],
    actionType: "github",
    repository: "https://github.com/jdx/mise",
    homepage: "https://mise.jdx.dev",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:fastfetch",
    name: "Fastfetch",
    category: "tools",
    description: "类似 Neofetch 但采用高效 C 语言编写、近乎零耗时的系统软硬件看板与环境概览工具。",
    recommendedReason: "在控制台中优雅直观地展示机器架构、显卡、内存与操作系统内核，运行飞快。",
    author: "Linus Dierheimer (fastfetch-cli)",
    tags: ["系统看板", "硬件侦测", "终端美学", "性能卓越"],
    actionType: "github",
    repository: "https://github.com/fastfetch-cli/fastfetch",
    stars: "14k+",
    license: "MIT",
  },
  {
    id: "res:bat",
    name: "bat",
    category: "tools",
    description: "带有完整语法高亮、Git 修改标记与自动分页的现代化 `cat` 命令替代品。",
    recommendedReason: "原生支持数十种语言语法高亮与 Git 行级差异指示，是终端中快速阅读代码的首选。",
    author: "David Peter (sharkdp)",
    tags: ["代码查看", "语法高亮", "Git集成", "Rust神器"],
    actionType: "github",
    repository: "https://github.com/sharkdp/bat",
    stars: "48k+",
    license: "Apache-2.0 / MIT",
  },
  {
    id: "res:eza",
    name: "eza (modern ls)",
    category: "tools",
    description: "采用 Rust 编写的现代化 `ls` 命令，拥有生动图标、色彩分区与 Git 状态指示。",
    recommendedReason: "支持树形目录（--tree）、扩展属性展示与文件大小色彩分阶，终端目录浏览一目了然。",
    author: "eza Community",
    tags: ["目录列表", "图标高亮", "树形视图", "Rust工具"],
    actionType: "github",
    repository: "https://github.com/eza-community/eza",
    stars: "18k+",
    license: "EUPL-1.2",
  },
  {
    id: "res:zoxide",
    name: "zoxide (smarter cd)",
    category: "tools",
    description: "记住你最常访问的目录并在不同路径间毫秒级快速跳转的智能 `cd` 命令替代者。",
    recommendedReason: "输入 `z setup` 即可自动模糊推算并跳转至 `D:\\AI-Vault\\DeepSeek\\setup-center`，效率极高。",
    author: "Ajeet D'Souza",
    tags: ["路径跳转", "模糊匹配", "终端提速", "Shell集成"],
    actionType: "github",
    repository: "https://github.com/ajeetdsouza/zoxide",
    stars: "22k+",
    license: "MIT",
    featured: true,
  },
  {
    id: "res:oxc",
    name: "Oxc (Oxidation Compiler)",
    category: "tools",
    description: "采用 Rust 编写的 JavaScript / TypeScript 极致性能解析器、Linter 与工具套件集合。",
    recommendedReason: "运行速度比 ESLint 快 50~100 倍，被现代全栈工程大量采用作为下一代代码合规引擎。",
    author: "Boshen & Oxc Team",
    tags: ["Rust编译器", "AST解析", "极致速度", "前端基建"],
    actionType: "github",
    repository: "https://github.com/oxc-project/oxc",
    homepage: "https://oxc.rs",
    stars: "11k+",
    license: "MIT",
  },
  {
    id: "res:rspack",
    name: "Rspack",
    category: "tools",
    description: "字节跳动开源的高性能基于 Rust 的 Web 构建工具，与 Webpack 生态深度兼容。",
    recommendedReason: "毫秒级构建大型复杂前端项目，完美兼容 Webpack 插件与 Loader，平滑实现无痛换代迁移。",
    author: "ByteDance Web Infra",
    tags: ["Rust打包器", "Webpack兼容", "企业级构建", "字节跳动"],
    actionType: "github",
    repository: "https://github.com/web-infra-dev/rspack",
    homepage: "https://rspack.dev",
    stars: "10k+",
    license: "Apache-2.0",
    featured: true,
  },
  {
    id: "res:neovim",
    name: "Neovim",
    category: "tools",
    description: "在 Vim 基础上彻底现代化重构的模态代码编辑器，支持 Lua 配置与内置 LSP、Tree-sitter。",
    recommendedReason: "可编程性极强而资源占用极低，配置一次即可在任意终端与远程服务器上获得完全一致的开发体验。",
    author: "Neovim Contributors",
    tags: ["模态编辑", "Lua配置", "内置LSP", "远程开发"],
    actionType: "github",
    repository: "https://github.com/neovim/neovim",
    homepage: "https://neovim.io",
    stars: "82k+",
    license: "Apache-2.0",
    featured: true,
  },
  {
    id: "res:helix",
    name: "Helix",
    category: "tools",
    description: "后现代模态编辑器，内置多重选择与开箱即用的 LSP，无需安装任何插件即可写代码。",
    recommendedReason: "选择再动作的逆向编辑模型上手即顺手，绕开了 Vim 生态繁琐的插件配置地狱。",
    author: "Helix Contributors",
    tags: ["开箱即用", "多重选择", "模态编辑", "Rust"],
    actionType: "github",
    repository: "https://github.com/helix-editor/helix",
    homepage: "https://helix-editor.com",
    stars: "34k+",
    license: "MPL-2.0",
  },
  {
    id: "res:wezterm",
    name: "WezTerm",
    category: "tools",
    description: "GPU 加速、跨平台并可用 Lua 深度脚本化的终端模拟器与多路复用器。",
    recommendedReason: "单份配置文件接管字体、标签页、多路复用与快捷键，是 Windows 下体验最接近自由配置 Unix 终端的选择。",
    author: "Wez Furlong",
    tags: ["GPU加速", "Lua脚本", "跨平台终端", "多路复用"],
    actionType: "github",
    repository: "https://github.com/wezterm/wezterm",
    homepage: "https://wezfurlong.org/wezterm",
    stars: "19k+",
    license: "MIT",
  },
  {
    id: "res:windows-terminal",
    name: "Windows Terminal",
    category: "tools",
    description: "微软官方现代终端宿主，支持多标签、GPU 渲染与自定义配色与字体连字。",
    recommendedReason: "Windows 上唯一官方维护、与 PowerShell 和 WSL 深度集成的终端，是所有 Windows 开发者的底座。",
    author: "Microsoft",
    tags: ["官方终端", "多标签", "GPU渲染", "WSL集成"],
    actionType: "github",
    repository: "https://github.com/microsoft/terminal",
    homepage: "https://aka.ms/terminal",
    stars: "96k+",
    license: "MIT",
  },
  {
    id: "res:oh-my-posh",
    name: "Oh My Posh",
    category: "tools",
    description: "跨 Shell 的可视化提示符定制引擎，用 JSON 主题定义每一段提示符样式。",
    recommendedReason: "比手写 Shell 脚本更直观地做出带 Git、语言版本与执行耗时的提示符，在 Windows PowerShell 上体验尤佳。",
    author: "Jan De Dobbeleer",
    tags: ["提示符美化", "跨Shell", "JSON主题", "Windows友好"],
    actionType: "github",
    repository: "https://github.com/JanDeDobbeleer/oh-my-posh",
    homepage: "https://ohmyposh.dev",
    stars: "20k+",
    license: "MIT",
  },
  {
    id: "res:nushell",
    name: "Nushell",
    category: "tools",
    description: "把一切命令输出都当作结构化表格处理的现代 Shell。",
    recommendedReason: "管道里传递的是带类型的表而不是字符串，过滤、排序、聚合数据不再需要 awk 与 sed 拼凑。",
    author: "Nushell Contributors",
    tags: ["结构化数据", "现代Shell", "管道表格", "Rust"],
    actionType: "github",
    repository: "https://github.com/nushell/nushell",
    homepage: "https://www.nushell.sh",
    stars: "35k+",
    license: "MIT",
  },
  {
    id: "res:gitui",
    name: "GitUI",
    category: "tools",
    description: "用 Rust 编写的极速 Git 终端界面，主打超大仓库下的流畅响应。",
    recommendedReason: "打开巨型 mono-repo 依然瞬间响应，区块级暂存与差异浏览的键位设计非常高效。",
    author: "Stephan Dilly",
    tags: ["Git TUI", "Rust极速", "大仓库友好", "键位直观"],
    actionType: "github",
    repository: "https://github.com/extrawurst/gitui",
    stars: "19k+",
    license: "MIT",
  },
  {
    id: "res:delta",
    name: "git-delta",
    category: "tools",
    description: "为 Git diff 提供语法高亮、并排对比与行号的可视化增强分页器。",
    recommendedReason: "让 git log -p 与代码审查中的每一处改动一眼可读，是终端阅读差异的体验分水岭。",
    author: "Dan Davison",
    tags: ["Diff高亮", "并排对比", "代码审查", "Git增强"],
    actionType: "github",
    repository: "https://github.com/dandavison/delta",
    stars: "26k+",
    license: "MIT",
  },
  {
    id: "res:gh-cli",
    name: "GitHub CLI",
    category: "tools",
    description: "GitHub 官方命令行工具，在终端内完成仓库、Issue、PR 与 Actions 的全流程操作。",
    recommendedReason: "把原本要开浏览器点十几下的操作压缩成一条命令，也是脚本化调用 GitHub API 最稳妥的路径。",
    author: "GitHub",
    tags: ["官方CLI", "PR管理", "Actions", "自动化"],
    actionType: "github",
    repository: "https://github.com/cli/cli",
    homepage: "https://cli.github.com",
    stars: "39k+",
    license: "MIT",
  },
  {
    id: "res:act",
    name: "act",
    category: "tools",
    description: "在本地用 Docker 直接运行 GitHub Actions 工作流的命令行工具。",
    recommendedReason: "不必反复 push 触发云端流水线，本地即可调试 CI 配置与环境变量，省下大量等待时间。",
    author: "Casey Lee (nektos)",
    tags: ["本地CI", "Actions调试", "Docker", "提效"],
    actionType: "github",
    repository: "https://github.com/nektos/act",
    stars: "62k+",
    license: "MIT",
  },
  {
    id: "res:just",
    name: "just",
    category: "tools",
    description: "类 Make 但语法更友好的命令运行器，用于统一管理项目里的常用脚本任务。",
    recommendedReason: "用一份 Justfile 收拢 npm、pytest、cargo 等杂散命令，让跨语言项目拥有一致的任务入口。",
    author: "Casey Rodarmor",
    tags: ["任务运行器", "Justfile", "跨语言", "替代Make"],
    actionType: "github",
    repository: "https://github.com/casey/just",
    homepage: "https://just.systems",
    stars: "24k+",
    license: "CC0-1.0",
  },
  {
    id: "res:hyperfine",
    name: "hyperfine",
    category: "tools",
    description: "带统计分析与预热功能的命令行基准测试工具。",
    recommendedReason: "几十次采样后给出置信区间，让「哪个工具更快」从主观感觉变成可复现的量化数据。",
    author: "David Peter (sharkdp)",
    tags: ["性能基准", "统计采样", "命令行", "可复现"],
    actionType: "github",
    repository: "https://github.com/sharkdp/hyperfine",
    stars: "24k+",
    license: "Apache-2.0",
  },
  {
    id: "res:dust",
    name: "dust",
    category: "tools",
    description: "以树形结构按体积排序展示磁盘占用的命令行分析工具。",
    recommendedReason: "一眼定位吃满硬盘的 node_modules 与构建缓存，删除之前先看清真实占用分布。",
    author: "Andy Boot (bootandy)",
    tags: ["磁盘分析", "树形排序", "清理空间", "Rust"],
    actionType: "github",
    repository: "https://github.com/bootandy/dust",
    stars: "10k+",
    license: "Apache-2.0",
  },
  {
    id: "res:btop",
    name: "btop",
    category: "tools",
    description: "集 CPU、内存、磁盘、网络与进程监控于一体、界面精致的终端资源监视器。",
    recommendedReason: "在终端里就能看到进程级资源曲线，排查本机跑大模型时的内存与 CPU 瓶颈格外直观。",
    author: "Aristocratos",
    tags: ["资源监控", "进程曲线", "终端UI", "性能排查"],
    actionType: "github",
    repository: "https://github.com/aristocratos/btop",
    stars: "24k+",
    license: "Apache-2.0",
  },
  {
    id: "res:glow",
    name: "glow",
    category: "tools",
    description: "在终端中渲染 Markdown 文档（含表格、代码块与链接）的命令行阅读器。",
    recommendedReason: "直接阅读本地 README 与 Agent 生成的 Markdown 文档，不用离开终端就能获得排版效果。",
    author: "Charm (charmbracelet)",
    tags: ["Markdown阅读", "终端渲染", "文档浏览", "Charm"],
    actionType: "github",
    repository: "https://github.com/charmbracelet/glow",
    stars: "18k+",
    license: "MIT",
  },
  {
    id: "res:bruno",
    name: "Bruno",
    category: "tools",
    description: "把 API 集合以纯文本文件保存在仓库中的离线优先 API 客户端。",
    recommendedReason: "集合可随代码一起 Git 版本化、无需登录云端账号，接口调试与代码走同一套评审流程。",
    author: "Bruno Software",
    tags: ["API客户端", "离线优先", "Git友好", "明文集合"],
    actionType: "github",
    repository: "https://github.com/usebruno/bruno",
    homepage: "https://www.usebruno.com",
    stars: "32k+",
    license: "MIT",
  },
  {
    id: "res:hoppscotch",
    name: "Hoppscotch",
    category: "tools",
    description: "开源 API 调试平台，覆盖 REST、GraphQL、WebSocket 与 Server-Sent Events。",
    recommendedReason: "打开网页即可用，也支持完全自托管，是团队共享接口集合与调用记录的轻量 Postman 替代方案。",
    author: "Hoppscotch",
    tags: ["API调试", "自托管", "GraphQL", "WebSocket"],
    actionType: "github",
    repository: "https://github.com/hoppscotch/hoppscotch",
    homepage: "https://hoppscotch.io",
    stars: "68k+",
    license: "MIT",
  },
  {
    id: "res:dbeaver",
    name: "DBeaver",
    category: "tools",
    description: "支持几乎所有主流关系型数据库与部分 NoSQL 的通用图形化数据库客户端。",
    recommendedReason: "一套界面连接 MySQL、PostgreSQL、SQLite、DuckDB，ER 图与数据导出能力尤其适合接手陌生库。",
    author: "DBeaver Corp",
    tags: ["数据库客户端", "多库支持", "ER图", "数据导出"],
    actionType: "github",
    repository: "https://github.com/dbeaver/dbeaver",
    homepage: "https://dbeaver.io",
    stars: "43k+",
    license: "Apache-2.0",
  },
  {
    id: "res:obsidian",
    name: "Obsidian",
    category: "tools",
    description: "以本地纯 Markdown 文件为存储核心的双向链接知识库应用。",
    recommendedReason: "数据完全本地可控且插件生态庞大，是开发者长期沉淀技术笔记与搭建第二大脑的可靠载体。",
    author: "Obsidian (Dynalist Inc.)",
    tags: ["本地Markdown", "双向链接", "插件生态", "知识管理"],
    actionType: "external",
    homepage: "https://obsidian.md",
  },
  {
    id: "res:logseq",
    name: "Logseq",
    category: "tools",
    description: "开源的本地优先大纲式笔记与知识图谱工具。",
    recommendedReason: "块级引用与日记流工作方式天然适合记录每日开发日志，并自动生成引用关系图。",
    author: "Logseq Inc.",
    tags: ["大纲笔记", "知识图谱", "开源", "本地优先"],
    actionType: "github",
    repository: "https://github.com/logseq/logseq",
    homepage: "https://logseq.com",
    stars: "36k+",
    license: "AGPL-3.0",
  },
  {
    id: "res:lazydocker",
    name: "Lazydocker",
    category: "tools",
    description: "Lazygit 同作者出品的 Docker 与 Docker Compose 终端管理界面。",
    recommendedReason: "在 TUI 中查看容器日志、进入 Shell、重启服务，比记一长串 docker 子命令高效得多。",
    author: "Jesse Duffield",
    tags: ["Docker TUI", "容器管理", "日志查看", "快捷键"],
    actionType: "github",
    repository: "https://github.com/jesseduffield/lazydocker",
    stars: "40k+",
    license: "MIT",
  },
  {
    id: "res:duckdb",
    name: "DuckDB",
    category: "tools",
    description: "面向分析场景的进程内列式 SQL 数据库，可直接查询 CSV、Parquet 与 JSON 文件。",
    recommendedReason: "几十行 SQL 就能对本地大数据文件做聚合分析，完全不需要搭建任何服务端。",
    author: "DuckDB Labs",
    tags: ["列式数据库", "OLAP", "进程内", "Parquet"],
    actionType: "github",
    repository: "https://github.com/duckdb/duckdb",
    homepage: "https://duckdb.org",
    stars: "25k+",
    license: "MIT",
  },
  {
    id: "res:supabase",
    name: "Supabase",
    category: "tools",
    description: "基于 PostgreSQL 的开源后端平台，提供数据库、认证、存储与实时订阅。",
    recommendedReason: "本地一条命令就能起完整后端栈，SQL 与行级权限同源，是快速验证产品想法的最短路径。",
    author: "Supabase Inc.",
    tags: ["PostgreSQL", "后端即服务", "认证与存储", "实时订阅"],
    actionType: "github",
    repository: "https://github.com/supabase/supabase",
    homepage: "https://supabase.com",
    stars: "78k+",
    license: "Apache-2.0",
  },
  {
    id: "res:grafana",
    name: "Grafana",
    category: "tools",
    description: "面向指标、日志与链路追踪的统一可视化与告警平台。",
    recommendedReason: "把 Prometheus、Loki、OpenTelemetry 的数据合成一块看板，是排查线上性能问题的事实标准入口。",
    author: "Grafana Labs",
    tags: ["可观测性", "看板可视化", "告警", "多数据源"],
    actionType: "github",
    repository: "https://github.com/grafana/grafana",
    homepage: "https://grafana.com",
    stars: "65k+",
    license: "AGPL-3.0",
  },
  {
    id: "res:uptime-kuma",
    name: "Uptime Kuma",
    category: "tools",
    description: "自托管的服务可用性与 HTTPS 证书到期监控面板。",
    recommendedReason: "自带数十种通知渠道与公开状态页，个人项目上线后能第一时间知道服务是否还活着。",
    author: "Louis Lam",
    tags: ["可用性监控", "自托管", "状态页", "告警通知"],
    actionType: "github",
    repository: "https://github.com/louislam/uptime-kuma",
    stars: "62k+",
    license: "MIT",
  },
  {
    id: "res:opentelemetry-collector",
    name: "OpenTelemetry Collector",
    category: "tools",
    description: "OpenTelemetry 官方厂商中立的遥测数据接收、处理与导出代理。",
    recommendedReason: "以统一协议接入 traces、metrics、logs，避免业务代码与任意监控后端厂商强绑定。",
    author: "OpenTelemetry (CNCF)",
    tags: ["可观测性标准", "遥测采集", "厂商中立", "CNCF"],
    actionType: "github",
    repository: "https://github.com/open-telemetry/opentelemetry-collector",
    homepage: "https://opentelemetry.io",
    stars: "6k+",
    license: "Apache-2.0",
  },
];

