import type { SetupStyle } from "../types";

export const kineticEditorialStyle: SetupStyle = {
  id: "kinetic-editorial",
  name: "Kinetic Editorial",
  version: "3.0.0",
  subtitle: "双栏折报版式 · 巨幅衬线序列 · 律动社论刻度线",
  description:
    "突破传统管理后台的扁平盒模型，采用不对称双栏宽幅报章架构。左栏固定 360px 社论导读台与超大字阶罗马序号，右侧展开律动两栏流式正文，呈现纯正的大报排版张力与出版物级视觉权重。",
  inspiration: "The New York Times Magazine, Zeit Magazin, Bloomberg Businessweek",
  author: "Setup Center Architecture",
  tags: ["报刊社论", "先锋排版", "不对称双栏", "衬线大字阶", "出版物"],
  implemented: true,
  palette: {
    baseBg: "#f5f3ec",
    surface: "#ffffff",
    cardBorder: "#18181b",
    accent: "#d63031",
    accentSecondary: "#27272a",
    text: "#111827",
  },
  features: [
    "左栏 360px 悬停折报导读台，配备 72px 巨幅衬线序数与出版物基线",
    "右栏双列流式内容排布，贯穿 2px 严谨墨色分隔线与专栏眉题",
    "正文与标题采用经典高对比衬线字阶，阅读节奏主次分明",
    "朱红（Crimson Ink）按压强调色，赋予操作如同铅字盖印的坚实触感",
  ],
  designPrinciples: [
    "Asymmetry Over Symmetry: 用黄金比例的不对称打破千篇一律的卡片陈列",
    "Typographic Authority: 字阶即骨架，首字母与章节大号数字承担构图重心",
    "Paper & Ink Tactility: 米白纸张质感底色与高纯度油墨黑对比，彻底剥离电子廉价感",
  ],
  experience: {
    tier: "experience",
    family: "editorial",
    scene: "split-reading",
    contentFlow: "asymmetric-split",
    navigationFlow: "ticker-rail",
    pageTransition: "newspaper-fold",
    heroMode: "giant-serif",
    layering: "paper-stack",
    shell: "editorial",
    navigation: "topbar",
    detail: "sheet",
    card: "editorial-block",
    composition: "news-columns",
    density: "normal",
    motion: "expressive",
    typography: {
      headingFamily: "'Georgia', 'Times New Roman', 'Noto Serif SC', serif",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 900,
      headingTracking: "-0.035em",
      bodyLeading: 1.65,
    },
    ornament: {
      rule: "heavy",
      corner: "square",
      decoration: "none",
      chrome: "title",
    },
    tokens: {
      panelRadius: "0px",
      controlRadius: "0px",
      borderWidth: "2px",
      shadow: {
        offsetX: "4px",
        offsetY: "4px",
        blur: "0px",
        spread: "0px",
        color: "#18181b",
      },
      accent: "#d63031",
      accentSecondary: "#27272a",
      surface: "#ffffff",
      text: "#111827",
      density: "normal",
      headingScale: 1.25,
      bodyScale: 1.0,
      motion: "expressive",
    },
    locked: {
      panelRadius: "社论折报排版要求严格直角基线，圆角会破坏版面网格的几何律动",
    },
    specimenNote: "剪影特征：左侧大号衬线栏目导读 + 顶部横向滚动新闻条 + 纯平直角报纸分栏",
  },
};

export default kineticEditorialStyle;
