import type { SetupStyle } from "../types";

export const posterWallStyle: SetupStyle = {
  id: "poster-wall",
  name: "Poster Wall",
  version: "3.0.0",
  subtitle: "极端排版张力 · 倾斜贴纸标牌 · 高能荧光撞色",
  description:
    "基于现代国际平面海报双年展的先锋视觉系统。摒弃温吞中庸的传统界面规矩，采用高饱和荧光绿与浓墨纯黑的高反差撞色，局部卡片与标签带轻微倾斜角度（-2° 撕裂感），辅以极端巨大的怪诞无衬线字阶（Grotesque 900+），让工具平台如同一面充满年轻生命力的街头艺术展墙。",
  inspiration: "Swiss Poster Biennial, Tokyo TDC, Brutalist Web Design",
  author: "Setup Center Architecture",
  tags: ["先锋海报", "倾斜排版", "荧光撞色", "粗野无衬线", "贴纸标牌"],
  implemented: true,
  palette: {
    baseBg: "#0c0c0c",
    surface: "#171717",
    cardBorder: "#a3e635",
    accent: "#a3e635",
    accentSecondary: "#ec4899",
    text: "#f4f4f5",
  },
  features: [
    "浓墨深黑底色 (#0c0c0c) 碰撞刺目夺目的电能荧光青柠绿 (#a3e635)",
    "卡片与徽章采用轻微自然物理倾斜 (-1.5° / +1.5°)，打破单调网格秩序",
    "超大字阶粗野黑色字体（Impact/Grotesque 900+），带来极强情绪感染力",
    "粉红朋克 (#ec4899) 警戒贴纸点缀，形成双色戏剧性视觉冲突",
  ],
  designPrinciples: [
    "Bold Over Polite: 敢于使用具有张力的对比与尺寸反差，平庸就是界面的慢性死亡",
    "Sticker Culture: 将每一个工具赋予如实体贴纸般的独立图腾感，激发收藏欲望",
    "Exhibition Canvas: 软件库不仅是冷冰冰的安装源，更是一面数字创作者的灵感展墙",
  ],
  experience: {
    tier: "experience",
    family: "playful",
    scene: "poster-canvas",
    contentFlow: "tilted-columns",
    navigationFlow: "slant-tabs",
    pageTransition: "poster-flip",
    heroMode: "bold-marquee",
    layering: "overlapping-stickers",
    shell: "canvas",
    navigation: "topbar",
    detail: "sheet",
    card: "poster",
    composition: "poster-wall",
    density: "spacious",
    motion: "expressive",
    typography: {
      headingFamily: "'Arial Black', 'Impact', -apple-system, sans-serif",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 900,
      headingTracking: "-0.04em",
      headingTransform: "uppercase",
      bodyLeading: 1.5,
    },
    ornament: {
      rule: "heavy",
      corner: "square",
      decoration: "none",
      chrome: "none",
    },
    tokens: {
      panelRadius: "0px",
      controlRadius: "0px",
      borderWidth: "2.5px",
      shadow: {
        offsetX: "6px",
        offsetY: "6px",
        blur: "0px",
        spread: "0px",
        color: "#a3e635",
      },
      accent: "#a3e635",
      accentSecondary: "#ec4899",
      surface: "#171717",
      text: "#f4f4f5",
      density: "spacious",
      headingScale: 1.35,
      bodyScale: 1.05,
      motion: "expressive",
    },
    locked: {
      panelRadius: "海报展墙要求纯平裁切直角与粗犷边框，圆角会削弱几何力量感",
    },
    specimenNote: "剪影特征：倾斜张贴的巨幅海报卡片 + 粗壮实线边框与偏移硬阴影 + 荧光黑绿撞色",
  },
};

export default posterWallStyle;
