import type { SetupStyle } from "../types";

export const quietGalleryStyle: SetupStyle = {
  id: "quiet-gallery",
  name: "Quiet Gallery",
  version: "3.0.0",
  subtitle: "极简美术馆基座 · 绝对克制留白 · 发丝细线与凝练雕塑感",
  description:
    "受极简主义当代艺术馆展台启发的设计系统。摒弃喧闹的背景色块、重阴影与强对比线条，采用极简暖黑石板底色 (#0e0e11) 与柔和象牙白 (#f4f2ee)，全界面贯穿 1px 发丝线（Hairline Border）、宽阔从容的呼吸留白（Serene Whitespace）与悬浮展台基座。让每一件工具与资源如同陈列在幽静展厅基座上的雕塑艺术品，专注其最纯粹的本质形态。",
  inspiration: "Dieter Rams, Tadao Ando, Peter Zumthor, MoMA Minimalist Architecture",
  author: "Setup Center Architecture",
  tags: ["极简展厅", "画廊基座", "发丝细线", "从容留白", "克制雕塑感"],
  implemented: true,
  palette: {
    baseBg: "#0e0e11",
    surface: "#161619",
    cardBorder: "rgba(255, 255, 255, 0.08)",
    accent: "#e2ded7",
    accentSecondary: "#8e8a84",
    text: "#f4f2ee",
  },
  features: [
    "沉静暖黑底色 (#0e0e11) 搭配柔光象牙白 (#f4f2ee)，极低视觉疲劳度",
    "全界面 1px 细微发丝线裁切，营造如实体精工展台的精致基座轮廓",
    "高留白比率与中心聚集布局（Serene Whitespace），引导视线聚焦单点",
    "克制而缓慢的渐隐动效（0.4s slow ease-out），呈现无声沉思的美学氛围",
  ],
  designPrinciples: [
    "Silence Over Noise: 移除一切多余装饰，让内容本身成为空间中唯一的聚焦点",
    "Plinth Architecture: 每一个卡片与视窗如同独立石质展台，具有厚重平稳的呼吸节奏",
    "Timeless Restraint: 不追逐短期流行特效，保持历久弥新的极简古典比例与发丝精度",
  ],
  experience: {
    tier: "experience",
    family: "minimal",
    scene: "minimal-gallery",
    contentFlow: "serene-centered",
    navigationFlow: "ghost-pill",
    pageTransition: "subtle-fade",
    heroMode: "monolithic-focus",
    layering: "single-plane",
    shell: "canvas",
    navigation: "topbar",
    detail: "sheet",
    card: "tile",
    composition: "magazine-index",
    density: "spacious",
    motion: "reduced",
    typography: {
      headingFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      bodyFamily: "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, 'SF Mono', Menlo, monospace",
      headingWeight: 400,
      headingTracking: "-0.015em",
      headingTransform: "none",
      bodyLeading: 1.6,
    },
    ornament: {
      rule: "hairline",
      corner: "rounded",
      decoration: "none",
      chrome: "none",
    },
    tokens: {
      panelRadius: "6px",
      controlRadius: "4px",
      borderWidth: "1px",
      shadow: {
        offsetX: "0px",
        offsetY: "8px",
        blur: "32px",
        spread: "0px",
        color: "rgba(0, 0, 0, 0.45)",
      },
      accent: "#e2ded7",
      accentSecondary: "#8e8a84",
      surface: "#161619",
      text: "#f4f2ee",
      density: "spacious",
      headingScale: 1.08,
      bodyScale: 0.98,
      motion: "reduced",
    },
    locked: {
      borderWidth: "画廊展台体系严守 1px 发丝线，加粗将破坏雕塑感与宁静秩序",
      motion: "极简画廊采用克制慢速淡入，禁止剧烈抖动与跳跃弹簧动效",
    },
    specimenNote: "剪影特征：中央聚拢的沉静展台 + 1px 极细发丝线微光轮廓 + 宽阔从容的呼吸留白",
  },
};

export default quietGalleryStyle;
