import type { SetupStyle } from "../types";

export const desktopStudioStyle: SetupStyle = {
  id: "desktop-studio",
  name: "Desktop Studio",
  version: "3.0.0",
  subtitle: "经典多视窗重叠 · 像素点阵阴影 · 复古标题栏操控",
  description:
    "基于 90 年代 NeXTSTEP 与经典 Unix 图形工作站的多视窗桌面系统。将各屏功能以立体的浮动独立窗口层叠展示，窗口具有经典的斜角立体边框、可点击标题栏与点阵抖动投影，还原个人计算机黄金时代的创造力与纯粹操作快感。",
  inspiration: "NeXTSTEP OS, IRIX Interactive Desktop, Classic Macintosh System 7",
  author: "Setup Center Architecture",
  tags: ["复古桌面", "多视窗", "NeXTSTEP", "立体边框", "点阵阴影"],
  implemented: true,
  palette: {
    baseBg: "#2c3e50",
    surface: "#c8ccd4",
    cardBorder: "#1e293b",
    accent: "#2563eb",
    accentSecondary: "#64748b",
    text: "#0f172a",
  },
  features: [
    "深度灰蓝桌面底色 (#2c3e50) 配合微细 45 度点阵防伪底纹",
    "各模块呈现为具备顶栏双色调控制条与点阵投影（Dithered Shadow）的独立视窗",
    "经典三维凸起凹陷边框（Beveled 3D Border），还原纯正硬件图形系统质感",
    "柯达钴蓝 (#2563eb) 激活视窗高亮条，状态聚焦一目了然",
  ],
  designPrinciples: [
    "Window as Workspace: 窗口是承载专注的独立舞台，通过层叠提供自然的物理空间联想",
    "Beveled Clarity: 用明确的凸起与凹陷表达可点击性，告别扁平化带来的识别困难",
    "Pioneer Workstation Dignity: 重现早期图形工作站对专业用户与创作者的崇高敬意",
  ],
  experience: {
    tier: "experience",
    family: "cyber",
    scene: "windowed-desktop",
    contentFlow: "floating-windows",
    navigationFlow: "window-taskbar",
    pageTransition: "window-cascade",
    heroMode: "desktop-stage",
    layering: "overlapping-windows",
    shell: "windowed",
    navigation: "topbar",
    detail: "window",
    card: "window",
    composition: "finder-list",
    density: "normal",
    motion: "normal",
    typography: {
      headingFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 700,
      headingTracking: "-0.01em",
      bodyLeading: 1.5,
    },
    ornament: {
      rule: "double",
      corner: "square",
      decoration: "pinstripe",
      chrome: "full",
    },
    tokens: {
      panelRadius: "0px",
      controlRadius: "0px",
      borderWidth: "2px",
      shadow: {
        offsetX: "6px",
        offsetY: "6px",
        blur: "0px",
        spread: "0px",
        color: "rgba(15, 23, 42, 0.65)",
      },
      accent: "#2563eb",
      accentSecondary: "#64748b",
      surface: "#c8ccd4",
      text: "#0f172a",
      density: "normal",
      headingScale: 1.05,
      bodyScale: 1.0,
      motion: "normal",
    },
    specimenNote: "剪影特征：外层桌面桌布底色 + 带有标题栏和关闭框的浮动窗口矩阵 + 像素硬投影",
  },
};

export default desktopStudioStyle;
