/**
 * UI Part & Component Snippet Renderer / Assembler (Issues K01, K06).
 *
 * ## Reusable Assembly & Honest Boundary (Issue K06)
 *
 * Provides standalone code synthesis, template inlining, and preview bundling
 * for UI Parts and design system components.
 *
 * Architectural Boundary:
 * Universal cross-stack auto-assembler (arbitrary AST code merging into any framework)
 * is explicitly deferred (DEFERRED_BY_SPEC). This module delivers reliable
 * standalone code inlining, ready-to-use component wrappers, and structured
 * export bundles.
 */

import type { UIPart } from "../../uiparts/types";

export interface RenderedComponentArtifact {
  partId: string;
  componentName: string;
  framework: "react" | "html" | "vue" | "svelte" | "vanilla";
  inlinedCode: string;
  cssStyles: string;
  exportFileName: string;
  importStatement: string;
  dependencies: Record<string, string>;
  isExecutable: boolean;
  notes: string;
}

export interface AssemblyRecipe {
  title: string;
  targetStack: string;
  filesToCreate: Array<{
    relativePath: string;
    content: string;
    description: string;
  }>;
  commandSnippet: string;
  manualSteps: string[];
}

/**
 * Normalizes a part title into a valid PascalCase component name.
 */
export function toPascalCase(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^[a-z]/, (c) => c.toUpperCase())
    .replace(/[^a-zA-Z0-9]/g, "");
}

/**
 * Synthesizes a self-contained, runnable React component file from a UI Part.
 */
export function renderPartAsReactComponent(part: UIPart): RenderedComponentArtifact {
  const componentName = toPascalCase(part.name || "CustomUIPart");
  const fileName = `${componentName}.tsx`;

  const primaryCode = part.codeAssets?.[0]?.content || `export function ${componentName}() {\n  return (\n    <div className="p-4 border rounded-lg bg-surface text-ink">\n      <h3 className="font-bold text-lg">${part.name}</h3>\n      <p className="text-sm opacity-80 mt-1">${part.description || "Reusable UI Component"}</p>\n    </div>\n  );\n}`;

  const styles = part.designTokens
    ? Object.entries(part.designTokens)
        .map(([k, v]) => `  --${k}: ${v};`)
        .join("\n")
    : "";

  const inlinedCode = `import React from "react";

/**
 * Generated by Setup Center Reusable Component Pipeline.
 * Part ID: ${part.id}
 * Version: ${part.version || "1.0.0"}
 */
${primaryCode}

export default ${componentName};
`;

  return {
    partId: part.id,
    componentName,
    framework: "react",
    inlinedCode,
    cssStyles: styles ? `:root {\n${styles}\n}` : "",
    exportFileName: fileName,
    importStatement: `import ${componentName} from "./${componentName}";`,
    dependencies: {
      react: "^19.0.0",
      "clsx": "^2.1.0",
    },
    isExecutable: true,
    notes: "可直接作为独立 React 组件导入项目。通用全自动跨框架注入引擎明确延期 (DEFERRED_BY_SPEC)。",
  };
}

/**
 * Builds an actionable assembly recipe for instantiating a UI Part in a project.
 */
export function buildPartAssemblyRecipe(part: UIPart): AssemblyRecipe {
  const artifact = renderPartAsReactComponent(part);

  return {
    title: `组装并引入 ${part.name}`,
    targetStack: "React + Vite / Next.js / Tailwind CSS",
    filesToCreate: [
      {
        relativePath: `src/components/${artifact.exportFileName}`,
        content: artifact.inlinedCode,
        description: `包含 ${part.name} 完整实现与内联样式的独立组件文件`,
      },
    ],
    commandSnippet: `// 在页面或视图中直接引用：\n${artifact.importStatement}\n\n// 渲染组件：\n<${artifact.componentName} />`,
    manualSteps: [
      `将生成的 ${artifact.exportFileName} 放置在工程 components 目录下`,
      "确认项目已安装 React 基础依赖",
      "在需要该交互零件的父级页面中引入并渲染",
    ],
  };
}
