import type { SetupStyle } from "../types";

export const cinematicProductStyle: SetupStyle = {
  id: "cinematic-product",
  name: "Cinematic Product",
  version: "3.0.0",
  subtitle: "2.35:1 宽银幕视口 · 时间轴刻度带 · 暗房 HUD 监视台",
  description:
    "基于专业电影调色监视器与院线 anamorphic 宽幅画幅的沉浸暗室工作台。界面顶部与底部自带胶片遮幅，配合专业摄影机 HUD 角标、精准毫秒时间码刻度与高动态范围（HDR）冷暖对比，将技术工具的装配过程渲染为一场精雕细琢的视听大片。",
  inspiration: "ARRI Alexa Viewfinder, RED Digital Cinema, Blackmagic DaVinci Resolve",
  author: "Setup Center Architecture",
  tags: ["宽幅电影", "时间轴", "HUD 监视器", "暗室美学", "摄影机取景"],
  implemented: true,
  palette: {
    baseBg: "#0a0a0c",
    surface: "#141418",
    cardBorder: "#26262e",
    accent: "#f59e0b",
    accentSecondary: "#06b6d4",
    text: "#f3f4f6",
  },
  features: [
    "电影暗室底色 (#0a0a0c) 伴随微妙的 2.35:1 宽银幕上下遮幅暗影",
    "取景器十字对焦线、网格安全框与四个内角四分之一 L 型 HUD 准星标",
    "顶栏嵌入实时运行时间码（Timecode 00:04:12:18）与录制指示灯",
    "暖色影视级钨丝灯琥珀金 (#f59e0b) 与变形镜头青蓝 (#06b6d4) 高反差对比",
  ],
  designPrinciples: [
    "Cinematic Framing: 每一个模块都是摄影机取景框中的主角，富有舞台光照感",
    "Timecode Rhythm: 界面状态流转带有电影帧推进般的精确节拍与淡入淡出",
    "Studio Focus: 极黑环境吸收一切视觉噪点，唯有当下聚焦的配置元素被聚光灯照亮",
  ],
  experience: {
    tier: "experience",
    family: "cinematic",
    scene: "viewport-hud",
    contentFlow: "widescreen-timeline",
    navigationFlow: "cinematic-scrubber",
    pageTransition: "camera-cut",
    heroMode: "anamorphic-scope",
    layering: "optical-glass",
    shell: "topbar",
    navigation: "command-bar",
    detail: "rail",
    card: "panel",
    composition: "magazine-index",
    density: "normal",
    motion: "expressive",
    typography: {
      headingFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 700,
      headingTracking: "0.06em",
      headingTransform: "uppercase",
      bodyLeading: 1.6,
    },
    ornament: {
      rule: "hairline",
      corner: "notch",
      decoration: "none",
      chrome: "full",
    },
    tokens: {
      panelRadius: "4px",
      controlRadius: "2px",
      borderWidth: "1px",
      shadow: {
        offsetX: "0px",
        offsetY: "16px",
        blur: "40px",
        spread: "-12px",
        color: "rgba(0, 0, 0, 0.9)",
      },
      accent: "#f59e0b",
      accentSecondary: "#06b6d4",
      surface: "#141418",
      text: "#f3f4f6",
      density: "normal",
      headingScale: 1.15,
      bodyScale: 1.0,
      motion: "expressive",
    },
    specimenNote: "剪影特征：顶部摄影机时间码条 + 四角 L 型 HUD 准星 + 2.35:1 宽银幕暗房对比",
  },
};

export default cinematicProductStyle;
