import type { SetupStyle } from "../types";

export const spatialConstellationStyle: SetupStyle = {
  id: "spatial-constellation",
  name: "Spatial Constellation",
  version: "3.0.0",
  subtitle: "天体星图拓扑 · 轨道环绕节点 · 视差浮动发光场",
  description:
    "打破平面矩形牢笼，将工作台构筑为深邃的宇宙天体拓扑场。各项工具与资产以轨道环状星环排列，发光向量连线与微弱星云噪点勾勒出开阔的景深层次，为工作站提供星舰级空间导航感。",
  inspiration: "The Expanse HUD, Astroneer UI, Apple VisionOS Constellations",
  author: "Setup Center Architecture",
  tags: ["星图拓扑", "三维空间", "轨道节点", "深空景深", "霓虹连线"],
  implemented: true,
  palette: {
    baseBg: "#080914",
    surface: "#0f1226",
    cardBorder: "#252b54",
    accent: "#00f0ff",
    accentSecondary: "#a855f7",
    text: "#e2e8f0",
  },
  features: [
    "深邃宇宙背景 (#080914) 叠加密集星尘噪点与径向天体引力光晕",
    "半透明微晶浮动面板，带有 1px 细微光通量边框与霓虹青色 (#00f0ff) 辉光",
    "悬浮程序坞导航与圆形轨道徽标，支持视差交互反馈",
    "拓扑连线与坐标读数 HUD 角标，呈现严谨的天文测绘美感",
  ],
  designPrinciples: [
    "Depth Over Flatness: 空间界面必须具备多层景深，让核心操作在视野中悬停聚焦",
    "Luminescence as Signal: 自发光边缘是高价值交互的信号，拒绝刺眼的纯白实体填充",
    "Orbital Equilibrium: 元素围绕用户视线重心平衡分布，如同稳定的行星引力系统",
  ],
  experience: {
    tier: "experience",
    family: "spatial",
    scene: "constellation",
    contentFlow: "orbital-nodes",
    navigationFlow: "radial-dock",
    pageTransition: "constellation-drift",
    heroMode: "hologram",
    layering: "deep-space",
    shell: "canvas",
    navigation: "dock",
    detail: "floating-inspector",
    card: "floating-surface",
    composition: "floating-panels",
    density: "spacious",
    motion: "expressive",
    typography: {
      headingFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 700,
      headingTracking: "0.04em",
      headingTransform: "uppercase",
      bodyLeading: 1.6,
    },
    ornament: {
      rule: "dashed",
      corner: "rounded",
      decoration: "noise",
      chrome: "none",
    },
    tokens: {
      panelRadius: "24px",
      controlRadius: "12px",
      borderWidth: "1px",
      shadow: {
        offsetX: "0px",
        offsetY: "20px",
        blur: "50px",
        spread: "-10px",
        color: "rgba(0, 240, 255, 0.15)",
      },
      accent: "#00f0ff",
      accentSecondary: "#a855f7",
      surface: "#0f1226",
      text: "#e2e8f0",
      density: "spacious",
      headingScale: 1.1,
      bodyScale: 1.0,
      motion: "expressive",
    },
    locked: {
      borderWidth: "空间星图必须依靠 1px 发光晶格边缘维持全息通透感，过粗边框会丧失轻盈度",
    },
    specimenNote: "剪影特征：底部浮动胶囊程序坞 + 带有光晕的圆形/弧角浮岛面板 + 宇宙天体黑夜背景",
  },
};

export default spatialConstellationStyle;
