import type { SetupStyle } from "../types";

export const singleScreenPlaygroundStyle: SetupStyle = {
  id: "single-screen-playground",
  name: "Single-Screen Playground",
  version: "3.0.0",
  subtitle: "无滚动密集机架 · 乐器触觉推子 · 拟物旋钮矩阵",
  description:
    "致敬 Teenage Engineering OP-1 与经典模拟合成器的无滚动单屏硬件系统。在固定的视口高度内紧凑陈列各项功能，通过工业级刻度旋钮、物理质感拨码开关与高对比度液晶屏槽位，将复杂的配置流程转变为如把玩随身乐器般的愉悦体验。",
  inspiration: "Teenage Engineering OP-1, Dieter Rams T3, Elektron Syntakt",
  author: "Setup Center Architecture",
  tags: ["硬件乐器", "合成器", "单屏无滚动", "紧凑机架", "触觉拨码"],
  implemented: true,
  palette: {
    baseBg: "#e8e6df",
    surface: "#dedbd2",
    cardBorder: "#78716c",
    accent: "#ff5722",
    accentSecondary: "#f59e0b",
    text: "#1c1917",
  },
  features: [
    "阳极氧化浅灰铝制机身底色 (#e8e6df)，结合精密冲压微粒倒角",
    "单屏高度严格锁定视口 (100vh)，杜绝拖沓的纵向长页面滚动",
    "各功能区以乐器模组（Rack Modules）紧凑插接，槽位边缘具有内凹铣槽阴影",
    "触觉醒目的工业橙 (#ff5722) 实体推杆与圆形旋钮交互指示器",
  ],
  designPrinciples: [
    "Single-Screen Completeness: 一切操作都在一个视窗内尽收眼底，无需迷失在滚动深度中",
    "Tactile Satisfaction: 每一个按键与拨码都必须拥有清晰的物理回弹与阻尼手感反馈",
    "Playful Precision: 严谨的工程工具也可以像便携式音乐玩具一样充满把玩乐趣",
  ],
  experience: {
    tier: "experience",
    family: "hardware",
    scene: "instrument-panel",
    contentFlow: "dense-rack",
    navigationFlow: "hardware-tabs",
    pageTransition: "knob-snap",
    heroMode: "synth-rack",
    layering: "chassis-chassis",
    shell: "command-centered",
    navigation: "tab-strip",
    detail: "inline",
    card: "tile",
    composition: "ledger",
    density: "compact",
    motion: "reduced",
    typography: {
      headingFamily: "ui-monospace, 'SF Mono', Consolas, monospace",
      bodyFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
      monoFamily: "ui-monospace, monospace",
      headingWeight: 800,
      headingTracking: "-0.01em",
      bodyLeading: 1.45,
    },
    ornament: {
      rule: "hairline",
      corner: "notch",
      decoration: "blueprint",
      chrome: "status",
    },
    tokens: {
      panelRadius: "6px",
      controlRadius: "4px",
      borderWidth: "1.5px",
      shadow: {
        offsetX: "0px",
        offsetY: "2px",
        blur: "0px",
        spread: "1px",
        color: "#a8a29e",
      },
      accent: "#ff5722",
      accentSecondary: "#f59e0b",
      surface: "#dedbd2",
      text: "#1c1917",
      density: "compact",
      headingScale: 0.95,
      bodyScale: 0.95,
      motion: "reduced",
    },
    locked: {
      density: "乐器机架要求绝对紧凑的高密度模块插槽，不可稀疏留白",
    },
    specimenNote: "剪影特征：顶部带刻度硬件标签栏 + 密集矩形机架卡槽 + 底部无纵向滚动条的紧凑视口",
  },
};

export default singleScreenPlaygroundStyle;
